force-app/main/default/objects/Tabulacao__c/Tabulacao__c.object-meta.xml
<CustomObject>
    <label>Tabulação</label>
    <nameField>
        <label>Nome da Tabulação</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tabulações</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tabulacao__c/fields/FormulaVisibilidade__c.field-meta.xml
<CustomField>
    <fullName>FormulaVisibilidade__c</fullName>
    <label>Formula de Visibilidade</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Tabulacao__c/fields/PermiteAtendimento__c.field-meta.xml
<CustomField>
    <fullName>PermiteAtendimento__c</fullName>
    <label>Permite Atendimento</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cliente - Pessoa Física</fullName>
            </value>
            <value>
                <fullName>Cliente - Pessoa Jurídica</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tabulacao__c/fields/TabulacaoInterna__c.field-meta.xml
<CustomField>
    <fullName>TabulacaoInterna__c</fullName>
    <defaultValue>false</defaultValue>
    <description>As tabulações internas não ficam visíveis para o componente de criação de casos de atendimento, mas somente para casos internos.</description>
    <inlineHelpText>As tabulações internas não ficam visíveis para o componente de criação de casos de atendimento, mas somente para casos internos.</inlineHelpText>
    <label>Tabulação Interna</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Tabulacao__c/fields/TabulacaoOculta__c.field-meta.xml
<CustomField>
    <fullName>TabulacaoOculta__c</fullName>
    <defaultValue>false</defaultValue>
    <description>As tabulações ocultas não ficam visíveis para os componentes de criação de casos.</description>
    <inlineHelpText>As tabulações ocultas não ficam visíveis para os componentes de criação de casos.</inlineHelpText>
    <label>Tabulação Oculta</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Tabulacao__c/recordTypes/FluxoTrabalho.recordType-meta.xml
<RecordType>
    <fullName>FluxoTrabalho</fullName>
    <active>true</active>
    <label>FluxoTrabalho</label>
</RecordType>

force-app/main/default/classes/TabulacaoSelector.cls
public class TabulacaoSelector extends SObjectSelector {
    protected override Schema.SObjectType getSObjectType() {
        return Tabulacao__c.sObjectType;
    }

    public List<Tabulacao__c> FindFluxoDeTrabalho(
        String keyword,
        String accountType,
        Boolean fluxoInterno
    ) {
        List<List<SObject>> results = [
            FIND :keyword
            IN ALL FIELDS
            RETURNING
                Tabulacao__c(
                    Id,
                    Name,
                    Descricao__c,
                    FormulaVisibilidade__c
                    WHERE
                        RecordType.DeveloperName = 'FluxoTrabalho'
                        AND PermiteAtendimento__c INCLUDES (:accountType)
                        AND TabulacaoOculta__c = FALSE
                        AND TabulacaoInterna__c = :fluxoInterno
                    ORDER BY Name)
        ];
        return results.get(0);
    }

    protected override string allFieldList() {
        List<String> strList = super.allFieldList().Split(',');
        strList.add('RecordType.DeveloperName');
        return STRING.join(strList, ',');
    }
}