force-app/main/default/objects/Tabulacao__c/Tabulacao__c.object-meta.xml
<CustomObject>
    <label>Tabulação</label>
    <nameField>
        <label>Nome da Tabulação</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tabulações</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tabulacao__c/fields/SLAConclusao__c.field-meta.xml
<CustomField>
    <fullName>SLAConclusao__c</fullName>
    <inlineHelpText>Horas para finalização do Marco</inlineHelpText>
    <label>SLA de Conclusão</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CaseTabulationMilestoneAssignment.cls
global class CaseTabulationMilestoneAssignment implements Support.MilestoneTriggerTimeCalculator {
    
    global Integer calculateMilestoneTriggerTime(String caseId, String milestoneTypeId) {
        CaseSelector selectCase = new CaseSelector();
        TabulacaoSelector selectTabulacao = new TabulacaoSelector();
        Case caso = (Case)selectCase.SelectId(caseId);
        Tabulacao__c tabulacao = (Tabulacao__c)selectTabulacao.SelectId(caso.Tabulacao__c);

        return Integer.valueOf(tabulacao.SLAConclusao__c * 60);
	}
}