force-app/main/default/objects/UsuarioSite__c/UsuarioSite__c.object-meta.xml
<CustomObject>
    <label>Usuário Site</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Usuários Site</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UsuarioSite__c/fields/IdSite__c.field-meta.xml
<CustomField>
    <fullName>IdSite__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Id do Site</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/UsuarioSite.cls
public class UsuarioSite extends fflib_SObjectDomain implements IUsuarioSite {

    public UsuarioSite(List<UsuarioSite__c> sObjectList)
    {
        super(sObjectList);
    }
    
    public static IUsuarioSite newInstance(List<UsuarioSite__c> sObjectList)
    {
        return (IUsuarioSite) Application.Domain.newInstance(sObjectList);
    }
    
    public class Constructor implements fflib_SObjectDomain.IConstructable
    {
        public fflib_SObjectDomain construct(List<SObject> sObjectList)
        {
            return new UsuarioSite(sObjectList);
        }
    }
    

    public static UsuarioSite__c atualizaUsuarioSite(
        fflib_ISObjectUnitOfWork uow, Id usuarioId, String nome, String idSite
    ) {
        UsuarioSite__c usuario = new UsuarioSite__c();
        usuario.Id = usuarioId;
        usuario.Name = nome;
        usuario.IdSite__c = idSite;

        if (usuarioId == null)
        {
            uow.registerNew(usuario);        
        } else {
            uow.registerDirty(usuario);
        }        

        return usuario;
    }    

}