force-app/main/default/objects/UsuarioSite__c/UsuarioSite__c.object-meta.xml
<CustomObject>
    <label>Usuário Site</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Usuários Site</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UsuarioSite__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Usuários Site</relationshipLabel>
    <relationshipName>UsuariosSite</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UsuarioSite__c/fields/IdSite__c.field-meta.xml
<CustomField>
    <fullName>IdSite__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Id do Site</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/UsuarioSiteSelector.cls
public class UsuarioSiteSelector extends fflib_SObjectSelector implements IUsuarioSiteSelector {

    public static IUsuarioSiteSelector newInstance()
    {
        return (IUsuarioSiteSelector) Application.Selector.newInstance(UsuarioSite__c.SObjectType);
    }
    
    public UsuarioSiteSelector(Boolean includeFieldSetFields)
    {
        super(includeFieldSetFields);
    }
    
    public UsuarioSiteSelector()
    {
        super(true);
    }
    
    public override List<Schema.FieldSet> getSObjectFieldSetList()
    {
        List<Schema.FieldSet> fieldSets = new List<Schema.FieldSet>();
        
        fieldSets.add(SobjectType.UsuarioSite__c.FieldSets.SelectFieldList);
        
        return fieldSets;
    }
    
    public List<Schema.SObjectField> getSObjectFieldList()
    {
        return new List<Schema.SObjectField> {
            UsuarioSite__c.Id
        };
    }
    
    public Schema.SObjectType getSObjectType()
    {
        return UsuarioSite__c.sObjectType;
    }
        
    
    public UsuarioSite__c encontraPeloIdUsuarioSite(String idUsuarioSite) {

        fflib_QueryFactory query = newQueryFactory();

        query.setCondition('IdSite__c = :idUsuarioSite');
        
        List<UsuarioSite__c> usuarios = Database.query( query.toSOQL() );

        return usuarios.size() > 0 ? usuarios[0] : null;         
    }

    public UsuarioSite__c encontraPelaConta(Id accountId) {

        fflib_QueryFactory query = newQueryFactory();

        query.setCondition('Conta__c = :accountId');
        
        List<UsuarioSite__c> usuarios = Database.query( query.toSOQL() );

        return usuarios.size() > 0 ? usuarios[0] : null;         
    }

}