force-app/main/default/objects/Missao__c/Missao__c.object-meta.xml
<CustomObject>
    <description>Objeto que registra os dados do cálculo da missão</description>
    <label>Missão</label>
    <nameField>
        <displayFormat>MI-{0000000}</displayFormat>
        <label>Número da Missão</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Missões</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Missao__c/fields/TempoMissao__c.field-meta.xml
<CustomField>
    <fullName>TempoMissao__c</fullName>
    <description>Tempo total a missão</description>
    <inlineHelpText>Tempo total a missão</inlineHelpText>
    <label>Tempo da Missão</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Missao__c/fields/Voo__c.field-meta.xml
<CustomField>
    <fullName>Voo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Voo ao qual o objeto Missão esta vinculado</description>
    <inlineHelpText>Voo ao qual o objeto Missão esta vinculado</inlineHelpText>
    <label>Voo</label>
    <referenceTo>Voo__c</referenceTo>
    <relationshipName>Missoes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Voo__c/Voo__c.object-meta.xml
<CustomObject>
    <description>O Voo de uma aeronave, do ponto de origem até o retorno</description>
    <label>Voo</label>
    <nameField>
        <displayFormat>REVO-{00000000}</displayFormat>
        <label>Número do Voo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Voos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Voo__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Conta para o faturamento do(s) voo(s)</description>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Voos</relationshipLabel>
    <relationshipName>Voos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Voo__c/fields/DataVoo__c.field-meta.xml
<CustomField>
    <fullName>DataVoo__c</fullName>
    <description>Dia e hora solicitada para a realização do voo</description>
    <inlineHelpText>Dia e hora solicitada para a realização do voo</inlineHelpText>
    <label>Data</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Voo__c/fields/Missao__c.field-meta.xml
<CustomField>
    <fullName>Missao__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contém dados de cálculo de missão de um voo</description>
    <label>Missão</label>
    <referenceTo>Missao__c</referenceTo>
    <relationshipLabel>Voos</relationshipLabel>
    <relationshipName>Voos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Voo__c/fields/Prefixo__c.field-meta.xml
<CustomField>
    <fullName>Prefixo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Prefixo da aeronave que realizará o voo</description>
    <inlineHelpText>Prefixo da aeronave que realizará o voo</inlineHelpText>
    <label>Prefixo</label>
    <referenceTo>Aeronave__c</referenceTo>
    <relationshipLabel>Voos</relationshipLabel>
    <relationshipName>Voos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Voo__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Define em que momento o voo se encontra</description>
    <inlineHelpText>Define em que momento o voo se encontra</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Rascunho</fullName>
                <default>true</default>
                <label>Rascunho</label>
            </value>
            <value>
                <fullName>Pré-reservado</fullName>
            </value>
            <value>
                <fullName>Reservado</fullName>
            </value>
            <value>
                <fullName>Confirmado</fullName>
            </value>
            <value>
                <fullName>Rota</fullName>
                <label>Em Rota</label>
            </value>
            <value>
                <fullName>LogPendente</fullName>
                <label>Concluindo o Voo</label>
            </value>
            <value>
                <fullName>Executado</fullName>
            </value>
            <value>
                <fullName>Em Faturamento</fullName>
                <isActive>false</isActive>
                <label>Em Faturamento</label>
            </value>
            <value>
                <fullName>Faturado</fullName>
                <isActive>false</isActive>
                <label>Faturado</label>
            </value>
            <value>
                <fullName>Pronto pra Voar</fullName>
                <isActive>false</isActive>
                <label>Pronto pra Voar</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Voo__c/fields/TempoMissao__c.field-meta.xml
<CustomField>
    <fullName>TempoMissao__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Tempo de missão do voo</description>
    <inlineHelpText>Tempo de missão do voo</inlineHelpText>
    <label>Tempo de Missão</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/MissoesTest.cls
@isTest
public class MissoesTest {
    @TestSetup
    static void setup()
    {
        Id standardPricebookId = TestUtil.SetupStandardPricebook();
        Datetime data = Datetime.newInstanceGmt(System.now().date().addDays(1), Time.newInstance(15, 0, 0, 0));
        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        Voo__c voo = TestUtil2.criarVooRascunho(data, true, uow);
        uow.commitWork();
    }
    
	@isTest
    static void constructorTest()
    {
        Test.startTest();
        Missoes missoesDomain = new Missoes(new List<Missao__c>());
        Test.stopTest();
        System.assert(true);
    }
    
    @isTest
    static void createMissaoTest()
    {
        Test.startTest();
        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        CalculoMissaoResult cmr = new CalculoMissaoResult();
        Missoes missoesDomain = new Missoes(new List<Missao__c>());
        Missao__c missao = missoesDomain.createMissao(cmr, uow);
        List<Voo__c> lista = [SELECT Id, Prefixo__c, Status__c, Cliente__c, Name, DataVoo__c FROM Voo__c ORDER BY Id DESC LIMIT 1];
        Missao__c missao2 = missoesDomain.criarMissao(cmr, lista[0].Id);
        Map<Id, CalculoMissaoResult> mapaVoo = new Map<Id, CalculoMissaoResult>();
        mapaVoo.put(lista[0].Id, cmr);
        Map<Id, Missao__c> mapa = missoesDomain.criarMissoes(mapaVoo);
        Test.stopTest();
        System.assert(missao != null && missao2 != null && mapa != null);
    }

	@isTest
    static void checkValidTempoMissaoTest()
    {
        Test.startTest();
        Missao__c missao = new Missao__c(TempoMissao__c=10);
        Missoes missoesDomain = new Missoes(new List<Missao__c>());
        missoesDomain.checkValidTempoMissao(missao);
        missao.TempoMissao__c = null;
        missoesDomain.checkValidTempoMissao(missao);
        Test.stopTest();
    }
}