force-app/main/default/objects/Aeronave__c/Aeronave__c.object-meta.xml
<CustomObject>
    <label>Aeronave</label>
    <nameField>
        <label>Prefixo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aeronaves</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CodigoPromocional__c/CodigoPromocional__c.object-meta.xml
<CustomObject>
    <label>Promoção</label>
    <nameField>
        <label>Código Promocional</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promoções</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CodigoPromocional__c/recordTypes/CodigoPromocional.recordType-meta.xml
<RecordType>
    <fullName>CodigoPromocional</fullName>
    <active>true</active>
    <label>Código Promocional</label>
</RecordType>

force-app/main/default/objects/ConfiguracaoPacote__c/ConfiguracaoPacote__c.object-meta.xml
<CustomObject>
    <label>Configuração do Pacote</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Configuração do Pacote</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Configurações dos Pacotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ConfiguracaoPacote__c/fields/ProdutoPacote__c.field-meta.xml
<CustomField>
    <fullName>ProdutoPacote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto do Pacote</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>ServicosTaxas</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Configurações dos Pacotes</relationshipLabel>
    <relationshipName>Configuracoes_dos_Pacotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ConfiguracaoPacote__c/fields/QuantidadePadrao__c.field-meta.xml
<CustomField>
    <fullName>QuantidadePadrao__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Quantidade Padrão</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConfiguracaoPacote__c/fields/QuantidadeRelativa__c.field-meta.xml
<CustomField>
    <fullName>QuantidadeRelativa__c</fullName>
    <label>Quantidade Relativa</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pelo Padrão</fullName>
                <default>true</default>
                <label>Pelo Padrão</label>
            </value>
            <value>
                <fullName>Por Passageiros</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Local__c/Local__c.object-meta.xml
<CustomObject>
    <label>Local</label>
    <nameField>
        <label>Local</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Local__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <description>Define se o local é em terra(onshore) ou em mar(offshore)</description>
    <inlineHelpText>Define se o local é em terra(onshore) ou em mar(offshore)</inlineHelpText>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Onshore</fullName>
            </value>
            <value>
                <fullName>Offshore</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RegraDesconto__c/RegraDesconto__c.object-meta.xml
<CustomObject>
    <label>Regra de Desconto</label>
    <nameField>
        <displayFormat>RD-{00000000}</displayFormat>
        <label>Regra de Desconto</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Regras de Descontos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RegraDesconto__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fixo</fullName>
            </value>
            <value>
                <fullName>Faixa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RegraPreco__c/RegraPreco__c.object-meta.xml
<CustomObject>
    <label>Regra de Preço</label>
    <nameField>
        <displayFormat>RP-{0000}</displayFormat>
        <label>Regra de Preço</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Regras de Preços</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RegraProduto__c/RegraProduto__c.object-meta.xml
<CustomObject>
    <label>Regra de Produto</label>
    <nameField>
        <displayFormat>RP-{0000}</displayFormat>
        <label>Regra de Produto</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Regras de Produtos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Voo__c/Voo__c.object-meta.xml
<CustomObject>
    <description>O Voo de uma aeronave, do ponto de origem até o retorno</description>
    <label>Voo</label>
    <nameField>
        <displayFormat>REVO-{00000000}</displayFormat>
        <label>Número do Voo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Voos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Voo__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <description>Informa o tipo de transporte realizado pelo voo.</description>
    <inlineHelpText>Informs the type of transport performed by the flight.</inlineHelpText>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TipoVoo</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/TipoVoo.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ShuttleSeat</fullName>
        <label>Shuttle Seat</label>
    </customValue>
    <customValue>
        <fullName>Charter</fullName>
    </customValue>
    <customValue>
        <fullName>FullCabin</fullName>
        <label>Full Cabin</label>
    </customValue>
    <customValue>
        <fullName>Sanitário</fullName>
        <isActive>false</isActive>
        <label>Sanitário</label>
    </customValue>
    <customValue>
        <fullName>Treinamento</fullName>
        <isActive>false</isActive>
        <label>Treinamento</label>
    </customValue>
    <customValue>
        <fullName>SAR</fullName>
        <isActive>false</isActive>
        <label>SAR</label>
    </customValue>
    <customValue>
        <fullName>Passageiros</fullName>
        <isActive>false</isActive>
        <label>Passageiros</label>
    </customValue>
    <customValue>
        <fullName>Manutenção</fullName>
        <isActive>false</isActive>
        <label>Manutenção</label>
    </customValue>
    <customValue>
        <fullName>Treinamento NDC</fullName>
        <isActive>false</isActive>
        <label>Treinamento NDC</label>
    </customValue>
    <customValue>
        <fullName>MEDVAC</fullName>
        <isActive>false</isActive>
        <label>MEDVAC</label>
    </customValue>
    <customValue>
        <fullName>Cargueiro</fullName>
        <isActive>false</isActive>
        <label>Cargueiro</label>
    </customValue>
    <customValue>
        <fullName>Passageiros e Cargas</fullName>
        <isActive>false</isActive>
        <label>Passageiros e Cargas</label>
    </customValue>
    <masterLabel>Tipo de voo</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BlocoCharter.cls
public class BlocoCharter {

    // #region Variáveis Publicas

    @AuraEnabled
    public DateTime	data {get; set;}

    @AuraEnabled    
    public String 	horaFormatada {get; set;}

    @AuraEnabled    
    public Integer  intervalo {get; set;}

    @AuraEnabled    
    public Boolean 	invalido {get; set;}

    @AuraEnabled         
    public Double tempoTransladoIda {get; set;}

    @AuraEnabled         
    public Double tempoTransladoRetorno {get; set;}

    @AuraEnabled    
    public Double tempoMissao {get; set;}

    @AuraEnabled    
    public Integer aeronavesDisponiveis {get; set;}

    @AuraEnabled    
    public Aeronave__c 	aeronave {get; set;}
    
    @AuraEnabled    
    public Id modeloId {get; set;}

    @AuraEnabled    
    public Decimal precoUnitario {get; set;}

    @AuraEnabled    
    public Decimal precoRevoSeats {get; set;}

    @AuraEnabled    
    public Decimal descontoPerc {get; set;}

    @AuraEnabled    
    public Decimal descontoValor {get; set;}

    @AuraEnabled    
    public Decimal precoFinal {get; set;}

    @AuraEnabled    
    public Decimal precoFinalRevoSeats {get; set;}

    @AuraEnabled    
    public Id idPromocional {get; set;}

    @AuraEnabled
    public String codigoPromocionalApurado {get; set;}

    @AuraEnabled
    public Boolean promocaoValida {get; set;}

    @AuraEnabled 
    public Id origemInicial {get; set;} 

    @AuraEnabled 
    public Id destinoFinal {get; set;} 

    @AuraEnabled    
    public List<ServicoDoPacote> servicos {get; set;}
    
    private Set<Id> servicosIds;
    private List<Local__c> trajeto;
    // #endregion

    // #region Construtor

    public BlocoCharter (DateTime data, Integer intervalo) {

        this.data = data;
        this.intervalo = intervalo;
        this.invalido = false;
        this.horaFormatada = data.hour() + ':' + (data.minute() >= 10 ? String.valueOf(data.minute()) : '0'+data.minute());
        this.servicosIds = new Set<Id>();
    }

    // #endregion

    // #region Métodos Publicos

    public void setBlocoCharter (
        Id produtoId, Id modeloId, String quem, Id contaId,
        List<Aeronave__c> aeronaves, Map<Id, List<Event>> eventosPorAeronave,
        Map<Id, CalculoMissaoResult> cmrsMapByAeronaveId, List<ConfiguracaoPacote__c> pacotesDosModelos, 
        Map<Id, List<RegraProduto__c>> regrasDosProdutos, Map<Id, List<RegraPreco__c>> regrasDosPrecos, 
        Map<Id, List<RegraDesconto__c>> regrasDeDescontos, CodigoPromocional__c codigo,
        Boolean codigoJaUtilizado, Boolean primeiraCompra, Map<Id, Integer> servicosContratados
    ) {
        carregaDadosCharter(
            produtoId, quem, modeloId, aeronaves, cmrsMapByAeronaveId, eventosPorAeronave
        );

        carregaDadosPreco(
            produtoId, modeloId, quem, contaId, regrasDosProdutos, regrasDosPrecos, regrasDeDescontos, codigo, codigoJaUtilizado, primeiraCompra
        );

        this.servicos = new List<ServicoDoPacote>();

        // Itera de 0 até o penúltimo índice
        for (Integer i = 0; i < this.trajeto.size() - 1; i++) {
            Local__c origem = this.trajeto[i];
            Local__c destino = this.trajeto[i + 1];
            
            carregaDadosServicos(
                produtoId, modeloId, quem, contaId, pacotesDosModelos, regrasDosProdutos, regrasDosPrecos, 
                regrasDeDescontos, codigo, codigoJaUtilizado, primeiraCompra, cmrsMapByAeronaveId, aeronaves, servicosContratados,
                origem, destino
            );
        }
    }

    // #endregion

    // #region Métodos Privados

    private void carregaDadosCharter (
        Id produtoId, String quem, Id modeloId,
        List<Aeronave__c> aeronaves, Map<Id, CalculoMissaoResult> cmrsMapByAeronaveId, 
        Map<Id, List<Event>> eventosPorAeronave
    ) 
    {

        this.aeronavesDisponiveis = 0;
        this.tempoMissao = 0;
        this.tempoTransladoIda = 0;
        this.tempoTransladoRetorno = 0;

        this.precoUnitario = 0;
        this.descontoPerc = 0;
        this.descontoValor = 0;
        this.modeloId = modeloId;

        CalculoMissaoResult calculo0 = cmrsMapByAeronaveId.get(aeronaves[0].Id);
        this.trajeto = calculo0.trajeto;
        this.origemInicial = calculo0.trajeto.isEmpty() ? null : calculo0.trajeto[0].Id;
        this.destinoFinal = calculo0.trajeto.isEmpty() ? null : calculo0.trajeto[calculo0.trajeto.size() - 1].Id;

        Integer aeronavesValidas = 0;

        for(Aeronave__c aeronave : aeronaves)
        {
            CalculoMissaoResult calculo = cmrsMapByAeronaveId.get(aeronave.Id);

            if(calculo.tempoMissao > this.tempoMissao)
            {
                this.tempoMissao = calculo.tempoMissao;
                this.tempoTransladoIda = calculo.tempoTransladoIda;
                this.tempoTransladoRetorno = calculo.tempoTransladoRetorno;
            }

            List<Event> eventosDaAeronave = eventosPorAeronave.get(aeronave.Id);

            Integer podeVoar = EventsService.podeExecutarVoo(calculo, this.data, eventosDaAeronave, new Voo__c(Tipo__c = 'Charter'));

            if (podeVoar > 0) {
                if (this.data > cmrsMapByAeronaveId.get(aeronave.Id).hrMaximoDecolagem) {
                    podeVoar = 0;
                }
            }

            if(podeVoar > 0)
            {
                if (this.aeronave == null) {
                    this.aeronave = aeronave;
                }

                aeronavesValidas++;
                this.aeronavesDisponiveis++;
            }else {
                this.aeronavesDisponiveis += Math.abs(podeVoar);
            }
        }

        this.invalido = this.invalido || aeronavesValidas == 0;        
    }

    private void carregaDadosPreco (
        Id produtoId, id modeloId, String quem, Id contaId, Map<Id, List<RegraProduto__c>> regrasDosProdutos,
        Map<Id, List<RegraPreco__c>> regrasDosPrecos, Map<Id, List<RegraDesconto__c>> regrasDeDescontos, 
        CodigoPromocional__c codigo, Boolean codigoJaUtilizado, Boolean primeiraCompra
    ) 
    {

        List<RegraProduto__c> regrasProdutos = regrasDosProdutos.containsKey(produtoId) ? regrasDosProdutos.get(produtoId) : new List<RegraProduto__c>();        
        List<RegraPreco__c> regrasPrecos = regrasDosPrecos.containsKey(produtoId) ? regrasDosPrecos.get(produtoId) : new List<RegraPreco__c>();
        List<RegraDesconto__c> regrasDescontos = regrasDeDescontos.containsKey(produtoId) ? regrasDeDescontos.get(produtoId) : new List<RegraDesconto__c>();

        
        Decimal quantidade = this.tempoMissao / 60;
        quantidade = quantidade.setScale(2, RoundingMode.HALF_UP);

        CalculaPrecosParaPesquisa.CalculaPrecosParaPesquisaResult result = CalculaPrecosParaPesquisa.calculaPrecosVoos(
            produtoId, contaId, quem, null, null, this.data, modeloId, quantidade, 
            regrasProdutos, regrasPrecos, regrasDescontos, codigo, 
            codigoJaUtilizado, primeiraCompra, true, false
        );

        this.invalido = this.invalido || result.invalido;

        if (this.invalido) return;

        this.precoUnitario = result.precoUnitario;
        this.precoRevoSeats = result.precoRevoSeats;
        this.descontoPerc = result.descontoPerc;
        this.descontoValor = result.descontoValor;
        this.promocaoValida = result.promocaoValida;
        this.idPromocional = result.idPromocional;
        this.codigoPromocionalApurado = result.codigoPromocionalApurado;
        this.precoFinal = result.precoFinal;
        this.precoFinalRevoSeats = result.precoFinalRevoSeats;
    }

    private void carregaDadosServicos(
        Id produtoId, Id modeloId, String quem, Id contaId, List<ConfiguracaoPacote__c> configuracaoPacotes,
        Map<Id, List<RegraProduto__c>> regrasDosProdutos, Map<Id, List<RegraPreco__c>> regrasDosPrecos, 
        Map<Id, List<RegraDesconto__c>> regrasDeDescontos, CodigoPromocional__c codigo,
        Boolean codigoJaUtilizado, Boolean primeiraCompra,
        Map<Id, CalculoMissaoResult> cmrsMapByAeronaveId, List<Aeronave__c> aeronaves, 
        Map<Id, Integer> servicosContratados, Local__c origem, Local__c destino
    ) 
    {
        for (ConfiguracaoPacote__c config : configuracaoPacotes) {

            if(servicosIds.contains(config.id)) continue;
            
            ServicoDoPacote.ServicoDoPacoteCache cache = new ServicoDoPacote.ServicoDoPacoteCache();

            cache.quem = quem;
            cache.produtoId = config.ProdutoPacote__c;
            cache.produtoPaiId = produtoId;
            cache.quantidadePai = 1;

            cache.origemId = origem.Id;
            cache.destinoId = destino.Id;
            cache.modeloId = modeloId;
            cache.previsaoDecolagem = this.data;

            cache.contaId = contaId;
            cache.quantidade = config.QuantidadeRelativa__c == 'Pelo Padrão' ? config.QuantidadePadrao__c.intValue() : cache.quantidadePai;
            cache.quantidade = servicosContratados.containsKey(config.ProdutoPacote__c) ? servicosContratados.get(config.ProdutoPacote__c) : cache.quantidade;
            cache.configuracaoPacote = config;
            cache.porPassageiro = config.QuantidadeRelativa__c != 'Pelo Padrão';

            cache.regraPrecos = regrasDosPrecos.containsKey(config.ProdutoPacote__c) ? regrasDosPrecos.get(config.ProdutoPacote__c) : new List<RegraPreco__c>();
            cache.regraProdutos = regrasDosProdutos.containsKey(config.ProdutoPacote__c) ? regrasDosProdutos.get(config.ProdutoPacote__c) : new List<RegraProduto__c>();
            cache.regraDescontos = regrasDeDescontos.containsKey(config.ProdutoPacote__c) ? regrasDeDescontos.get(config.ProdutoPacote__c) : new List<RegraDesconto__c>();
            cache.codigoPromocional = codigo;
            cache.codigoJaUtilizado = codigoJaUtilizado;
            cache.primeiraCompra = primeiraCompra;

            ServicoDoPacote servico = new ServicoDoPacote(cache);
            
            if (!servico.invalido) {
                this.servicosIds.add(config.id);
                this.servicos.add(servico);
            } 
        }        
    }    

    // #endregion
}