force-app/main/default/objects/Aeronave__c/Aeronave__c.object-meta.xml
<CustomObject>
    <label>Aeronave</label>
    <nameField>
        <label>Prefixo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aeronaves</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Aeronave__c/fields/BaseMae__c.field-meta.xml
<CustomField>
    <fullName>BaseMae__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Base Mãe da Aeronave</description>
    <inlineHelpText>Base Mãe da Aeronave</inlineHelpText>
    <label>Base Mãe</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Local__c.Base__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Local__c</referenceTo>
    <relationshipLabel>Aeronaves Hospedadas</relationshipLabel>
    <relationshipName>AeronaveLocal</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Aeronave__c/fields/ModeloAeronave__c.field-meta.xml
<CustomField>
    <fullName>ModeloAeronave__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Define o modelo de aeronave</description>
    <inlineHelpText>Define o modelo de aeronave</inlineHelpText>
    <label>Modelo de aeronave</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Aeronaves</relationshipLabel>
    <relationshipName>Aeronaves</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EnvelopeAeronave__c/EnvelopeAeronave__c.object-meta.xml
<CustomObject>
    <label>Envelope da Aeronave</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Nome de EnvelopeAeronave</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Envelope da Aeronave</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EnvelopeAeronave__c/fields/Aeronave__c.field-meta.xml
<CustomField>
    <fullName>Aeronave__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Aeronave</label>
    <referenceTo>Aeronave__c</referenceTo>
    <relationshipLabel>Envelope da Aeronave</relationshipLabel>
    <relationshipName>EnvelopeAeronave</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EnvelopeAeronave__c/fields/balanceamento__c.field-meta.xml
<CustomField>
    <fullName>balanceamento__c</fullName>
    <label>Braço</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EnvelopeAeronave__c/fields/Peso__c.field-meta.xml
<CustomField>
    <fullName>Peso__c</fullName>
    <label>Peso</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Local__c/Local__c.object-meta.xml
<CustomObject>
    <label>Local</label>
    <nameField>
        <label>Local</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/EnvelopeAeronaveControllerTest.cls
@isTest
public with sharing class EnvelopeAeronaveControllerTest 
{
    @TestSetup
    static void makeData()
    {
        TestUtil.SetupStandardPricebook();
        
        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();       
        
        Local__c baseMae = TestUtil.carregaLocais(1)[0];
        uow.registerNew(baseMae);
        List<Product2> modelos = new List<Product2>{TestUtil.createProduct('Modelo'), TestUtil.createProduct('Modelo2')};
        insert modelos;
        Integer j = 1;
        for(Product2 modelo : modelos)
        {
            for(Integer i = 1; i < 5; i++)
            {
                Aeronave__c aeronave = TestUtil.carregaAeronave('Aeronave ' + i + '-' + j);
                uow.registerRelationship(aeronave, Aeronave__c.BaseMae__c, baseMae);
                uow.registerNew(aeronave, Aeronave__c.ModeloAeronave__c, modelo);
            }
            j++;
        }   
        uow.commitWork();
        Aeronave__c aeronave = [SELECT Id FROM Aeronave__c LIMIT 1];
        EnvelopeAeronave__c envelope = new EnvelopeAeronave__c(Aeronave__c = aeronave.Id, Peso__c = 17300, balanceamento__c = 360);
        insert envelope;
    }
    @IsTest
    static void pageTest()
    {
        EnvelopeAeronaveController envelope = new EnvelopeAeronaveController();
        Test.startTest();
        PageReference pageRef = Page.envelopeAeronave;
        Aeronave__c aeronave = [SELECT Id FROM Aeronave__c LIMIT 1];
        Test.setCurrentPage(pageRef);
        pageRef.getParameters().put('id',aeronave.Id);
        pageRef.getParameters().put('atualValue1', '500');
        pageRef.getParameters().put('atualValue2', '500');
        pageRef.getParameters().put('zeroValue1', '500');
        pageRef.getParameters().put('zeroValue2', '500');
        ApexPages.StandardController sc = new ApexPages.standardController(aeronave);
        EnvelopeAeronaveController controller = new EnvelopeAeronaveController(sc);
        
        Test.stopTest();
        
    }
    @IsTest
    static void atributtesTest()
    {
        EnvelopeAeronaveController envelope = new EnvelopeAeronaveController();
        System.assertEquals(System.Label.Braco, envelope.braco, 'Algo deu errado - atributtesTest() - EnvelopeAeronaveController');
        System.assertEquals(System.Label.PesoEnvelope, envelope.peso, 'Algo deu errado - atributtesTest() - EnvelopeAeronaveController');
        System.assertEquals(System.Label.EnvelopeCG, envelope.envelope, 'Algo deu errado - atributtesTest() - EnvelopeAeronaveController');
        System.assertEquals(System.Label.PasseioCG, envelope.passeio, 'Algo deu errado - atributtesTest() - EnvelopeAeronaveController');
        System.assertEquals(System.Label.CGAtual, envelope.cgAtual, 'Algo deu errado - atributtesTest() - EnvelopeAeronaveController');
        System.assertEquals(System.Label.CGZeroComb, envelope.cgZeroComb, 'Algo deu errado - atributtesTest() - EnvelopeAeronaveController');
    }
}