force-app/main/default/objects/Aeronave__c/Aeronave__c.object-meta.xml
<CustomObject>
    <label>Aeronave</label>
    <nameField>
        <label>Prefixo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aeronaves</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ConfiguracaoPacote__c/ConfiguracaoPacote__c.object-meta.xml
<CustomObject>
    <label>Configuração do Pacote</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Configuração do Pacote</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Configurações dos Pacotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ConfiguracaoPacote__c/fields/Empacotado__c.field-meta.xml
<CustomField>
    <fullName>Empacotado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Empacotado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ConfiguracaoPacote__c/fields/Obrigatorio__c.field-meta.xml
<CustomField>
    <fullName>Obrigatorio__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Obrigatório</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ConfiguracaoPacote__c/fields/Posicao__c.field-meta.xml
<CustomField>
    <fullName>Posicao__c</fullName>
    <label>Posição</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConfiguracaoPacote__c/fields/ProdutoPacote__c.field-meta.xml
<CustomField>
    <fullName>ProdutoPacote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto do Pacote</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>ServicosTaxas</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Configurações dos Pacotes</relationshipLabel>
    <relationshipName>Configuracoes_dos_Pacotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ConfiguracaoPacote__c/fields/ProdutoPai__c.field-meta.xml
<CustomField>
    <fullName>ProdutoPai__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto Pai</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Configurações dos Pacotes</relationshipLabel>
    <relationshipName>ConfiguracoesPacotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ConfiguracaoPacote__c/fields/QuantidadePadrao__c.field-meta.xml
<CustomField>
    <fullName>QuantidadePadrao__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Quantidade Padrão</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConfiguracaoPacote__c/fields/QuantidadeRelativa__c.field-meta.xml
<CustomField>
    <fullName>QuantidadeRelativa__c</fullName>
    <label>Quantidade Relativa</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pelo Padrão</fullName>
                <default>true</default>
                <label>Pelo Padrão</label>
            </value>
            <value>
                <fullName>Por Passageiros</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ConfiguracaoPacote__c/fields/Selecionado__c.field-meta.xml
<CustomField>
    <fullName>Selecionado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Selecionado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Local__c/Local__c.object-meta.xml
<CustomObject>
    <label>Local</label>
    <nameField>
        <label>Local</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Local__c/fields/CodigoLocal__c.field-meta.xml
<CustomField>
    <fullName>CodigoLocal__c</fullName>
    <description>Código que identifica o local</description>
    <externalId>true</externalId>
    <inlineHelpText>Código que identifica o local</inlineHelpText>
    <label>Código do local</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/MalhaVoo__c/MalhaVoo__c.object-meta.xml
<CustomObject>
    <label>Malha de Voo</label>
    <nameField>
        <displayFormat>MV-{000000}</displayFormat>
        <label>Malha de Voo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Malhas de Voos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MalhaVoo__c/fields/Ativa__c.field-meta.xml
<CustomField>
    <fullName>Ativa__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ativa</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MalhaVoo__c/fields/Destino__c.field-meta.xml
<CustomField>
    <fullName>Destino__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Destino</label>
    <referenceTo>Local__c</referenceTo>
    <relationshipLabel>Malhas de Voos (Destino)</relationshipLabel>
    <relationshipName>MalhasVoosDestino</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MalhaVoo__c/fields/Duracao__c.field-meta.xml
<CustomField>
    <fullName>Duracao__c</fullName>
    <inlineHelpText>Duração do voo em minutos que será exibido na pesquisa de malha de voo</inlineHelpText>
    <label>Duração</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MalhaVoo__c/fields/Origem__c.field-meta.xml
<CustomField>
    <fullName>Origem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Origem</label>
    <referenceTo>Local__c</referenceTo>
    <relationshipLabel>Malhas de Voos</relationshipLabel>
    <relationshipName>MalhasVoosOrigem</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MalhaVoo__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>ShuttleSeat</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Malhas de Voos</relationshipLabel>
    <relationshipName>Malhas_de_Voos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MalhaVoo__c/fields/SegundaFeira__c.field-meta.xml
<CustomField>
    <fullName>SegundaFeira__c</fullName>
    <label>Segunda-feira</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Programacao</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PrioridadeMalha__c/PrioridadeMalha__c.object-meta.xml
<CustomObject>
    <label>Prioridade da Malha</label>
    <nameField>
        <displayFormat>PRIO-{0000000}</displayFormat>
        <label>Prioridade da Malha</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prioridades da Malha</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PrioridadeMalha__c/fields/Aeronave__c.field-meta.xml
<CustomField>
    <fullName>Aeronave__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Aeronave</label>
    <referenceTo>Aeronave__c</referenceTo>
    <relationshipLabel>Prioridades da Malha</relationshipLabel>
    <relationshipName>PrioridadesMalha</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PrioridadeMalha__c/fields/MalhaVoo__c.field-meta.xml
<CustomField>
    <fullName>MalhaVoo__c</fullName>
    <label>Malha de Voo</label>
    <referenceTo>MalhaVoo__c</referenceTo>
    <relationshipLabel>Prioridades da Malha</relationshipLabel>
    <relationshipName>PrioridadesMalha</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Programacao.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>00:00</fullName>
    </customValue>
    <customValue>
        <fullName>00:05</fullName>
    </customValue>
    <customValue>
        <fullName>00:10</fullName>
    </customValue>
    <customValue>
        <fullName>00:15</fullName>
    </customValue>
    <customValue>
        <fullName>00:20</fullName>
    </customValue>
    <customValue>
        <fullName>00:25</fullName>
    </customValue>
    <customValue>
        <fullName>00:30</fullName>
    </customValue>
    <customValue>
        <fullName>00:35</fullName>
    </customValue>
    <customValue>
        <fullName>00:40</fullName>
    </customValue>
    <customValue>
        <fullName>00:45</fullName>
    </customValue>
    <customValue>
        <fullName>00:50</fullName>
    </customValue>
    <customValue>
        <fullName>00:55</fullName>
    </customValue>
    <customValue>
        <fullName>01:00</fullName>
    </customValue>
    <customValue>
        <fullName>01:05</fullName>
    </customValue>
    <customValue>
        <fullName>01:10</fullName>
    </customValue>
    <customValue>
        <fullName>01:15</fullName>
    </customValue>
    <customValue>
        <fullName>01:20</fullName>
    </customValue>
    <customValue>
        <fullName>01:25</fullName>
    </customValue>
    <customValue>
        <fullName>01:30</fullName>
    </customValue>
    <customValue>
        <fullName>01:35</fullName>
    </customValue>
    <customValue>
        <fullName>01:40</fullName>
    </customValue>
    <customValue>
        <fullName>01:45</fullName>
    </customValue>
    <customValue>
        <fullName>01:50</fullName>
    </customValue>
    <customValue>
        <fullName>01:55</fullName>
    </customValue>
    <customValue>
        <fullName>02:00</fullName>
    </customValue>
    <customValue>
        <fullName>02:05</fullName>
    </customValue>
    <customValue>
        <fullName>02:10</fullName>
    </customValue>
    <customValue>
        <fullName>02:15</fullName>
    </customValue>
    <customValue>
        <fullName>02:20</fullName>
    </customValue>
    <customValue>
        <fullName>02:25</fullName>
    </customValue>
    <masterLabel>Programação</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RevoSiteShuttleSearchTest.cls
@IsTest
private class RevoSiteShuttleSearchTest {

    @TestSetup
    static void setup() {
        RevoTestUtil.setupSiteUser('ws-user');
        RevoTestUtil.ConfigurarProdutosEServicos();
    }

    @IsTest
    static void testSearch() {
        // Cria usuário do site com conta vinculada
        
        RevoTestUtil.setupRestContext('/services/apexrest/revosite/v1/shuttle/search', 'POST');

        // Monta o payload com webSiteUserId existente
        RevoSiteShuttleSearch.ShuttleSeatSearch param = new RevoSiteShuttleSearch.ShuttleSeatSearch();
        param.webSiteUserId = 'ws-user';
        param.departurePointId = [SELECT Id FROM Local__c WHERE CodigoLocal__c = 'SBGR' limit 1].Id;
        param.destinationPointId = [SELECT Id FROM Local__c WHERE CodigoLocal__c = 'SDOF' limit 1].Id;
        param.quantity = 1;
        param.flightDate = Date.today().addDays(1);
        param.dateOffSet = 1;
        param.promotionalCode = 'PROMO10';

        Test.startTest();
        RevoSiteShuttleSearch.search(param);
        Test.stopTest();
        // Verifica se retornou pelo menos uma configuração de data disponível
        System.assertNotEquals(null, RestContext.response.responseBody, 'Resposta deve ter corpo');
        
        // Deserializa o JSON para verificar se há pelo menos uma configuração disponível
        String responseBody = RestContext.response.responseBody.toString();
        
        List<RevoSiteShuttleSearch.ShuttleSeatResults> results = 
            (List<RevoSiteShuttleSearch.ShuttleSeatResults>) JSON.deserialize(responseBody, List<RevoSiteShuttleSearch.ShuttleSeatResults>.class);
        
        System.assert(results != null && results.size() > 0, 'Deve retornar pelo menos uma configuração de data disponível');
    }

    @IsTest
    static void testCheckoutWithoutConfirmation() {
        
        MalhaVoo__c malhaVoo = [SELECT Id, Origem__c, Destino__c, Produto__c, Duracao__c, SegundaFeira__c,
                                (SELECT Aeronave__r.ModeloAeronave__c FROM PrioridadesMalha__r)
                                FROM MalhaVoo__c WHERE Ativa__c = true LIMIT 1];
        
        // Cria parâmetro de checkout baseado no resultado da busca
        RevoSiteCheckout.OpportunityCheckout checkoutParam = new RevoSiteCheckout.OpportunityCheckout();
        checkoutParam.webSiteUserId = 'ws-user';
        checkoutParam.confirmCheckout = false;
        checkoutParam.oppotunityType = 'ShuttleSeat';
        checkoutParam.source = 'Site';
        checkoutParam.promotionalCode = 'PROMO10';
        checkoutParam.priceBlockUntil = DateTime.now().addDays(1);
        // Cria lista de shuttle seats baseada no resultado

        String horaVoo = malhaVoo.SegundaFeira__c.split(';')[3];
        DateTime dataHoraVoo = DateTime.newInstance(System.today().addDays(1), Time.newInstance(Integer.valueOf(horaVoo.split(':')[0]), 
        Integer.valueOf(horaVoo.split(':')[1]), 0, 0));

        List<RevoSiteCheckout.ShuttleSeat> shuttleSeats = new List<RevoSiteCheckout.ShuttleSeat>();
        RevoSiteCheckout.ShuttleSeat shuttleSeat = new RevoSiteCheckout.ShuttleSeat();

        Integer quantidadePassageiros = 1;

        shuttleSeat.key = 'shuttle-1';
        shuttleSeat.productId = malhaVoo.Produto__c;
        shuttleSeat.aircraftModelId = malhaVoo.PrioridadesMalha__r[0].Aeronave__r.ModeloAeronave__c;
        shuttleSeat.routeId = malhaVoo.Id;
        shuttleSeat.departurePointId = malhaVoo.Origem__c;
        shuttleSeat.destinationPointId = malhaVoo.Destino__c;
        shuttleSeat.flightDateTime = dataHoraVoo;
        shuttleSeat.missionTime = malhaVoo.Duracao__c;
        shuttleSeat.unitPrice = 1000;
        shuttleSeat.quantity = quantidadePassageiros; // Número de passageiros
        shuttleSeat.percDiscount = 10;
        shuttleSeat.valueDiscount = 0;
        shuttleSeat.totalPrice = 900;
        shuttleSeat.appliedPromotion = true;
    

        List<ConfiguracaoPacote__c> servicos = [SELECT Id, Empacotado__c, Obrigatorio__c, Posicao__c,
        ProdutoPacote__c, ProdutoPai__c, QuantidadePadrao__c, QuantidadeRelativa__c, Selecionado__c
         FROM ConfiguracaoPacote__c WHERE ProdutoPai__c = :malhaVoo.Produto__c];

        List<RevoSiteCheckout.PackageServices> checkoutServices = new List<RevoSiteCheckout.PackageServices>();
        for (ConfiguracaoPacote__c service : servicos) {
            RevoSiteCheckout.PackageServices checkoutService = new RevoSiteCheckout.PackageServices();
            checkoutService.productId = service.ProdutoPacote__c;
            checkoutService.required = service.Obrigatorio__c;
            checkoutService.Bundled = service.Empacotado__c;
            checkoutService.selected = service.Selecionado__c;
            checkoutService.passengerQty = service.QuantidadeRelativa__c == 'Por Passageiros' ? true : false;
            checkoutService.position = service.Posicao__c.intValue();
            checkoutService.unitPrice = 150.00;
            checkoutService.quantity = service.QuantidadePadrao__c.intValue();
            checkoutService.percDiscount = 10;
            checkoutService.valueDiscount = 0;
            checkoutService.totalPrice = 130.00;
            checkoutService.appliedPromotion = true;
            
            // Cria passenger services para cada passageiro se o serviço for por passageiro
            List<RevoSiteCheckout.PassengerService> passengerServices = new List<RevoSiteCheckout.PassengerService>();
            if (checkoutService.passengerQty ) {
                for (Integer i = 0; i < quantidadePassageiros; i++) {
                    RevoSiteCheckout.PassengerService passengerService = new RevoSiteCheckout.PassengerService();
                    passengerService.keyPassenger = 'passenger-' + (i + 1);
                    passengerService.serviceAddress = 'Rua Teste ' + (i + 1);
                    passengerService.servicecity = 'São Paulo';
                    passengerService.servicestate = 'SP';
                    passengerService.servicezipcode = '01234-567';
                    passengerService.servicecountry = 'BR';
                    passengerService.serviceaddressLine2 = 'Apto ' + (i + 1);
                    passengerService.serviceAirline = 'LATAM';
                    passengerService.serviceFlightNumber = 'LA1234';
                    passengerService.smallBags = 1;
                    passengerService.mediumBags = 0;
                    passengerService.bigBags = 0;
                    passengerServices.add(passengerService);
                }
            }
            checkoutService.passengerServices = passengerServices;
            checkoutServices.add(checkoutService);
        }
        shuttleSeat.services = checkoutServices;
        
        
        // Cria passenger services gerais para o shuttle seat
        List<RevoSiteCheckout.PassengerService> shuttlePassengerServices = new List<RevoSiteCheckout.PassengerService>();
        for (Integer i = 0; i < quantidadePassageiros ; i++) {
            RevoSiteCheckout.PassengerService passengerService = new RevoSiteCheckout.PassengerService();
            passengerService.keyPassenger = 'passenger-' + (i + 1);
            passengerService.serviceAddress = 'Rua Teste ' + (i + 1);
            passengerService.servicecity = 'São Paulo';
            passengerService.servicestate = 'SP';
            passengerService.servicezipcode = '01234-567';
            passengerService.servicecountry = 'BR';
            passengerService.serviceaddressLine2 = 'Apto ' + (i + 1);
            passengerService.serviceAirline = 'LATAM';
            passengerService.serviceFlightNumber = 'LA1234';
            passengerService.smallBags = 1;
            passengerService.mediumBags = 0;
            passengerService.bigBags = 0;
            shuttlePassengerServices.add(passengerService);
        }
        shuttleSeat.passengerServices = shuttlePassengerServices;
        shuttleSeats.add(shuttleSeat);
        checkoutParam.shuttleSeats = shuttleSeats;
        
        // Cria lista de passageiros baseada na quantidade
        List<RevoSiteCheckout.Passenger> passengers = new List<RevoSiteCheckout.Passenger>();
        for (Integer i = 0; i < quantidadePassageiros ; i++) {
            RevoSiteCheckout.Passenger passenger = new RevoSiteCheckout.Passenger();
            passenger.key = 'passenger-' + (i + 1);
            passenger.fullName = 'Passageiro ' + (i + 1);
            passenger.birthDate = Date.today().addYears(-30);
            passenger.nationality = 'BR';
            passenger.documentType = 'CPF';
            passenger.document = GeraCpfCnpj.cpf(true);
            passenger.email = 'passageiro' + (i + 1) + '@test.com';
            passenger.phone = '11999999999';
            passenger.hasSpecialNeeds = false;
            passenger.smallBags = 1;
            passenger.mediumBags = 0;
            passenger.bigBags = 0;
            passengers.add(passenger);
        }
        checkoutParam.passengers = passengers;
        RevoTestUtil.setupRestContext('/services/apexrest/revosite/v1/checkout', 'POST');

        Test.startTest();
        RevoSiteCheckout.checkout(checkoutParam);
        Test.stopTest();
        
        // Verifica se o checkout retornou resposta
        System.assertNotEquals(null, RestContext.response.responseBody, 'Checkout deve retornar resposta');
        
        // Deserializa o retorno do checkout
        String responseBodyString = RestContext.response.responseBody.toString();
        RevoSiteCheckout.CheckoutResult checkoutResult = (RevoSiteCheckout.CheckoutResult) JSON.deserialize(responseBodyString, RevoSiteCheckout.CheckoutResult.class);
        
        // Verifica se gerou ID de oportunidade
        System.assertEquals(null, checkoutResult.opportunityId, 'Deve gerar ID de oportunidade');
        
        // Verifica se gerou ID de pagamento
        System.assertEquals(null, checkoutResult.paymentId, 'Deve gerar ID de pagamento');
        
        // Verifica se o status da oportunidade foi definido
        System.assertEquals(null, checkoutResult.opportunityStatus, 'Status da oportunidade deve ser definido');
    }

    @IsTest
    static void testCheckoutWithConfirmation() {
        
        MalhaVoo__c malhaVoo = [SELECT Id, Origem__c, Destino__c, Produto__c, Duracao__c, SegundaFeira__c,
                                (SELECT Aeronave__r.ModeloAeronave__c FROM PrioridadesMalha__r)
                                FROM MalhaVoo__c WHERE Ativa__c = true LIMIT 1];
        
        // Cria parâmetro de checkout baseado no resultado da busca
        RevoSiteCheckout.OpportunityCheckout checkoutParam = new RevoSiteCheckout.OpportunityCheckout();
        checkoutParam.webSiteUserId = 'ws-user';
        checkoutParam.confirmCheckout = true;
        checkoutParam.oppotunityType = 'ShuttleSeat';
        checkoutParam.source = 'Site';
        checkoutParam.promotionalCode = 'PROMO10';
        checkoutParam.priceBlockUntil = DateTime.now().addDays(1);
        // Cria lista de shuttle seats baseada no resultado

        String horaVoo = malhaVoo.SegundaFeira__c.split(';')[3];
        DateTime dataHoraVoo = DateTime.newInstance(System.today().addDays(1), Time.newInstance(Integer.valueOf(horaVoo.split(':')[0]), 
        Integer.valueOf(horaVoo.split(':')[1]), 0, 0));

        List<RevoSiteCheckout.ShuttleSeat> shuttleSeats = new List<RevoSiteCheckout.ShuttleSeat>();
        RevoSiteCheckout.ShuttleSeat shuttleSeat = new RevoSiteCheckout.ShuttleSeat();

        Integer quantidadePassageiros = 1;

        shuttleSeat.key = 'shuttle-1';
        shuttleSeat.productId = malhaVoo.Produto__c;
        shuttleSeat.aircraftModelId = malhaVoo.PrioridadesMalha__r[0].Aeronave__r.ModeloAeronave__c;
        shuttleSeat.routeId = malhaVoo.Id;
        shuttleSeat.departurePointId = malhaVoo.Origem__c;
        shuttleSeat.destinationPointId = malhaVoo.Destino__c;
        shuttleSeat.flightDateTime = dataHoraVoo;
        shuttleSeat.missionTime = malhaVoo.Duracao__c;
        shuttleSeat.unitPrice = 1000;
        shuttleSeat.quantity = quantidadePassageiros; // Número de passageiros
        shuttleSeat.percDiscount = 10;
        shuttleSeat.valueDiscount = 0;
        shuttleSeat.totalPrice = 900;
        shuttleSeat.appliedPromotion = true;
    

        List<ConfiguracaoPacote__c> servicos = [SELECT Id, Empacotado__c, Obrigatorio__c, Posicao__c,
        ProdutoPacote__c, ProdutoPai__c, QuantidadePadrao__c, QuantidadeRelativa__c, Selecionado__c
         FROM ConfiguracaoPacote__c WHERE ProdutoPai__c = :malhaVoo.Produto__c];

        List<RevoSiteCheckout.PackageServices> checkoutServices = new List<RevoSiteCheckout.PackageServices>();
        for (ConfiguracaoPacote__c service : servicos) {
            RevoSiteCheckout.PackageServices checkoutService = new RevoSiteCheckout.PackageServices();
            checkoutService.productId = service.ProdutoPacote__c;
            checkoutService.required = service.Obrigatorio__c;
            checkoutService.Bundled = service.Empacotado__c;
            checkoutService.selected = service.Selecionado__c;
            checkoutService.passengerQty = service.QuantidadeRelativa__c == 'Por Passageiros' ? true : false;
            checkoutService.position = service.Posicao__c.intValue();
            checkoutService.unitPrice = 150.00;
            checkoutService.quantity = service.QuantidadePadrao__c.intValue();
            checkoutService.percDiscount = 10;
            checkoutService.valueDiscount = 0;
            checkoutService.totalPrice = 130.00;
            checkoutService.appliedPromotion = true;
            
            // Cria passenger services para cada passageiro se o serviço for por passageiro
            List<RevoSiteCheckout.PassengerService> passengerServices = new List<RevoSiteCheckout.PassengerService>();
            if (checkoutService.passengerQty ) {
                for (Integer i = 0; i < quantidadePassageiros; i++) {
                    RevoSiteCheckout.PassengerService passengerService = new RevoSiteCheckout.PassengerService();
                    passengerService.keyPassenger = 'passenger-' + (i + 1);
                    passengerService.serviceAddress = 'Rua Teste ' + (i + 1);
                    passengerService.servicecity = 'São Paulo';
                    passengerService.servicestate = 'SP';
                    passengerService.servicezipcode = '01234-567';
                    passengerService.servicecountry = 'BR';
                    passengerService.serviceaddressLine2 = 'Apto ' + (i + 1);
                    passengerService.serviceAirline = 'LATAM';
                    passengerService.serviceFlightNumber = 'LA1234';
                    passengerService.smallBags = 1;
                    passengerService.mediumBags = 0;
                    passengerService.bigBags = 0;
                    passengerServices.add(passengerService);
                }
            }
            checkoutService.passengerServices = passengerServices;
            checkoutServices.add(checkoutService);
        }
        shuttleSeat.services = checkoutServices;
        
        
        // Cria passenger services gerais para o shuttle seat
        List<RevoSiteCheckout.PassengerService> shuttlePassengerServices = new List<RevoSiteCheckout.PassengerService>();
        for (Integer i = 0; i < quantidadePassageiros ; i++) {
            RevoSiteCheckout.PassengerService passengerService = new RevoSiteCheckout.PassengerService();
            passengerService.keyPassenger = 'passenger-' + (i + 1);
            passengerService.serviceAddress = 'Rua Teste ' + (i + 1);
            passengerService.servicecity = 'São Paulo';
            passengerService.servicestate = 'SP';
            passengerService.servicezipcode = '01234-567';
            passengerService.servicecountry = 'BR';
            passengerService.serviceaddressLine2 = 'Apto ' + (i + 1);
            passengerService.serviceAirline = 'LATAM';
            passengerService.serviceFlightNumber = 'LA1234';
            passengerService.smallBags = 1;
            passengerService.mediumBags = 0;
            passengerService.bigBags = 0;
            shuttlePassengerServices.add(passengerService);
        }
        shuttleSeat.passengerServices = shuttlePassengerServices;
        shuttleSeats.add(shuttleSeat);
        checkoutParam.shuttleSeats = shuttleSeats;
        
        // Cria lista de passageiros baseada na quantidade
        List<RevoSiteCheckout.Passenger> passengers = new List<RevoSiteCheckout.Passenger>();
        for (Integer i = 0; i < quantidadePassageiros ; i++) {
            RevoSiteCheckout.Passenger passenger = new RevoSiteCheckout.Passenger();
            passenger.key = 'passenger-' + (i + 1);
            passenger.fullName = 'Passageiro ' + (i + 1);
            passenger.birthDate = Date.today().addYears(-30);
            passenger.nationality = 'BR';
            passenger.documentType = 'CPF';
            passenger.document = GeraCpfCnpj.cpf(true);
            passenger.email = 'passageiro' + (i + 1) + '@test.com';
            passenger.phone = '11999999999';
            passenger.hasSpecialNeeds = false;
            passenger.smallBags = 1;
            passenger.mediumBags = 0;
            passenger.bigBags = 0;
            passengers.add(passenger);
        }
        checkoutParam.passengers = passengers;
        RevoTestUtil.setupRestContext('/services/apexrest/revosite/v1/checkout', 'POST');

        Test.startTest();
        RevoSiteCheckout.checkout(checkoutParam);
        Test.stopTest();
        
        // Verifica se o checkout retornou resposta
        System.assertNotEquals(null, RestContext.response.responseBody, 'Checkout deve retornar resposta');
        
        // Deserializa o retorno do checkout
        String responseBodyString = RestContext.response.responseBody.toString();
        RevoSiteCheckout.CheckoutResult checkoutResult = (RevoSiteCheckout.CheckoutResult) JSON.deserialize(responseBodyString, RevoSiteCheckout.CheckoutResult.class);
        
        // Verifica se gerou ID de oportunidade
        System.assertNotEquals(null, checkoutResult.opportunityId, 'Deve gerar ID de oportunidade');
        System.assertNotEquals('', checkoutResult.opportunityId, 'ID de oportunidade não pode estar vazio');
        
        // Verifica se gerou ID de pagamento
        System.assertNotEquals(null, checkoutResult.paymentId, 'Deve gerar ID de pagamento');
        System.assertNotEquals('', checkoutResult.paymentId, 'ID de pagamento não pode estar vazio');
        
        // Verifica se o status da oportunidade foi definido
        System.assertNotEquals(null, checkoutResult.opportunityStatus, 'Status da oportunidade deve ser definido');
        System.assertNotEquals('', checkoutResult.opportunityStatus, 'Status da oportunidade não pode estar vazio');
    }
}