force-app/main/default/objects/Aeronave__c/Aeronave__c.object-meta.xml
<CustomObject>
    <label>Aeronave</label>
    <nameField>
        <label>Prefixo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aeronaves</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ConfiguracaoTempo__c/ConfiguracaoTempo__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Configurações de Tempo</label>
</CustomObject>

force-app/main/default/objects/ConfiguracaoTempo__c/fields/IntervaloEmDiasBuscaEventos__c.field-meta.xml
<CustomField>
    <fullName>IntervaloEmDiasBuscaEventos__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Intervalo em dias para buscar eventos relacionados a uma data.
Ex:. Se um voo vai ser inserido, e o intervalo é 15, irá buscar 15 dias antes e 15 dias depois de eventos para analisar referente ao voo</description>
    <inlineHelpText>Intervalo em dias para buscar eventos relacionados a uma data.</inlineHelpText>
    <label>Intervalo em Dias de Busca de Eventos</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConfiguracoesGerais__c/ConfiguracoesGerais__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Configurações Gerais</label>
</CustomObject>

force-app/main/default/objects/ConfiguracoesGerais__c/fields/IdChatterGrupoComercial__c.field-meta.xml
<CustomField>
    <fullName>IdChatterGrupoComercial__c</fullName>
    <label>Id Chatter Grupo Comercial</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trecho__c/Trecho__c.object-meta.xml
<CustomObject>
    <description>Define um trecho com origem e destino dentro de um Voo</description>
    <label>Trecho</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Código do Trecho</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trechos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trecho__c/fields/TempoCruzeiro__c.field-meta.xml
<CustomField>
    <fullName>TempoCruzeiro__c</fullName>
    <description>Tempo de cruzeiro para o trecho</description>
    <inlineHelpText>Tempo de cruzeiro para o trecho</inlineHelpText>
    <label>Tempo de cruzeiro</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trecho__c/fields/TempoSolo__c.field-meta.xml
<CustomField>
    <fullName>TempoSolo__c</fullName>
    <description>Tempo de solo para o trecho</description>
    <inlineHelpText>Tempo de solo para o trecho</inlineHelpText>
    <label>Tempo de solo</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trecho__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <description>Passageiro - Transporte apenas de passageiros no trecho
Carga e passageiro - Transporte de passageiros e carga no trecho
Cargueiro - Transporte apenas de carga no trecho
Translado - Translado da aeronave para reposicionamento
Translado com passageiro - Translado da aeronave para reposicionamento com passageiro a bordo
Comitiva</description>
    <inlineHelpText>Transporte apenas de passageiros no trecho
Transporte de passageiros e carga no trecho
Transporte apenas de carga no trecho
Translado da aeronave para reposicionamento
Translado da aeronave para reposicionamento com passageiro
Comitiva</inlineHelpText>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Passageiros</fullName>
            </value>
            <value>
                <fullName>Cargueiro</fullName>
            </value>
            <value>
                <fullName>Passageiros e Cargas</fullName>
            </value>
            <value>
                <fullName>Translado</fullName>
            </value>
            <value>
                <fullName>Translado com passageiro</fullName>
            </value>
            <value>
                <fullName>Comitiva</fullName>
            </value>
            <value>
                <fullName>Sanitário</fullName>
            </value>
            <value>
                <fullName>Treinamento</fullName>
            </value>
            <value>
                <fullName>SAR</fullName>
            </value>
            <value>
                <fullName>MEDVAC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trecho__c/fields/Voo__c.field-meta.xml
<CustomField>
    <fullName>Voo__c</fullName>
    <description>Voo ao qual o trecho pertence</description>
    <inlineHelpText>Voo ao qual o trecho pertence</inlineHelpText>
    <label>Voo</label>
    <referenceTo>Voo__c</referenceTo>
    <relationshipLabel>Trechos</relationshipLabel>
    <relationshipName>Trechos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Voo__c/Voo__c.object-meta.xml
<CustomObject>
    <description>O Voo de uma aeronave, do ponto de origem até o retorno</description>
    <label>Voo</label>
    <nameField>
        <displayFormat>REVO-{00000000}</displayFormat>
        <label>Número do Voo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Voos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Voo__c/fields/DataVoo__c.field-meta.xml
<CustomField>
    <fullName>DataVoo__c</fullName>
    <description>Dia e hora solicitada para a realização do voo</description>
    <inlineHelpText>Dia e hora solicitada para a realização do voo</inlineHelpText>
    <label>Data</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Voo__c/fields/RotaAbreviada__c.field-meta.xml
<CustomField>
    <fullName>RotaAbreviada__c</fullName>
    <description>Rota do Voo com locais abreviados</description>
    <inlineHelpText>Rota do Voo com locais abreviados</inlineHelpText>
    <label>Rota</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Voo__c/fields/TempoCorteCliente__c.field-meta.xml
<CustomField>
    <fullName>TempoCorteCliente__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Tempo de corte solicitado pelo cliente na tela de solicitação de voos</description>
    <inlineHelpText>Tempo total de corte que a aeronave fará durante o Voo. Solicitado pelo cliente na tela de solicitar Voo</inlineHelpText>
    <label>Corte Solicitado</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Voo__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <description>Informa o tipo de transporte realizado pelo voo.</description>
    <inlineHelpText>Informs the type of transport performed by the flight.</inlineHelpText>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TipoVoo</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/TipoVoo.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ShuttleSeat</fullName>
        <label>Shuttle Seat</label>
    </customValue>
    <customValue>
        <fullName>Charter</fullName>
    </customValue>
    <customValue>
        <fullName>FullCabin</fullName>
        <label>Full Cabin</label>
    </customValue>
    <customValue>
        <fullName>Sanitário</fullName>
        <isActive>false</isActive>
        <label>Sanitário</label>
    </customValue>
    <customValue>
        <fullName>Treinamento</fullName>
        <isActive>false</isActive>
        <label>Treinamento</label>
    </customValue>
    <customValue>
        <fullName>SAR</fullName>
        <isActive>false</isActive>
        <label>SAR</label>
    </customValue>
    <customValue>
        <fullName>Passageiros</fullName>
        <isActive>false</isActive>
        <label>Passageiros</label>
    </customValue>
    <customValue>
        <fullName>Manutenção</fullName>
        <isActive>false</isActive>
        <label>Manutenção</label>
    </customValue>
    <customValue>
        <fullName>Treinamento NDC</fullName>
        <isActive>false</isActive>
        <label>Treinamento NDC</label>
    </customValue>
    <customValue>
        <fullName>MEDVAC</fullName>
        <isActive>false</isActive>
        <label>MEDVAC</label>
    </customValue>
    <customValue>
        <fullName>Cargueiro</fullName>
        <isActive>false</isActive>
        <label>Cargueiro</label>
    </customValue>
    <customValue>
        <fullName>Passageiros e Cargas</fullName>
        <isActive>false</isActive>
        <label>Passageiros e Cargas</label>
    </customValue>
    <masterLabel>Tipo de voo</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Events.cls
public without sharing class Events extends fflib_SObjectDomain implements IEvents {
    
    public static FINAL String VOO_EVENT_SUBJECT = 'Voo';
    public static FINAL String ENTRE_VOOS_EVENT_SUBJECT = 'Entre Voos';
    static FINAL Id RECORD_TYPE_VOO_EVENT_ID = Schema.SObjectType.Event.getRecordTypeInfosByDeveloperName().get('Voo').getRecordTypeId();
    static FINAL Id RECORD_TYPE_MANUTENCAO_EVENT_ID = Schema.SObjectType.Event.getRecordTypeInfosByDeveloperName().get('Manutencao').getRecordTypeId();
    
    static FINAL Id RECORD_TYPE_ENTRE_VOOS_EVENT_ID = Schema.SObjectType.Event.getRecordTypeInfosByDeveloperName().get('EntreVoos').getRecordTypeId();
    
    public static IEvents newInstance(List<Event> sObjectList)
    {
        return (IEvents) Application.Domain.newInstance(sObjectList);
    }
    
    public Events(List<Event> sObjectList) {
        super(sObjectList);
    }
    
    public class Constructor implements fflib_SObjectDomain.IConstructable {
        public fflib_SObjectDomain construct(List<SObject> sObjectList) {
            return new Events(sObjectList);
        }
    }
    
    public List<Event> getEventByDeveloperName(String recordTypeName)
    {
        return getEventByDeveloperName(recordTypeName, null);
    }
    
    public List<Event> getEventByDeveloperName(String recordTypeName, String tipo)
    {
        Id RECORD_TYPE_EVENT_ID = Schema.SObjectType.Event.getRecordTypeInfosByDeveloperName().get(recordTypeName).getRecordTypeId();
        
        List<Event> eventsByType = new List<Event>();
        
        for(Event evt: (List<Event>) Records)
        {
            if(String.isNotBlank(evt.RecordTypeId) && evt.RecordTypeId.equals(RECORD_TYPE_EVENT_ID) &&
               (String.isBlank(tipo) || (String.isNotBlank(tipo) && evt.Type.equals(tipo))))
            {
                eventsByType.add(evt);
            }
        }
        
        return eventsByType;
    }
    
    public List<Event> getEntreVoos()
    {
        return getEntreVoos(null);
    }
    
    public List<Event> getEntreVoos(String tipo)
    {
        return getEventByDeveloperName('EntreVoos', tipo);
    }
    
    public List<Event> getManutencao()
    {
        return getEventByDeveloperName('Manutencao');
    }
    
    public List<Event> getVoo()
    {
        return getEventByDeveloperName('Voo');
    }
    
    public List<Event> groupEventsList(List<List<Event>> eventsToGroup)
    {
        List<Event> events = new List<Event>();
        for (List<Event> evtList : eventsToGroup)
        {
            events.addAll(evtList);
        }
        return events;
    }
    
    public static Datetime calculeDatetimeStartEvent(Voo__c voo, CalculoMissaoResult cmr)
    {
        if(voo == null) throw new EventsException('Para calcular data/hora de início do voo, o voo não pode ser nulo');
        if(cmr == null) throw new EventsException('Para calcular data/hora de início do voo, o CalculoMissaoResult não pode ser nulo');
        Integer TransladoIda = Integer.valueOf(cmr.tempoTransladoIda != null ? cmr.tempoTransladoIda : 0);
        Datetime activyDatetime = calculeDatetimeStartEvent(voo.DataVoo__c, TransladoIda);
        return activyDatetime;
    }
    
    public static Datetime calculeDatetimeStartEvent(Datetime dataVoo, Integer TransladoIda)
    {
        if(dataVoo == null) throw new EventsException('Para calcular data/hora de início do voo, a data/hora do voo não pode ser nulo');
        if(TransladoIda == null) throw new EventsException('Para calcular data/hora de início do voo, o translado de ida não pode ser nulo');
        Datetime activyDatetime = dataVoo.addMinutes(-TransladoIda);
        return activyDatetime;
    }
    
    public static Datetime calculeDatetimeEndEvent(Voo__c voo, CalculoMissaoResult cmr)
    {
        if(voo == null) throw new EventsException('Para calcular data/hora de fim do voo, o voo não pode ser nulo');
        if(cmr == null) throw new EventsException('Para calcular data/hora de fim do voo, o CalculoMissaoResult não pode ser nulo');
        Integer TransladoIda = Integer.valueOf(cmr.tempoTransladoIda != null ? cmr.tempoTransladoIda : 0);
        Integer TempoMissao = Integer.valueOf(cmr.tempoMissao != null ? cmr.tempoMissao : 0);
        Integer TempoCorteCliente = Integer.valueOf(voo.TempoCorteCliente__c != null ? voo.TempoCorteCliente__c : 0);
        Datetime endDateTime = calculeDatetimeEndEvent(voo.DataVoo__c, TransladoIda, TempoMissao, TempoCorteCliente);
        //System.debug('End Date: ' + endDateTime);
        return endDateTime;
    }
    
    public static Datetime calculeDatetimeEndEvent(Datetime dataVoo, Integer TransladoIda, Integer TempoMissao, Integer TempoCorteCliente)
    {
        if(dataVoo == null) throw new EventsException('Para calcular data/hora de fim do voo, a data do voo não pode ser nulo');
        if(TransladoIda == null) throw new EventsException('Para calcular data/hora de fim do voo, o translado de ida não pode ser nulo');
        if(TempoMissao == null) throw new EventsException('Para calcular data/hora de fim do voo, o tempo de missão não pode ser nulo');
        if(TempoCorteCliente == null) throw new EventsException('Para calcular data/hora de fim do voo, o tempo de corte do cliente não pode ser nulo');
        Integer DuracaoTotal = TempoMissao + TempoCorteCliente;
        Datetime endDateTime = dataVoo.addMinutes(-TransladoIda).addMinutes(DuracaoTotal);
        return endDateTime;
    }
    
    public void createEvent(
        Voo__c voo,  Calendar calendario, CalculoMissaoResult cmr, Account cliente, Aeronave__c aeronave, fflib_ISObjectUnitOfWork uow)
    {
        Integer TransladoIda = Integer.valueOf(cmr.tempoTransladoIda != null ? cmr.tempoTransladoIda : 0);
        if(voo.Trechos__r != null && voo.Trechos__r.size() > 0 && voo.Trechos__r[0].Tipo__c == 'Translado')
        {
            if(cmr != null && cmr.trechos != null && cmr.trechos.size() > 0 && cmr.trechos[0].tempoMissao != null)
            {
                TransladoIda = Integer.valueOf(cmr.trechos[0].tempoMissao);
            }
        }
        Integer TransladoVolta = Integer.valueOf(cmr.tempoTransladoRetorno != null ? cmr.tempoTransladoRetorno : 0);
        Integer TempoCruzeiro = Integer.valueOf(cmr.tempoCruzeiro != null ? cmr.tempoCruzeiro : 0);
        Integer TempoSolo = Integer.valueOf(cmr.tempoSolo != null ? cmr.tempoSolo : 0);
        Integer TempoMissao = Integer.valueOf(cmr.tempoMissao != null ? cmr.tempoMissao : 0);
        Integer TempoCorteCliente = Integer.valueOf(voo.TempoCorteCliente__c != null ? voo.TempoCorteCliente__c : 0);
        Integer DuracaoTotal = TempoMissao + TempoCorteCliente;
        Datetime activyDatetime = calculeDatetimeStartEvent(voo.DataVoo__c, TransladoIda);
        
        List<Event> eventAndEntreVooEvent = new List<Event>();
        String clienteName = cliente != null && cliente.Name != null ? cliente.Name : '';
        Event event = new Event(Subject = aeronave.Name + ' - ' + clienteName + ' - ' + voo.RotaAbreviada__c,
                                OwnerId = calendario.Id,
                                ActivityDateTime = activyDatetime,
                                DurationInMinutes = DuracaoTotal,
                                WhatId = voo.Id,
                                Voo__c = voo.Id,
                                TransladoIda__c = TransladoIda,
                                TransladoVolta__c = TransladoVolta,
                                TempoCruzeiro__c = TempoCruzeiro,
                                TempoCorteCliente__c = TempoCorteCliente,
                                TempoSolo__c = TempoSolo,
                                RecordTypeId = Schema.SObjectType.Event.getRecordTypeInfosByDeveloperName().get('Voo').getRecordTypeId());
        eventAndEntreVooEvent.add(event);
        
        eventAndEntreVooEvent.add(createEntreVoosEvent(calendario.Id, voo.DataVoo__c.addMinutes(-TransladoIda), voo, Label.Pre));
        eventAndEntreVooEvent.add(createEntreVoosEvent(calendario.Id, voo.DataVoo__c.addMinutes(DuracaoTotal - TransladoIda), voo, Label.Pos));
        
        if(String.isNotBlank(event.OwnerId) && String.isNotBlank(event.WhatId))
            uow.registerNew(eventAndEntreVooEvent);
    }
    
    public void deleteEventRelatedToVoos(List<Voo__c> voos, fflib_ISObjectUnitOfWork uow)
    {
        for(Voo__c voo : voos) deleteEventRelatedToVoo(voo, uow);
    }
    
    public void deleteEventRelatedToVoo(Voo__c voo, fflib_ISObjectUnitOfWork uow)
    {
        List<Event> eventsToDelete = new List<Event>();
        for(Event e : (List<Event>) records)
        {
            if(voo != null && String.isNotBlank(voo.Id) && voo.Id.equals(e.WhatId) && !e.isChild)
            {
                e.ByPassDeleteRules__c = true;
                eventsToDelete.add(e);
            }
        }
        uow.registerDirty(eventsToDelete);
    }
    
    // Deletar um evento do voo
    public void deleteEventRelatedToVoo(
        Voo__c voo, List<Event> entreVoosPreEventList, List<Event> eventList, List<Event> entreVoosPosEventList, fflib_ISObjectUnitOfWork uow)
    {
        List<Event> eventsToDelete = new List<Event>();
        
        List<List<Event>> ell = new List<List<Event>>();
        ell.add(entreVoosPreEventList);
        ell.add(eventList);
        ell.add(entreVoosPosEventList);
        
        for(List<Event> eList : ell) {
            for(Event event : eList) {
                if(voo.Id.equals(event.WhatId) && !event.isChild) {
                    event.ByPassDeleteRules__c = true;
                    eventsToDelete.add(event);
                }
            }
        }
        // Ao atualizar, no after update, é analisado o ByPassDeleteRules, e se estiver true, os eventos são deletados
        uow.registerDirty(eventsToDelete);
        //uow.registerDeleted(eventsToDelete);
    }
    
    public Event createEntreVoosEvent(Id calendarId, Datetime data, Voo__c voo, String tipo)
    {
        Datetime activityDateTime = null;
        Integer durationInMinutes = 0;
        
        if(tipo.equals(Label.Pre)) {
            Integer tempoPlanejamentoPre = Voos.getTempoPlanejamentoPre(voo);
            // Data em Entre Voos Pré é a data que o voo começa
            activityDateTime = data.addMinutes(-tempoPlanejamentoPre);
            durationInMinutes = tempoPlanejamentoPre;
        } else if(tipo.equals(Label.Pos)) {

            ConfiguracaoTempoSelector.ConfiguracaoTempo entreVoos = new ConfiguracaoTempoSelector().getEntrevoosPorTipoVoo(voo.Tipo__c);

            Integer tempoPlanejamentoPos = entreVoos.entreVoosPos;
            // Data em Entre Voos Pós é a data que o voo começa mais a duração do voo
            activityDateTime = data; 
            durationInMinutes = tempoPlanejamentoPos;
        }
        
        Event eventEntreVoos = new Event(Subject = ENTRE_VOOS_EVENT_SUBJECT,
                                         OwnerId = calendarId,
                                         ActivityDateTime = activityDateTime,
                                         DurationInMinutes = durationInMinutes,
                                         WhatId = voo.Id,
                                         Voo__c = voo.Id,
                                         Type = tipo,
                                         RecordTypeId = Schema.SObjectType.Event.getRecordTypeInfosByDeveloperName().get('EntreVoos').getRecordTypeId());
        
        return eventEntreVoos;
    }
    
    public Map<Id, List<Event>> getPorAeronave(Map<String, Aeronave__c> aeronavePorNome)
    {
        Map<Id, List<Event>> mapPorAeronave = new Map<Id, List<Event>>();
        for(Event evento : (List<Event>)Records)
        {
            Id aeronaveId = aeronavePorNome.get(evento.OwnerName__c).Id;
            if(mapPorAeronave.containsKey(aeronaveId))
            {
                List<Event> eventos = mapPorAeronave.get(aeronaveId);
                eventos.add(evento);
                mapPorAeronave.put(aeronaveId, eventos);
            }
            else
            {
                List<Event> eventos = new List<Event>();
                eventos.add(evento);
                mapPorAeronave.put(aeronaveId, eventos);
            }
        }
        return mapPorAeronave;
    }
    
    public Boolean checkIfEventIsManutencao(Event event)
    {
        return String.isNotBlank(event.RecordTypeId) && event.RecordTypeId.equals(RECORD_TYPE_MANUTENCAO_EVENT_ID);
    }
    
    public Boolean validateIfDateOfEventEntersInDateOfAnotherEvent(
        Datetime eventStart, Datetime eventEnd, Datetime anotherEventStart, Datetime anotherEventEnd)
    {
        Boolean enter = false;
        if(// Evento avaliado dentro do período do evento existente
            (anotherEventStart <= eventStart && eventEnd <= anotherEventEnd) ||
            // Evento existente dentro do período do evento avaliado
            (eventStart <= anotherEventStart && anotherEventEnd <= eventEnd) ||
            // Evento existente começa antes do evento avaliado e acaba dentro do evento avaliado
            (anotherEventStart < eventStart && eventStart < anotherEventEnd && anotherEventEnd <= eventEnd) ||
            // Evento existente começa dentro do evento avaliado e acaba depois do evento avaliado
            (eventStart < anotherEventStart && anotherEventStart < eventEnd && eventEnd <= anotherEventEnd))
        {
            enter = true;
        }
        return enter;        
    }
    
    public Boolean validateIfEventEntersInAnother(Event eventToValidate, Event anotherEvent)
    {
        // Datas do Evento Avaliado
        Datetime eventStart = eventToValidate.StartDateTime;
        Datetime eventEnd = eventToValidate.EndDateTime;
        // Datas do Evento Recuperado do Calendário
        Datetime anotherEventStart = anotherEvent.StartDateTime;
        Datetime anotherEventEnd = anotherEvent.EndDateTime;
        Boolean enter = false;
        if(validateIfDateOfEventEntersInDateOfAnotherEvent(eventStart, eventEnd, anotherEventStart, anotherEventEnd))
        {
            enter = true;
        }
        // System.debug('Inside?' + enter + '\n' + eventStart + '\n' + eventEnd + '\n' + anotherEventStart + '\n' + anotherEventEnd);
        return enter;
    }
    
    public Boolean validateEventManutencao(Event event, List<Event> calendarEvents)
    {
        Boolean valid = true;
        // Lista de Eventos de qualquer Tipo de Registro referente ao Calendário do Evento avaliado
        for (Event calendarEvent : calendarEvents)
        {
            Boolean calendarEventEnterInAnother = validateIfEventEntersInAnother(event, calendarEvent) && calendarEvent.RecordTypeId != RECORD_TYPE_MANUTENCAO_EVENT_ID;
            if(// Insert, o evento avaliado não possui Id
                (String.isBlank(event.Id) ||
                 /*
                * Update, o evento avaliado possui Id e é recuperado com a lista de eventos do calendário
                * Tem que ter Id diferente do Evento avaliado
                */
                 (String.isNotBlank(event.Id) && !event.Id.equals(calendarEvent.Id))) &&
                 calendarEventEnterInAnother)
            {
                valid = false;
            }
        }
        return valid;
    }
    
    public override void onBeforeDelete()
    {
       	List<FeedItem> posts = new List<FeedItem>();
        
        for (Event e : (List<Event>)records)
        {
            //System.debug(e.ByPassDeleteRules__c);
            if(String.isNotBlank(e.RecordTypeId) &&
               (e.RecordTypeId.equals(RECORD_TYPE_VOO_EVENT_ID) || e.RecordTypeId.equals(RECORD_TYPE_ENTRE_VOOS_EVENT_ID)) &&
               String.isNotBlank(e.WhatId) && !e.ByPassDeleteRules__c
              )
            {
                e.addError(Label.ErroExclusaoVooEntreVooComVooExistente);
            }
            else if (String.isNotBlank(e.RecordTypeId) && e.RecordTypeId.equals(RECORD_TYPE_MANUTENCAO_EVENT_ID))
            {
                posts.add(createFeedItem(e));
            }
        }
        
        insert posts;
    }
    
    private FeedItem createFeedItem(Event e)
    {
        return new FeedItem(
            ParentId = ConfiguracoesGerais__c.getOrgDefaults().IdChatterGrupoComercial__c,
            Body = Label.ChatterManutencaoExcluidaCorpo,
            Title = e.OwnerName__c,
            LinkUrl = '/lightning/r/Aeronave__c/' + e.WhatId + '/view'
        );
    }
    
    public override void onBeforeInsert()
    {
        //System.debug('Events - Before Insert');
        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        
        Integer IntervaloEmDiasBuscaEventos = Integer.valueOf(ConfiguracaoTempo__c.getOrgDefaults().IntervaloEmDiasBuscaEventos__c);
        Datetime smallerDate = retrieveSmallerDateFromRecords();
        smallerDate = smallerDate != null ? Datetime.newInstance(smallerDate.date(), Time.newInstance(0, 0, 0, 0)).addDays(-IntervaloEmDiasBuscaEventos) : null;
        Datetime biggerDate = retrieveBiggerDateFromRecords();
        biggerDate = biggerDate != null ? Datetime.newInstance(biggerDate.date(), Time.newInstance(23, 59, 0, 0)).addDays(IntervaloEmDiasBuscaEventos) : null;
        
        Set<Id> calendarSetId = Utils.getSetIds(records, 'OwnerId');
        List<Event> calendarEvents = EventsSelector.newInstance().selectEventsByOwnerId(calendarSetId, smallerDate, biggerDate);
        List<Aeronave__c> aeronaves = AeronavesSelector.newInstance().selectAll();
        Map<String, Aeronave__c> aeronaveMapByName = new Map<String, Aeronave__c>();
        for(Aeronave__c a : aeronaves) aeronaveMapByName.put(a.Name, a);
        
        for(Event event : (List<Event>) records)
        {
            // Se possui Tipo de Registro, e é do tipo Manutenção
            if(checkIfEventIsManutencao(event))
            {
                if(!validateEventManutencao(event, calendarEvents))
                {
                    event.StartDateTime.addError(Label.ErroConflitoHorarioEvento);
                }
                fillWhatIdInEventManutencao(event, aeronaveMapByName);
            }
        }
        
        uow.commitWork();
    }
    
    public override void onBeforeUpdate(Map<Id,SObject> existingRecords)
    {
        //System.debug('Events - Before Update');
        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        
        Datetime smallerDate = retrieveSmallerDateFromRecords();
        smallerDate = smallerDate != null ? Datetime.newInstance(smallerDate.date(), Time.newInstance(0, 0, 0, 0)).addDays(-15) : null;
        Datetime biggerDate = retrieveBiggerDateFromRecords();
        biggerDate = biggerDate != null ? Datetime.newInstance(biggerDate.date(), Time.newInstance(23, 59, 0, 0)).addDays(15) : null;
        
        Set<Id> calendarSetId = Utils.getSetIds(records, 'OwnerId');
        List<Event> calendarEvents = EventsSelector.newInstance().selectEventsByOwnerId(calendarSetId, smallerDate, biggerDate);
        
        for(Event event : (List<Event>) records)
        {
            // Se possui Tipo de Registro, e é do tipo Manutenção
            if(checkIfEventIsManutencao(event))
            {
                if(!validateEventManutencao(event, calendarEvents) &&
                   (!event.Cancelado__c || (event.Cancelado__c && ((Event)existingRecords.get(event.Id)).Cancelado__c)))
                {
                    event.StartDateTime.addError(Label.ErroConflitoHorarioEvento);
                } else if(event.Cancelado__c && validateEventManutencao(event, calendarEvents))
                {
                    event.Cancelado__c = false;
                }
            }
        }
        uow.commitWork();
    }
    
    public override void handleAfterInsert()
    {
    	/*if(Configuration.EnforcingTriggerCRUDSecurity && !SObjectDescribe.isCreateable()) 
    	   throw new DomainException('Permission to create an ' + SObjectDescribe.getName() + ' denied.');*/
    	   
    	onValidate();
    	onAfterInsert(); 
    }
    public override void handleAfterDelete() 
    {
    	/*if(Configuration.EnforcingTriggerCRUDSecurity && !SObjectDescribe.isDeletable())
    	   throw new DomainException('Permission to delete an ' + SObjectDescribe.getName() + ' denied.');*/
    	   
    	onAfterDelete();
    }
    
    @InvocableMethod(label='Event - Deleta Eventos do Tipo Voo/Entre Voos' description='Deleta eventos do tipo Voo e Entre Voos que forem definidos com ByPassValidationRule__c = true')
    public static void deleteEventsByDeleteByPassValidationRule(List<Id> eventsIdList)
    {
        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        List<Event> eventsToDelete = new List<Event>();
        for(Id i : eventsIdList)
        {
            Event event = new Event(Id=i);
            eventsToDelete.add(event);
        }
        uow.registerDeleted(eventsToDelete);
        uow.commitWork();
    }
    
    public Datetime retrieveSmallerDateFromRecords() {
        ConfiguracaoTempoSelector.ConfiguracaoTempo entreVoos = new ConfiguracaoTempoSelector().getEntrevoosPorTipoVoo('');
        Integer tempoPlanejamentoPre = entreVoos.entreVoosPre;
        Datetime smallerDate = null;
        for(Event e : (List<Event>) records) {
            if(smallerDate == null && e.StartDateTime != null) smallerDate = e.StartDateTime.addMinutes(-tempoPlanejamentoPre);
            else if(e.StartDateTime != null && e.StartDateTime < smallerDate) smallerDate = e.StartDateTime.addMinutes(-tempoPlanejamentoPre);
        }
        return smallerDate;
    }
    
    public Datetime retrieveBiggerDateFromRecords() {
        ConfiguracaoTempoSelector.ConfiguracaoTempo entreVoos = new ConfiguracaoTempoSelector().getEntrevoosPorTipoVoo('');
        Integer tempoPlanejamentoPos = entreVoos.entreVoosPos;
        Datetime biggerDate = null;
        for(Event e : (List<Event>) records) {
            if(biggerDate == null && e.EndDateTime != null) biggerDate = e.EndDateTime.addMinutes(tempoPlanejamentoPos);
            else if(e.EndDateTime != null && e.EndDateTime > biggerDate) biggerDate = e.EndDateTime.addMinutes(tempoPlanejamentoPos);
        }
        return biggerDate;
    }
    
    private void fillWhatIdInEventManutencao(Event e, Map<String, Aeronave__c> aeronaveMapByName)
    {
        if(checkIfEventIsManutencao(e) && String.isNotBlank(e.OwnerName__c))
        {
            e.WhatId = aeronaveMapByName.get(e.OwnerName__c).Id;
        }
    }
}