force-app/main/default/objects/Aeronave__c/Aeronave__c.object-meta.xml
<CustomObject>
    <label>Aeronave</label>
    <nameField>
        <label>Prefixo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aeronaves</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Aeronave__c/fields/ModeloAeronave__c.field-meta.xml
<CustomField>
    <fullName>ModeloAeronave__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Define o modelo de aeronave</description>
    <inlineHelpText>Define o modelo de aeronave</inlineHelpText>
    <label>Modelo de aeronave</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Aeronaves</relationshipLabel>
    <relationshipName>Aeronaves</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Aeronave__c/fields/NumeroAssentos__c.field-meta.xml
<CustomField>
    <fullName>NumeroAssentos__c</fullName>
    <description>Número de assentos do aeronave utilizado a princípio para limitar o número de passageiros em um trecho.</description>
    <formula>ModeloAeronave__r.CapacidadePassageiros__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Número de assentos da aeronave</inlineHelpText>
    <label>Número de Assentos</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Aeronave__c/fields/Prefixo__c.field-meta.xml
<CustomField>
    <fullName>Prefixo__c</fullName>
    <description>Id externo para integrações com o prefixo da aeronave</description>
    <externalId>true</externalId>
    <inlineHelpText>Id externo para integrações com o prefixo da aeronave</inlineHelpText>
    <label>Prefixo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Carga__c/Carga__c.object-meta.xml
<CustomObject>
    <label>Carga</label>
    <nameField>
        <label>Identificação</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cargas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Carga__c/fields/Destino__c.field-meta.xml
<CustomField>
    <fullName>Destino__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Destino</label>
    <referenceTo>Local__c</referenceTo>
    <relationshipLabel>Cargas (Destino)</relationshipLabel>
    <relationshipName>CargasDestino</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Carga__c/fields/Origem__c.field-meta.xml
<CustomField>
    <fullName>Origem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Origem</label>
    <referenceTo>Local__c</referenceTo>
    <relationshipLabel>Cargas</relationshipLabel>
    <relationshipName>CargasOrigem</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Carga__c/fields/PassageiroDel__c.field-meta.xml
<CustomField>
    <fullName>PassageiroDel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Passageiro</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Trecho__c</field>
            <operation>equals</operation>
            <valueField>Passageiro__c.Trecho__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Passageiro__c</referenceTo>
    <relationshipLabel>Cargas</relationshipLabel>
    <relationshipName>Cargas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Carga__c/fields/Trecho__c.field-meta.xml
<CustomField>
    <fullName>Trecho__c</fullName>
    <description>Trecho o qual a carga pertence</description>
    <inlineHelpText>Trecho o qual a carga pertence</inlineHelpText>
    <label>Trecho</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Trecho Em Rota ou Finalizado</errorMessage>
        <filterItems>
            <field>Trecho__c.Status__c</field>
            <operation>equals</operation>
            <value>Não Iniciado</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Trecho__c</referenceTo>
    <relationshipLabel>Cargas</relationshipLabel>
    <relationshipName>Cargas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Local__c/Local__c.object-meta.xml
<CustomObject>
    <label>Local</label>
    <nameField>
        <label>Local</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Local__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status para validação de um local</description>
    <inlineHelpText>Status para validação de um local</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>StatusPendenteAprovado</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MalhaVoo__c/MalhaVoo__c.object-meta.xml
<CustomObject>
    <label>Malha de Voo</label>
    <nameField>
        <displayFormat>MV-{000000}</displayFormat>
        <label>Malha de Voo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Malhas de Voos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MalhaVoo__c/fields/Destino__c.field-meta.xml
<CustomField>
    <fullName>Destino__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Destino</label>
    <referenceTo>Local__c</referenceTo>
    <relationshipLabel>Malhas de Voos (Destino)</relationshipLabel>
    <relationshipName>MalhasVoosDestino</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MalhaVoo__c/fields/NumeroAssentos__c.field-meta.xml
<CustomField>
    <fullName>NumeroAssentos__c</fullName>
    <description>Número máximo de assentos disponibilizados para a malha de voo</description>
    <label>Número de Assentos</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MalhaVoo__c/fields/Origem__c.field-meta.xml
<CustomField>
    <fullName>Origem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Origem</label>
    <referenceTo>Local__c</referenceTo>
    <relationshipLabel>Malhas de Voos</relationshipLabel>
    <relationshipName>MalhasVoosOrigem</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Passageiro__c/Passageiro__c.object-meta.xml
<CustomObject>
    <label>Passageiro</label>
    <nameField>
        <displayFormat>P-{000000000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Passageiros</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Passageiro__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contato</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Passageiro não pode ser do tipo Contato, mas sim do tipo Passageiro ou Cliente - Pessoa Física</errorMessage>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Contato</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Passageiros</relationshipLabel>
    <relationshipName>Passageiros</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Passageiro__c/fields/Destino__c.field-meta.xml
<CustomField>
    <fullName>Destino__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Destino</label>
    <referenceTo>Local__c</referenceTo>
    <relationshipLabel>Passageiros (Destino)</relationshipLabel>
    <relationshipName>PassageirosDestino</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Passageiro__c/fields/Origem__c.field-meta.xml
<CustomField>
    <fullName>Origem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Origem</label>
    <referenceTo>Local__c</referenceTo>
    <relationshipLabel>Passageiros (Origem)</relationshipLabel>
    <relationshipName>PassageirosOrigem</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Passageiro__c/fields/TransferidoParaVoo__c.field-meta.xml
<CustomField>
    <fullName>TransferidoParaVoo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transferido para</label>
    <referenceTo>Voo__c</referenceTo>
    <relationshipLabel>TransferidoParaVoo</relationshipLabel>
    <relationshipName>Passageiros</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Passageiro__c/fields/Trecho__c.field-meta.xml
<CustomField>
    <fullName>Trecho__c</fullName>
    <label>Trecho</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Trecho__c.Status__c</field>
            <operation>equals</operation>
            <value>Não Iniciado</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Trecho__c</referenceTo>
    <relationshipLabel>Passageiros</relationshipLabel>
    <relationshipName>Passageiros</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Trecho__c/Trecho__c.object-meta.xml
<CustomObject>
    <description>Define um trecho com origem e destino dentro de um Voo</description>
    <label>Trecho</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Código do Trecho</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trechos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trecho__c/fields/Destino__c.field-meta.xml
<CustomField>
    <fullName>Destino__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Local de destino do trecho</description>
    <inlineHelpText>Local de destino do trecho</inlineHelpText>
    <label>Destino</label>
    <referenceTo>Local__c</referenceTo>
    <relationshipLabel>Trechos (Destino)</relationshipLabel>
    <relationshipName>TrechosDestino</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trecho__c/fields/MalhaVoo__c.field-meta.xml
<CustomField>
    <fullName>MalhaVoo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Malha de Voo</label>
    <referenceTo>MalhaVoo__c</referenceTo>
    <relationshipLabel>Trechos</relationshipLabel>
    <relationshipName>Trechos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trecho__c/fields/ModeloAeronave__c.field-meta.xml
<CustomField>
    <fullName>ModeloAeronave__c</fullName>
    <formula>Voo__r.Prefixo__r.ModeloAeronave__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Modelo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trecho__c/fields/OrdemExecucao__c.field-meta.xml
<CustomField>
    <fullName>OrdemExecucao__c</fullName>
    <description>Ordem de execução em que o trecho será executado no voo</description>
    <inlineHelpText>Ordem de execução em que o trecho será executado no voo</inlineHelpText>
    <label>Ordem de execução</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trecho__c/fields/Origem__c.field-meta.xml
<CustomField>
    <fullName>Origem__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Local de origem do trecho</description>
    <inlineHelpText>Local de origem do trecho</inlineHelpText>
    <label>Origem</label>
    <referenceTo>Local__c</referenceTo>
    <relationshipLabel>Trechos (Origem)</relationshipLabel>
    <relationshipName>TrechosOrigem</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trecho__c/fields/ProdutoShuttleSeat__c.field-meta.xml
<CustomField>
    <fullName>ProdutoShuttleSeat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto Shuttle Seat</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Trechos</relationshipLabel>
    <relationshipName>Trechos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trecho__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Não Iniciado</fullName>
                <default>true</default>
                <label>Não Iniciado</label>
            </value>
            <value>
                <fullName>Check In Fechado</fullName>
            </value>
            <value>
                <fullName>Em Rota</fullName>
            </value>
            <value>
                <fullName>Finalizado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trecho__c/fields/Voo__c.field-meta.xml
<CustomField>
    <fullName>Voo__c</fullName>
    <description>Voo ao qual o trecho pertence</description>
    <inlineHelpText>Voo ao qual o trecho pertence</inlineHelpText>
    <label>Voo</label>
    <referenceTo>Voo__c</referenceTo>
    <relationshipLabel>Trechos</relationshipLabel>
    <relationshipName>Trechos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Voo__c/Voo__c.object-meta.xml
<CustomObject>
    <description>O Voo de uma aeronave, do ponto de origem até o retorno</description>
    <label>Voo</label>
    <nameField>
        <displayFormat>REVO-{00000000}</displayFormat>
        <label>Número do Voo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Voos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Voo__c/fields/Prefixo__c.field-meta.xml
<CustomField>
    <fullName>Prefixo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Prefixo da aeronave que realizará o voo</description>
    <inlineHelpText>Prefixo da aeronave que realizará o voo</inlineHelpText>
    <label>Prefixo</label>
    <referenceTo>Aeronave__c</referenceTo>
    <relationshipLabel>Voos</relationshipLabel>
    <relationshipName>Voos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/StatusPendenteAprovado.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pendente</fullName>
        <default>true</default>
        <label>Pendente</label>
    </customValue>
    <customValue>
        <fullName>Validado</fullName>
    </customValue>
    <masterLabel>Status Pendente/Aprovado</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TrechosSelector.cls
public class TrechosSelector extends fflib_SObjectSelector 
implements ITrechosSelector
{
    
    public static ITrechosSelector newInstance()
    {
        return (ITrechosSelector) Application.Selector.newInstance(Trecho__c.SObjectType);
    }
    
    public TrechosSelector(Boolean includeFieldSetFields)
    {
        super(includeFieldSetFields);

        this.setDataAccess(fflib_SObjectSelector.DataAccess.SYSTEM_MODE);
    }
    
    public TrechosSelector()
    {
        super(true);

        this.setDataAccess(fflib_SObjectSelector.DataAccess.SYSTEM_MODE);
    }
    
    public override List<Schema.FieldSet> getSObjectFieldSetList()
    {
        List<Schema.FieldSet> fieldSets = new List<Schema.FieldSet>();
        
        fieldSets.add(SobjectType.Trecho__c.FieldSets.SelectFieldList);
        fieldSets.add(SobjectType.Trecho__c.FieldSets.SelectFieldList2);
        fieldSets.add(SobjectType.Trecho__c.FieldSets.OrigemFieldList);
        fieldSets.add(SobjectType.Trecho__c.FieldSets.DestinoFieldList);
        
        return fieldSets;
    }
    
    public List<Schema.SObjectField> getSObjectFieldList()
    {
        return new List<Schema.SObjectField> {
            Trecho__c.Id
        };
    }
    
    public Schema.SObjectType getSObjectType()
    {
        return Trecho__c.sObjectType;
    }
    
    public List<Trecho__c> selectById(Set<ID> idSet)
    {
        return (List<Trecho__c>) selectSObjectsById(idSet);
    }
    
    public List<Trecho__c> selectByVooId(Set<Id> vooId)
    {
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('Voo__c IN :vooId');
        query.setOrdering('OrdemExecucao__c', fflib_QueryFactory.SortOrder.ASCENDING);
        
        fflib_SObjectSelector voosSelector = new VoosSelector();
        voosSelector.configureQueryFactoryFields(query, 'Voo__r'); 
        
        fflib_SObjectSelector locaisSelector = new LocaisSelector();
        locaisSelector.configureQueryFactoryFields(query, 'Origem__r');
        locaisSelector.configureQueryFactoryFields(query, 'Destino__r');
        
        new PassageirosSelector(true).addQueryFactorySubselect(query, 'Passageiros__r');
        new CargasSelector(true).addQueryFactorySubselect(query, 'Cargas__r');
        
        return (List<Trecho__c>) Database.query(query.toSOQL());
    }
    
    public List<Trecho__c> selectByVooIdOrderByOrdemExecucao(Set<Id> voosIds)
    {
        fflib_QueryFactory query = newQueryFactory();
        
        fflib_SObjectSelector locaisSelector = new LocaisSelector();
        locaisSelector.configureQueryFactoryFields(query, 'Origem__r');
        locaisSelector.configureQueryFactoryFields(query, 'Destino__r');
        
        fflib_SObjectSelector voosSelector = new VoosSelector();
        voosSelector.configureQueryFactoryFields(query, 'Voo__r');        
        
        query.setCondition('Voo__c IN :voosIds');
        query.addOrdering('OrdemExecucao__c', fflib_QueryFactory.SortOrder.ASCENDING);
        
        return (List<Trecho__c>) Database.query(query.toSOQL()); 
    }

    public List<Trecho__c> getTrechoWithPassageirosByVooId(Set<Id> voosId, Set<Id> contatosId)
    {
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('Voo__c IN :voosId');
        query.setOrdering('OrdemExecucao__c', fflib_QueryFactory.SortOrder.ASCENDING);
        
        /*fflib_SObjectSelector voosSelector = new VoosSelector();
		voosSelector.configureQueryFactoryFields(query, 'Voo__r'); */
        
        fflib_SObjectSelector locaisSelector = new LocaisSelector();
        locaisSelector.configureQueryFactoryFields(query, 'Origem__r');
        locaisSelector.configureQueryFactoryFields(query, 'Destino__r');
        
        fflib_QueryFactory passageirosQuery = new PassageirosSelector().addQueryFactorySubselect(query, 'Passageiros__r');
        passageirosQuery.setCondition('Contato__c IN :contatosId');
        
        return (List<Trecho__c>) Database.query(query.toSOQL());
    }
    
    public List<Trecho__c> getTrechosByMalha(Id produtoId, Id malhaId, DateTime startdate, DateTime enddate)
    {
        Set<String> statusInvalidos = new Set<String> { 'Cancelado' };

        fflib_QueryFactory query = newQueryFactory();
        query.selectField('Voo__r.Prefixo__r.NumeroAssentos__c');
        query.selectField('Voo__r.Prefixo__r.Name');
        query.selectField('Voo__r.Prefixo__r.ModeloAeronave__c');
        query.selectField('Voo__r.Prefixo__r.ModeloAeronave__r.Name');
        query.selectField('Voo__r.Prefixo__r.ModeloAeronave__r.ImagemUrl__c');

        query.setCondition('ProdutoShuttleSeat__c = :produtoId And MalhaVoo__c = :malhaId And Voo__r.Status__c Not IN :statusInvalidos And Voo__r.DataVoo__c >= :startdate And Voo__r.DataVoo__c <= :enddate');
        query.setOrdering('Voo__r.DataVoo__c', fflib_QueryFactory.SortOrder.ASCENDING);
        
        return (List<Trecho__c>) Database.query( query.toSOQL() ); 
    }

}