force-app/main/default/objects/Aeronave__c/Aeronave__c.object-meta.xml
<CustomObject>
    <label>Aeronave</label>
    <nameField>
        <label>Prefixo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aeronaves</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Aeronave__c/fields/Prefixo__c.field-meta.xml
<CustomField>
    <fullName>Prefixo__c</fullName>
    <description>Id externo para integrações com o prefixo da aeronave</description>
    <externalId>true</externalId>
    <inlineHelpText>Id externo para integrações com o prefixo da aeronave</inlineHelpText>
    <label>Prefixo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Local__c/Local__c.object-meta.xml
<CustomObject>
    <label>Local</label>
    <nameField>
        <label>Local</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Local__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Referência para um cliente caso este local seja de uso específico dele</description>
    <inlineHelpText>Referência para um cliente caso este local seja de uso específico dele</inlineHelpText>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Locais</relationshipLabel>
    <relationshipName>Locais</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Local__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status para validação de um local</description>
    <inlineHelpText>Status para validação de um local</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>StatusPendenteAprovado</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PAD__c/PAD__c.object-meta.xml
<CustomObject>
    <description>Plano de Atendimento a Demanda</description>
    <label>PAD</label>
    <nameField>
        <displayFormat>PAD - {00000000}</displayFormat>
        <label>Código do PAD</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PAD&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PAD__c/fields/Prefixo__c.field-meta.xml
<CustomField>
    <fullName>Prefixo__c</fullName>
    <formula>HYPERLINK(&quot;/lightning/r/ItemContrato__c/&quot;&amp; Aeronave__r.Id &amp;&quot;/view&quot;,  Aeronave__r.Aeronave__r.Name, &quot;_self&quot; )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Prefixo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PAD__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Indica se o PAD está ativo ou inativo.</description>
    <formula>IF(TODAY()&gt;= InicioVigencia__c  &amp;&amp; TODAY()&lt;= FimVigencia__c, &quot;Ativo&quot;,&quot;Inativo&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Indica se o PAD está ativo ou inativo.</inlineHelpText>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trecho__c/Trecho__c.object-meta.xml
<CustomObject>
    <description>Define um trecho com origem e destino dentro de um Voo</description>
    <label>Trecho</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Código do Trecho</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trechos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trecho__c/fields/Observacoes__c.field-meta.xml
<CustomField>
    <fullName>Observacoes__c</fullName>
    <inlineHelpText>Observações sobre o trecho</inlineHelpText>
    <label>Observações</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trecho__c/fields/RelatorioVoo__c.field-meta.xml
<CustomField>
    <fullName>RelatorioVoo__c</fullName>
    <formula>Voo__r.RelatorioVoo__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Relatório de voo&apos;</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trecho__c/fields/Rota__c.field-meta.xml
<CustomField>
    <fullName>Rota__c</fullName>
    <formula>Origem__r.CodigoLocal__c &amp; &apos; - &apos; &amp; Origem__r.Name &amp; &apos; &gt; &apos; &amp; Destino__r.CodigoLocal__c &amp; &apos; - &apos; &amp; Destino__r.Name</formula>
    <label>Rota</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trecho__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Não Iniciado</fullName>
                <default>true</default>
                <label>Não Iniciado</label>
            </value>
            <value>
                <fullName>Check In Fechado</fullName>
            </value>
            <value>
                <fullName>Em Rota</fullName>
            </value>
            <value>
                <fullName>Finalizado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trecho__c/fields/Voo__c.field-meta.xml
<CustomField>
    <fullName>Voo__c</fullName>
    <description>Voo ao qual o trecho pertence</description>
    <inlineHelpText>Voo ao qual o trecho pertence</inlineHelpText>
    <label>Voo</label>
    <referenceTo>Voo__c</referenceTo>
    <relationshipLabel>Trechos</relationshipLabel>
    <relationshipName>Trechos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Voo__c/Voo__c.object-meta.xml
<CustomObject>
    <description>O Voo de uma aeronave, do ponto de origem até o retorno</description>
    <label>Voo</label>
    <nameField>
        <displayFormat>REVO-{00000000}</displayFormat>
        <label>Número do Voo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Voos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Voo__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Conta para o faturamento do(s) voo(s)</description>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Voos</relationshipLabel>
    <relationshipName>Voos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Voo__c/fields/Comandante__c.field-meta.xml
<CustomField>
    <fullName>Comandante__c</fullName>
    <description>Comandante responsável pelo voo</description>
    <inlineHelpText>Comandante responsável pelo voo</inlineHelpText>
    <label>Comandante</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Voo__c/fields/Comissario__c.field-meta.xml
<CustomField>
    <fullName>Comissario__c</fullName>
    <description>Comissário alocado para o voo</description>
    <inlineHelpText>Comissário alocado para o voo</inlineHelpText>
    <label>Comissário</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Voo__c/fields/Copiloto__c.field-meta.xml
<CustomField>
    <fullName>Copiloto__c</fullName>
    <description>Copiloto responsável pelo voo</description>
    <inlineHelpText>Copiloto responsável pelo voo</inlineHelpText>
    <label>Copiloto</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Voo__c/fields/DataVoo__c.field-meta.xml
<CustomField>
    <fullName>DataVoo__c</fullName>
    <description>Dia e hora solicitada para a realização do voo</description>
    <inlineHelpText>Dia e hora solicitada para a realização do voo</inlineHelpText>
    <label>Data</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Voo__c/fields/DiaVoo__c.field-meta.xml
<CustomField>
    <fullName>DiaVoo__c</fullName>
    <description>Retorna o dia da data do voo</description>
    <formula>DATEVALUE(DataVoo__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Retorna o dia da data do voo</inlineHelpText>
    <label>Dia do Voo</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Voo__c/fields/Observacoes__c.field-meta.xml
<CustomField>
    <fullName>Observacoes__c</fullName>
    <description>Observações com relação ao voo</description>
    <inlineHelpText>Observações com relação ao voo</inlineHelpText>
    <label>Observações</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Voo__c/fields/PAD__c.field-meta.xml
<CustomField>
    <fullName>PAD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identifica que este é um voo regular associado a um PAD de um contrato de Logística integrada.</description>
    <inlineHelpText>Identifica que este é um voo regular associado a um PAD de um contrato de Logística integrada.</inlineHelpText>
    <label>PAD</label>
    <referenceTo>PAD__c</referenceTo>
    <relationshipLabel>Voos</relationshipLabel>
    <relationshipName>Voos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Voo__c/fields/Prefixo__c.field-meta.xml
<CustomField>
    <fullName>Prefixo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Prefixo da aeronave que realizará o voo</description>
    <inlineHelpText>Prefixo da aeronave que realizará o voo</inlineHelpText>
    <label>Prefixo</label>
    <referenceTo>Aeronave__c</referenceTo>
    <relationshipLabel>Voos</relationshipLabel>
    <relationshipName>Voos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Voo__c/fields/PrefixoTexto__c.field-meta.xml
<CustomField>
    <fullName>PrefixoTexto__c</fullName>
    <description>Replica o Prefixo da Aeronave</description>
    <formula>Prefixo__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Replica o Prefixo da Aeronave</inlineHelpText>
    <label>Prefixo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Voo__c/fields/QtdTrechosOrigemOffshore__c.field-meta.xml
<CustomField>
    <fullName>QtdTrechosOrigemOffshore__c</fullName>
    <description>Quantidade de trechos no voo que possuem a origem OFFSHORE</description>
    <inlineHelpText>Quantidade de trechos no voo que possuem a origem OFFSHORE</inlineHelpText>
    <label>Qtd Trechos Origem Offshore</label>
    <summaryFilterItems>
        <field>Trecho__c.Offshore__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Trecho__c.Voo__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Voo__c/fields/RelatorioVoo__c.field-meta.xml
<CustomField>
    <fullName>RelatorioVoo__c</fullName>
    <description>Coordenação deve inserir número do relatório de voo</description>
    <externalId>true</externalId>
    <inlineHelpText>Número do relatório de voo</inlineHelpText>
    <label>Relatório de Voo</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Voo__c/fields/Rota__c.field-meta.xml
<CustomField>
    <fullName>Rota__c</fullName>
    <description>Rota de execução do voo. Local 1 &gt; Local 2 &gt; Local 3</description>
    <inlineHelpText>Rota de execução do voo. Local 1 &gt; Local 2 &gt; Local 3</inlineHelpText>
    <label>Rota (Extenso)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Voo__c/fields/RotaCompleta__c.field-meta.xml
<CustomField>
    <fullName>RotaCompleta__c</fullName>
    <description>Rota de execução do voo. Local 1 &gt; Local 2 &gt; Local 3</description>
    <inlineHelpText>Rota de execução do voo. Local 1 &gt; Local 2 &gt; Local 3</inlineHelpText>
    <label>Rota (Completa)</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Voo__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Define em que momento o voo se encontra</description>
    <inlineHelpText>Define em que momento o voo se encontra</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Rascunho</fullName>
                <default>true</default>
                <label>Rascunho</label>
            </value>
            <value>
                <fullName>Pré-reservado</fullName>
            </value>
            <value>
                <fullName>Reservado</fullName>
            </value>
            <value>
                <fullName>Confirmado</fullName>
            </value>
            <value>
                <fullName>Rota</fullName>
                <label>Em Rota</label>
            </value>
            <value>
                <fullName>LogPendente</fullName>
                <label>Concluindo o Voo</label>
            </value>
            <value>
                <fullName>Executado</fullName>
            </value>
            <value>
                <fullName>Em Faturamento</fullName>
                <isActive>false</isActive>
                <label>Em Faturamento</label>
            </value>
            <value>
                <fullName>Faturado</fullName>
                <isActive>false</isActive>
                <label>Faturado</label>
            </value>
            <value>
                <fullName>Pronto pra Voar</fullName>
                <isActive>false</isActive>
                <label>Pronto pra Voar</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Voo__c/fields/TipoPAD__c.field-meta.xml
<CustomField>
    <fullName>TipoPAD__c</fullName>
    <description>Indica como o voo PAD é classificado em função da rota, ocupação, aeronave e rota do PAD.</description>
    <inlineHelpText>Indica como o voo PAD é classificado em função da rota, ocupação, aeronave e rota do PAD.</inlineHelpText>
    <label>Modalidade</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Regular</fullName>
            </value>
            <value>
                <fullName>Especial</fullName>
            </value>
            <value>
                <fullName>Aeromédico</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/StatusPendenteAprovado.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pendente</fullName>
        <default>true</default>
        <label>Pendente</label>
    </customValue>
    <customValue>
        <fullName>Validado</fullName>
    </customValue>
    <masterLabel>Status Pendente/Aprovado</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/VoosSelector.cls
public class VoosSelector extends fflib_SObjectSelector
    implements IVoosSelector
{

    public static IVoosSelector newInstance()
    {
        return (IVoosSelector) Application.Selector.newInstance(Voo__c.SObjectType);
    }
    
    public VoosSelector(Boolean includeFieldSetFields) 
    {
        super(includeFieldSetFields);
    }
    
    public VoosSelector()
    {
        super(true);
    }
    
    public override List<Schema.FieldSet> getSObjectFieldSetList()
    {
        return new List<Schema.FieldSet>    
        {   SobjectType.Voo__c.FieldSets.SelectFieldList    };
    }
    
    public List<Schema.SObjectField> getSObjectFieldList()
    {
        return new List<Schema.SObjectField> {
            Voo__c.Id,
            Voo__c.Status__c,
            Voo__c.Rota__c,
            Voo__c.RotaCompleta__c,
            Voo__c.DataVoo__c,
            Voo__c.Observacoes__c,    
            Voo__c.CreatedDate,
            Voo__c.Name,
            Voo__c.Comandante__c,
            Voo__c.Copiloto__c,
            Voo__c.Comissario__c,
            Voo__c.Prefixo__c,
            Voo__c.Prefixo__r.Name, 
            Voo__c.PrefixoTexto__c,
            Voo__c.Cliente__c.Name,
            Voo__c.QtdTrechosOrigemOffshore__c,
            Voo__c.PAD__c,    
            Voo__c.TipoPAD__c,
            Voo__c.RelatorioVoo__c,
            Voo__c.DiaVoo__c,
            Voo__c.MEDVAC__c,
            Voo__c.SAR2__c,
            Voo__c.Spot__c,
            Voo__c.ReceitaVoo__c
        };
    }
    
    public Schema.SObjectType getSObjectType()
    {
        return Voo__c.sObjectType;
    }
    
    public List<Voo__c> selectById(Set<ID> idSet)
    {
        return (List<Voo__c>) selectSObjectsById(idSet);
    }
    
    public List<Voo__c> selectDeletedById(Set<Id> idSet)
    {
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('IsDeleted = true AND Id IN :idSet');
        return (List<Voo__c>) Database.query(query.toSOQL() + ' ALL ROWS');
    }
    
    public List<Voo__c> selectWithTrechosById(Set<Id> vooId)
    {
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('Id IN :vooId');
        
        fflib_SObjectSelector aeronaves = new AeronavesSelector();
        aeronaves.configureQueryFactoryFields(query, 'Prefixo__r');
        
        new TrechosSelector().addQueryFactorySubselect(query, 'Trechos__r')
            .selectField('Origem__r.Name')
            .selectField('Origem__r.CodigoLocal__c')
            .selectField('Destino__r.Name')
            .selectField('Destino__r.CodigoLocal__c')
            .selectField('PrimeiroTrechoFixo__c')
            .selectField('TrechoAnterior__c')
            .selectField('Tipo__c')
            .selectField('PrimeiroTrechoFixo__c')
            .selectField('PousoTrechoAnterior__c')
            .selectField('TipoHoraFaturamento__c')
            .setOrdering('OrdemExecucao__c', fflib_QueryFactory.SortOrder.ASCENDING);
        
        return (List<Voo__c>) Database.query(query.toSOQL());
    }
    
    public List<Voo__c> selectWithPrimeiroTrechoById(Set<Id> vooId)
    {
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('Id IN :vooId');
        
        new TrechosSelector().addQueryFactorySubselect(query, 'Trechos__r')
            .setCondition('PrimeiroTrecho__c = TRUE');
        
        return (List<Voo__c>) Database.query(query.toSOQL());
    }
    
    public List<Voo__c> selectByIdWithLead(Set<Id> idSet)
    {
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('Id IN :idSet');
        
        fflib_SObjectSelector leadsSelector = new LeadsSelector();
        leadsSelector.configureQueryFactoryFields(query, 'LeadGerouVoo__r');
        
        return (List<Voo__c>) Database.query(query.toSOQL());
    }
    
    public List<Voo__c> selectRecentsWithTrechos()
    {
        fflib_QueryFactory query = newQueryFactory();
        query.setOrdering('CreatedDate', fflib_QueryFactory.SortOrder.DESCENDING);
        query.setCondition('QtdTrechos__c > 1');
        query.setLimit(2000);
        
        fflib_QueryFactory trechosQuery = new TrechosSelector().addQueryFactorySubselect(query, 'Trechos__r');
        trechosQuery.setOrdering('OrdemExecucao__c', fflib_QueryFactory.SortOrder.ASCENDING);
        
        return (List<Voo__c>) Database.query(query.toSOQL());
    }
    
    public List<Voo__c> getVoosAmanhaByStatus(String status)
    {
        Time horainicio = Time.newInstance(0, 0, 0, 0);
        Time horafim = Time.newInstance(23, 59, 59, 0);
        Datetime inicioDia = Datetime.newInstance(Date.today().addDays(1), horainicio);
        Datetime fimDia = Datetime.newInstance(Date.today().addDays(1), horafim);
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('DataVoo__c >= :inicioDia AND DataVoo__c <= :fimDia AND Status__c = :status');
        
        fflib_QueryFactory trechosQuery = new TrechosSelector().addQueryFactorySubselect(query, 'Trechos__r');
        trechosQuery.setOrdering('OrdemExecucao__c', fflib_QueryFactory.SortOrder.ASCENDING);
        
        return (List<Voo__c>) Database.query(query.toSOQL());
    }
    
    public List<Voo__c> selectByIdWithCombinedAttachments(Set<Id> ids)
    {        
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('Id IN :ids');
        
        query.subselectQuery('CombinedAttachments').selectField('Title');

        
        return (List<Voo__c>) Database.query(query.toSOQL());
    }
    
    public List<Voo__c> selectByIdToInteressadosFaturamento(Set<Id> ids)
    {        
        Boolean enviado = false;
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('Id IN :ids AND FaturamentoInformado__c = :enviado');
        return (List<Voo__c>) Database.query(query.toSOQL());
    }
    
    public List<Voo__c> selectWithPrefixosAndBetweenDates(Set<Id> prefixosIds, Date menorData, Date maiorData)
    {
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('Prefixo__c IN :prefixosIds AND DataVoo__c >= :menorData AND DataVoo__c <= :maiorData');
        return (List<Voo__c>) Database.query(query.toSOQL());
    }
    
    public List<Voo__c> selectRastreaveisBetweenDates(Datetime menorData, Datetime maiorData)
    {
        fflib_QueryFactory query = newQueryFactory();
        Set<String> rastreaveis = new Set<String>{Voos.RESERVADO, Voos.CONFIRMADO, Voos.ROTA};
        query.setCondition('Status__c IN :rastreaveis AND DataVoo__c >= :menorData AND DataVoo__c <= :maiorData');
        query.setOrdering('DataVoo__c', fflib_QueryFactory.SortOrder.ASCENDING);
        return (List<Voo__c>) Database.query(query.toSOQL());
    }
      
    public Voo__c getVoosToOOS(Id vooId)
    { 
        fflib_QueryFactory query = newQueryFactory();
        query.selectField('IdExternoOOs__c');
        query.selectField('Prefixo__r.IdExternoOOs__c');
        query.selectField('Cliente__r.IdExternoOOs__c');
        query.setCondition('Id = :vooId');
        List<Voo__c> voos = (List<Voo__c>) Database.query( query.toSOQL() );
        if(voos.size()>0) return voos[0];
        return null;
    }

    public List<Voo__c> selectByAccountAndBetweenDates(Set<Id> accountIds, Date startDate, Date endDate)
    {
        fflib_QueryFactory query = newQueryFactory();
        String CANCELADO = Voos.CANCELADO;
        query.setCondition('Cliente__c IN :accountIds AND Status__c != :CANCELADO AND DiaVoo__c >= :startDate AND DiaVoo__c <= :endDate');
        query.setOrdering('DataVoo__c', fflib_QueryFactory.SortOrder.ASCENDING);
        return (List<Voo__c>) Database.query(query.toSOQL());
    }
}