force-app/main/default/objects/Aeronave__c/Aeronave__c.object-meta.xml
<CustomObject>
    <label>Aeronave</label>
    <nameField>
        <label>Prefixo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aeronaves</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Local__c/Local__c.object-meta.xml
<CustomObject>
    <label>Local</label>
    <nameField>
        <label>Local</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Passageiro__c/Passageiro__c.object-meta.xml
<CustomObject>
    <label>Passageiro</label>
    <nameField>
        <displayFormat>P-{000000000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Passageiros</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Passageiro__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contato</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Passageiro não pode ser do tipo Contato, mas sim do tipo Passageiro ou Cliente - Pessoa Física</errorMessage>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Contato</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Passageiros</relationshipLabel>
    <relationshipName>Passageiros</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Passageiro__c/fields/IdVoo__c.field-meta.xml
<CustomField>
    <fullName>IdVoo__c</fullName>
    <description>Replica o Id do Voo em que o passageiro estará presente</description>
    <formula>CASESAFEID(Trecho__r.Voo__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Replica o Id do Voo em que o passageiro estará presente</inlineHelpText>
    <label>Id do Voo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Passageiro__c/fields/Trecho__c.field-meta.xml
<CustomField>
    <fullName>Trecho__c</fullName>
    <label>Trecho</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Trecho__c.Status__c</field>
            <operation>equals</operation>
            <value>Não Iniciado</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Trecho__c</referenceTo>
    <relationshipLabel>Passageiros</relationshipLabel>
    <relationshipName>Passageiros</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Trecho__c/Trecho__c.object-meta.xml
<CustomObject>
    <description>Define um trecho com origem e destino dentro de um Voo</description>
    <label>Trecho</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Código do Trecho</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trechos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trecho__c/fields/Voo__c.field-meta.xml
<CustomField>
    <fullName>Voo__c</fullName>
    <description>Voo ao qual o trecho pertence</description>
    <inlineHelpText>Voo ao qual o trecho pertence</inlineHelpText>
    <label>Voo</label>
    <referenceTo>Voo__c</referenceTo>
    <relationshipLabel>Trechos</relationshipLabel>
    <relationshipName>Trechos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Voo__c/Voo__c.object-meta.xml
<CustomObject>
    <description>O Voo de uma aeronave, do ponto de origem até o retorno</description>
    <label>Voo</label>
    <nameField>
        <displayFormat>REVO-{00000000}</displayFormat>
        <label>Número do Voo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Voos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Voo__c/fields/TotalPassageiros__c.field-meta.xml
<CustomField>
    <fullName>TotalPassageiros__c</fullName>
    <description>Quantidade de passageiros no voo. 
Campo populado ao final do voo.</description>
    <inlineHelpText>Quantidade de passageiros no voo</inlineHelpText>
    <label>Total de Passageiros</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/VoosServiceImpl.cls
public class VoosServiceImpl implements IVoosService {

    protected Voo__c voo;
    protected List<Voo__c> voosList;
    protected List<Trecho__c> trechosList;
    protected List<Aeronave__c> aeronavesList;
    protected List<Local__c> locaisList;
    protected List<Id> localIdList;
    protected Set<Id> localSetIds;
    protected Set<Id> aeronaveSetIds;
    protected List<Local__c> trajetoLocaisList;
    protected Map<Id, Local__c> locaisMap;

    public VoosServiceImpl(){
        this.voo = new Voo__c();
        this.voosList = new List<Voo__c>();
        this.trechosList = new List<Trecho__c>();
        this.aeronavesList = new List<Aeronave__c>();
        this.locaisList = new List<Local__c>();
        this.localIdList = new List<Id>();
        this.localSetIds = new Set<Id>();
        this.aeronaveSetIds = new Set<Id>();
        this.trajetoLocaisList = new List<Local__c>();
        this.locaisMap = new Map<Id, Local__c>();
    }
    
    
    public List<Voo__c> getVoos(Set<Id> voosId) {
        return VoosSelector.newInstance().selectWithTrechosById(voosId);
    }
    
    public void undeleteVoos(Set<Id> voosId) {
        List<Voo__c> voosDeletados = VoosSelector.newInstance()
            .selectDeletedById(voosId);
        undelete voosDeletados;
    }
    
    public static void countPassengers(List<Id> vooIds) {
        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        List<Passageiro__c> passageiros = PassageiroSelector.getPassageirosToSurveyBySetVoosIds(
            Utils.getSetIdsByListIds(vooIds)
        );
        Map<Id, Set<Id>> contatosPorVoo = new Map<Id, Set<Id>>();
        for (Passageiro__c pass : passageiros) {
            if (!contatosPorVoo.containsKey(pass.IdVoo__c)) {
                contatosPorVoo.put(pass.IdVoo__c, new Set<Id>{ pass.Contato__c });
            } else {
                Set<Id> contatosDoVoo = contatosPorVoo.get(pass.IdVoo__c);
                contatosDoVoo.add(pass.Contato__c);
                contatosPorVoo.put(pass.IdVoo__c, contatosDoVoo);
            }
        }
        
        for (Id vooId : contatosPorVoo.keySet()) {
            Set<Id> quantidade = contatosPorVoo.get(vooId);
            Integer numeroContatos = quantidade.size();
            Voo__c novo = new Voo__c();
            novo.Id = vooId;
            novo.TotalPassageiros__c = numeroContatos;
            uow.registerDirty(novo);
        }
        uow.commitWork();
    }
}