force-app/main/default/objects/Aeronave__c/Aeronave__c.object-meta.xml
<CustomObject>
    <label>Aeronave</label>
    <nameField>
        <label>Prefixo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aeronaves</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CodigoPromocional__c/CodigoPromocional__c.object-meta.xml
<CustomObject>
    <label>Promoção</label>
    <nameField>
        <label>Código Promocional</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promoções</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CodigoPromocional__c/recordTypes/CodigoPromocional.recordType-meta.xml
<RecordType>
    <fullName>CodigoPromocional</fullName>
    <active>true</active>
    <label>Código Promocional</label>
</RecordType>

force-app/main/default/objects/ConfiguracaoPacote__c/ConfiguracaoPacote__c.object-meta.xml
<CustomObject>
    <label>Configuração do Pacote</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Configuração do Pacote</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Configurações dos Pacotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Local__c/Local__c.object-meta.xml
<CustomObject>
    <label>Local</label>
    <nameField>
        <label>Local</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MalhaVoo__c/MalhaVoo__c.object-meta.xml
<CustomObject>
    <label>Malha de Voo</label>
    <nameField>
        <displayFormat>MV-{000000}</displayFormat>
        <label>Malha de Voo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Malhas de Voos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RegraDesconto__c/RegraDesconto__c.object-meta.xml
<CustomObject>
    <label>Regra de Desconto</label>
    <nameField>
        <displayFormat>RD-{00000000}</displayFormat>
        <label>Regra de Desconto</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Regras de Descontos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RegraPreco__c/RegraPreco__c.object-meta.xml
<CustomObject>
    <label>Regra de Preço</label>
    <nameField>
        <displayFormat>RP-{0000}</displayFormat>
        <label>Regra de Preço</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Regras de Preços</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RegraProduto__c/RegraProduto__c.object-meta.xml
<CustomObject>
    <label>Regra de Produto</label>
    <nameField>
        <displayFormat>RP-{0000}</displayFormat>
        <label>Regra de Produto</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Regras de Produtos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trecho__c/Trecho__c.object-meta.xml
<CustomObject>
    <description>Define um trecho com origem e destino dentro de um Voo</description>
    <label>Trecho</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Código do Trecho</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trechos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trecho__c/fields/MalhaVoo__c.field-meta.xml
<CustomField>
    <fullName>MalhaVoo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Malha de Voo</label>
    <referenceTo>MalhaVoo__c</referenceTo>
    <relationshipLabel>Trechos</relationshipLabel>
    <relationshipName>Trechos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PesquisaParametroOportunidade.cls
public class PesquisaParametroOportunidade {
    // All Filled
    public String quem;
    public Id contaId;
    public Integer quantidade;
    public Product2 produto;
    public DateTime previsaoDeVoo;
    public List<Local__c> locais;
    public List<Aeronave__c> aeronaves;
    public Map<Id, List<Event>> eventosPorAeronave;
    public Map<Id, CalculoMissaoResult> cmrsMapByAeronaveId;
    public List<ConfiguracaoPacote__c> servicosDoProduto;        
    public Map<Id, List<RegraProduto__c>> regrasDosProdutos;
    public Map<Id, List<RegraPreco__c>> regrasDosPrecos;
    public Map<Id, List<RegraDesconto__c>> regrasDeDescontos;
    public CodigoPromocional__c codigoPromocional;
    public Boolean codigoJaUtilizado;
    public Boolean primeiraCompra;
    public Boolean checkOut;
    
    public Map<Id, Integer> servicosContratados;

    // Optional
    public Map<Id, Product2> charter_modelos;
    public List<Trecho__c> malha_trechos;
    public Integer malha_offsetDatas;
    public MalhaVoo__c malha;
}