force-app/main/default/objects/Abastecimento__c/Abastecimento__c.object-meta.xml
<CustomObject>
    <label>Abastecimento</label>
    <nameField>
        <displayFormat>Abast-{00000}</displayFormat>
        <label>Abastecimento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Abastecimentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Abastecimento__c/fields/Local__c.field-meta.xml
<CustomField>
    <fullName>Local__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Local</label>
    <referenceTo>Local__c</referenceTo>
    <relationshipLabel>Abastecimentos</relationshipLabel>
    <relationshipName>Abastecimentos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Abastecimento__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Novo</fullName>
                <default>true</default>
                <label>Novo</label>
            </value>
            <value>
                <fullName>Faturado</fullName>
            </value>
            <value>
                <fullName>Em faturamento</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Abastecimento__c/fields/Trecho__c.field-meta.xml
<CustomField>
    <fullName>Trecho__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trecho</label>
    <referenceTo>Trecho__c</referenceTo>
    <relationshipLabel>Abastecimentos</relationshipLabel>
    <relationshipName>Abastecimentos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IntervaloSol__c/IntervaloSol__c.object-meta.xml
<CustomObject>
    <label>Intervalo do Sol</label>
    <nameField>
        <displayFormat>PS-{00000000}</displayFormat>
        <label>Código de Por do Sol</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intervalos de Sol</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IntervaloSol__c/fields/CodigoICAO__c.field-meta.xml
<CustomField>
    <fullName>CodigoICAO__c</fullName>
    <description>Código ICAO</description>
    <inlineHelpText>Código ICAO</inlineHelpText>
    <label>Código ICAO</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IntervaloSol__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Data de referência do por do sol</description>
    <label>Data</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/IntervaloSol__c/fields/Sunrise__c.field-meta.xml
<CustomField>
    <fullName>Sunrise__c</fullName>
    <description>Hora do nascer do sol</description>
    <inlineHelpText>Hora do nascer do sol</inlineHelpText>
    <label>Nascer do Sol</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/IntervaloSol__c/fields/Sunset__c.field-meta.xml
<CustomField>
    <fullName>Sunset__c</fullName>
    <description>Hora do por do sol</description>
    <inlineHelpText>Hora do por do sol</inlineHelpText>
    <label>Por do Sol</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Local__c/Local__c.object-meta.xml
<CustomObject>
    <label>Local</label>
    <nameField>
        <label>Local</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Local__c/fields/Abastecimento__c.field-meta.xml
<CustomField>
    <fullName>Abastecimento__c</fullName>
    <description>Tipo de Abastecimento disponíveis no Local</description>
    <inlineHelpText>Tipo de Abastecimento disponíveis no Local</inlineHelpText>
    <label>Abastecimento</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>QAV</fullName>
            </value>
            <value>
                <fullName>AVGAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Local__c/fields/Base__c.field-meta.xml
<CustomField>
    <fullName>Base__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Define se o local cadastro é uma base onde uma ou mais equipes operam.</description>
    <inlineHelpText>Define se o local cadastro é uma base onde uma ou mais equipes operam.</inlineHelpText>
    <label>É Base</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Local__c/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <label>Modelo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Base</fullName>
            </value>
            <value>
                <fullName>FPSO</fullName>
            </value>
            <value>
                <fullName>FSO</fullName>
            </value>
            <value>
                <fullName>Plataforma</fullName>
            </value>
            <value>
                <fullName>Sonda</fullName>
            </value>
            <value>
                <fullName>UMS</fullName>
            </value>
            <value>
                <fullName>Sísmica</fullName>
            </value>
            <value>
                <fullName>PLSV</fullName>
            </value>
            <value>
                <fullName>Clareira</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Local__c/fields/CodigoICAO__c.field-meta.xml
<CustomField>
    <fullName>CodigoICAO__c</fullName>
    <description>Código ICAO da estação meteorológica mais próxima</description>
    <inlineHelpText>Código ICAO da estação meteorológica mais próxima</inlineHelpText>
    <label>Estação meteorológica</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Local__c/fields/CodigoLocal__c.field-meta.xml
<CustomField>
    <fullName>CodigoLocal__c</fullName>
    <description>Código que identifica o local</description>
    <externalId>true</externalId>
    <inlineHelpText>Código que identifica o local</inlineHelpText>
    <label>Código do local</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Local__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status para validação de um local</description>
    <inlineHelpText>Status para validação de um local</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>StatusPendenteAprovado</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Local__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <description>Define se o local é em terra(onshore) ou em mar(offshore)</description>
    <inlineHelpText>Define se o local é em terra(onshore) ou em mar(offshore)</inlineHelpText>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Onshore</fullName>
            </value>
            <value>
                <fullName>Offshore</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trecho__c/Trecho__c.object-meta.xml
<CustomObject>
    <description>Define um trecho com origem e destino dentro de um Voo</description>
    <label>Trecho</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Código do Trecho</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trechos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trecho__c/fields/Destino__c.field-meta.xml
<CustomField>
    <fullName>Destino__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Local de destino do trecho</description>
    <inlineHelpText>Local de destino do trecho</inlineHelpText>
    <label>Destino</label>
    <referenceTo>Local__c</referenceTo>
    <relationshipLabel>Trechos (Destino)</relationshipLabel>
    <relationshipName>TrechosDestino</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trecho__c/fields/OrdemExecucao__c.field-meta.xml
<CustomField>
    <fullName>OrdemExecucao__c</fullName>
    <description>Ordem de execução em que o trecho será executado no voo</description>
    <inlineHelpText>Ordem de execução em que o trecho será executado no voo</inlineHelpText>
    <label>Ordem de execução</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trecho__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Não Iniciado</fullName>
                <default>true</default>
                <label>Não Iniciado</label>
            </value>
            <value>
                <fullName>Check In Fechado</fullName>
            </value>
            <value>
                <fullName>Em Rota</fullName>
            </value>
            <value>
                <fullName>Finalizado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trecho__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <description>Passageiro - Transporte apenas de passageiros no trecho
Carga e passageiro - Transporte de passageiros e carga no trecho
Cargueiro - Transporte apenas de carga no trecho
Translado - Translado da aeronave para reposicionamento
Translado com passageiro - Translado da aeronave para reposicionamento com passageiro a bordo
Comitiva</description>
    <inlineHelpText>Transporte apenas de passageiros no trecho
Transporte de passageiros e carga no trecho
Transporte apenas de carga no trecho
Translado da aeronave para reposicionamento
Translado da aeronave para reposicionamento com passageiro
Comitiva</inlineHelpText>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Passageiros</fullName>
            </value>
            <value>
                <fullName>Cargueiro</fullName>
            </value>
            <value>
                <fullName>Passageiros e Cargas</fullName>
            </value>
            <value>
                <fullName>Translado</fullName>
            </value>
            <value>
                <fullName>Translado com passageiro</fullName>
            </value>
            <value>
                <fullName>Comitiva</fullName>
            </value>
            <value>
                <fullName>Sanitário</fullName>
            </value>
            <value>
                <fullName>Treinamento</fullName>
            </value>
            <value>
                <fullName>SAR</fullName>
            </value>
            <value>
                <fullName>MEDVAC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trecho__c/fields/Voo__c.field-meta.xml
<CustomField>
    <fullName>Voo__c</fullName>
    <description>Voo ao qual o trecho pertence</description>
    <inlineHelpText>Voo ao qual o trecho pertence</inlineHelpText>
    <label>Voo</label>
    <referenceTo>Voo__c</referenceTo>
    <relationshipLabel>Trechos</relationshipLabel>
    <relationshipName>Trechos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Voo__c/Voo__c.object-meta.xml
<CustomObject>
    <description>O Voo de uma aeronave, do ponto de origem até o retorno</description>
    <label>Voo</label>
    <nameField>
        <displayFormat>REVO-{00000000}</displayFormat>
        <label>Número do Voo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Voos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Voo__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Define em que momento o voo se encontra</description>
    <inlineHelpText>Define em que momento o voo se encontra</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Rascunho</fullName>
                <default>true</default>
                <label>Rascunho</label>
            </value>
            <value>
                <fullName>Pré-reservado</fullName>
            </value>
            <value>
                <fullName>Reservado</fullName>
            </value>
            <value>
                <fullName>Confirmado</fullName>
            </value>
            <value>
                <fullName>Rota</fullName>
                <label>Em Rota</label>
            </value>
            <value>
                <fullName>LogPendente</fullName>
                <label>Concluindo o Voo</label>
            </value>
            <value>
                <fullName>Executado</fullName>
            </value>
            <value>
                <fullName>Em Faturamento</fullName>
                <isActive>false</isActive>
                <label>Em Faturamento</label>
            </value>
            <value>
                <fullName>Faturado</fullName>
                <isActive>false</isActive>
                <label>Faturado</label>
            </value>
            <value>
                <fullName>Pronto pra Voar</fullName>
                <isActive>false</isActive>
                <label>Pronto pra Voar</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Voo__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <description>Informa o tipo de transporte realizado pelo voo.</description>
    <inlineHelpText>Informs the type of transport performed by the flight.</inlineHelpText>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TipoVoo</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/StatusPendenteAprovado.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pendente</fullName>
        <default>true</default>
        <label>Pendente</label>
    </customValue>
    <customValue>
        <fullName>Validado</fullName>
    </customValue>
    <masterLabel>Status Pendente/Aprovado</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/TipoVoo.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ShuttleSeat</fullName>
        <label>Shuttle Seat</label>
    </customValue>
    <customValue>
        <fullName>Charter</fullName>
    </customValue>
    <customValue>
        <fullName>FullCabin</fullName>
        <label>Full Cabin</label>
    </customValue>
    <customValue>
        <fullName>Sanitário</fullName>
        <isActive>false</isActive>
        <label>Sanitário</label>
    </customValue>
    <customValue>
        <fullName>Treinamento</fullName>
        <isActive>false</isActive>
        <label>Treinamento</label>
    </customValue>
    <customValue>
        <fullName>SAR</fullName>
        <isActive>false</isActive>
        <label>SAR</label>
    </customValue>
    <customValue>
        <fullName>Passageiros</fullName>
        <isActive>false</isActive>
        <label>Passageiros</label>
    </customValue>
    <customValue>
        <fullName>Manutenção</fullName>
        <isActive>false</isActive>
        <label>Manutenção</label>
    </customValue>
    <customValue>
        <fullName>Treinamento NDC</fullName>
        <isActive>false</isActive>
        <label>Treinamento NDC</label>
    </customValue>
    <customValue>
        <fullName>MEDVAC</fullName>
        <isActive>false</isActive>
        <label>MEDVAC</label>
    </customValue>
    <customValue>
        <fullName>Cargueiro</fullName>
        <isActive>false</isActive>
        <label>Cargueiro</label>
    </customValue>
    <customValue>
        <fullName>Passageiros e Cargas</fullName>
        <isActive>false</isActive>
        <label>Passageiros e Cargas</label>
    </customValue>
    <masterLabel>Tipo de voo</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CalculoMissaoResultTest.cls
@isTest
public with sharing class CalculoMissaoResultTest {
    
    @TestSetup
    static void makeData(){

        Id standardPricebookId = TestUtil.SetupStandardPricebook();

        Date dataMissao = Date.today().addDays(2);
        Datetime data = Datetime.newInstance(dataMissao, Time.newInstance(15, 0, 0, 0));

        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        Voo__c voo = TestUtil2.criarVooRascunho(data, false, uow);
        uow.commitWork();

        Trecho__c primeiroTrecho = [SELECT Id, Destino__c FROM Trecho__c WHERE OrdemExecucao__c = 10 AND Voo__c = :voo.Id];
        Local__c localDestino = new Local__c(Id = primeiroTrecho.Destino__c, Tipo__c='Offshore');
        update localDestino;

        IntervaloSol__c intervalo = new IntervaloSol__c(
            CodigoICAO__c = 'ABCD',
            Date__c = dataMissao,
            Sunrise__c = Time.newInstance(20, 0, 0, 0),
            Sunset__c = Time.newInstance(6, 0, 0, 0));
        insert intervalo;
        
        Local__c base = new Local__c(
            Name='Teste',
            Tipo__c='Onshore',
            Categoria__c='Base',
            Base__c=true,
            CodigoLocal__c='ABCD',
            CodigoICAO__c='ABCD',
            Status__c='Validado',
            Abastecimento__c='QAV',
            CoordenadasLatitudeGraus__c=22,
            CoordenadasLatitudeMinutos__c=22,
            CoordenadasLatitudeSegundos__c=0,
            CoordenadasLatitudeDirecao__c='S',
            CoordenadasLongitudeGraus__c=41,
            CoordenadasLongitudeMinutos__c=41,
            CoordenadasLongitudeSegundos__c=0);
        insert base;

        Aeronave__c aeronave = [SELECT Id, Name, BaseMae__c FROM Aeronave__c WHERE Id = :voo.Prefixo__c LIMIT 1];
        aeronave.BaseMae__c = base.Id;
        update aeronave;
    }

    @isTest
    static void ExecutarCalculoMissaoTest(){
        Voo__c voo = [SELECT Id, Prefixo__c, Prefixo__r.Name FROM Voo__c LIMIT 1];

        Map<Id, Voo__c> mapVooComTrecho = new Map<Id, Voo__c>(VoosSelector.newInstance().selectWithTrechosById(new Set<Id> {voo.Id}));
        List<Local__c> trajeto = Trechos.newInstance(mapVooComTrecho.get(voo.Id).Trechos__r).getTrajeto();
        
        Test.startTest();
        CalculoMissaoResult cmr = new CalculoMissaoResult();
        cmr.ExecutarCalculoMissao(voo.Prefixo__r, trajeto, mapVooComTrecho.get(voo.Id).DataVoo__c.date());
        Test.stopTest();
    }
}