force-app/main/default/objects/Abastecimento__c/Abastecimento__c.object-meta.xml
<CustomObject>
    <label>Abastecimento</label>
    <nameField>
        <displayFormat>Abast-{00000}</displayFormat>
        <label>Abastecimento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Abastecimentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Abastecimento__c/fields/Local__c.field-meta.xml
<CustomField>
    <fullName>Local__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Local</label>
    <referenceTo>Local__c</referenceTo>
    <relationshipLabel>Abastecimentos</relationshipLabel>
    <relationshipName>Abastecimentos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Abastecimento__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Novo</fullName>
                <default>true</default>
                <label>Novo</label>
            </value>
            <value>
                <fullName>Faturado</fullName>
            </value>
            <value>
                <fullName>Em faturamento</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Aeronave__c/Aeronave__c.object-meta.xml
<CustomObject>
    <label>Aeronave</label>
    <nameField>
        <label>Prefixo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aeronaves</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Aeronave__c/fields/BaseMae__c.field-meta.xml
<CustomField>
    <fullName>BaseMae__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Base Mãe da Aeronave</description>
    <inlineHelpText>Base Mãe da Aeronave</inlineHelpText>
    <label>Base Mãe</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Local__c.Base__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Local__c</referenceTo>
    <relationshipLabel>Aeronaves Hospedadas</relationshipLabel>
    <relationshipName>AeronaveLocal</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Aeronave__c/fields/CapacidadeTotalCombustivel__c.field-meta.xml
<CustomField>
    <fullName>CapacidadeTotalCombustivel__c</fullName>
    <description>Capacidade total de combustível suportada pela aeronave</description>
    <inlineHelpText>Capacidade total de combustível suportada pela aeronave</inlineHelpText>
    <label>Capacidade Total de Combustível</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Aeronave__c/fields/ConsumoHoraSolo__c.field-meta.xml
<CustomField>
    <fullName>ConsumoHoraSolo__c</fullName>
    <description>Consumo por hora no solo</description>
    <inlineHelpText>Consumo por hora no solo</inlineHelpText>
    <label>Consumo/Hora (Solo)</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Aeronave__c/fields/ConsumoHoraVoo__c.field-meta.xml
<CustomField>
    <fullName>ConsumoHoraVoo__c</fullName>
    <description>Consumo por hora durante o voo</description>
    <inlineHelpText>Consumo por hora durante o voo</inlineHelpText>
    <label>Consumo/Hora (Voo)</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Aeronave__c/fields/ModeloAeronave__c.field-meta.xml
<CustomField>
    <fullName>ModeloAeronave__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Define o modelo de aeronave</description>
    <inlineHelpText>Define o modelo de aeronave</inlineHelpText>
    <label>Modelo de aeronave</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Aeronaves</relationshipLabel>
    <relationshipName>Aeronaves</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Aeronave__c/fields/PesoBasicoOperacional__c.field-meta.xml
<CustomField>
    <fullName>PesoBasicoOperacional__c</fullName>
    <description>Indica o peso básico de operação da aeronave incluindo a tripulação.</description>
    <inlineHelpText>Indica o peso básico de operação da aeronave incluindo a tripulação.</inlineHelpText>
    <label>Peso Básico Operacional (PBO)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Aeronave__c/fields/Tamanho__c.field-meta.xml
<CustomField>
    <fullName>Tamanho__c</fullName>
    <description>Tamanho da aeronave em metros</description>
    <inlineHelpText>Tamanho da aeronave em metros</inlineHelpText>
    <label>Tamanho (m)</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Aeronave__c/fields/TempoSoloAterrissagem__c.field-meta.xml
<CustomField>
    <fullName>TempoSoloAterrissagem__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Tempo de solo da aterrissagem em segundos</inlineHelpText>
    <label>Tempo de Solo Aterrissagem</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Aeronave__c/fields/TempoSoloDecolagem__c.field-meta.xml
<CustomField>
    <fullName>TempoSoloDecolagem__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Tempo de solo da decolagem em segundos</inlineHelpText>
    <label>Tempo de Solo Decolagem</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Aeronave__c/fields/TipoCombustivel__c.field-meta.xml
<CustomField>
    <fullName>TipoCombustivel__c</fullName>
    <description>Tipo de combustível utilizado pela aeronave</description>
    <inlineHelpText>Tipo de combustível utilizado pela aeronave</inlineHelpText>
    <label>Tipo de Combustível</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TipoCombustivel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Aeronave__c/fields/TipoOperacao__c.field-meta.xml
<CustomField>
    <fullName>TipoOperacao__c</fullName>
    <label>Tipo de Operação</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Spot</fullName>
            </value>
            <value>
                <fullName>Contrato</fullName>
            </value>
            <value>
                <fullName>Shared</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Aeronave__c/fields/VelocidadeCruzeiro__c.field-meta.xml
<CustomField>
    <fullName>VelocidadeCruzeiro__c</fullName>
    <description>Velocidade de Cruzeiro da Aeronave</description>
    <inlineHelpText>Velocidade de Cruzeiro da Aeronave</inlineHelpText>
    <label>Velocidade de Cruzeiro (nm/h)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Aerovia__c/Aerovia__c.object-meta.xml
<CustomObject>
    <label>Aerovia</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Nome</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Aerovias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Aerovia__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unidirecional</fullName>
            </value>
            <value>
                <fullName>Bidirecional</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IntervaloSol__c/IntervaloSol__c.object-meta.xml
<CustomObject>
    <label>Intervalo do Sol</label>
    <nameField>
        <displayFormat>PS-{00000000}</displayFormat>
        <label>Código de Por do Sol</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intervalos de Sol</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IntervaloSol__c/fields/CodigoICAO__c.field-meta.xml
<CustomField>
    <fullName>CodigoICAO__c</fullName>
    <description>Código ICAO</description>
    <inlineHelpText>Código ICAO</inlineHelpText>
    <label>Código ICAO</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Local__c/Local__c.object-meta.xml
<CustomObject>
    <label>Local</label>
    <nameField>
        <label>Local</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Local__c/fields/Abastecimento__c.field-meta.xml
<CustomField>
    <fullName>Abastecimento__c</fullName>
    <description>Tipo de Abastecimento disponíveis no Local</description>
    <inlineHelpText>Tipo de Abastecimento disponíveis no Local</inlineHelpText>
    <label>Abastecimento</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>QAV</fullName>
            </value>
            <value>
                <fullName>AVGAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Local__c/fields/Base__c.field-meta.xml
<CustomField>
    <fullName>Base__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Define se o local cadastro é uma base onde uma ou mais equipes operam.</description>
    <inlineHelpText>Define se o local cadastro é uma base onde uma ou mais equipes operam.</inlineHelpText>
    <label>É Base</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Local__c/fields/CapacidadeMaxima__c.field-meta.xml
<CustomField>
    <fullName>CapacidadeMaxima__c</fullName>
    <description>Capacidade Máxima de peso suportada pelo helideck</description>
    <inlineHelpText>Maximum weight capacity supported by the helideck</inlineHelpText>
    <label>Capacidade Máxima (t)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Local__c/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <label>Modelo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Base</fullName>
            </value>
            <value>
                <fullName>FPSO</fullName>
            </value>
            <value>
                <fullName>FSO</fullName>
            </value>
            <value>
                <fullName>Plataforma</fullName>
            </value>
            <value>
                <fullName>Sonda</fullName>
            </value>
            <value>
                <fullName>UMS</fullName>
            </value>
            <value>
                <fullName>Sísmica</fullName>
            </value>
            <value>
                <fullName>PLSV</fullName>
            </value>
            <value>
                <fullName>Clareira</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Local__c/fields/CodigoICAO__c.field-meta.xml
<CustomField>
    <fullName>CodigoICAO__c</fullName>
    <description>Código ICAO da estação meteorológica mais próxima</description>
    <inlineHelpText>Código ICAO da estação meteorológica mais próxima</inlineHelpText>
    <label>Estação meteorológica</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Local__c/fields/CodigoLocal__c.field-meta.xml
<CustomField>
    <fullName>CodigoLocal__c</fullName>
    <description>Código que identifica o local</description>
    <externalId>true</externalId>
    <inlineHelpText>Código que identifica o local</inlineHelpText>
    <label>Código do local</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Local__c/fields/Coordenadas__c.field-meta.xml
<CustomField>
    <fullName>Coordenadas__c</fullName>
    <description>Latitude e longitude que indicam a posição de um local</description>
    <inlineHelpText>Latitude e longitude que indicam a posição de um local</inlineHelpText>
    <label>Coordenadas</label>
    <scale>8</scale>
    <type>Location</type>
</CustomField>

force-app/main/default/objects/Local__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status para validação de um local</description>
    <inlineHelpText>Status para validação de um local</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>StatusPendenteAprovado</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Local__c/fields/Tamanho__c.field-meta.xml
<CustomField>
    <fullName>Tamanho__c</fullName>
    <description>Tamanho do helideck em metros</description>
    <inlineHelpText>Tamanho do helideck em metros</inlineHelpText>
    <label>Tamanho (m)</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Local__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <description>Define se o local é em terra(onshore) ou em mar(offshore)</description>
    <inlineHelpText>Define se o local é em terra(onshore) ou em mar(offshore)</inlineHelpText>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Onshore</fullName>
            </value>
            <value>
                <fullName>Offshore</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/StatusPendenteAprovado.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pendente</fullName>
        <default>true</default>
        <label>Pendente</label>
    </customValue>
    <customValue>
        <fullName>Validado</fullName>
    </customValue>
    <masterLabel>Status Pendente/Aprovado</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/TipoCombustivel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>QAV</fullName>
    </customValue>
    <customValue>
        <fullName>AVGAS</fullName>
    </customValue>
    <masterLabel>Tipo combustível</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CalculoMissaoSingleton.cls
public class CalculoMissaoSingleton 
{
    private static CalculoMissaoSingleton instance =null;
    public static CalculoMissaoSingleton getInstance()
    {
        if(instance == null) instance = new CalculoMissaoSingleton();
        return instance;
    }
    
    public Map<id, local__c> locais
    {
        get
        {
            if(this.locais == null) locais = new Map<id, local__c> ([SELECT Id, Name, Tipo__c, Coordenadas__Latitude__s, Coordenadas__Longitude__s, Coordenadas__c, 
                                              CodigoLocal__c, Categoria__c, Base__c, Status__c, CodigoICAO__c, CapacidadeMaxima__c, Abastecimento__c, RecordType.Name FROM Local__c where Coordenadas__Latitude__s <> null and Coordenadas__Longitude__s <> null]);
            return locais;
        }
        private set;
        
    }
    
    public Map<id, local__c> locaisCoordenadasAlteradas
    {
        get
        {
            if (locaisCoordenadasAlteradas==null)
            {
                this.locaisCoordenadasAlteradas = new Map<id, local__c>();
                return locaisCoordenadasAlteradas;
            }
            else return locaisCoordenadasAlteradas;
        }
        private set;
        
    }
    
    public Map<id,Aeronave__c> aeronaves
    {
        get
        {
            if(this.aeronaves == null) aeronaves = new Map<id,Aeronave__c>([SELECT Name, TipoOperacao__c, ModeloAeronave__c, BaseMae__c, VelocidadeCruzeiro__c, ConsumoHoraSolo__c, ConsumoHoraVoo__c, Tamanho__c, 
                                                    TipoCombustivel__c, CapacidadeTotalCombustivel__c, PesoBasicoOperacional__c, TempoSoloAterrissagem__c, TempoSoloDecolagem__c,
                                                    NumeroAssentos__c, Id, UnidadeMedida__c, AnoFabricacao__c, ModeloAeronave__r.Porte__c, PesoMaximoDecolagem__c, ModeloAeronave__r.Name FROM Aeronave__c]);
            return aeronaves;
        }
        private set;
        
    }
        
    public Map<id,Aerovia__c> aerovias
    {
        get
        {
            if(this.aerovias == null) aerovias = new Map<id,Aerovia__c>([SELECT Id, Name, Origem__c, Destino__c, Tipo__c FROM Aerovia__c]);
            return aerovias;
        }
        private set;
        
    }
    
    public Map<date,Map<string, IntervaloSol__c>> horariosSol
    {
        get
        {
            if(this.horariosSol ==null)
            {
                horariosSol = new Map<date,Map<string, IntervaloSol__c>>();
                List<IntervaloSol__c> intervalos = IntervalosSolSelector.newInstance().selectAllFuture();
                for(IntervaloSol__c intervalo :intervalos)
                {
                    if(horariosSol.containsKey(intervalo.date__c))
                    {
                        horariosSol.get(intervalo.date__c).put(intervalo.CodigoICAO__c, intervalo);
                    }
                    else
                    {
                        horariosSol.put(intervalo.date__c, new Map<string, IntervaloSol__c>{intervalo.CodigoICAO__c => intervalo});
                    }
                }
            }
            return horariosSol;
        }
        private set;
    }
    
    public Map<string, FlightLeg> calculatedRoute = new Map<string, FlightLeg>();
    

}