force-app/main/default/objects/Carga__c/Carga__c.object-meta.xml
<CustomObject>
    <label>Carga</label>
    <nameField>
        <label>Identificação</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cargas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Carga__c/fields/Trecho__c.field-meta.xml
<CustomField>
    <fullName>Trecho__c</fullName>
    <description>Trecho o qual a carga pertence</description>
    <inlineHelpText>Trecho o qual a carga pertence</inlineHelpText>
    <label>Trecho</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Trecho Em Rota ou Finalizado</errorMessage>
        <filterItems>
            <field>Trecho__c.Status__c</field>
            <operation>equals</operation>
            <value>Não Iniciado</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Trecho__c</referenceTo>
    <relationshipLabel>Cargas</relationshipLabel>
    <relationshipName>Cargas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Local__c/Local__c.object-meta.xml
<CustomObject>
    <label>Local</label>
    <nameField>
        <label>Local</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Local__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status para validação de um local</description>
    <inlineHelpText>Status para validação de um local</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>StatusPendenteAprovado</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trecho__c/Trecho__c.object-meta.xml
<CustomObject>
    <description>Define um trecho com origem e destino dentro de um Voo</description>
    <label>Trecho</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Código do Trecho</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trechos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trecho__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Não Iniciado</fullName>
                <default>true</default>
                <label>Não Iniciado</label>
            </value>
            <value>
                <fullName>Check In Fechado</fullName>
            </value>
            <value>
                <fullName>Em Rota</fullName>
            </value>
            <value>
                <fullName>Finalizado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trecho__c/fields/Voo__c.field-meta.xml
<CustomField>
    <fullName>Voo__c</fullName>
    <description>Voo ao qual o trecho pertence</description>
    <inlineHelpText>Voo ao qual o trecho pertence</inlineHelpText>
    <label>Voo</label>
    <referenceTo>Voo__c</referenceTo>
    <relationshipLabel>Trechos</relationshipLabel>
    <relationshipName>Trechos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Voo__c/Voo__c.object-meta.xml
<CustomObject>
    <description>O Voo de uma aeronave, do ponto de origem até o retorno</description>
    <label>Voo</label>
    <nameField>
        <displayFormat>REVO-{00000000}</displayFormat>
        <label>Número do Voo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Voos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Voo__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Define em que momento o voo se encontra</description>
    <inlineHelpText>Define em que momento o voo se encontra</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Rascunho</fullName>
                <default>true</default>
                <label>Rascunho</label>
            </value>
            <value>
                <fullName>Pré-reservado</fullName>
            </value>
            <value>
                <fullName>Reservado</fullName>
            </value>
            <value>
                <fullName>Confirmado</fullName>
            </value>
            <value>
                <fullName>Rota</fullName>
                <label>Em Rota</label>
            </value>
            <value>
                <fullName>LogPendente</fullName>
                <label>Concluindo o Voo</label>
            </value>
            <value>
                <fullName>Executado</fullName>
            </value>
            <value>
                <fullName>Em Faturamento</fullName>
                <isActive>false</isActive>
                <label>Em Faturamento</label>
            </value>
            <value>
                <fullName>Faturado</fullName>
                <isActive>false</isActive>
                <label>Faturado</label>
            </value>
            <value>
                <fullName>Pronto pra Voar</fullName>
                <isActive>false</isActive>
                <label>Pronto pra Voar</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/StatusPendenteAprovado.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pendente</fullName>
        <default>true</default>
        <label>Pendente</label>
    </customValue>
    <customValue>
        <fullName>Validado</fullName>
    </customValue>
    <masterLabel>Status Pendente/Aprovado</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CargasSelectorTest.cls
@isTest
public class CargasSelectorTest {
    
    @testSetup
    public static void setup()
    {
        Id standardPricebookId = TestUtil.SetupStandardPricebook();
        
        TestUtil.insereConfiguracoesPersonalizadas();
    }

    @IsTest
	private static void testSelectById()
	{
        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        
        Integer numCargasTrecho = 2;
        
        List<Account> contas = TestUtil.criarContas(uow, 1);
        List<Voo__c> voos = TestUtil.criarVoos(uow, 1, contas);
        List<Local__c> locais = TestUtil.criarLocais(uow, 2);
        List<Trecho__c> trechos = TestUtil.criarTrechos(uow, voos, locais.get(0), locais.get(1), 2);
        List<Carga__c> cargas = TestUtil.criarCargas(uow, trechos, numCargasTrecho);
        
        uow.commitWork();
        
		Carga__c carga = [SELECT Id, Trecho__c FROM Carga__c LIMIT 1];		
        
        // Query
        List<Carga__c> cargasSelecionadas = new CargasSelector().selectById(new Set<Id> {carga.Id});
        Carga__c cargaSelecionada = cargasSelecionadas.get(0);
		// Assert
		System.assertEquals(carga.Id, cargaSelecionada.Id);		
		System.assertEquals(carga.Trecho__c, cargaSelecionada.Trecho__c);	
	}
    
    @IsTest
	private static void testSelectByIdWithTrechosIniciados()
	{
		
        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        
        Integer numCargasTrecho = 2;
        
        List<Account> contas = TestUtil.criarContas(uow, 1);
        List<Voo__c> voos = TestUtil.criarVoos(uow, 2, contas);        
        List<Local__c> locais = TestUtil.criarLocais(uow, 2);
        List<Trecho__c> trechos = TestUtil.criarTrechos(uow, voos, locais.get(0), locais.get(1), 2);
        List<Carga__c> cargas = TestUtil.criarCargas(uow, trechos, numCargasTrecho);
        
        Trecho__c trecho3 = trechos.get(2);
        
        uow.commitWork();
        
        Test.startTest();

        Trecho__c trecho1 = trechos.get(0);
        Trecho__c trecho2 = trechos.get(1);
		trecho1.Status__c = 'Em Rota';
        trecho2.Status__c = 'Finalizado';
        
        List<Trecho__c> trechosToUpdate = new List<Trecho__c>();
        trechosToUpdate.add(trecho1);
        trechosToUpdate.add(trecho2);
        update trechosToUpdate;
            
        Set<Id> trechoIds = new Set<Id> {trecho1.Id, trecho2.Id, trecho3.Id};
        List<Trecho__c> trechosAValidar = [SELECT Id, (SELECT Id FROM Cargas__r) FROM Trecho__c WHERE ID IN : trechoIds];
        Set<Id> cargaIds = new Set<Id>();
        for(Trecho__c trecho : trechosAValidar)
        {
            for(Carga__c carga : trecho.Cargas__r)
            {
                cargaIds.add(carga.Id);
            }
        }
        
        Test.stopTest();
        // Query
        List<Carga__c> cargasSelecionadas = new CargasSelector().selectByIdWithTrechosIniciados(cargaIds);
        // Assert
        System.assertEquals(4, cargasSelecionadas.size());	
		
	}
    
    @IsTest
	private static void testQueryLocatorCargasDeletadas()
	{
        
        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        
        List<Account> contas = TestUtil.criarContas(uow, 1);
        List<Voo__c> voos = TestUtil.criarVoos(uow, 1, contas);
        List<Local__c> locais = TestUtil.criarLocais(uow, 2);
        List<Trecho__c> trechos = TestUtil.criarTrechos(uow, voos, locais.get(0), locais.get(1), 1);
        Carga__c carga = new Carga__c();
        carga.Name = 'Baita carga';
        uow.registerNew(carga, Carga__c.Trecho__c, trechos.get(0));

        uow.commitWork();
        
        fflib_ISObjectUnitOfWork uow2 = Application.UnitOfWork.newInstance();
        uow2.registerDeleted(carga);
        uow2.commitWork();
        
		// Query
        Database.QueryLocator queryLocator = 
			new CargasSelector().queryLocatorCargasDeletadas();
			
		// Assert
		Database.QueryLocatorIterator cargasIterator = queryLocator.iterator();
		Carga__c queriedCarga = (Carga__c) cargasIterator.next();
		System.assertEquals('Baita carga', queriedCarga.Name);		
	
	}

    
    @IsTest
    private static void testNewInstance()
	{
		ICargasSelector cargasSelector = CargasSelector.newInstance();
        System.assertNotEquals(cargasSelector, null);
	}
    
    @isTest
    private static void selectByVooIdTest() {  
        Test.startTest();
        List<Carga__c> cargaList = new CargasSelector(true).selectByVooId(new Set<Id>());
        Test.stopTest();
        
        System.assert(cargaList.size() == 0);
    }
}