force-app/main/default/objects/Carga__c/Carga__c.object-meta.xml
<CustomObject>
    <label>Carga</label>
    <nameField>
        <label>Identificação</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cargas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Carga__c/fields/Peso__c.field-meta.xml
<CustomField>
    <fullName>Peso__c</fullName>
    <description>Define o peso em kg da carga</description>
    <inlineHelpText>Define o peso em kg da carga</inlineHelpText>
    <label>Peso (kg)</label>
    <precision>9</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Carga__c/fields/Trecho__c.field-meta.xml
<CustomField>
    <fullName>Trecho__c</fullName>
    <description>Trecho o qual a carga pertence</description>
    <inlineHelpText>Trecho o qual a carga pertence</inlineHelpText>
    <label>Trecho</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Trecho Em Rota ou Finalizado</errorMessage>
        <filterItems>
            <field>Trecho__c.Status__c</field>
            <operation>equals</operation>
            <value>Não Iniciado</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Trecho__c</referenceTo>
    <relationshipLabel>Cargas</relationshipLabel>
    <relationshipName>Cargas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Trecho__c/Trecho__c.object-meta.xml
<CustomObject>
    <description>Define um trecho com origem e destino dentro de um Voo</description>
    <label>Trecho</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Código do Trecho</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trechos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trecho__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Não Iniciado</fullName>
                <default>true</default>
                <label>Não Iniciado</label>
            </value>
            <value>
                <fullName>Check In Fechado</fullName>
            </value>
            <value>
                <fullName>Em Rota</fullName>
            </value>
            <value>
                <fullName>Finalizado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trecho__c/fields/Voo__c.field-meta.xml
<CustomField>
    <fullName>Voo__c</fullName>
    <description>Voo ao qual o trecho pertence</description>
    <inlineHelpText>Voo ao qual o trecho pertence</inlineHelpText>
    <label>Voo</label>
    <referenceTo>Voo__c</referenceTo>
    <relationshipLabel>Trechos</relationshipLabel>
    <relationshipName>Trechos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Voo__c/Voo__c.object-meta.xml
<CustomObject>
    <description>O Voo de uma aeronave, do ponto de origem até o retorno</description>
    <label>Voo</label>
    <nameField>
        <displayFormat>REVO-{00000000}</displayFormat>
        <label>Número do Voo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Voos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Voo__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Define em que momento o voo se encontra</description>
    <inlineHelpText>Define em que momento o voo se encontra</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Rascunho</fullName>
                <default>true</default>
                <label>Rascunho</label>
            </value>
            <value>
                <fullName>Pré-reservado</fullName>
            </value>
            <value>
                <fullName>Reservado</fullName>
            </value>
            <value>
                <fullName>Confirmado</fullName>
            </value>
            <value>
                <fullName>Rota</fullName>
                <label>Em Rota</label>
            </value>
            <value>
                <fullName>LogPendente</fullName>
                <label>Concluindo o Voo</label>
            </value>
            <value>
                <fullName>Executado</fullName>
            </value>
            <value>
                <fullName>Em Faturamento</fullName>
                <isActive>false</isActive>
                <label>Em Faturamento</label>
            </value>
            <value>
                <fullName>Faturado</fullName>
                <isActive>false</isActive>
                <label>Faturado</label>
            </value>
            <value>
                <fullName>Pronto pra Voar</fullName>
                <isActive>false</isActive>
                <label>Pronto pra Voar</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CargasSelector.cls
public class CargasSelector extends fflib_SObjectSelector 
	implements ICargasSelector
{

    private static FINAL String naoIniciado = 'Não Iniciado';
    
    public static ICargasSelector newInstance()
	{
		return (ICargasSelector) Application.Selector.newInstance(Carga__c.SObjectType);
	}
    
    public CargasSelector(Boolean includeFieldSetFields)
    {
        super(includeFieldSetFields);

        this.setDataAccess(fflib_SObjectSelector.DataAccess.SYSTEM_MODE);
    }
    
    public CargasSelector()
    {
        super(true);

        this.setDataAccess(fflib_SObjectSelector.DataAccess.SYSTEM_MODE);
    }
    
    public override List<Schema.FieldSet> getSObjectFieldSetList()
    {
        return new List<Schema.FieldSet>	
        {	SobjectType.Carga__c.FieldSets.SelectFieldList	};
    }
    
    public List<Schema.SObjectField> getSObjectFieldList()
	{
		return new List<Schema.SObjectField> {
			Carga__c.Id,
            Carga__c.Name,
            Carga__c.Trecho__c,
           	Carga__c.Peso__c
		};
	}
    
    public List<Carga__c> selectByIdWithTrechosIniciados(Set<ID> idSet)
	{
        fflib_QueryFactory cargasQueryFactory = newQueryFactory();
 
      	/*fflib_SObjectSelector trechosSelector = new TrechosSelector();
      	trechosSelector.configureQueryFactoryFields(cargasQueryFactory, 'Trecho__r');*/

		return (List<Carga__c>) Database.query(
			cargasQueryFactory
            .setCondition('Id in :idSet AND Trecho__r.Status__c != :naoIniciado')
            .toSOQL());
	}
    
    public List<Carga__c> selectByVooId(Set<Id> vooId)
    {
        fflib_QueryFactory cargasQueryFactory = newQueryFactory();
        
        return (List<Carga__c>) Database.query(
            cargasQueryFactory
            .setCondition('Trecho__r.Voo__c IN :vooId')
            .toSOQL());
    }
    
    public Database.QueryLocator queryLocatorCargasDeletadas()
	{
        fflib_QueryFactory cargasQueryFactory = newQueryFactory();
 		
        new contentDocumentLinksSelector().
            addQueryFactorySubselect(cargasQueryFactory,'ContentDocumentLinks');
        
		return Database.getQueryLocator(
			cargasQueryFactory.setCondition('IsDeleted = true').toSOQL() + ' ALL ROWS');
	}
    
    public Schema.SObjectType getSObjectType()
	{
		return Carga__c.sObjectType;
	}
    
    public List<Carga__c> selectById(Set<ID> idSet)
	{
		return (List<Carga__c>) selectSObjectsById(idSet);
	}
}