force-app/main/default/objects/RegraPreco__c/RegraPreco__c.object-meta.xml
<CustomObject>
    <label>Regra de Preço</label>
    <nameField>
        <displayFormat>RP-{0000}</displayFormat>
        <label>Regra de Preço</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Regras de Preços</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RegraPreco__c/fields/DataFinal__c.field-meta.xml
<CustomField>
    <fullName>DataFinal__c</fullName>
    <label>Data Final</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RegraPreco__c/fields/DataInicial__c.field-meta.xml
<CustomField>
    <fullName>DataInicial__c</fullName>
    <label>Data Inicial</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RegraPreco__c/fields/DiaSemana__c.field-meta.xml
<CustomField>
    <fullName>DiaSemana__c</fullName>
    <label>Dia da Semana</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Domingo</fullName>
            </value>
            <value>
                <fullName>Segunda-feira</fullName>
            </value>
            <value>
                <fullName>Terça-feira</fullName>
            </value>
            <value>
                <fullName>Quarta-feira</fullName>
            </value>
            <value>
                <fullName>Quinta-feira</fullName>
            </value>
            <value>
                <fullName>Sexta-feira</fullName>
            </value>
            <value>
                <fullName>Sábado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RegraPreco__c/fields/HorarioFinal__c.field-meta.xml
<CustomField>
    <fullName>HorarioFinal__c</fullName>
    <label>Horário Final</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/RegraPreco__c/fields/HorarioInicial__c.field-meta.xml
<CustomField>
    <fullName>HorarioInicial__c</fullName>
    <label>Horário Inicial</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/RegraPreco__c/fields/LocalDestino__c.field-meta.xml
<CustomField>
    <fullName>LocalDestino__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Local Destino</label>
    <referenceTo>Local__c</referenceTo>
    <relationshipLabel>Regras de Preços (Local Destino)</relationshipLabel>
    <relationshipName>Regras_de_Precos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RegraPreco__c/fields/LocalOrigem__c.field-meta.xml
<CustomField>
    <fullName>LocalOrigem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Local Origem</label>
    <referenceTo>Local__c</referenceTo>
    <relationshipLabel>Regras de Preços</relationshipLabel>
    <relationshipName>RegrasPrecos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RegraPreco__c/fields/MinutosAntecedencia__c.field-meta.xml
<CustomField>
    <fullName>MinutosAntecedencia__c</fullName>
    <label>Minutos Antecedência</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RegraPreco__c/fields/ModeloAeronave__c.field-meta.xml
<CustomField>
    <fullName>ModeloAeronave__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Modelo Aeronave</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Regras de Preços (Modelo Aeronave)</relationshipLabel>
    <relationshipName>RegrasPrecosModelos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RegraPreco.cls
public class RegraPreco extends fflib_SObjectDomain {
    
    public RegraPreco(List<RegraPreco__c> sObjectList)
	{
		super(sObjectList);
	}
    
    public class Constructor implements fflib_SObjectDomain.IConstructable
	{
		public fflib_SObjectDomain construct(List<SObject> sObjectList)
		{
			return new RegraPreco(sObjectList);
		}
	}

    public static RegraPreco__c encontraRegraPrecoServico(List<RegraPreco__c> regras, DateTime previsaoDecolagem, Id modeloId, Id origemId, Id destinoId, String quem) {
        return encontraRegraPreco(true, true, regras, previsaoDecolagem, modeloId, origemId, destinoId, quem);
    }

    public static RegraPreco__c encontraRegraPrecoVoo(List<RegraPreco__c> regras, DateTime previsaoDecolagem, Id modeloId, String quem) {
        return encontraRegraPreco(true, true, regras, previsaoDecolagem, modeloId, null, null, quem);
    }

    public static RegraPreco__c encontraRegraPrecoCharter(List<RegraPreco__c> regras, DateTime previsaoDecolagem, Id modeloId, String quem) {
        return encontraRegraPreco(true, true, regras, previsaoDecolagem, modeloId, null, null, quem);
    }

    public static RegraPreco__c encontraRegraPreco(Boolean servicoValidaLocal, Boolean vooValidaModeloAeronave, List<RegraPreco__c> regras, DateTime previsaoDecolagem, Id modeloId, Id origemId, Id destinoId, String quem) {

        List<String> diasSemana = new List<String>{'Domingo', 'Segunda-feira', 'Terça-feira', 'Quarta-feira', 'Quinta-feira', 'Sexta-feira', 'Sábado'};

        String dia = diasSemana.get(Integer.valueOf(previsaoDecolagem.format('u')) - 1);
        Long diferencaMinutos = (previsaoDecolagem.getTime() - Datetime.now().getTime()) / (1000 * 60);

        RegraPreco__c selecionado = null;
        Integer espDatas = 0;
        Boolean aeronave = false;
        Boolean local = false;
        Decimal minutos = 0;

        if (regras.isEmpty()) return null;

        for (RegraPreco__c regra : regras) {
            if (!regra.Ativo__c) continue;

            if (servicoValidaLocal) {
                if (RegraPreco.localInvalido(regra, origemId, destinoId)) {
                    continue;                    
                }
            }

            if (RegraPreco.dataHoraInvalida(regra, previsaoDecolagem)) {
                continue;
            } 

            if (!regra.DiaSemana__c.contains(dia))  {
                continue;
            }

            if (vooValidaModeloAeronave) {
                if (regra.ModeloAeronave__c != null && regra.ModeloAeronave__c != modeloId) {
                    continue;
                } 
            }

            if (regra.MinutosAntecedencia__c > diferencaMinutos) {
                continue;
            } 

            Integer tmpEspDatas = regra.DataFinal__c.daysBetween(regra.DataInicial__c);
            Boolean tmpLocal = servicoValidaLocal && (regra.LocalOrigem__c != null || regra.LocalDestino__c != null);
            Boolean tmpAeronave = vooValidaModeloAeronave && regra.ModeloAeronave__c != null;
            Decimal tmpMinutos = regra.MinutosAntecedencia__c;

            /* 1) Priorizar a Escolha quando for selecionada um modelo de aeronave ou local */
            /* 2) Priorizar a Escolha quando for o menor tempo de minutos de antecedencia */
            /* 3) Priorizar a Escolha quando for a seleção de datas mais específica */

            if (selecionado != null) {
                if (aeronave && !tmpAeronave) continue;
                if (local && !tmpLocal) continue;

                if (tmpAeronave == aeronave) {
                    if (tmpMinutos > minutos) continue;
                    if (tmpEspDatas > espDatas) continue;
                }
            } 

            selecionado = regra;
            espDatas = tmpEspDatas;
            aeronave = tmpAeronave;
            local = tmpLocal;
            minutos = tmpMinutos;
        }

        return selecionado;
    }

    private static Boolean dataHoraInvalida(RegraPreco__c regra, Datetime previsaoDecolagem) {
        return (regra.DataInicial__c > previsaoDecolagem.date())
            || (regra.DataFinal__c < previsaoDecolagem.date())
            || (regra.HorarioInicial__c > previsaoDecolagem.time())
            || (regra.HorarioFinal__c < previsaoDecolagem.time());
    }

    private static Boolean localInvalido(RegraPreco__c regra, Id origemId, Id destinoId) {
        return (regra.LocalOrigem__c != null && regra.LocalOrigem__c != origemId)
            || (regra.LocalDestino__c != null && regra.LocalDestino__c != destinoId);
    }    
}