force-app/main/default/objects/Empenho__c/Empenho__c.object-meta.xml
<CustomObject>
    <label>Empenho</label>
    <nameField>
        <displayFormat>EMP-{0000000}</displayFormat>
        <label>Empenho</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Empenhos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Empenho__c/fields/DataVoo__c.field-meta.xml
<CustomField>
    <fullName>DataVoo__c</fullName>
    <formula>Servico__r.Voo__r.DataVoo__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Data Voo</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Empenho__c/fields/NomePassageiro__c.field-meta.xml
<CustomField>
    <fullName>NomePassageiro__c</fullName>
    <formula>Servico__r.Passageiro__r.NomeContato__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nome Passageiro</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Empenho__c/fields/NomeProduto__c.field-meta.xml
<CustomField>
    <fullName>NomeProduto__c</fullName>
    <formula>Servico__r.Produto__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nome Produto</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Empenho__c/fields/Pagamento__c.field-meta.xml
<CustomField>
    <fullName>Pagamento__c</fullName>
    <label>Pagamento</label>
    <referenceTo>Pagamento__c</referenceTo>
    <relationshipLabel>Empenhos</relationshipLabel>
    <relationshipName>Empenhos</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Empenho__c/fields/RotaVoo__c.field-meta.xml
<CustomField>
    <fullName>RotaVoo__c</fullName>
    <formula>Servico__r.Voo__r.Rota__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Rota Voo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Empenho__c/fields/Servico__c.field-meta.xml
<CustomField>
    <fullName>Servico__c</fullName>
    <label>Serviço</label>
    <referenceTo>Servico__c</referenceTo>
    <relationshipLabel>Empenhos</relationshipLabel>
    <relationshipName>Empenhos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Empenho__c/fields/ValorEmpenho__c.field-meta.xml
<CustomField>
    <fullName>ValorEmpenho__c</fullName>
    <label>Valor do Empenho</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Pagamento__c/Pagamento__c.object-meta.xml
<CustomObject>
    <label>Pagamento</label>
    <nameField>
        <displayFormat>PAGTO-{0000000}</displayFormat>
        <label>Pagamento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pagamentos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Pagamento__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pagamentos</relationshipLabel>
    <relationshipName>Pagamentos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Pagamento__c/fields/StatusPagamento__c.field-meta.xml
<CustomField>
    <fullName>StatusPagamento__c</fullName>
    <label>Status do Pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendente</fullName>
                <default>true</default>
                <label>Pendente</label>
            </value>
            <value>
                <fullName>Efetuado</fullName>
            </value>
            <value>
                <fullName>Devolvido</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Faturado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Servico__c/Servico__c.object-meta.xml
<CustomObject>
    <label>Serviço</label>
    <nameField>
        <displayFormat>SERV-{0000000}</displayFormat>
        <label>Serviço</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Serviços</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Servico__c/fields/NomePassageiro__c.field-meta.xml
<CustomField>
    <fullName>NomePassageiro__c</fullName>
    <formula>Passageiro__r.Contato__r.FirstName + &apos; &apos; + Passageiro__r.Contato__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nome Passageiro</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Servico__c/fields/NomeProduto__c.field-meta.xml
<CustomField>
    <fullName>NomeProduto__c</fullName>
    <formula>Produto__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nome Produto</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Servico__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Serviços</relationshipLabel>
    <relationshipName>Servicos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Servico__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aguardando Execução</fullName>
            </value>
            <value>
                <fullName>PreReservado</fullName>
                <label>Pré-Reservado</label>
            </value>
            <value>
                <fullName>Pago</fullName>
            </value>
            <value>
                <fullName>Executado</fullName>
            </value>
            <value>
                <fullName>No-Show</fullName>
            </value>
            <value>
                <fullName>Faturado</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Servico__c/fields/ValorPago__c.field-meta.xml
<CustomField>
    <fullName>ValorPago__c</fullName>
    <label>Valor Pago</label>
    <summarizedField>Empenho__c.ValorEmpenho__c</summarizedField>
    <summaryForeignKey>Empenho__c.Servico__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Servico__c/fields/ValorTotal__c.field-meta.xml
<CustomField>
    <fullName>ValorTotal__c</fullName>
    <label>Valor Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/UsuarioSite__c/UsuarioSite__c.object-meta.xml
<CustomObject>
    <label>Usuário Site</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Usuários Site</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UsuarioSite__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Usuários Site</relationshipLabel>
    <relationshipName>UsuariosSite</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UsuarioSite__c/fields/IdSite__c.field-meta.xml
<CustomField>
    <fullName>IdSite__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Id do Site</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/RevoSitePaymentView.cls
@RestResource(urlMapping='/revosite/v1/payment/view')
global without sharing class RevoSitePaymentView {

    @HttpPost
    global static void view(PaymentView view) {
        try {
            fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();

            Pagamento__c pagamento = PagamentosSelector.newInstance().selectPagamentoGateway(view.salesforcePaymentId);

            if (pagamento == null) {
                throw new PagamentoNaoEncontradoException(true);
            }            

            UsuarioSite__c usuario = UsuarioSiteSelector.newInstance().encontraPelaConta(pagamento.Conta__c);

            PaymentViewResult resultado = new PaymentViewResult();

            resultado.webSiteUserId = usuario != null ? usuario.IdSite__c : null;
            resultado.customerName = pagamento.conta__r.Name;
            resultado.customerTypeDocument = pagamento.conta__r.isPersonAccount ? pagamento.conta__r.TipoDocumento__pc : 'CNPJ';
            resultado.customerDocument = pagamento.conta__r.isPersonAccount ? pagamento.conta__r.NumeroDocumento__pc : pagamento.conta__r.CNPJCPF__c;
            resultado.customerPhone = pagamento.conta__r.Phone;
            resultado.customerEmail = pagamento.conta__r.isPersonAccount ? pagamento.conta__r.PersonEmail : pagamento.conta__r.Email__c;
            resultado.paymentStatus = pagamento.StatusPagamento__c;         

            resultado.totalPending = 0;

            if (pagamento.StatusPagamento__c == 'Pendente') {

                for (Empenho__c empenho : pagamento.Empenhos__r) {

                    if (sfd(empenho.ValorEmpenho__c) != 0) {
                        continue;
                    }

                    if (empenho.Servico__r.Status__c != 'PreReservado') {
                        continue;
                    }

                    Service servico = new Service();

                    servico.productId = empenho.Servico__r.Produto__c;
                    servico.serviceId = empenho.Servico__c;
                    servico.serviceProductName = empenho.NomeProduto__c;
                    servico.routeFlightName = empenho.RotaVoo__c;
                    servico.flightDateTime = empenho.DataVoo__c;
                    servico.passangerName = empenho.NomePassageiro__c;

                    servico.pendingPayment = sfd(empenho.Servico__r.ValorTotal__c) - sfd(empenho.Servico__r.ValorPago__c);

                    resultado.totalPending += servico.pendingPayment;

                    resultado.servicesToPay.add(servico);
                }         
            }

            RestContext.response.addHeader('Content-Type', 'application/json');
            RestContext.response.responseBody = Blob.valueOf(
                JSON.serialize(resultado)
            );

        } catch (Exception e) {
            RevoSiteApi.standardBadResult(e);
        }
    }

    private static Decimal sfd(Decimal value) {
        return (value == null) ? 0 : value;
    }

    global class PaymentView {

        public String salesforcePaymentId { get; set; }

    }

    global class PaymentViewResult {
        public String webSiteUserId {get;set;}
        public String customerName {get;set;}
        public String customerTypeDocument {get;set;}
        public String customerDocument {get;set;}
        public String customerPhone {get;set;}
        public String customerEmail {get;set;}
        public String paymentStatus {get;set;}
        public List<Service> servicesToPay {get;set;}

        public PaymentViewResult() {
            servicesToPay = new List<Service>();
        }
        public Decimal totalPending { get; set; }
    }    

    global class Service {
        public String productId {get;set;}
        public String serviceId {get;set;}
        public String serviceProductName {get;set;}
        public String routeFlightName {get;set;}
        public DateTime flightDateTime {get;set;}
        public String flightTimeZone {get { return 'GMT-03:00'; } set;}
        public String passangerName {get;set;}
        public Decimal pendingPayment {get;set;}
    }


    // #region Excepitions

    public class PagamentoNaoEncontradoException extends RevoSiteApi.RevoSiteApiException {
        public PagamentoNaoEncontradoException(Boolean voidParam) {
            super('API-0007','Pagamento não encontrado!');
        }
    }

    // #endregion
}