force-app/main/default/objects/Empenho__c/Empenho__c.object-meta.xml
<CustomObject>
    <label>Empenho</label>
    <nameField>
        <displayFormat>EMP-{0000000}</displayFormat>
        <label>Empenho</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Empenhos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Empenho__c/fields/Pagamento__c.field-meta.xml
<CustomField>
    <fullName>Pagamento__c</fullName>
    <label>Pagamento</label>
    <referenceTo>Pagamento__c</referenceTo>
    <relationshipLabel>Empenhos</relationshipLabel>
    <relationshipName>Empenhos</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Empenho__c/fields/RevoSeatEmpenhado__c.field-meta.xml
<CustomField>
    <fullName>RevoSeatEmpenhado__c</fullName>
    <label>RevoSeat Empenhado</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Empenho__c/fields/Servico__c.field-meta.xml
<CustomField>
    <fullName>Servico__c</fullName>
    <label>Serviço</label>
    <referenceTo>Servico__c</referenceTo>
    <relationshipLabel>Empenhos</relationshipLabel>
    <relationshipName>Empenhos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Empenho__c/fields/ValorEmpenho__c.field-meta.xml
<CustomField>
    <fullName>ValorEmpenho__c</fullName>
    <label>Valor do Empenho</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/LancamentoRevoSeat__c/LancamentoRevoSeat__c.object-meta.xml
<CustomObject>
    <label>Lançamento Revo Seat</label>
    <nameField>
        <displayFormat>RS-{0000000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lançamentos Revo Seats</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LancamentoRevoSeat__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Lançamentos Revo Seats</relationshipLabel>
    <relationshipName>LancamentosRevoSeats</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Pagamento__c/Pagamento__c.object-meta.xml
<CustomObject>
    <label>Pagamento</label>
    <nameField>
        <displayFormat>PAGTO-{0000000}</displayFormat>
        <label>Pagamento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pagamentos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Pagamento__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pagamentos</relationshipLabel>
    <relationshipName>Pagamentos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Pagamento__c/fields/OportunidadeOrigem__c.field-meta.xml
<CustomField>
    <fullName>OportunidadeOrigem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidade Origem</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Pagamentos</relationshipLabel>
    <relationshipName>Pagamentos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pagamento__c/fields/RevoseatsOrigem__c.field-meta.xml
<CustomField>
    <fullName>RevoseatsOrigem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RevoSeats Origem</label>
    <referenceTo>LancamentoRevoSeat__c</referenceTo>
    <relationshipLabel>Pagamentos</relationshipLabel>
    <relationshipName>Pagamentos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pagamento__c/fields/StatusPagamento__c.field-meta.xml
<CustomField>
    <fullName>StatusPagamento__c</fullName>
    <label>Status do Pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendente</fullName>
                <default>true</default>
                <label>Pendente</label>
            </value>
            <value>
                <fullName>Efetuado</fullName>
            </value>
            <value>
                <fullName>Devolvido</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Faturado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pagamento__c/fields/TipoVoucher__c.field-meta.xml
<CustomField>
    <fullName>TipoVoucher__c</fullName>
    <label>Tipo de Voucher</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Valor Fechado</fullName>
            </value>
            <value>
                <fullName>Valor Aberto</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pagamento__c/recordTypes/GatewayPagamento.recordType-meta.xml
<RecordType>
    <fullName>GatewayPagamento</fullName>
    <active>true</active>
    <label>Gateway Pagamento</label>
</RecordType>

force-app/main/default/objects/Pagamento__c/recordTypes/VoucherRevoSeats.recordType-meta.xml
<RecordType>
    <fullName>VoucherRevoSeats</fullName>
    <active>true</active>
    <label>Voucher RevoSeats</label>
</RecordType>

force-app/main/default/objects/Servico__c/Servico__c.object-meta.xml
<CustomObject>
    <label>Serviço</label>
    <nameField>
        <displayFormat>SERV-{0000000}</displayFormat>
        <label>Serviço</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Serviços</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Servico__c/fields/LancamentoRevoSeat__c.field-meta.xml
<CustomField>
    <fullName>LancamentoRevoSeat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lançamento Revo Seat</label>
    <referenceTo>LancamentoRevoSeat__c</referenceTo>
    <relationshipLabel>Serviços</relationshipLabel>
    <relationshipName>Servicos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TransacaoGateway__c/TransacaoGateway__c.object-meta.xml
<CustomObject>
    <label>Transação Gateway</label>
    <nameField>
        <displayFormat>TRNS-{0000000}</displayFormat>
        <label>Transação Gateway</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transações Gateway</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TransacaoGateway__c/fields/FormaPagamento__c.field-meta.xml
<CustomField>
    <fullName>FormaPagamento__c</fullName>
    <label>Forma de Pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cartão de Crédito</fullName>
            </value>
            <value>
                <fullName>Pix</fullName>
            </value>
            <value>
                <fullName>Paypal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TransacaoGateway__c/fields/IdTransacaoGateway__c.field-meta.xml
<CustomField>
    <fullName>IdTransacaoGateway__c</fullName>
    <label>Id Registro do Gateway</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TransacaoGateway__c/fields/MensagensGateway__c.field-meta.xml
<CustomField>
    <fullName>MensagensGateway__c</fullName>
    <label>Mensagens do Gateway</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TransacaoGateway__c/fields/NomeGateway__c.field-meta.xml
<CustomField>
    <fullName>NomeGateway__c</fullName>
    <label>Gateway de Pagamento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TransacaoGateway__c/fields/Pagamento__c.field-meta.xml
<CustomField>
    <fullName>Pagamento__c</fullName>
    <label>Pagamento</label>
    <referenceTo>Pagamento__c</referenceTo>
    <relationshipLabel>Transações Gateway</relationshipLabel>
    <relationshipName>TransacesGateway</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TransacaoGateway__c/fields/StatusGateway__c.field-meta.xml
<CustomField>
    <fullName>StatusGateway__c</fullName>
    <label>Status Gateway</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Authorized</fullName>
            </value>
            <value>
                <fullName>Not Authorized</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Undefined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TransacaoGateway__c/fields/ValorTransacao__c.field-meta.xml
<CustomField>
    <fullName>ValorTransacao__c</fullName>
    <label>Valor da Transação</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/Pagamentos.cls
public with sharing class Pagamentos extends fflib_SObjectDomain implements IPagamentos
{
    
    public Pagamentos(List<Pagamento__c> sObjectList)
    {
        super(sObjectList);
    }
    
    public static IPagamentos newInstance(List<Pagamento__c> sObjectList)
    {
        return (IPagamentos) Application.Domain.newInstance(sObjectList);
    }
    
    public class Constructor implements fflib_SObjectDomain.IConstructable
    {
        public fflib_SObjectDomain construct(List<SObject> sObjectList)
        {
            return new Pagamentos(sObjectList);
        }
    }

    public static Pagamento__c criaLinkPagamento(
        fflib_ISObjectUnitOfWork uow, Id oportunidadeId, Id contaId
    ) {

        Schema.DescribeSObjectResult describeResult = Schema.getGlobalDescribe().get('Pagamento__c').getDescribe();
        Map<Id, Schema.RecordTypeInfo> recordTypeInfoMap = describeResult.getRecordTypeInfosById();

        Id GatewayPagamento = null;

        for (Schema.RecordTypeInfo rtInfo : recordTypeInfoMap.values()) {
            if (rtInfo.getDeveloperName() == 'GatewayPagamento') {
                GatewayPagamento = rtInfo.getRecordTypeId();
            }
        }        

        Pagamento__c pagamento = new Pagamento__c();

        pagamento.RecordTypeId = GatewayPagamento;
        pagamento.Conta__c = contaId;
        pagamento.OportunidadeOrigem__c = oportunidadeId;
        pagamento.StatusPagamento__c = 'Pendente';

        uow.registerNew(pagamento);

        return pagamento;
    }


    public static Pagamento__c criaPagamentoVoucher(
        fflib_ISObjectUnitOfWork uow, Id contaDestinoId, LancamentoRevoSeat__c lancamentoRevoSeat, String tipoVoucher
    ) {

        Schema.DescribeSObjectResult describeResult = Schema.getGlobalDescribe().get('Pagamento__c').getDescribe();
        Map<Id, Schema.RecordTypeInfo> recordTypeInfoMap = describeResult.getRecordTypeInfosById();

        Id VoucherRevoSeats = null;

        for (Schema.RecordTypeInfo rtInfo : recordTypeInfoMap.values()) {
            if (rtInfo.getDeveloperName() == 'VoucherRevoSeats') {
                VoucherRevoSeats = rtInfo.getRecordTypeId();
            }
        }        

        Pagamento__c pagamento = new Pagamento__c();

        pagamento.RecordTypeId = VoucherRevoSeats;
        pagamento.Conta__c = contaDestinoId;
        pagamento.TipoVoucher__c = tipoVoucher;
        pagamento.StatusPagamento__c = 'Efetuado';

        uow.registerNew(pagamento);

        if (lancamentoRevoSeat.id == null) {
            uow.registerRelationship(pagamento, Pagamento__c.RevoseatsOrigem__c, lancamentoRevoSeat);
        } else {
            pagamento.RevoseatsOrigem__c = lancamentoRevoSeat.Id;
        }

        return pagamento;
    }    

    public static TransacaoGateway__c criaTransacaoGateway(
        fflib_ISObjectUnitOfWork uow, Id pagamentoId, String nomeGateway, String metodoPagamento, String transacaoId, String transacaoStatus, 
        String mensagemGateway, Decimal transacaoValor
    ) {
        TransacaoGateway__c transacao = new TransacaoGateway__c();

        transacao.Pagamento__c = pagamentoId;
        transacao.NomeGateway__c = nomeGateway;
        transacao.FormaPagamento__c = metodoPagamento;
        transacao.IdTransacaoGateway__c = transacaoId;
        transacao.StatusGateway__c = transacaoStatus;
        transacao.MensagensGateway__c = mensagemGateway;
        transacao.ValorTransacao__c = transacaoValor;

        uow.registerNew(transacao);

        return transacao;
    }    

    public static Empenho__c criaEmpenho(
        fflib_ISObjectUnitOfWork uow, Id pagamentoId, Id servicoId, Decimal ValorEmpenho
    ) {
        Empenho__c empenho = new Empenho__c();

        empenho.Pagamento__c = pagamentoId;
        empenho.Servico__c = servicoId;
        empenho.ValorEmpenho__c = ValorEmpenho;

        uow.registerNew(empenho);

        return empenho;
    }

    public static Empenho__c atualizaValorEmpenho(
        fflib_ISObjectUnitOfWork uow, Empenho__c empenho, Decimal ValorEmpenho
    ) {

        empenho.ValorEmpenho__c = ValorEmpenho;

        uow.registerDirty(empenho);

        return empenho;
    }           


    public static Empenho__c atualizaValorEmpenhoRevoSeats(
        fflib_ISObjectUnitOfWork uow, Empenho__c empenho, Decimal ValorEmpenhoRevoSeats, Decimal ValorEmpenho
    ) {

        empenho.ValorEmpenho__c = ValorEmpenho;
        empenho.RevoSeatEmpenhado__c = ValorEmpenhoRevoSeats;

        uow.registerDirty(empenho);

        return empenho;
    }               
}