force-app/main/default/objects/Empenho__c/Empenho__c.object-meta.xml
<CustomObject>
    <label>Empenho</label>
    <nameField>
        <displayFormat>EMP-{0000000}</displayFormat>
        <label>Empenho</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Empenhos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Empenho__c/fields/Pagamento__c.field-meta.xml
<CustomField>
    <fullName>Pagamento__c</fullName>
    <label>Pagamento</label>
    <referenceTo>Pagamento__c</referenceTo>
    <relationshipLabel>Empenhos</relationshipLabel>
    <relationshipName>Empenhos</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Pagamento__c/Pagamento__c.object-meta.xml
<CustomObject>
    <label>Pagamento</label>
    <nameField>
        <displayFormat>PAGTO-{0000000}</displayFormat>
        <label>Pagamento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pagamentos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Pagamento__c/fields/OportunidadeOrigem__c.field-meta.xml
<CustomField>
    <fullName>OportunidadeOrigem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidade Origem</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Pagamentos</relationshipLabel>
    <relationshipName>Pagamentos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pagamento__c/fields/StatusPagamento__c.field-meta.xml
<CustomField>
    <fullName>StatusPagamento__c</fullName>
    <label>Status do Pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendente</fullName>
                <default>true</default>
                <label>Pendente</label>
            </value>
            <value>
                <fullName>Efetuado</fullName>
            </value>
            <value>
                <fullName>Devolvido</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Faturado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pagamento__c/recordTypes/GatewayPagamento.recordType-meta.xml
<RecordType>
    <fullName>GatewayPagamento</fullName>
    <active>true</active>
    <label>Gateway Pagamento</label>
</RecordType>

force-app/main/default/objects/TransacaoGateway__c/TransacaoGateway__c.object-meta.xml
<CustomObject>
    <label>Transação Gateway</label>
    <nameField>
        <displayFormat>TRNS-{0000000}</displayFormat>
        <label>Transação Gateway</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transações Gateway</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TransacaoGateway__c/fields/Pagamento__c.field-meta.xml
<CustomField>
    <fullName>Pagamento__c</fullName>
    <label>Pagamento</label>
    <referenceTo>Pagamento__c</referenceTo>
    <relationshipLabel>Transações Gateway</relationshipLabel>
    <relationshipName>TransacesGateway</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PagamentosSelector.cls
public class PagamentosSelector extends fflib_SObjectSelector
	implements IPagamentosSelector
{

    public static IPagamentosSelector newInstance()
	{
		return (IPagamentosSelector) Application.Selector.newInstance(Pagamento__c.SObjectType);
	}
    
    public PagamentosSelector()
    {
        super(true);

        this.setDataAccess(fflib_SObjectSelector.DataAccess.SYSTEM_MODE);
    }	

    public List<Schema.SObjectField> getSObjectFieldList()
	{
		return new List<Schema.SObjectField> {
			Pagamento__c.Id
		};
	}
    
    public override List<Schema.FieldSet> getSObjectFieldSetList()
    {
        return new List<Schema.FieldSet>    
        {   SobjectType.Pagamento__c.FieldSets.SobjectFieldList    };
    }
    	
    
    public Schema.SObjectType getSObjectType()
	{
		return Pagamento__c.sObjectType;
	}
    
    public List<Pagamento__c> selectById(Set<ID> idSet)
	{
		return (List<Pagamento__c>) selectSObjectsById(idSet);
	}
  
    public Pagamento__c selectPagamentoGateway(Id pagamentoId)
	{
        fflib_QueryFactory query = newQueryFactory();

        query.setCondition('Id = :pagamentoId').setForUpdate();

        System.debug(query.getOrderings());

        fflib_QueryFactory subquery = query.subselectQuery('TransacesGateway__r')
        .selectFieldSet(SobjectType.TransacaoGateway__c.FieldSets.SobjectFieldList)
		.setOrdering('CreatedDate', fflib_QueryFactory.SortOrder.DESCENDING);

        fflib_QueryFactory subquery1 = query.subselectQuery('Empenhos__r')
        .selectFieldSet(SobjectType.Empenho__c.FieldSets.SobjectFieldList);

        System.debug(query.getOrderings());

        System.debug(query.toSOQL());

        List<Pagamento__c> pagts = Database.query( query.toSOQL() );
        
        return pagts.size() > 0 ? pagts[0] : null;		
	}	

    public List<Pagamento__c> selectPagamentoPendenteGatewayOppId(Set<ID> idSet)
	{
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('OportunidadeOrigem__c IN :idSet And RecordType.DeveloperName = \'GatewayPagamento\' And StatusPagamento__c = \'Pendente\'');

        return (List<Pagamento__c>) Database.query(query.toSOQL());
	}	

}