force-app/main/default/objects/Empenho__c/Empenho__c.object-meta.xml
<CustomObject>
    <label>Empenho</label>
    <nameField>
        <displayFormat>EMP-{0000000}</displayFormat>
        <label>Empenho</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Empenhos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Empenho__c/fields/Pagamento__c.field-meta.xml
<CustomField>
    <fullName>Pagamento__c</fullName>
    <label>Pagamento</label>
    <referenceTo>Pagamento__c</referenceTo>
    <relationshipLabel>Empenhos</relationshipLabel>
    <relationshipName>Empenhos</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Pagamento__c/Pagamento__c.object-meta.xml
<CustomObject>
    <label>Pagamento</label>
    <nameField>
        <displayFormat>PAGTO-{0000000}</displayFormat>
        <label>Pagamento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pagamentos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Pagamento__c/fields/OportunidadeOrigem__c.field-meta.xml
<CustomField>
    <fullName>OportunidadeOrigem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidade Origem</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Pagamentos</relationshipLabel>
    <relationshipName>Pagamentos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pagamento__c/fields/ValorPagamento__c.field-meta.xml
<CustomField>
    <fullName>ValorPagamento__c</fullName>
    <label>Valor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/FlowPagaOportunidadeTest.cls
@isTest
public with sharing class FlowPagaOportunidadeTest {
    
    @TestSetup
    static void makeData(){
        RevoTestUtil.ConfigurarOportunidadeShuttleSeat();
        List<Id> idsOportunidade = new List<Id>{[SELECT Id FROM Opportunity WHERE Type = 'ShuttleSeat' LIMIT 1].Id};
        FlowCheckoutOportunidade.checkoutOportunidade(idsOportunidade);
        FlowCriarPagamentoOportunidade.criarPagamentoOportunidade(idsOportunidade);   
    }

    @IsTest
    static void testFlowPagaOportunidadeShuttleSeat(){
        
        List<Id> idsOportunidade = new List<Id>{[SELECT Id FROM Opportunity WHERE Type = 'ShuttleSeat' LIMIT 1].Id};


        Pagamento__c pagamento = [SELECT Id, ValorPagamento__c FROM Pagamento__c WHERE OportunidadeOrigem__c = :idsOportunidade[0] LIMIT 1];
        pagamento.ValorPagamento__c = 100000;
        update pagamento;

        List<Empenho__c> empenhos = [SELECT Id FROM Empenho__c WHERE Pagamento__c = :pagamento.Id];
        delete empenhos;
        
        FlowPagaOportunidade.FlowPagaOportunidadeChamada chamada = new FlowPagaOportunidade.FlowPagaOportunidadeChamada();
        chamada.pagamentoId = pagamento.Id;
        chamada.oportunidadeId = idsOportunidade[0];    

        List<String> result = FlowPagaOportunidade.pagaOportunidade(new List<FlowPagaOportunidade.FlowPagaOportunidadeChamada>{chamada});

        System.assertEquals(1, result.size());
        System.assertEquals('SUCESSO', result[0]);
    }
}