force-app/main/default/objects/Local__c/Local__c.object-meta.xml
<CustomObject>
    <label>Local</label>
    <nameField>
        <label>Local</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Local__c/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <label>Modelo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Base</fullName>
            </value>
            <value>
                <fullName>FPSO</fullName>
            </value>
            <value>
                <fullName>FSO</fullName>
            </value>
            <value>
                <fullName>Plataforma</fullName>
            </value>
            <value>
                <fullName>Sonda</fullName>
            </value>
            <value>
                <fullName>UMS</fullName>
            </value>
            <value>
                <fullName>Sísmica</fullName>
            </value>
            <value>
                <fullName>PLSV</fullName>
            </value>
            <value>
                <fullName>Clareira</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Local__c/fields/CodigoLocal__c.field-meta.xml
<CustomField>
    <fullName>CodigoLocal__c</fullName>
    <description>Código que identifica o local</description>
    <externalId>true</externalId>
    <inlineHelpText>Código que identifica o local</inlineHelpText>
    <label>Código do local</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Local__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <description>Define se o local é em terra(onshore) ou em mar(offshore)</description>
    <inlineHelpText>Define se o local é em terra(onshore) ou em mar(offshore)</inlineHelpText>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Onshore</fullName>
            </value>
            <value>
                <fullName>Offshore</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LocaisSelector.cls
public class LocaisSelector extends fflib_SObjectSelector 
implements ILocaisSelector
{
    private static final String validado = 'Validado';
    
    public static ILocaisSelector newInstance()
    {
        return (ILocaisSelector) Application.Selector.newInstance(Local__c.SObjectType);
    }
    
    public LocaisSelector(Boolean includeFieldSetFields)
    {
        super(includeFieldSetFields);
    }
    
    public LocaisSelector()
    {
        super(true);
    }
    
    public override List<Schema.FieldSet> getSObjectFieldSetList()
    {
        return new List<Schema.FieldSet>
        {	SobjectType.Local__c.FieldSets.SelectFieldList	};
    }
    
    public List<Schema.SObjectField> getSObjectFieldList()
    {
        return new List<Schema.SObjectField> 
        {
            Local__c.Id,
            Local__c.Name,
            Local__c.CodigoLocal__c,
            Local__c.Categoria__c,
            Local__c.Tipo__c
        };
    }
    
    public Schema.SObjectType getSObjectType()
    {
        return Local__c.sObjectType;
    }
    
    public List<Local__c> selectById(Set<ID> idSet)
    {
        return (List<Local__c>) selectSObjectsById(idSet);
    }
}