force-app/main/default/objects/Local__c/Local__c.object-meta.xml
<CustomObject>
    <label>Local</label>
    <nameField>
        <label>Local</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Local__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <description>Define se o local é em terra(onshore) ou em mar(offshore)</description>
    <inlineHelpText>Define se o local é em terra(onshore) ou em mar(offshore)</inlineHelpText>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Onshore</fullName>
            </value>
            <value>
                <fullName>Offshore</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LogVoo__c/LogVoo__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar inforamações oriundas do Skytrac</description>
    <label>Log de Voo</label>
    <nameField>
        <displayFormat>LV-{00000000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs de Voos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LogVoo__c/fields/Local__c.field-meta.xml
<CustomField>
    <fullName>Local__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Local</label>
    <referenceTo>Local__c</referenceTo>
    <relationshipLabel>Logs de Voos</relationshipLabel>
    <relationshipName>LogsVoos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LogVoo__c/fields/Trecho__c.field-meta.xml
<CustomField>
    <fullName>Trecho__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trecho</label>
    <referenceTo>Trecho__c</referenceTo>
    <relationshipLabel>Logs de Voos</relationshipLabel>
    <relationshipName>LogsVoos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LogVoo__c/fields/Voo__c.field-meta.xml
<CustomField>
    <fullName>Voo__c</fullName>
    <label>Voo</label>
    <referenceTo>Voo__c</referenceTo>
    <relationshipLabel>Logs de Voos</relationshipLabel>
    <relationshipName>LogsVoos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Trecho__c/Trecho__c.object-meta.xml
<CustomObject>
    <description>Define um trecho com origem e destino dentro de um Voo</description>
    <label>Trecho</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Código do Trecho</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trechos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trecho__c/fields/Comentarios__c.field-meta.xml
<CustomField>
    <fullName>Comentarios__c</fullName>
    <description>Campo do Star</description>
    <label>Comentários</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Trecho__c/fields/PrevisaoPouso__c.field-meta.xml
<CustomField>
    <fullName>PrevisaoPouso__c</fullName>
    <label>Previsão de Pouso do Voo</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Trecho__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <description>Passageiro - Transporte apenas de passageiros no trecho
Carga e passageiro - Transporte de passageiros e carga no trecho
Cargueiro - Transporte apenas de carga no trecho
Translado - Translado da aeronave para reposicionamento
Translado com passageiro - Translado da aeronave para reposicionamento com passageiro a bordo
Comitiva</description>
    <inlineHelpText>Transporte apenas de passageiros no trecho
Transporte de passageiros e carga no trecho
Transporte apenas de carga no trecho
Translado da aeronave para reposicionamento
Translado da aeronave para reposicionamento com passageiro
Comitiva</inlineHelpText>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Passageiros</fullName>
            </value>
            <value>
                <fullName>Cargueiro</fullName>
            </value>
            <value>
                <fullName>Passageiros e Cargas</fullName>
            </value>
            <value>
                <fullName>Translado</fullName>
            </value>
            <value>
                <fullName>Translado com passageiro</fullName>
            </value>
            <value>
                <fullName>Comitiva</fullName>
            </value>
            <value>
                <fullName>Sanitário</fullName>
            </value>
            <value>
                <fullName>Treinamento</fullName>
            </value>
            <value>
                <fullName>SAR</fullName>
            </value>
            <value>
                <fullName>MEDVAC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trecho__c/fields/Voo__c.field-meta.xml
<CustomField>
    <fullName>Voo__c</fullName>
    <description>Voo ao qual o trecho pertence</description>
    <inlineHelpText>Voo ao qual o trecho pertence</inlineHelpText>
    <label>Voo</label>
    <referenceTo>Voo__c</referenceTo>
    <relationshipLabel>Trechos</relationshipLabel>
    <relationshipName>Trechos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Voo__c/Voo__c.object-meta.xml
<CustomObject>
    <description>O Voo de uma aeronave, do ponto de origem até o retorno</description>
    <label>Voo</label>
    <nameField>
        <displayFormat>REVO-{00000000}</displayFormat>
        <label>Número do Voo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Voos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Voo__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <description>Informa o tipo de transporte realizado pelo voo.</description>
    <inlineHelpText>Informs the type of transport performed by the flight.</inlineHelpText>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TipoVoo</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/TipoVoo.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ShuttleSeat</fullName>
        <label>Shuttle Seat</label>
    </customValue>
    <customValue>
        <fullName>Charter</fullName>
    </customValue>
    <customValue>
        <fullName>FullCabin</fullName>
        <label>Full Cabin</label>
    </customValue>
    <customValue>
        <fullName>Sanitário</fullName>
        <isActive>false</isActive>
        <label>Sanitário</label>
    </customValue>
    <customValue>
        <fullName>Treinamento</fullName>
        <isActive>false</isActive>
        <label>Treinamento</label>
    </customValue>
    <customValue>
        <fullName>SAR</fullName>
        <isActive>false</isActive>
        <label>SAR</label>
    </customValue>
    <customValue>
        <fullName>Passageiros</fullName>
        <isActive>false</isActive>
        <label>Passageiros</label>
    </customValue>
    <customValue>
        <fullName>Manutenção</fullName>
        <isActive>false</isActive>
        <label>Manutenção</label>
    </customValue>
    <customValue>
        <fullName>Treinamento NDC</fullName>
        <isActive>false</isActive>
        <label>Treinamento NDC</label>
    </customValue>
    <customValue>
        <fullName>MEDVAC</fullName>
        <isActive>false</isActive>
        <label>MEDVAC</label>
    </customValue>
    <customValue>
        <fullName>Cargueiro</fullName>
        <isActive>false</isActive>
        <label>Cargueiro</label>
    </customValue>
    <customValue>
        <fullName>Passageiros e Cargas</fullName>
        <isActive>false</isActive>
        <label>Passageiros e Cargas</label>
    </customValue>
    <masterLabel>Tipo de voo</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TrechosTest.cls
@isTest
public class TrechosTest {

    @TestSetup
    static void setup()
    {
        TestUtil.SetupStandardPricebook();
        
        Datetime data = Datetime.newInstance(System.now().date().addDays(1), Time.newInstance(15, 0, 0, 0));
        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        TestUtil2.criarVooRascunho(data, true, uow);
        uow.commitWork();
    }
    
    @isTest
    static void insertUpdateDeleteTest()
    {
        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        Test.startTest();
        Voo__c voo = [SELECT Id FROM Voo__c ORDER BY Id DESC LIMIT 1];
        List<Local__c> locais = [SELECT Id FROM Local__c ORDER BY Id DESC LIMIT 2];
       	Trecho__C trecho1 = TestUtil2.createTrecho(voo, locais[0], locais[1], 30, uow);
        Trecho__C trecho2 = TestUtil2.createTrecho(voo, locais[0], locais[1], 40, uow);
        uow.commitWork();
        trecho1.PrevisaoPouso__c = System.now();
        update trecho1;
        delete trecho2;
        
        Test.stopTest();
    }
    
    @isTest
    static void testes()
    {
        Voo__c voo = [SELECT Id FROM Voo__c ORDER BY Id DESC LIMIT 1];
        List<Trecho__c> trechosDoVoo = TrechosSelector.newInstance().selectByVooId(new Set<Id> {voo.Id});
        Trechos trechos = new Trechos(trechosDoVoo);
        trechos.getTrajeto();
        Trecho__c trecho = trechosDoVoo[0];
        trecho.Comentarios__c = null;
        Boolean assert = trechos.existsFieldAndValueIsBlankOrNull(trecho, Trecho__c.Comentarios__c);
        Object o = trechos.getValueByField(Trecho__c.Comentarios__c, new LogVoo__c(), trecho);
        Boolean assert1 = trechos.checkCoordenadas(22, 22, 22, 22);
        Boolean assert2 = trechos.isOffshore(null);
        assert2 = trechos.isOffshore(new Local__c(Tipo__c='Offshore'));
    }
}