force-app/main/default/objects/ConfiguracaoPacote__c/ConfiguracaoPacote__c.object-meta.xml
<CustomObject>
    <label>Configuração do Pacote</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Configuração do Pacote</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Configurações dos Pacotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ConfiguracaoPacote__c/fields/Posicao__c.field-meta.xml
<CustomField>
    <fullName>Posicao__c</fullName>
    <label>Posição</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConfiguracaoPacote__c/fields/ProdutoPacote__c.field-meta.xml
<CustomField>
    <fullName>ProdutoPacote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto do Pacote</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>ServicosTaxas</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Configurações dos Pacotes</relationshipLabel>
    <relationshipName>Configuracoes_dos_Pacotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ConfiguracaoPacote__c/fields/ProdutoPai__c.field-meta.xml
<CustomField>
    <fullName>ProdutoPai__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto Pai</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Configurações dos Pacotes</relationshipLabel>
    <relationshipName>ConfiguracoesPacotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ConfiguracaoPacoteSelector.cls
public class ConfiguracaoPacoteSelector extends fflib_SObjectSelector 
implements IConfiguracaoPacoteSelector {

    public static IConfiguracaoPacoteSelector newInstance()
    {
        return (IConfiguracaoPacoteSelector) Application.Selector.newInstance(ConfiguracaoPacote__c.SObjectType);
    }
    
    public ConfiguracaoPacoteSelector(Boolean includeFieldSetFields)
    {
        super(includeFieldSetFields);
    }
    
    public ConfiguracaoPacoteSelector()
    {
        super(true);
    }
    
    public override List<Schema.FieldSet> getSObjectFieldSetList()
    {
        List<Schema.FieldSet> fieldSets = new List<Schema.FieldSet>();
        
        fieldSets.add(SobjectType.ConfiguracaoPacote__c.FieldSets.ParaCalculoPreco);
        
        return fieldSets;
    }
    
    public List<Schema.SObjectField> getSObjectFieldList()
    {
        return new List<Schema.SObjectField> {
            ConfiguracaoPacote__c.Id
        };
    }
    
    public Schema.SObjectType getSObjectType()
    {
        return ConfiguracaoPacote__c.sObjectType;
    }    

    public Map<Id, List<ConfiguracaoPacote__c>> selectByIdProducts(Set<ID> idProducts) 
    {
        fflib_QueryFactory query = newQueryFactory();

        query.setCondition('ProdutoPai__c IN :idProducts And ProdutoPacote__r.IsActive = true');
        query.setOrdering('Posicao__c', fflib_QueryFactory.SortOrder.ASCENDING);

        List<ConfiguracaoPacote__c> configs = Database.query( query.toSOQL() );

        Map<Id, List<ConfiguracaoPacote__c>> result = new Map<Id, List<ConfiguracaoPacote__c>>();

        for (ConfiguracaoPacote__c config : configs) {
            
            if (!result.containsKey(config.ProdutoPai__c)) {
                result.put(config.ProdutoPai__c, new List<ConfiguracaoPacote__c>());
            }

            result.get(config.ProdutoPai__c).add(config);
        }

        return result; 
    }
}