force-app/main/default/objects/CodigoPromocional__c/CodigoPromocional__c.object-meta.xml
<CustomObject>
    <label>Promoção</label>
    <nameField>
        <label>Código Promocional</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promoções</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Local__c/Local__c.object-meta.xml
<CustomObject>
    <label>Local</label>
    <nameField>
        <label>Local</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Local__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status para validação de um local</description>
    <inlineHelpText>Status para validação de um local</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>StatusPendenteAprovado</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/LocalOportunidade__c/LocalOportunidade__c.object-meta.xml
<CustomObject>
    <label>Local do Produto Oportunidade</label>
    <nameField>
        <displayFormat>LOOP-{0000000}</displayFormat>
        <label>Local da Oportunidade</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Locais do Produto Oportunidade</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LocalOportunidade__c/fields/Local__c.field-meta.xml
<CustomField>
    <fullName>Local__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Local</label>
    <referenceTo>Local__c</referenceTo>
    <relationshipName>LocaisProdutoOportunidade</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LocalOportunidade__c/fields/Oportunidade__c.field-meta.xml
<CustomField>
    <fullName>Oportunidade__c</fullName>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>LocaisOportunidade</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LocalOportunidade__c/fields/ProdutoOportunidade__c.field-meta.xml
<CustomField>
    <fullName>ProdutoOportunidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto de oportunidade</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipName>LocaisProdutoOportunidade</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LocalOportunidade__c/fields/Sequencia__c.field-meta.xml
<CustomField>
    <fullName>Sequencia__c</fullName>
    <label>Sequencia</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MalhaVoo__c/MalhaVoo__c.object-meta.xml
<CustomObject>
    <label>Malha de Voo</label>
    <nameField>
        <displayFormat>MV-{000000}</displayFormat>
        <label>Malha de Voo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Malhas de Voos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MalhaVoo__c/fields/Destino__c.field-meta.xml
<CustomField>
    <fullName>Destino__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Destino</label>
    <referenceTo>Local__c</referenceTo>
    <relationshipLabel>Malhas de Voos (Destino)</relationshipLabel>
    <relationshipName>MalhasVoosDestino</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MalhaVoo__c/fields/Origem__c.field-meta.xml
<CustomField>
    <fullName>Origem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Origem</label>
    <referenceTo>Local__c</referenceTo>
    <relationshipLabel>Malhas de Voos</relationshipLabel>
    <relationshipName>MalhasVoosOrigem</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Passageiro__c/Passageiro__c.object-meta.xml
<CustomObject>
    <label>Passageiro</label>
    <nameField>
        <displayFormat>P-{000000000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Passageiros</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Passageiro__c/fields/CodigoReserva__c.field-meta.xml
<CustomField>
    <fullName>CodigoReserva__c</fullName>
    <label>Código da Reserva</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Passageiro__c/fields/Destino__c.field-meta.xml
<CustomField>
    <fullName>Destino__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Destino</label>
    <referenceTo>Local__c</referenceTo>
    <relationshipLabel>Passageiros (Destino)</relationshipLabel>
    <relationshipName>PassageirosDestino</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Passageiro__c/fields/Origem__c.field-meta.xml
<CustomField>
    <fullName>Origem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Origem</label>
    <referenceTo>Local__c</referenceTo>
    <relationshipLabel>Passageiros (Origem)</relationshipLabel>
    <relationshipName>PassageirosOrigem</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PassageiroOportunidade__c/PassageiroOportunidade__c.object-meta.xml
<CustomObject>
    <label>Passageiro da Oportunidade</label>
    <nameField>
        <displayFormat>PASS-{0000000}</displayFormat>
        <label>Passageiro da Oportunidade</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Passageiros da Oportunidade</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PassageiroOportunidade__c/fields/Oportunidade__c.field-meta.xml
<CustomField>
    <fullName>Oportunidade__c</fullName>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Passageiros da Oportunidade</relationshipLabel>
    <relationshipName>PassageirosOportunidade</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PassageiroOportunidade__c/fields/Passageiro__c.field-meta.xml
<CustomField>
    <fullName>Passageiro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Passageiro</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Passageiro não pode ser do tipo Contato, mas sim do tipo Passageiro ou Cliente - Pessoa Física</errorMessage>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Contato</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Passageiros da Oportunidade</relationshipLabel>
    <relationshipName>PassageirosOportunidade</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProdutoPassageiro__c/ProdutoPassageiro__c.object-meta.xml
<CustomObject>
    <label>Produto do Passageiro</label>
    <nameField>
        <displayFormat>PPO-{0000000}</displayFormat>
        <label>Produto do Passageiro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Produtos do Passageiro</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProdutoPassageiro__c/fields/CEPServico__c.field-meta.xml
<CustomField>
    <fullName>CEPServico__c</fullName>
    <label>CEP Serviço</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProdutoPassageiro__c/fields/CidadeServico__c.field-meta.xml
<CustomField>
    <fullName>CidadeServico__c</fullName>
    <label>Cidade Serviço</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProdutoPassageiro__c/fields/CompanhiaAerea__c.field-meta.xml
<CustomField>
    <fullName>CompanhiaAerea__c</fullName>
    <label>Companhia Aérea</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProdutoPassageiro__c/fields/ComplementoEndereco__c.field-meta.xml
<CustomField>
    <fullName>ComplementoEndereco__c</fullName>
    <label>Complemento Endereço</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProdutoPassageiro__c/fields/EnderecoServico__c.field-meta.xml
<CustomField>
    <fullName>EnderecoServico__c</fullName>
    <label>Endereço Serviço</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProdutoPassageiro__c/fields/EstadoServico__c.field-meta.xml
<CustomField>
    <fullName>EstadoServico__c</fullName>
    <label>Estado Serviço</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProdutoPassageiro__c/fields/NumeroVoo__c.field-meta.xml
<CustomField>
    <fullName>NumeroVoo__c</fullName>
    <label>Número do Voo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProdutoPassageiro__c/fields/PaisServico__c.field-meta.xml
<CustomField>
    <fullName>PaisServico__c</fullName>
    <label>País Serviço</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProdutoPassageiro__c/fields/Passageiro__c.field-meta.xml
<CustomField>
    <fullName>Passageiro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Passageiro</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Passageiro não pode ser do tipo Contato, mas sim do tipo Passageiro ou Cliente - Pessoa Física</errorMessage>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Contato</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Produtos do Passageiro</relationshipLabel>
    <relationshipName>ProdutosPassageiro</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProdutoPassageiro__c/fields/PassageiroOportunidade__c.field-meta.xml
<CustomField>
    <fullName>PassageiroOportunidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Passageiro da Oportunidade</label>
    <referenceTo>PassageiroOportunidade__c</referenceTo>
    <relationshipLabel>Produtos do Passageiro</relationshipLabel>
    <relationshipName>ProdutosPassageiro</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProdutoPassageiro__c/fields/ProdutoOportunidade__c.field-meta.xml
<CustomField>
    <fullName>ProdutoOportunidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto de Oportunidade</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipLabel>Passageiros do Produto</relationshipLabel>
    <relationshipName>ProdutosPassageiro</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProdutoPassageiro__c/fields/QtdsMalasGrandes__c.field-meta.xml
<CustomField>
    <fullName>QtdsMalasGrandes__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Qtds. Malas Grandes</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProdutoPassageiro__c/fields/QtdsMalasMedias__c.field-meta.xml
<CustomField>
    <fullName>QtdsMalasMedias__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Qtds. Malas Médias</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProdutoPassageiro__c/fields/QtdsMalasPequenas__c.field-meta.xml
<CustomField>
    <fullName>QtdsMalasPequenas__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Qtds. Malas Pequenas</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProdutoPassageiro__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendente</fullName>
            </value>
            <value>
                <fullName>Configurado</fullName>
            </value>
            <value>
                <fullName>Removido</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PromocaoOportunidade__c/PromocaoOportunidade__c.object-meta.xml
<CustomObject>
    <label>Promoção Oportunidade</label>
    <nameField>
        <displayFormat>PROP-{00000000}</displayFormat>
        <label>Promoção Oportunidade</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promoções Oportunidades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PromocaoOportunidade__c/fields/Oportunidade__c.field-meta.xml
<CustomField>
    <fullName>Oportunidade__c</fullName>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Promoções Oportunidades</relationshipLabel>
    <relationshipName>PromocoesOportunidades</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PromocaoOportunidade__c/fields/Promocao__c.field-meta.xml
<CustomField>
    <fullName>Promocao__c</fullName>
    <label>Promoção</label>
    <referenceTo>CodigoPromocional__c</referenceTo>
    <relationshipLabel>Promoções Oportunidades</relationshipLabel>
    <relationshipName>PromocoesOportunidades</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/StatusPendenteAprovado.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pendente</fullName>
        <default>true</default>
        <label>Pendente</label>
    </customValue>
    <customValue>
        <fullName>Validado</fullName>
    </customValue>
    <masterLabel>Status Pendente/Aprovado</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Opportunities.cls
public class Opportunities extends fflib_SObjectDomain implements IOpportunities
{
    public Opportunities(List<Opportunity> sObjectList)
    {
        super(sObjectList);
    }
    
    public class Constructor implements fflib_SObjectDomain.IConstructable
    {
        public fflib_SObjectDomain construct(List<SObject> sObjectList)
        {
            return new Opportunities(sObjectList);
        }
    }
    
    public static Opportunity criaOportunidade(
        fflib_ISObjectUnitOfWork uow, Id invoicedId, Id customerId, String customerName, String typeOpp, Id promotionId, String codigoReserva, String source
    ) {

        Pricebook2 standardPricebook = [SELECT Id FROM Pricebook2 WHERE IsStandard = TRUE AND IsActive = TRUE LIMIT 1];

        Datetime agora = Datetime.now();
        Integer numero = agora.second() + agora.millisecond() + agora.month();

        Opportunity oportunidade = new Opportunity();
        oportunidade.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Oportunidade').getRecordTypeId();
        oportunidade.Type = typeOpp;
        oportunidade.Name = typeOpp + ' - ' + customerName + ' - ' + System.today().format() + ' - ' + codigoReserva;
        oportunidade.StageName = 'Cotação';
        oportunidade.FaturadoPara__c = invoicedId;
        oportunidade.Pricebook2Id = standardPricebook.Id;
        oportunidade.AccountId = customerId;
        oportunidade.CodigoPromocional__c = promotionId;
        oportunidade.closeDate = System.today();
        oportunidade.CodigoReserva__c = codigoReserva;
        oportunidade.Origem__c = source ?? 'Salesforce';
        
        uow.registerNew(oportunidade);

        return oportunidade;
    }


    public static Opportunity criaOportunidadeRevoSeats(
        fflib_ISObjectUnitOfWork uow, Id invoicedId, Id customerId, String customerName, Id promotionId, String codigoReserva, String source
    ) {

        Pricebook2 revoSeatsPricebook = [SELECT Id FROM Pricebook2 WHERE IsStandard = TRUE LIMIT 1];

        Datetime agora = Datetime.now();
        Integer numero = agora.second() + agora.millisecond() + agora.month();

        Opportunity oportunidade = new Opportunity();
        oportunidade.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('RevoSeats').getRecordTypeId();
        oportunidade.Name = 'Revo Seats - ' + customerName + ' - ' + System.today().format() + ' - ' + codigoReserva;
        oportunidade.StageName = 'Cotação';
        oportunidade.FaturadoPara__c = invoicedId;
        oportunidade.Pricebook2Id = revoSeatsPricebook.Id;
        oportunidade.AccountId = customerId;
        oportunidade.CodigoPromocional__c = promotionId;
        oportunidade.closeDate = System.today();
        oportunidade.CodigoReserva__c = codigoReserva;
        oportunidade.Origem__c = source ?? 'Salesforce';
        
        uow.registerNew(oportunidade);

        Product2 product = [SELECT Id FROM Product2 WHERE RecordType.DeveloperName = 'RevoSeats' LIMIT 1];
        PricebookEntry pricebookEntry = [SELECT Id, UnitPrice FROM PricebookEntry WHERE Pricebook2Id = :revoSeatsPricebook.Id AND Product2Id = :product.Id LIMIT 1];

        OpportunityLineItem line = new OpportunityLineItem();
        line.Product2Id = product.Id;
        line.Quantity = 1;
        line.PrecoUnitario__c = pricebookEntry.UnitPrice;
        line.UnitPrice = pricebookEntry.UnitPrice;

        uow.registerNew(line, OpportunityLineItem.OpportunityId, oportunidade);

        return oportunidade;
    }    

    public static OpportunityLineItem criaLinhaShuttleSeat(
        fflib_ISObjectUnitOfWork uow, Id productId, Id aircraftModel, Decimal missionTime, Integer quantity, Boolean appliedPromotion, 
        Datetime flightDateTime, Decimal unitPrice, Decimal revoSeatsPrice, Opportunity oportunidade, Id departurePointId, Id destinationPointId, 
        Id routeId, Decimal totalPrice, Decimal totalPriceRevoSeats, Decimal valueDiscount, Decimal percDiscount
    ) {

        OpportunityLineItem line = new OpportunityLineItem();
        line.Product2Id = productId;
        line.TempoMissao__c = missionTime;
        line.Quantity = quantity;
        line.ModeloSelecionado__c = aircraftModel;
        line.PromocaoAplicada__c = appliedPromotion;
        line.PrevisaoEmbarque__c = flightDateTime;
        line.PrecoUnitario__c = unitPrice;
        line.Pacote__c = null;
        line.Origem__c = departurePointId;
        line.UnitPrice = totalPrice / quantity;
        line.PrecoRevoSeats__c = revoSeatsPrice;
        line.Obrigatorio__c = false;
        line.MalhaVoo__c = routeId;
        line.Empacotado__c = false;
        line.Destino__c = destinationPointId;
        line.DescontoValor__c = valueDiscount;
        line.DescontoPercentual__c = percDiscount;
        line.TotalRevoSeats__c = totalPriceRevoSeats;

        uow.registerNew(line, OpportunityLineItem.OpportunityId, oportunidade);

        return line;
    }        

    public static OpportunityLineItem criaLinhaFullCabin(
        fflib_ISObjectUnitOfWork uow, Id productId, Id aircraftModel, Decimal missionTime, Boolean appliedPromotion, 
        Datetime flightDateTime, Decimal unitPrice, Decimal revoSeatsPrice, Opportunity oportunidade, Id departurePointId, Id destinationPointId, 
        Decimal totalPrice, Decimal totalPriceRevoSeats, Decimal valueDiscount, Decimal percDiscount
    ) {

        OpportunityLineItem line = new OpportunityLineItem();
        line.Product2Id = productId;
        line.ModeloSelecionado__c = aircraftModel;
        line.TempoMissao__c = missionTime;
        line.Quantity = 1;
        line.PromocaoAplicada__c = appliedPromotion;
        line.PrevisaoEmbarque__c = flightDateTime;
        line.PrecoUnitario__c = unitPrice;
        line.Pacote__c = null;
        line.Origem__c = departurePointId;
        line.UnitPrice = totalPrice;
        line.Obrigatorio__c = false;
        line.Empacotado__c = false;
        line.Destino__c = destinationPointId;
        line.DescontoValor__c = valueDiscount;
        line.DescontoPercentual__c = percDiscount;
        line.PrecoRevoSeats__c = revoSeatsPrice;
        line.TotalRevoSeats__c = totalPriceRevoSeats;

        uow.registerNew(line, OpportunityLineItem.OpportunityId, oportunidade);

        return line;
    }        

    public static OpportunityLineItem criaLinhaCharter(
        fflib_ISObjectUnitOfWork uow, Id productId, Id aircraftModel, Decimal missionTime, Boolean appliedPromotion, 
        Datetime flightDateTime, Decimal unitPrice, Decimal revoSeatsPrice, Opportunity oportunidade, Id departurePointId, Id destinationPointId,
        Decimal totalPrice, Decimal totalPriceRevoSeats, Decimal valueDiscount, Decimal percDiscount
    ) {
        Decimal quantidade = missionTime / 60;
        quantidade = quantidade.setScale(2, RoundingMode.HALF_UP);

        OpportunityLineItem line = new OpportunityLineItem();
        line.Product2Id = productId;
        line.ModeloSelecionado__c = aircraftModel;        
        line.TempoMissao__c = missionTime;
        line.Quantity = quantidade;
        line.PromocaoAplicada__c = appliedPromotion;
        line.PrevisaoEmbarque__c = flightDateTime;
        line.PrecoUnitario__c = unitPrice;
        line.Pacote__c = null;
        line.Origem__c = departurePointId;
        line.Destino__c = destinationPointId;
        line.UnitPrice = totalPrice / line.Quantity;
        line.Obrigatorio__c = false;
        line.Empacotado__c = false;
        line.DescontoValor__c = valueDiscount;
        line.DescontoPercentual__c = percDiscount;
        line.PrecoRevoSeats__c = revoSeatsPrice;
        line.TotalRevoSeats__c = totalPriceRevoSeats;

        uow.registerNew(line, OpportunityLineItem.OpportunityId, oportunidade);

        return line;
    }        

    public static OpportunityLineItem criaLinhaServico(
        fflib_ISObjectUnitOfWork uow, Opportunity oportunidade, OpportunityLineItem pacote, Id productId, Integer quantity, 
        Boolean obrigatorio, Boolean empacotado, Boolean porPassageiro, Boolean appliedPromotion, Datetime flightDateTime, Decimal unitPrice, Decimal revoSeatsPrice,  
        Decimal totalPrice, Decimal totalPriceRevoSeats, Decimal valueDiscount, Decimal percDiscount
    ) {

        OpportunityLineItem line = new OpportunityLineItem();
        line.Product2Id = productId;
        line.Quantity = quantity;
        line.PromocaoAplicada__c = appliedPromotion;
        //line.PrevisaoEmbarque__c = flightDateTime;
        line.PrecoUnitario__c = unitPrice;
        line.UnitPrice = totalPrice / quantity;
        line.Obrigatorio__c = obrigatorio;
        line.Empacotado__c = empacotado;
        line.ServicaoPorPassageiro__c = porPassageiro;
        line.DescontoValor__c = valueDiscount;
        line.DescontoPercentual__c = percDiscount;
        line.PrecoRevoSeats__c = revoSeatsPrice;
        line.TotalRevoSeats__c = totalPriceRevoSeats;

        uow.registerNew(line, OpportunityLineItem.OpportunityId, oportunidade);
        uow.registerRelationship(line, OpportunityLineItem.Pacote__c, pacote);
        
        return line;
    }          

    public static PassageiroOportunidade__c criaPassageiroOportunidade(
        fflib_ISObjectUnitOfWork uow, Opportunity oportunidade, Contact passageiro
    ) {

        PassageiroOportunidade__c passOpp = new PassageiroOportunidade__c();

        uow.registerNew(passOpp, PassageiroOportunidade__c.Oportunidade__c, oportunidade);
        uow.registerRelationship(passOpp, PassageiroOportunidade__c.Passageiro__c, passageiro);

        return passOpp;
    }           

    public static LocalOportunidade__c criaLocal(
        fflib_ISObjectUnitOfWork uow, Opportunity oportunidade, OpportunityLineItem item, Integer sequencia, Id localId, Decimal latitude, Decimal longitude
    ) {
        List<LocalOportunidade__c> result = new List<LocalOportunidade__c>();

        LocalOportunidade__c local = new LocalOportunidade__c();

        local.Sequencia__c = sequencia;
        local.Local__c = localId;
        local.Coordenadas__Latitude__s = latitude;
        local.Coordenadas__Longitude__s = longitude;

        uow.registerNew(local, LocalOportunidade__c.Oportunidade__c, oportunidade);
        uow.registerRelationship(local, LocalOportunidade__c.ProdutoOportunidade__c, item);

        return local;
    }    

    public static List<LocalOportunidade__c> criaLocaisOrigemDestino(
        fflib_ISObjectUnitOfWork uow, Opportunity oportunidade, OpportunityLineItem item, Id origemId, Id destinoId
    ) {
        List<LocalOportunidade__c> result = new List<LocalOportunidade__c>();

        LocalOportunidade__c origem = new LocalOportunidade__c();
        origem.Sequencia__c = 10;
        origem.Local__c = origemId;

        result.add(origem);

        uow.registerNew(origem, LocalOportunidade__c.Oportunidade__c, oportunidade);
        uow.registerRelationship(origem, LocalOportunidade__c.ProdutoOportunidade__c, item);

        LocalOportunidade__c destino = new LocalOportunidade__c();
        destino.Sequencia__c = 20;
        destino.Local__c = destinoId;

        result.add(destino);

        uow.registerNew(destino, LocalOportunidade__c.Oportunidade__c, oportunidade);
        uow.registerRelationship(destino, LocalOportunidade__c.ProdutoOportunidade__c, item);
                
        return result;
    }
    

    public static ProdutoPassageiro__c criaProdutoDoPassageiro(
        fflib_ISObjectUnitOfWork uow, PassageiroOportunidade__c passageiro, OpportunityLineItem item, String endereco,
        String cidade, String estado, String zipcode, String pais, String complemento, Integer qtdMalasPequenas, 
        Integer qtdMalasMedias, Integer qtdMalasGrandes, String status, String airline, String flightNumber
    ) {

        ProdutoPassageiro__c produto = new ProdutoPassageiro__c();

        produto.EnderecoServico__c = endereco;
        produto.CidadeServico__c = cidade;
        produto.EstadoServico__c = estado;
        produto.PaisServico__c = pais;
        produto.CEPServico__c = zipcode;
        produto.ComplementoEndereco__c = complemento;
        produto.QtdsMalasPequenas__c = qtdMalasPequenas;
        produto.QtdsMalasGrandes__c = qtdMalasGrandes;
        produto.QtdsMalasMedias__c = qtdMalasMedias;
        produto.Status__c = status ?? 'Pendente';
        produto.CompanhiaAerea__c = airline;
        produto.NumeroVoo__c = flightNumber;

        uow.registerNew(produto, ProdutoPassageiro__c.PassageiroOportunidade__c, passageiro);
        uow.registerRelationship(produto, ProdutoPassageiro__c.ProdutoOportunidade__c, item);

        return produto;
    }          


    public static PromocaoOportunidade__c criaPromocaoOportunidade(
        fflib_ISObjectUnitOfWork uow, Opportunity oportunidade, Id codigoPromocionalId
    ) {

        PromocaoOportunidade__c promocao = new PromocaoOportunidade__c();

        promocao.Promocao__c = codigoPromocionalId;

        uow.registerNew(promocao, PromocaoOportunidade__c.Oportunidade__c, oportunidade);

        return promocao;
    }          
}