force-app/main/default/objects/CodigoPromocional__c/CodigoPromocional__c.object-meta.xml
<CustomObject>
    <label>Promoção</label>
    <nameField>
        <label>Código Promocional</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promoções</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CodigoPromocional__c/fields/Parceiro__c.field-meta.xml
<CustomField>
    <fullName>Parceiro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parceiro</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Promoções (Parceiro)</relationshipLabel>
    <relationshipName>PromocoesParceiro</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CodigoPromocional__c/fields/ValorCobrancaParceiro__c.field-meta.xml
<CustomField>
    <fullName>ValorCobrancaParceiro__c</fullName>
    <label>Valor Cobrança Parceiro</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Passageiro__c/Passageiro__c.object-meta.xml
<CustomObject>
    <label>Passageiro</label>
    <nameField>
        <displayFormat>P-{000000000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Passageiros</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Passageiro__c/fields/DataVoo__c.field-meta.xml
<CustomField>
    <fullName>DataVoo__c</fullName>
    <formula>Trecho__r.Voo__r.DataVoo__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Data/Hora Voo</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Passageiro__c/fields/Trecho__c.field-meta.xml
<CustomField>
    <fullName>Trecho__c</fullName>
    <label>Trecho</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Trecho__c.Status__c</field>
            <operation>equals</operation>
            <value>Não Iniciado</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Trecho__c</referenceTo>
    <relationshipLabel>Passageiros</relationshipLabel>
    <relationshipName>Passageiros</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Servico__c/Servico__c.object-meta.xml
<CustomObject>
    <label>Serviço</label>
    <nameField>
        <displayFormat>SERV-{0000000}</displayFormat>
        <label>Serviço</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Serviços</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Servico__c/fields/CEPServico__c.field-meta.xml
<CustomField>
    <fullName>CEPServico__c</fullName>
    <label>CEP Serviço</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Servico__c/fields/CidadeServico__c.field-meta.xml
<CustomField>
    <fullName>CidadeServico__c</fullName>
    <label>Cidade Serviço</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Servico__c/fields/ComplementoEndereco__c.field-meta.xml
<CustomField>
    <fullName>ComplementoEndereco__c</fullName>
    <label>Complemento Endereço</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Servico__c/fields/ContaComprador__c.field-meta.xml
<CustomField>
    <fullName>ContaComprador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta Comprador</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Serviços (Conta Comprador)</relationshipLabel>
    <relationshipName>ServicosComprador</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Servico__c/fields/ContaFaturamento__c.field-meta.xml
<CustomField>
    <fullName>ContaFaturamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta Faturamento</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Serviços</relationshipLabel>
    <relationshipName>Servicos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Servico__c/fields/DataServico__c.field-meta.xml
<CustomField>
    <fullName>DataServico__c</fullName>
    <label>Data do Serviço</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Servico__c/fields/EnderecoServico__c.field-meta.xml
<CustomField>
    <fullName>EnderecoServico__c</fullName>
    <label>Endereço Serviço</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Servico__c/fields/EstadoServico__c.field-meta.xml
<CustomField>
    <fullName>EstadoServico__c</fullName>
    <label>Estado Serviço</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Servico__c/fields/Observacoes__c.field-meta.xml
<CustomField>
    <fullName>Observacoes__c</fullName>
    <label>Observações</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Servico__c/fields/Oportunidade__c.field-meta.xml
<CustomField>
    <fullName>Oportunidade__c</fullName>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Serviços</relationshipLabel>
    <relationshipName>Servicos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Servico__c/fields/PaisServico__c.field-meta.xml
<CustomField>
    <fullName>PaisServico__c</fullName>
    <label>País Serviço</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Servico__c/fields/Passageiro__c.field-meta.xml
<CustomField>
    <fullName>Passageiro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Passageiro</label>
    <referenceTo>Passageiro__c</referenceTo>
    <relationshipLabel>Serviços</relationshipLabel>
    <relationshipName>Servicos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Servico__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Serviços</relationshipLabel>
    <relationshipName>Servicos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Servico__c/fields/ProdutoOportunidade__c.field-meta.xml
<CustomField>
    <fullName>ProdutoOportunidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto de oportunidade</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipLabel>Serviços</relationshipLabel>
    <relationshipName>Servicos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Servico__c/fields/PromocaoParceiro__c.field-meta.xml
<CustomField>
    <fullName>PromocaoParceiro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promoção Parceiro</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CodigoPromocional__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Promoção Parceiro</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CodigoPromocional__c</referenceTo>
    <relationshipLabel>Serviços</relationshipLabel>
    <relationshipName>Servicos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Servico__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aguardando Execução</fullName>
            </value>
            <value>
                <fullName>PreReservado</fullName>
                <label>Pré-Reservado</label>
            </value>
            <value>
                <fullName>Pago</fullName>
            </value>
            <value>
                <fullName>Executado</fullName>
            </value>
            <value>
                <fullName>No-Show</fullName>
            </value>
            <value>
                <fullName>Faturado</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Servico__c/fields/TotalRevoSeats__c.field-meta.xml
<CustomField>
    <fullName>TotalRevoSeats__c</fullName>
    <label>Total RevoSeats</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Servico__c/fields/Trecho__c.field-meta.xml
<CustomField>
    <fullName>Trecho__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trecho</label>
    <referenceTo>Trecho__c</referenceTo>
    <relationshipLabel>Serviços</relationshipLabel>
    <relationshipName>Servicos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Servico__c/fields/ValorTotal__c.field-meta.xml
<CustomField>
    <fullName>ValorTotal__c</fullName>
    <label>Valor Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Servico__c/fields/Voo__c.field-meta.xml
<CustomField>
    <fullName>Voo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Voo</label>
    <referenceTo>Voo__c</referenceTo>
    <relationshipLabel>Serviços</relationshipLabel>
    <relationshipName>Servicos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Servico__c/recordTypes/CharterFlight.recordType-meta.xml
<RecordType>
    <fullName>CharterFlight</fullName>
    <active>true</active>
    <label>Charter Flight</label>
</RecordType>

force-app/main/default/objects/Servico__c/recordTypes/CobrancaParceiro.recordType-meta.xml
<RecordType>
    <fullName>CobrancaParceiro</fullName>
    <active>true</active>
    <label>Cobrança Parceiro</label>
</RecordType>

force-app/main/default/objects/Servico__c/recordTypes/FullCabin.recordType-meta.xml
<RecordType>
    <fullName>FullCabin</fullName>
    <active>true</active>
    <label>Full Cabin</label>
</RecordType>

force-app/main/default/objects/Servico__c/recordTypes/ServicosTaxas.recordType-meta.xml
<RecordType>
    <fullName>ServicosTaxas</fullName>
    <active>true</active>
    <label>Serviços e Taxas</label>
</RecordType>

force-app/main/default/objects/Servico__c/recordTypes/ShuttleSeat.recordType-meta.xml
<RecordType>
    <fullName>ShuttleSeat</fullName>
    <active>true</active>
    <label>Shuttle Seat</label>
</RecordType>

force-app/main/default/objects/Trecho__c/Trecho__c.object-meta.xml
<CustomObject>
    <description>Define um trecho com origem e destino dentro de um Voo</description>
    <label>Trecho</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Código do Trecho</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trechos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trecho__c/fields/Observacoes__c.field-meta.xml
<CustomField>
    <fullName>Observacoes__c</fullName>
    <inlineHelpText>Observações sobre o trecho</inlineHelpText>
    <label>Observações</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trecho__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Não Iniciado</fullName>
                <default>true</default>
                <label>Não Iniciado</label>
            </value>
            <value>
                <fullName>Check In Fechado</fullName>
            </value>
            <value>
                <fullName>Em Rota</fullName>
            </value>
            <value>
                <fullName>Finalizado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trecho__c/fields/Voo__c.field-meta.xml
<CustomField>
    <fullName>Voo__c</fullName>
    <description>Voo ao qual o trecho pertence</description>
    <inlineHelpText>Voo ao qual o trecho pertence</inlineHelpText>
    <label>Voo</label>
    <referenceTo>Voo__c</referenceTo>
    <relationshipLabel>Trechos</relationshipLabel>
    <relationshipName>Trechos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Voo__c/Voo__c.object-meta.xml
<CustomObject>
    <description>O Voo de uma aeronave, do ponto de origem até o retorno</description>
    <label>Voo</label>
    <nameField>
        <displayFormat>REVO-{00000000}</displayFormat>
        <label>Número do Voo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Voos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Voo__c/fields/DataVoo__c.field-meta.xml
<CustomField>
    <fullName>DataVoo__c</fullName>
    <description>Dia e hora solicitada para a realização do voo</description>
    <inlineHelpText>Dia e hora solicitada para a realização do voo</inlineHelpText>
    <label>Data</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Voo__c/fields/Observacoes__c.field-meta.xml
<CustomField>
    <fullName>Observacoes__c</fullName>
    <description>Observações com relação ao voo</description>
    <inlineHelpText>Observações com relação ao voo</inlineHelpText>
    <label>Observações</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Voo__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Voos</relationshipLabel>
    <relationshipName>Voos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Voo__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Define em que momento o voo se encontra</description>
    <inlineHelpText>Define em que momento o voo se encontra</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Rascunho</fullName>
                <default>true</default>
                <label>Rascunho</label>
            </value>
            <value>
                <fullName>Pré-reservado</fullName>
            </value>
            <value>
                <fullName>Reservado</fullName>
            </value>
            <value>
                <fullName>Confirmado</fullName>
            </value>
            <value>
                <fullName>Rota</fullName>
                <label>Em Rota</label>
            </value>
            <value>
                <fullName>LogPendente</fullName>
                <label>Concluindo o Voo</label>
            </value>
            <value>
                <fullName>Executado</fullName>
            </value>
            <value>
                <fullName>Em Faturamento</fullName>
                <isActive>false</isActive>
                <label>Em Faturamento</label>
            </value>
            <value>
                <fullName>Faturado</fullName>
                <isActive>false</isActive>
                <label>Faturado</label>
            </value>
            <value>
                <fullName>Pronto pra Voar</fullName>
                <isActive>false</isActive>
                <label>Pronto pra Voar</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Servicos.cls
public without sharing class Servicos extends fflib_SObjectDomain implements IServicos {    
   
    private enum TiposDeServicos {
        ShuttleSeat, FullCabin, CharterFlight, ServicosTaxas
    }        

    public Servicos(List<Servico__c> sObjectList) {
        super(sObjectList);
    }

    public static IServicos newInstance(List<Servico__c> sObjectList) {
        return (IServicos) Application.Domain.newInstance(sObjectList);
    }

    public class Constructor implements fflib_SObjectDomain.IConstructable {
        public fflib_SObjectDomain construct(List<SObject> sObjectList) {
            return new Servicos(sObjectList);
        }
    }


    public static Servico__c criarServicoParceiro(
        fflib_ISObjectUnitOfWork uow, Opportunity oportunidade, CodigoPromocional__c promocao
    ) {
        Map<String, Id> mapServicosTypes = servicoRecordTypesNameIds();

        Servico__c servico = new Servico__c();
        servico.RecordTypeId = mapServicosTypes.get('CobrancaParceiro');
        servico.Status__c = 'Aguardando Execução';
        servico.ContaComprador__c = oportunidade.AccountId;
        servico.ContaFaturamento__c = promocao.Parceiro__c;
        servico.Oportunidade__c = oportunidade.Id;
        servico.ValorTotal__c = promocao.ValorCobrancaParceiro__c;
        servico.DataServico__c = Date.today();
        servico.PromocaoParceiro__c = promocao.Id;

        uow.registerNew(servico);        

        return servico;
    }    

    public static Servico__c criarServicoOportunidadeRevoSeats(
        fflib_ISObjectUnitOfWork uow, Opportunity oportunidade, OpportunityLineItem line, 
        Decimal valorTotal
    ) {
        Map<Id, String> mapProductsTypes = productRecordTypesIds();
        Map<String, Id> mapServicosTypes = servicoRecordTypesNameIds();

        Servico__c servico = new Servico__c();
        servico.RecordTypeId = mapServicosTypes.get(mapProductsTypes.get(line.Product2.RecordTypeId));
        servico.Status__c = 'PreReservado';
        servico.Produto__c = line.Product2Id;
        servico.ContaComprador__c = oportunidade.AccountId;
        servico.ContaFaturamento__c = oportunidade.FaturadoPara__c;
        servico.Oportunidade__c = oportunidade.Id;
        servico.ProdutoOportunidade__c = line.Id;
        servico.ValorTotal__c = valorTotal;
        servico.DataServico__c = Date.today();

        uow.registerNew(servico);        

        return servico;
    }

    public static Servico__c criarServicoOportunidade(
        fflib_ISObjectUnitOfWork uow, Opportunity oportunidade, OpportunityLineItem line, 
        Voo__c voo, Trecho__c trecho, Passageiro__c pasageiro, Decimal valorTotal, Decimal valorTotalRevoSeats
    ) {
        return criarServicoOportunidade(uow, oportunidade, line, voo, trecho, pasageiro, valorTotal, valorTotalRevoSeats, null, null, null, null, null, null,
        null, null, null, null, null, null);
    }

    public static Servico__c criarServicoOportunidade(
        fflib_ISObjectUnitOfWork uow, Opportunity oportunidade, OpportunityLineItem line, 
        Voo__c voo, Trecho__c trecho, Passageiro__c pasageiro, Decimal valorTotal, Decimal valorTotalRevoSeats, String observacoes, String enderecoServico,
        String cidadeServico, String estadoServico, String paisServico, String complementoEndereco,
        String CEPServico, String companhiaAerea, String numeroVoo, Decimal qtdsMalasGrandes, 
        Decimal qtdsMalasMedias, Decimal qtdsMalasPequenas
    ) {
        Map<Id, String> mapProductsTypes = productRecordTypesIds();
        Map<String, Id> mapServicosTypes = servicoRecordTypesNameIds();

        Servico__c servico = new Servico__c();
        servico.RecordTypeId = mapServicosTypes.get(mapProductsTypes.get(line.Product2.RecordTypeId));
        servico.Status__c = 'PreReservado';
        servico.Produto__c = line.Product2Id;
        servico.ContaComprador__c = oportunidade.AccountId;
        servico.ContaFaturamento__c = oportunidade.FaturadoPara__c;
        servico.Oportunidade__c = oportunidade.Id;
        servico.ProdutoOportunidade__c = line.Id;
        servico.ValorTotal__c = valorTotal;
        servico.TotalRevoSeats__c = valorTotalRevoSeats;
        servico.DataServico__c = voo.DataVoo__c;

        servico.Observacoes__c = observacoes;
        servico.EnderecoServico__c = enderecoServico;
        servico.CidadeServico__c = cidadeServico;
        servico.EstadoServico__c = estadoServico;
        servico.ComplementoEndereco__c = complementoEndereco;
        servico.CEPServico__c = CEPServico;
        servico.PaisServico__c = paisServico;
        servico.CompanhiaAerea__c = companhiaAerea;
        servico.NumeroVoo__c = numeroVoo; 
        servico.QtdsMalasGrandes__c = qtdsMalasGrandes;
        servico.QtdsMalasMedias__c = qtdsMalasMedias;
        servico.QtdsMalasPequenas__c = qtdsMalasPequenas;

        uow.registerNew(servico);        
        uow.registerRelationship(servico, Servico__c.Voo__c, voo);

        if (trecho != null) {
            uow.registerRelationship(servico, Servico__c.Trecho__c, trecho);
        }

        if (pasageiro != null) {
            uow.registerRelationship(servico, Servico__c.Passageiro__c, pasageiro);
        }

        return servico;
    }    

    private static Map<Id, String> productRecordTypesIds() {
        Schema.DescribeSObjectResult describeResult = Schema.getGlobalDescribe().get('Product2').getDescribe();
        Map<Id, Schema.RecordTypeInfo> recordTypeInfoMap = describeResult.getRecordTypeInfosById();

        Map<Id, String> result = new Map<Id, String>();

        for (Schema.RecordTypeInfo rtInfo : recordTypeInfoMap.values()) {
            result.put(rtInfo.getRecordTypeId(), rtInfo.getDeveloperName());
        }

        return result;
    }    

    private static Map<String, Id> servicoRecordTypesNameIds() {
        Schema.DescribeSObjectResult describeResult = Schema.getGlobalDescribe().get('Servico__c').getDescribe();
        Map<Id, Schema.RecordTypeInfo> recordTypeInfoMap = describeResult.getRecordTypeInfosById();

        Map<String, Id> result = new Map<String, Id>();

        for (Schema.RecordTypeInfo rtInfo : recordTypeInfoMap.values()) {
            result.put(rtInfo.getDeveloperName(), rtInfo.getRecordTypeId());
        }

        return result;
    }    

}