force-app/main/default/objects/CodigoPromocional__c/CodigoPromocional__c.object-meta.xml
<CustomObject>
    <label>Promoção</label>
    <nameField>
        <label>Código Promocional</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promoções</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ConfiguracaoTempo__c/ConfiguracaoTempo__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Configurações de Tempo</label>
</CustomObject>

force-app/main/default/objects/ConfiguracaoTempo__c/fields/MinutosBloqueioReservarVoo__c.field-meta.xml
<CustomField>
    <fullName>MinutosBloqueioReservarVoo__c</fullName>
    <description>Minutos de bloqueio na pré-reserva para reservar o voo na última etapa (carrinho de voos)</description>
    <inlineHelpText>Minutos de bloqueio na pré-reserva para reservar o voo na última etapa (carrinho de voos)</inlineHelpText>
    <label>Minutos de bloqueio para reservar o voo</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PromocaoOportunidade__c/PromocaoOportunidade__c.object-meta.xml
<CustomObject>
    <label>Promoção Oportunidade</label>
    <nameField>
        <displayFormat>PROP-{00000000}</displayFormat>
        <label>Promoção Oportunidade</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promoções Oportunidades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PromocaoOportunidade__c/fields/Promocao__c.field-meta.xml
<CustomField>
    <fullName>Promocao__c</fullName>
    <label>Promoção</label>
    <referenceTo>CodigoPromocional__c</referenceTo>
    <relationshipLabel>Promoções Oportunidades</relationshipLabel>
    <relationshipName>PromocoesOportunidades</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Servico__c/Servico__c.object-meta.xml
<CustomObject>
    <label>Serviço</label>
    <nameField>
        <displayFormat>SERV-{0000000}</displayFormat>
        <label>Serviço</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Serviços</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Servico__c/fields/PromocaoParceiro__c.field-meta.xml
<CustomField>
    <fullName>PromocaoParceiro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promoção Parceiro</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CodigoPromocional__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Promoção Parceiro</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CodigoPromocional__c</referenceTo>
    <relationshipLabel>Serviços</relationshipLabel>
    <relationshipName>Servicos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Servico__c/fields/ServicoPromocao__c.field-meta.xml
<CustomField>
    <fullName>ServicoPromocao__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Serviço Promoção</label>
    <referenceTo>Servico__c</referenceTo>
    <relationshipLabel>Serviços</relationshipLabel>
    <relationshipName>Servicos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Servico__c/recordTypes/RevoSeats.recordType-meta.xml
<RecordType>
    <fullName>RevoSeats</fullName>
    <active>true</active>
    <label>Revo Seats</label>
</RecordType>

force-app/main/default/classes/CheckoutOportunidadeRevoSeats.cls
public without sharing class CheckoutOportunidadeRevoSeats implements INucleoCheckoutOportunidade {

    // #region Variaveis Privadas

    private Opportunity oportunidade;
    private enum TiposDeProdutos {
        RevoSeats
    }    

    // #endregion

    // #region Construtor    

    public CheckoutOportunidadeRevoSeats(Opportunity oportunidade) {
        if (oportunidade == null) {
            throw new OportunidadeNaoEncontradaException(true);
        }

        this.oportunidade = oportunidade;

        Map<Id, String> mapProductsTypes = productRecordTypesIds();        
        Set<String> OpportunityProducts = enumTiposDeProdutosToSet();

        for (OpportunityLineItem item : oportunidade.OpportunityLineItems) {
            
            if (!OpportunityProducts.contains(mapProductsTypes.get(item.Product2.RecordTypeId))) {
                throw new ProdutoInvalidoNaOportunidadeException(true);
            }
        }
    }    

    // #endregion

    // #region Métodos Públicos

    public void validaOportunidade() {

        if (oportunidade.StageName != 'Cotação' && oportunidade.StageName != 'Aguardando Validação') {
            throw new OportunidadeFaseInvalidaException(true);
        }

        if (oportunidade.AccountId == null) {
            throw new ContaOportunidadeNaoInformadaException(true);
        }

        if (oportunidade.FaturadoPara__c == null) {
            throw new ContaDeFaturamentoNaoInformadaException(true);
        }

        if (oportunidade.OpportunityLineItems.isEmpty()) {
            throw new OportunidadeSemProdutosException(true);
        }

    }    

    public void validaOsProdutos() {

        Map<Id, String> mapProductsTypes = productRecordTypesIds();

        Map<Id, OpportunityLineItem> mapProdutoOportunidade = new Map<Id, OpportunityLineItem>(oportunidade.OpportunityLineItems);

        for (OpportunityLineItem item : oportunidade.OpportunityLineItems) {
            if (mapProductsTypes.get(item.Product2.RecordTypeId) == TiposDeProdutos.RevoSeats.name()){
                if (item.Quantity <= 0.00) {
                    throw new QuantidadeInvalidoException(true);
                }
            }
        }               
    }

    public void confirmaCheckout(fflib_ISObjectUnitOfWork uow) {

        Map<Id, String> mapProductsTypes = productRecordTypesIds();

        for (OpportunityLineItem item : oportunidade.OpportunityLineItems) {

            if (mapProductsTypes.get(item.Product2.RecordTypeId) == TiposDeProdutos.RevoSeats.name()){
                Servicos.criarServicoOportunidadeRevoSeats(uow, this.oportunidade, item, item.TotalPrice);
            }
        }            

        if (oportunidade.CodigoPromocional__c != null) {
            Opportunities.criaPromocaoOportunidade(uow, oportunidade, oportunidade.CodigoPromocional__c);
        }
        
        oportunidade.StageName = 'Aguardando Pagamento';
        oportunidade.Sistema__c = true;

        ConfiguracaoTempo__c configuracaoTempo = ConfiguracaoTempo__c.getOrgDefaults();
		Decimal tempoParaResetar = configuracaoTempo.MinutosBloqueioReservarVoo__c;

        this.oportunidade.LimitePagamento__c = System.now();
        this.oportunidade.LimitePagamento__c = this.oportunidade.LimitePagamento__c.addMinutes(Integer.valueOf(tempoParaResetar));        

        uow.registerDirty(oportunidade);
    }    

    public void cancelaOportunidade(fflib_ISObjectUnitOfWork uow) {
        
        if (oportunidade.StageName != 'Cotação' && oportunidade.StageName != 'Aguardando Validação'
        && oportunidade.StageName != 'Aguardando Pagamento') {
            throw new OportunidadeFaseInvalidaException(true);
        }

        this.oportunidade.Sistema__c = true;

        this.oportunidade.StageName = 'Cancelado';

        uow.registerDirty(this.oportunidade);

        if (this.oportunidade.PromocoesOportunidades__r != null && !this.oportunidade.PromocoesOportunidades__r.isEmpty()) {
            uow.registerDeleted(this.oportunidade.PromocoesOportunidades__r);
        }

        if (this.oportunidade.Servicos__r != null && !this.oportunidade.Servicos__r.isEmpty()) {
            uow.registerDeleted(this.oportunidade.Servicos__r);
        }
    }

    public void bloqueiaAlteracoesFase(fflib_ISObjectUnitOfWork uow) {

        oportunidade.Sistema__c = false;

        uow.registerDirty(oportunidade);
    }        

    // #endregion

    // #region Métodos Privados

    private Map<Id, String> productRecordTypesIds() {
        Schema.DescribeSObjectResult describeResult = Schema.getGlobalDescribe().get('Product2').getDescribe();
        Map<Id, Schema.RecordTypeInfo> recordTypeInfoMap = describeResult.getRecordTypeInfosById();

        Map<Id, String> result = new Map<Id, String>();

        for (Schema.RecordTypeInfo rtInfo : recordTypeInfoMap.values()) {
            result.put(rtInfo.getRecordTypeId(), rtInfo.getDeveloperName());
        }

        return result;
    }    

    private Set<String> enumTiposDeProdutosToSet() {
        Set<String> result = new Set<String>();

        for (TiposDeProdutos tipo : TiposDeProdutos.values()) {
            result.add(tipo.name());
        }

        return result;
    }

    // #endregion

    // #region Catálogo de Erros

    public virtual class OpportunityException extends Exception {
        public String codigo;
    
        public OpportunityException(String codigo, String mensagem) {
            this(codigo + ': ' + mensagem);
            this.codigo = codigo;
        }
    }    

    public class OportunidadeNaoEncontradaException extends OpportunityException {
        public OportunidadeNaoEncontradaException(Boolean voidParam) {
            super('CKV-0001','Oportunidade não encontrada!');
        }
    }

    public class OportunidadeFaseInvalidaException extends OpportunityException {
        public OportunidadeFaseInvalidaException(Boolean voidParam) {
            super('CKV-0002','Fase da Oportunidade Inválida!');
        }
    }

    public class OportunidadeSemProdutosException extends OpportunityException {
        public OportunidadeSemProdutosException(Boolean voidParam) {
            super('CKV-0003','Oportunidade sem Produtos!');
        }
    }

    public class ProdutoInvalidoNaOportunidadeException extends OpportunityException {
        public ProdutoInvalidoNaOportunidadeException(Boolean voidParam) {
            super('CKV-0004','Produto Inválido na Oportunidade!');
        }
    }        

    public class QuantidadeInvalidoException extends OpportunityException {
        public QuantidadeInvalidoException(Boolean voidParam) {
            super('CKV-0008','Quantidade inválida!');
        }
    }        

    public class ContaOportunidadeNaoInformadaException extends OpportunityException {
        public ContaOportunidadeNaoInformadaException(Boolean voidParam) {
            super('CKV-0025','Conta da Oportunidade não informada!');
        }
    }           

    public class ContaDeFaturamentoNaoInformadaException extends OpportunityException {
        public ContaDeFaturamentoNaoInformadaException(Boolean voidParam) {
            super('CKV-0026','Conta da Faturamento não informada!');
        }
    }              
    // #endregion    

}