force-app/main/default/objects/CodigoPromocional__c/CodigoPromocional__c.object-meta.xml
<CustomObject>
    <label>Promoção</label>
    <nameField>
        <label>Código Promocional</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promoções</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CodigoPromocional__c/recordTypes/CodigoPromocional.recordType-meta.xml
<RecordType>
    <fullName>CodigoPromocional</fullName>
    <active>true</active>
    <label>Código Promocional</label>
</RecordType>

force-app/main/default/objects/CodigoPromocional__c/recordTypes/PromocaoParceiro.recordType-meta.xml
<RecordType>
    <fullName>PromocaoParceiro</fullName>
    <active>true</active>
    <label>Promoção Parceiro</label>
</RecordType>

force-app/main/default/objects/ItemPromocao__c/ItemPromocao__c.object-meta.xml
<CustomObject>
    <label>Item da Promoção</label>
    <nameField>
        <displayFormat>ITP-{000000}</displayFormat>
        <label>Item da Promoção</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itens da Promoções</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ItemPromocao__c/fields/Promocao__c.field-meta.xml
<CustomField>
    <fullName>Promocao__c</fullName>
    <label>Promoção</label>
    <referenceTo>CodigoPromocional__c</referenceTo>
    <relationshipLabel>Itens da Promoção</relationshipLabel>
    <relationshipName>ItensPromocoes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ItemPromocao__c/fields/QuantidadeMinima__c.field-meta.xml
<CustomField>
    <fullName>QuantidadeMinima__c</fullName>
    <label>Quantidade Mínima</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CodigoPromocionalSelector.cls
public class CodigoPromocionalSelector extends fflib_SObjectSelector 
implements ICodigoPromocionalSelector  {

    public static ICodigoPromocionalSelector newInstance()
    {
        return (ICodigoPromocionalSelector) Application.Selector.newInstance(CodigoPromocional__c.SObjectType);
    }
    
    public CodigoPromocionalSelector(Boolean includeFieldSetFields)
    {
        super(includeFieldSetFields);
    }
    
    public CodigoPromocionalSelector()
    {
        super(true);
    }
    
    public override List<Schema.FieldSet> getSObjectFieldSetList()
    {
        List<Schema.FieldSet> fieldSets = new List<Schema.FieldSet>();
        
        fieldSets.add(SobjectType.CodigoPromocional__c.FieldSets.ParaCalculoPreco);
        
        return fieldSets;
    }
    
    public List<Schema.SObjectField> getSObjectFieldList()
    {
        return new List<Schema.SObjectField> {
            CodigoPromocional__c.Id
        };
    }
    
    public Schema.SObjectType getSObjectType()
    {
        return CodigoPromocional__c.sObjectType;
    }    

    public List<CodigoPromocional__c> selectById(Set<ID> idSet)
    {
        return (List<CodigoPromocional__c>) selectSObjectsById(idSet);
    }
        
    public CodigoPromocional__c selectByCodigo(String codigoPromocional)
    {
        fflib_QueryFactory query = newQueryFactory();

        query.setCondition('Name = :codigoPromocional And Ativo__c = true And (RecordType.DeveloperName = \'PromocaoParceiro\' OR RecordType.DeveloperName = \'CodigoPromocional\')');

        query.setLimit(1);

        query.subselectQuery('ItensPromocoes__r')
        .selectFieldSet(SobjectType.ItemPromocao__c.FieldSets.SobjectFieldList)
        .setOrdering('QuantidadeMinima__c', fflib_QueryFactory.SortOrder.DESCENDING, true);    

        List<CodigoPromocional__c> codigos = Database.query( query.toSOQL() );

        return codigos.size() > 0 ? codigos[0] : null;         
    }    

    public CodigoPromocional__c selectById(Id codigoPromocionalId)
    {
        fflib_QueryFactory query = newQueryFactory();

        query.setCondition('Id = :codigoPromocionalId And Ativo__c = true');

        query.setLimit(1);

        query.subselectQuery('ItensPromocoes__r')
        .selectFieldSet(SobjectType.ItemPromocao__c.FieldSets.SobjectFieldList)
        .setOrdering('QuantidadeMinima__c', fflib_QueryFactory.SortOrder.DESCENDING, true);    

        List<CodigoPromocional__c> codigos = Database.query( query.toSOQL() );

        return codigos.size() > 0 ? codigos[0] : null;         
    }    


}