force-app/main/default/objects/CodigoPromocional__c/CodigoPromocional__c.object-meta.xml
<CustomObject>
    <label>Promoção</label>
    <nameField>
        <label>Código Promocional</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promoções</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CodigoPromocional__c/recordTypes/CodigoPromocional.recordType-meta.xml
<RecordType>
    <fullName>CodigoPromocional</fullName>
    <active>true</active>
    <label>Código Promocional</label>
</RecordType>

force-app/main/default/objects/ConfiguracaoPacote__c/ConfiguracaoPacote__c.object-meta.xml
<CustomObject>
    <label>Configuração do Pacote</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Configuração do Pacote</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Configurações dos Pacotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ConfiguracaoPacote__c/fields/Empacotado__c.field-meta.xml
<CustomField>
    <fullName>Empacotado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Empacotado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ConfiguracaoPacote__c/fields/Obrigatorio__c.field-meta.xml
<CustomField>
    <fullName>Obrigatorio__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Obrigatório</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ConfiguracaoPacote__c/fields/Posicao__c.field-meta.xml
<CustomField>
    <fullName>Posicao__c</fullName>
    <label>Posição</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConfiguracaoPacote__c/fields/ProdutoPacote__c.field-meta.xml
<CustomField>
    <fullName>ProdutoPacote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto do Pacote</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>ServicosTaxas</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Configurações dos Pacotes</relationshipLabel>
    <relationshipName>Configuracoes_dos_Pacotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ConfiguracaoPacote__c/fields/QuantidadePadrao__c.field-meta.xml
<CustomField>
    <fullName>QuantidadePadrao__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Quantidade Padrão</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConfiguracaoPacote__c/fields/Selecionado__c.field-meta.xml
<CustomField>
    <fullName>Selecionado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Selecionado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RegraDesconto__c/RegraDesconto__c.object-meta.xml
<CustomObject>
    <label>Regra de Desconto</label>
    <nameField>
        <displayFormat>RD-{00000000}</displayFormat>
        <label>Regra de Desconto</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Regras de Descontos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RegraPreco__c/RegraPreco__c.object-meta.xml
<CustomObject>
    <label>Regra de Preço</label>
    <nameField>
        <displayFormat>RP-{0000}</displayFormat>
        <label>Regra de Preço</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Regras de Preços</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RegraProduto__c/RegraProduto__c.object-meta.xml
<CustomObject>
    <label>Regra de Produto</label>
    <nameField>
        <displayFormat>RP-{0000}</displayFormat>
        <label>Regra de Produto</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Regras de Produtos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ServicoDoPacote.cls
public class ServicoDoPacote {

    // #region Definições Internas

    public class ServicoDoPacoteCache {
        public String quem;

        public Id produtoId;
        public Id produtoPaiId;
        public Integer quantidadePai;

        public Id origemId;
        public Id destinoId;
        public Id modeloId;
        public DateTime previsaoDecolagem;

        public Id contaId;

        public Integer quantidade;

        public Boolean porPassageiro;

        public ConfiguracaoPacote__c configuracaoPacote;
        public List<RegraPreco__c> regraPrecos;
        public List<RegraProduto__c> regraProdutos;
        public List<RegraDesconto__c> regraDescontos;
        public CodigoPromocional__c codigoPromocional;
        public Boolean codigoJaUtilizado;
        public Boolean primeiraCompra;        
    }

    // #endregion    

    // #region Variáveis Publicas    

    @AuraEnabled
    public Id produto {get; set;} 

    @AuraEnabled
    public String servico {get; set;} 

    @AuraEnabled    
    public Boolean invalido {get; set;}

    @AuraEnabled    
    public Boolean obrigatorio {get; set;}

    @AuraEnabled        
    public Boolean empacotado {get; set;}

    @AuraEnabled        
    public Boolean porPassageiro {get; set;}

    @AuraEnabled        
    public Boolean selecionado {get; set;}

    @AuraEnabled        
    public Integer posicao {get; set;}
    
    @AuraEnabled        
    public Integer quantidadePadrao {get; set;}

    @AuraEnabled        
    public Double precoUnitario {get; set;}

    @AuraEnabled        
    public Double precoRevoSeats {get; set;}

    @AuraEnabled        
    public Integer quantidade {get; set;}

    @AuraEnabled        
    public Decimal descontoPerc {get; set;}

    @AuraEnabled        
    public Decimal descontoValor {get; set;}

    @AuraEnabled        
    public Double precoFinal {get; set;}    

    @AuraEnabled        
    public Double precoFinalRevoSeats {get; set;}

    @AuraEnabled        
    public Id IdPromocional {get; set;}

    @AuraEnabled        
    public String codigoPromocionalApurado {get; set;}
    
    @AuraEnabled        
    public Boolean promocaoValida {get; set;}

    // #endregion    

    // #region Construtor

    public ServicoDoPacote(ServicoDoPacoteCache parameter) 
    {
        carregaDadosServico(parameter);

        carregaDadosPrecoTrecho(parameter);
    }

    // #endregion    

    // #region Métodos Privados

    private void carregaDadosServico(ServicoDoPacoteCache parameter) {
        this.produto = parameter.produtoId;
        this.servico = parameter.configuracaoPacote.ProdutoPacote__r.Name;
        this.obrigatorio = parameter.configuracaoPacote.Obrigatorio__c;
        this.empacotado = parameter.configuracaoPacote.Empacotado__c;
        this.selecionado = parameter.configuracaoPacote.Selecionado__c;
        this.quantidadePadrao = parameter.configuracaoPacote.QuantidadePadrao__c.intValue();
        this.posicao = parameter.configuracaoPacote.Posicao__c.intValue();
        this.porPassageiro = parameter.porPassageiro;
    }

    private void carregaDadosPrecoTrecho(ServicoDoPacoteCache parameter) {

        CalculaPrecosParaPesquisa.CalculaPrecosParaPesquisaResult result = CalculaPrecosParaPesquisa.calculaPrecosServicos(
            parameter.produtoId, parameter.contaId, parameter.quem, parameter.origemId, parameter.destinoId, parameter.previsaoDecolagem, 
            parameter.modeloId, parameter.quantidade, parameter.regraProdutos, parameter.regraPrecos, parameter.regraDescontos, parameter.codigoPromocional,
            parameter.codigoJaUtilizado, parameter.primeiraCompra, true, true
        );

        this.invalido = result.invalido;

        if (this.invalido) return;

        this.precoUnitario = result.precoUnitario;
        this.precoRevoSeats = result.precoRevoSeats;
        this.descontoPerc = result.descontoPerc;
        this.descontoValor = result.descontoValor;
        this.promocaoValida = result.promocaoValida;
        this.idPromocional = result.idPromocional;
        this.codigoPromocionalApurado = result.codigoPromocionalApurado;
        this.precoFinal = result.precoFinal;
        this.precoFinalRevoSeats = result.precoFinalRevoSeats;

        this.quantidade = parameter.quantidade;
        
        if (this.empacotado) {
            this.precoFinal = 0;
            this.precoFinalRevoSeats = 0;
        }
    }
    
    // #endregion
}