force-app/main/default/objects/Pagamento__c/Pagamento__c.object-meta.xml
<CustomObject>
    <label>Pagamento</label>
    <nameField>
        <displayFormat>PAGTO-{0000000}</displayFormat>
        <label>Pagamento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pagamentos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Pagamento__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pagamentos</relationshipLabel>
    <relationshipName>Pagamentos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Passageiro__c/Passageiro__c.object-meta.xml
<CustomObject>
    <label>Passageiro</label>
    <nameField>
        <displayFormat>P-{000000000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Passageiros</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Passageiro__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contato</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Passageiro não pode ser do tipo Contato, mas sim do tipo Passageiro ou Cliente - Pessoa Física</errorMessage>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Contato</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Passageiros</relationshipLabel>
    <relationshipName>Passageiros</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Protocolo__c/Protocolo__c.object-meta.xml
<CustomObject>
    <label>Protocolo</label>
    <nameField>
        <displayFormat>{MM}{YY}{0000}{DD}</displayFormat>
        <label>Número Protocolo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Protocolos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Protocolo__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Protocolos</relationshipLabel>
    <relationshipName>Protocolos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Protocolo__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contato</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Protocolos</relationshipLabel>
    <relationshipName>Protocolos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Protocolo__c/fields/OrigemProtocolo__c.field-meta.xml
<CustomField>
    <fullName>OrigemProtocolo__c</fullName>
    <label>Origem do Protocolo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>E-mail</fullName>
            </value>
            <value>
                <fullName>Telefone</fullName>
            </value>
            <value>
                <fullName>Whatsapp</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>Bot</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Protocolo__c/fields/OrigemProtocoloMessaging__c.field-meta.xml
<CustomField>
    <fullName>OrigemProtocoloMessaging__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Origem Protocolo de Messaging</label>
    <referenceTo>MessagingSession</referenceTo>
    <relationshipLabel>Protocolos</relationshipLabel>
    <relationshipName>Protocolos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Servico__c/Servico__c.object-meta.xml
<CustomObject>
    <label>Serviço</label>
    <nameField>
        <displayFormat>SERV-{0000000}</displayFormat>
        <label>Serviço</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Serviços</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Servico__c/fields/Passageiro__c.field-meta.xml
<CustomField>
    <fullName>Passageiro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Passageiro</label>
    <referenceTo>Passageiro__c</referenceTo>
    <relationshipLabel>Serviços</relationshipLabel>
    <relationshipName>Servicos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Servico__c/fields/Voo__c.field-meta.xml
<CustomField>
    <fullName>Voo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Voo</label>
    <referenceTo>Voo__c</referenceTo>
    <relationshipLabel>Serviços</relationshipLabel>
    <relationshipName>Servicos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tabulacao__c/Tabulacao__c.object-meta.xml
<CustomObject>
    <label>Tabulação</label>
    <nameField>
        <label>Nome da Tabulação</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tabulações</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tabulacao__c/fields/CodigoAtribuicao__c.field-meta.xml
<CustomField>
    <fullName>CodigoAtribuicao__c</fullName>
    <label>Código de Atribuição</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tabulacao__c/fields/DescricaoCasoPadrao__c.field-meta.xml
<CustomField>
    <fullName>DescricaoCasoPadrao__c</fullName>
    <label>Descrição Caso Padrão</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Tabulacao__c/fields/DireitoPadrao__c.field-meta.xml
<CustomField>
    <fullName>DireitoPadrao__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Direito Padrão</label>
    <referenceTo>Entitlement</referenceTo>
    <relationshipLabel>Tabulações</relationshipLabel>
    <relationshipName>Tabulacoes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tabulacao__c/fields/PrioridadeCasoPadrao__c.field-meta.xml
<CustomField>
    <fullName>PrioridadeCasoPadrao__c</fullName>
    <label>Prioridade Caso Padrão</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alta</fullName>
            </value>
            <value>
                <fullName>Média</fullName>
            </value>
            <value>
                <fullName>Baixa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tabulacao__c/fields/TipoAtribuicao__c.field-meta.xml
<CustomField>
    <fullName>TipoAtribuicao__c</fullName>
    <label>Tipo Atribuição</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Criador do Caso</fullName>
            </value>
            <value>
                <fullName>Fila Salesforce</fullName>
            </value>
            <value>
                <fullName>Regra de Atribuição</fullName>
            </value>
            <value>
                <fullName>Proprietário da Conta</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tabulacao__c/fields/TipoCasoPadrao__c.field-meta.xml
<CustomField>
    <fullName>TipoCasoPadrao__c</fullName>
    <label>Tipo Caso Padrão</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Solicitação</fullName>
            </value>
            <value>
                <fullName>Reclamação</fullName>
            </value>
            <value>
                <fullName>Informação</fullName>
            </value>
            <value>
                <fullName>Elogio</fullName>
            </value>
            <value>
                <fullName>Resolução</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tabulacao__c/recordTypes/FluxoTrabalho.recordType-meta.xml
<RecordType>
    <fullName>FluxoTrabalho</fullName>
    <active>true</active>
    <label>FluxoTrabalho</label>
</RecordType>

force-app/main/default/objects/Voo__c/Voo__c.object-meta.xml
<CustomObject>
    <description>O Voo de uma aeronave, do ponto de origem até o retorno</description>
    <label>Voo</label>
    <nameField>
        <displayFormat>REVO-{00000000}</displayFormat>
        <label>Número do Voo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Voos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CaseDomain.cls
public class CaseDomain extends SObjectDomain {
    protected override Schema.SObjectType getSObjectType() {
        return Case.sObjectType;
    }
    
    protected override Map<Id, Schema.RecordTypeInfo> getRecordTypeInfosById() {
        return Schema.SObjectType.Case.getRecordTypeInfosById();
    }
    
    public CaseDomain() {
    }
    
    public List<Case> newInstance(List<Id> idTabulacoes, List<Id> recordIds, List<Id> lastCaseIds) {
        List<Case> casos = newInstance(idTabulacoes);
        
        List<Id> accountIds = new List<Id>();
        List<Id> contactIds = new List<Id>();
        List<Id> caseIds = new List<Id>();
        List<Id> protocolIds = new List<Id>();
        
        AccountSelector accountSel = new AccountSelector();
        ContactSelector contactSel = new ContactSelector();
        CaseSelector caseSel = new CaseSelector();
        ProtocoloSelector protocoloSel = new ProtocoloSelector();
        
        for (Id recordId : recordIds) {
            String objectType = recordId.getSObjectType().getDescribe().getName();
            
            if (objectType == 'Account') {
                accountIds.add(recordId);
            } else if (objectType == 'Contact') {
                contactIds.add(recordId);
            } else if (objectType == 'Case') {
                caseIds.add(recordId);
            } else if (objectType == 'Protocolo__c') {
                protocolIds.add(recordId);
            }
        }
        
        Map<Id, Account> accounts = new Map<Id, Account>(
            (List<Account>) accountSel.selectIn(accountIds)
        );
        Map<Id, Contact> contacts = new Map<Id, Contact>(
            (List<Contact>) contactSel.selectIn(contactIds)
        );
        Map<Id, Case> cases = new Map<Id, Case>(
            (List<Case>) caseSel.selectIn(caseIds)
        );
        Map<Id, Protocolo__c> protocols = new Map<Id, Protocolo__c>(
            (List<Protocolo__c>) protocoloSel.selectIn(protocolIds)
        );
        Map<Id, Case> lastCases = new Map<Id, Case>(
            (List<Case>) caseSel.selectIn(lastCaseIds)
        );
        
        for (Integer i = 0; i < casos.size(); i++) {
            Case newCase = casos.get(i);
            Id recordId = recordIds.get(i);
            
            String objectType = recordId.getSObjectType().getDescribe().getName();
            
            if (objectType == 'Account') {
                Account account = accounts.get(recordId);
                newCase.AccountId = account.Id;
                newCase.ContactId = account.PersonContactId;
            } else if (objectType == 'Contact') {
                Contact contact = contacts.get(recordId);
                newCase.AccountId = contact.AccountId;
                newCase.ContactId = contact.Id;
            } else if (objectType == 'Case') {
                Case parentCase = cases.get(recordId);
                newCase.AccountId = parentCase.AccountId;
                newCase.ContactId = parentCase.ContactId;
                newCase.ParentId = parentCase.Id;
                newCase.Origin = parentCase.Origin;
                
                Id lastCaseId = lastCaseIds.size() >= i ? lastCaseIds.get(i) : null;

                newCase.casoAnterior__c = lastCaseId;
                
                Case baseCase = null;
                
                if (lastCases.containsKey(lastCaseId)) {
                    baseCase = lastCases.get(lastCaseId);
                } else {
                    baseCase = parentCase;
                }
                
                newCase.Voo__c = baseCase.Voo__c;
                newCase.Passageiro__c = baseCase.Passageiro__c;
                newCase.Servico__c = baseCase.Servico__c;
                newCase.Pagamento__c = baseCase.Pagamento__c;
                
            } else if (objectType == 'Protocolo__c') {
                Protocolo__c protocolo = protocols.get(recordId);
                newCase.AccountId = protocolo.Conta__c;
                newCase.ContactId = protocolo.Contato__c;
                newCase.Protocolo__c = protocolo.Id;
                newCase.Origin = protocolo.OrigemProtocolo__c;
                newCase.SourceId = protocolo.OrigemProtocoloMessaging__c;
            }
        }
        
        return casos;
    }
    
    public List<Case> newInstance(List<Id> idTabulacoes) {
        TabulacaoSelector seletorTabulacao = new TabulacaoSelector();
        Map<Id, Tabulacao__c> tabulacoes = new Map<Id, Tabulacao__c>(
            (List<Tabulacao__c>) seletorTabulacao.selectIn(idTabulacoes)
        );
        List<Case> newCases = new List<Case>();
        
        for (Id idTabulacao : idTabulacoes) {
            Tabulacao__c tabulacao = tabulacoes.get(idTabulacao);
            Case newCase = new Case();
            
            changeInstance(newCase, tabulacao);
            
            newCases.add(newCase);
        }
        
        return newCases;
    }
    
    public void changeInstance(Case newCase, Tabulacao__c tabulacao) {
        newCase.Subject = tabulacao.Name;
        newCase.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName()
            .get(tabulacao.RecordType.DeveloperName)
            .getRecordTypeId();
        newCase.Type = tabulacao.TipoCasoPadrao__c;
        newCase.Priority = tabulacao.PrioridadeCasoPadrao__c;
        newCase.Description = tabulacao.DescricaoCasoPadrao__c;
        newCase.EntitlementId = tabulacao.DireitoPadrao__c;
        newCase.Status = tabulacao.RecordType.DeveloperName == 'FluxoTrabalho'
            ? 'Aberto'
            : 'Em Andamento';
        newCase.Tabulacao__c = tabulacao.Id;
    }
    
    public AssignmentRule standardAssignmentRule() {
        List<AssignmentRule> defaultAr = [
            SELECT id
            FROM AssignmentRule
            WHERE SobjectType = 'Case' AND Active = TRUE
            LIMIT 1
        ];
        return defaultAr.size() > 0 ? defaultAr.get(0) : null;
    }
    
    public void applyAssignmentRule(List<Case> newCases) {

        TabulacaoSelector seletorTabulacao = new TabulacaoSelector();
        AccountSelector seletorContas = new AccountSelector();
        
        Map<Id, Tabulacao__c> tabulacoes = new Map<Id, Tabulacao__c>(
            (List<Tabulacao__c>) seletorTabulacao.selectIn(SObjectSelectorUtil.ExtractIds(newCases, 'Tabulacao__c'))
        );

        Map<Id, Account> contas = new Map<Id, Account>(
            (List<Account>) seletorContas.selectIn(SObjectSelectorUtil.ExtractIds(newCases, 'AccountId'))
        );
        
        List<String> filas = new List<String>();
        
        for (Tabulacao__c tb : tabulacoes.values()) {
            if (tb.TipoAtribuicao__c == 'Fila Salesforce' && !String.IsEmpty(tb.CodigoAtribuicao__c)) 
                filas.add(tb.CodigoAtribuicao__c);
        }
        
        Map<String, List<Group>> filaMap = (Map<String, List<Group>>)SObjectSelectorUtil.BreakByString(
            [Select Id, DeveloperName From Group Where Type = 'Queue' And DeveloperName IN :filas], 'DeveloperName');

        
        AssignmentRule defaultAr = standardAssignmentRule();
        Database.DMLOptions dmlOpts = new Database.DMLOptions();
        
        if (defaultAr != null) {
            dmlOpts.assignmentRuleHeader.assignmentRuleId = defaultAr.Id;
        }
            
        for (Case newCase : newCases) {
            Tabulacao__c tabulacao = tabulacoes.get(newCase.Tabulacao__c);
            
            if (tabulacao.TipoAtribuicao__c == 'Criador do Caso') continue;

            if (tabulacao.TipoAtribuicao__c == 'Fila Salesforce' && 
                !String.IsEmpty(tabulacao.CodigoAtribuicao__c) && 
                filaMap.containskey(tabulacao.CodigoAtribuicao__c)) 
            {
                newCase.OwnerId = filaMap.get(tabulacao.CodigoAtribuicao__c)[0].Id;
            }
            
            if (tabulacao.TipoAtribuicao__c == 'Proprietário da Conta') {
                newCase.OwnerId = contas.get(newCase.AccountId).OwnerId;
            }
            
            if (tabulacao.TipoAtribuicao__c == 'Regra de Atribuição' && 
                defaultAr != null && !String.IsEmpty(tabulacao.CodigoAtribuicao__c)) {
                newCase.setOptions(dmlOpts);
            }
        }
        
    }    
    
    @TestVisible
    protected override void onBeforeInsert() {
        super.onBeforeInsert();
        
        System.debug('context CaseDomain Operation: ' + context.Operation);
        if (context.News != null)
            System.debug('context CaseDomain News: ' + context.News.Size());
        if (context.Olds != null)
            System.debug('context CaseDomain Olds: ' + context.Olds.Size());
    }
    
    @TestVisible
    protected override void onBeforeUpdate() {
        super.onBeforeUpdate();
        
        System.debug('context CaseDomain Operation: ' + context.Operation);
        if (context.News != null)
            System.debug('context CaseDomain News: ' + context.News.Size());
        if (context.Olds != null)
            System.debug('context CaseDomain Olds: ' + context.Olds.Size());
    }
    
    @TestVisible
    protected override void onAfterInsert() {
        super.onAfterInsert();
        
        System.debug('context CaseDomain Operation: ' + context.Operation);
        if (context.News != null)
            System.debug('context CaseDomain News: ' + context.News.Size());
        if (context.Olds != null)
            System.debug('context CaseDomain Olds: ' + context.Olds.Size());
    }
    
    @TestVisible
    protected override void onAfterUpdate() {
        super.onAfterUpdate();
        
        System.debug('context CaseDomain Operation: ' + context.Operation);
        if (context.News != null)
            System.debug('context CaseDomain News: ' + context.News.Size());
        if (context.Olds != null)
            System.debug('context CaseDomain Olds: ' + context.Olds.Size());
    }
}