force-app/main/default/objects/Voo__c/Voo__c.object-meta.xml
<CustomObject>
    <description>O Voo de uma aeronave, do ponto de origem até o retorno</description>
    <label>Voo</label>
    <nameField>
        <displayFormat>REVO-{00000000}</displayFormat>
        <label>Número do Voo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Voos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Voo__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Conta para o faturamento do(s) voo(s)</description>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Voos</relationshipLabel>
    <relationshipName>Voos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Voo__c/fields/QtdTrechos__c.field-meta.xml
<CustomField>
    <fullName>QtdTrechos__c</fullName>
    <label>Quantidade de Trechos</label>
    <summaryForeignKey>Trecho__c.Voo__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Voo__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Define em que momento o voo se encontra</description>
    <inlineHelpText>Define em que momento o voo se encontra</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Rascunho</fullName>
                <default>true</default>
                <label>Rascunho</label>
            </value>
            <value>
                <fullName>Pré-reservado</fullName>
            </value>
            <value>
                <fullName>Reservado</fullName>
            </value>
            <value>
                <fullName>Confirmado</fullName>
            </value>
            <value>
                <fullName>Rota</fullName>
                <label>Em Rota</label>
            </value>
            <value>
                <fullName>LogPendente</fullName>
                <label>Concluindo o Voo</label>
            </value>
            <value>
                <fullName>Executado</fullName>
            </value>
            <value>
                <fullName>Em Faturamento</fullName>
                <isActive>false</isActive>
                <label>Em Faturamento</label>
            </value>
            <value>
                <fullName>Faturado</fullName>
                <isActive>false</isActive>
                <label>Faturado</label>
            </value>
            <value>
                <fullName>Pronto pra Voar</fullName>
                <isActive>false</isActive>
                <label>Pronto pra Voar</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Voo__c/fields/TrechosNaoIniciados__c.field-meta.xml
<CustomField>
    <fullName>TrechosNaoIniciados__c</fullName>
    <description>Indica a quantidade trechos do voo que ainda não foram iniciados e permitem a atualização de dados</description>
    <inlineHelpText>Indica a quantidade trechos do voo que ainda não foram iniciados</inlineHelpText>
    <label>Trechos Não Iniciados</label>
    <summaryFilterItems>
        <field>Trecho__c.Status__c</field>
        <operation>equals</operation>
        <value>Não Iniciado</value>
    </summaryFilterItems>
    <summaryForeignKey>Trecho__c.Voo__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/VooDomain.cls
public class VooDomain 
{
    List<Voo__c> voos;
    //List<SolicitacaoCotacao__c> solicitacoes;
    FINAL String RASCUNHO = 'Rascunho';
    FINAL String RESERVADO = 'Reservado';
    FINAL String CONFIRMADO = 'Confirmado';
    FINAL String EMROTA = 'Em Rota';
    FINAL String EXECUTADO = 'Executado';
    FINAL String EMFATURAMENTO = 'Em Faturamento';
    FINAL String FATURADO = 'Faturado';
    
   /* public VooDomain(SolicitacaoCotacao__c solicitacao)
    {
        solicitacoes = new List<SolicitacaoCotacao__c>();
        solicitacoes.add(solicitacao);
        voos = new List<Voo__c>();
    }*/

    public VooDomain()
    {
        voos = new List<Voo__c>();
    }
        
    /*public void criaVoo(SolicitacaoCotacao__c solicitacao)
    {
        Voo__c voo = new Voo__c();
        voo.Cliente__c = solicitacao.Conta__c;
        voo.SolicitacaoCotacao__c = solicitacao.Id;
        voos.add(voo);
    }*/
    /*
    public SolicitacaoCotacao__c getSolicitacaoUnica()
    {
        return solicitacoes.get(0);
    }*/

    public Boolean checkStatusRascunho(Voo__c voo)
    {
        return voo.Status__c.equals(RASCUNHO);
    }

    public Boolean checkPassageirosCargas(Voo__c voo)
    {        
        return
        (
            (voo.Status__c.equals(RASCUNHO) && voo.QtdTrechos__c > 0) ||
            (
                (
                    voo.Status__c.equals(RESERVADO) ||
                    voo.Status__c.equals(CONFIRMADO)||
                    voo.Status__c.equals(EMROTA)
                ) &&
                voo.TrechosNaoIniciados__c > 0
            )
        );
    }

    public Boolean checkVooNaoGerenciavel(Voo__c voo)
    {
        return
        (
            voo.Status__c.equals(EXECUTADO) ||
            voo.Status__c.equals(EMFATURAMENTO) ||
            voo.Status__c.equals(FATURADO)
        );
    }
}