force-app/main/default/objects/Voo__c/Voo__c.object-meta.xml
<CustomObject>
    <description>O Voo de uma aeronave, do ponto de origem até o retorno</description>
    <label>Voo</label>
    <nameField>
        <displayFormat>REVO-{00000000}</displayFormat>
        <label>Número do Voo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Voos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Voo__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Conta para o faturamento do(s) voo(s)</description>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Voos</relationshipLabel>
    <relationshipName>Voos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Voo__c/fields/DataVoo__c.field-meta.xml
<CustomField>
    <fullName>DataVoo__c</fullName>
    <description>Dia e hora solicitada para a realização do voo</description>
    <inlineHelpText>Dia e hora solicitada para a realização do voo</inlineHelpText>
    <label>Data</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Voo__c/fields/IgnorarTrigger__c.field-meta.xml
<CustomField>
    <fullName>IgnorarTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Caso marcado voo não será utilizado na trigger</description>
    <inlineHelpText>Caso marcado voo não será utilizado na trigger</inlineHelpText>
    <label>Ignorar trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Voo__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Define em que momento o voo se encontra</description>
    <inlineHelpText>Define em que momento o voo se encontra</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Rascunho</fullName>
                <default>true</default>
                <label>Rascunho</label>
            </value>
            <value>
                <fullName>Pré-reservado</fullName>
            </value>
            <value>
                <fullName>Reservado</fullName>
            </value>
            <value>
                <fullName>Confirmado</fullName>
            </value>
            <value>
                <fullName>Rota</fullName>
                <label>Em Rota</label>
            </value>
            <value>
                <fullName>LogPendente</fullName>
                <label>Concluindo o Voo</label>
            </value>
            <value>
                <fullName>Executado</fullName>
            </value>
            <value>
                <fullName>Em Faturamento</fullName>
                <isActive>false</isActive>
                <label>Em Faturamento</label>
            </value>
            <value>
                <fullName>Faturado</fullName>
                <isActive>false</isActive>
                <label>Faturado</label>
            </value>
            <value>
                <fullName>Pronto pra Voar</fullName>
                <isActive>false</isActive>
                <label>Pronto pra Voar</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VooDomainTest.cls
@isTest
private class VooDomainTest {
    @TestSetup
    static void Setup(){
        TestUtil.SetupStandardPricebook();
        TestUtil.insereConfiguracoesPersonalizadas();    
    }

    @isTest
    static void checkStatusRascunhoTest() {
        TestUtil.SetupAccountContactVoo('Fernando', 'test@gmail.com', 'Rascunho');
        Account acc = [SELECT Id, Name FROM Account LIMIT 1];
        Contact contact = [SELECT Id, Name FROM Contact LIMIT 1];
        Voo__c voo = [SELECT Id FROM Voo__c LIMIT 1];

        VooDomain vooDomain = new VooDomain();

        Test.startTest();

        voo = VooService.getVooById(voo.Id);
        Boolean statusRascunho = vooDomain.checkStatusRascunho(voo);
        System.assert(
            statusRascunho && voo.Status__c == 'Rascunho' &&
            voo.DataVoo__c != null && voo.Cliente__c == acc.Id,
            'Algo não correu bem.\nClasse: \'vooDomain\''
            + '\nFunção:\'checkStatusRascunho\'\n'
            + acc + '\n' + contact + '\n' + voo);
        Test.stopTest();
    }
    
    @isTest
    static void checkPassageirosCargasTest()
    {
        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        Voo__c voo = TestUtil2.criarVooRascunho(system.now()+10, false, uow);
        voo.Status__c = 'Reservado';
        voo.IgnorarTrigger__c = true;
        uow.commitWork();

        Test.startTest();
        VooDomain vd = new VooDomain();
        Boolean check = vd.checkPassageirosCargas(voo);
        Test.stopTest();
        system.assertEquals(check, false);
    }

    @isTest
    static void checkPassageirosCargasTest2() {
        TestUtil.SetupAccountContactVooComTrecho('Fernando', 'test@gmail.com', 'Rascunho', 'Não Iniciado');
        Account acc = [SELECT Id, Name FROM Account LIMIT 1];
        Contact contact = [SELECT Id, Name FROM Contact LIMIT 1];
        Voo__c voo = [SELECT Id FROM Voo__c LIMIT 1];

        VooDomain vooDomain = new VooDomain();

        Test.startTest();

        voo = VooService.getVooById(voo.Id);
        Boolean checkPassageirosCargas = vooDomain.checkPassageirosCargas(voo);
        System.assert(
            checkPassageirosCargas && voo.Status__c == 'Rascunho' &&
            voo.DataVoo__c != null && voo.Cliente__c == acc.Id,
            'Algo não correu bem.\nClasse: \'vooDomain\''
            + '\nFunção:\'checkPassageirosCargas\'\n'
            + acc + '\n' + contact + '\n' + voo);
        Test.stopTest();
    }
    
    @isTest
    static void checkVooNaoGerenciavelTest() {
        Test.startTest();
        Voo__c voo = new Voo__c(Status__c='Rascunho');
        VooDomain vooDomain = new VooDomain();
        Boolean checkVooNaoGerenciavel = vooDomain.checkVooNaoGerenciavel(voo);
        System.assert(
            !checkVooNaoGerenciavel, 'Algo não correu bem.\nClasse: \'vooDomain\'' + '\nFunção:\'checkVooNaoGerenciavel\'\n' + voo);
        Test.stopTest();
    }
}