force-app/main/default/objects/PassageiroVoo__c/PassageiroVoo__c.object-meta.xml
<CustomObject>
    <description>Armazena os passageiros de um voo</description>
    <label>Passageiro do Voo</label>
    <nameField>
        <displayFormat>PV-{00}</displayFormat>
        <label>Código do Passageiro do Voo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Passageiros do Voo</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PassageiroVoo__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <description>Contato que será usado para criar um passageiro em um trecho</description>
    <inlineHelpText>Contato que será usado para criar um passageiro em um trecho</inlineHelpText>
    <label>Contato</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Passageiro não pode ser do tipo Contato, mas sim do tipo Passageiro ou Cliente - Pessoa Física</errorMessage>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Contato</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Passageiros do Voo</relationshipLabel>
    <relationshipName>PassageirosVoo</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PassageiroVoo__c/fields/Voo__c.field-meta.xml
<CustomField>
    <fullName>Voo__c</fullName>
    <description>Voo ao qual o contato está vinculado e será registrado como passageiro</description>
    <inlineHelpText>Voo ao qual o contato está vinculado e será registrado como passageiro</inlineHelpText>
    <label>Voo</label>
    <referenceTo>Voo__c</referenceTo>
    <relationshipLabel>Passageiros do Voo</relationshipLabel>
    <relationshipName>PassageirosVoo</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Voo__c/Voo__c.object-meta.xml
<CustomObject>
    <description>O Voo de uma aeronave, do ponto de origem até o retorno</description>
    <label>Voo</label>
    <nameField>
        <displayFormat>REVO-{00000000}</displayFormat>
        <label>Número do Voo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Voos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PassageirosVooSelector.cls
public class PassageirosVooSelector extends fflib_SObjectSelector implements IPassageirosVooSelector
{    
    public List<PassageiroVoo__c> selectByVooId(Set<Id> voosId)
    {
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('Voo__c IN :voosId');
        return (List<PassageiroVoo__c>) Database.query(query.toSOQL());
    }

    public List<Schema.SObjectField> getSObjectFieldList()
	{
		return new List<Schema.SObjectField> {
				PassageiroVoo__c.Id,
                PassageiroVoo__c.Voo__c,
                PassageiroVoo__c.Contato__c
		};
	}              
    
    public Schema.SObjectType getSObjectType()
    {
        return PassageiroVoo__c.sObjectType;
    }
    
    public PassageirosVooSelector()
    {
        super(true);
    }
    
    public override List<Schema.FieldSet> getSObjectFieldSetList()
    {
        return new List<Schema.FieldSet>	
        {	SobjectType.PassageiroVoo__c.FieldSets.SelectFieldList	};
    }
    
    public static IPassageirosVooSelector newInstance()
    {
        return (IPassageirosVooSelector) Application.Selector.newInstance(PassageiroVoo__c.SObjectType);
    }
}