force-app/main/default/objects/PassageiroVoo__c/PassageiroVoo__c.object-meta.xml
<CustomObject>
    <description>Armazena os passageiros de um voo</description>
    <label>Passageiro do Voo</label>
    <nameField>
        <displayFormat>PV-{00}</displayFormat>
        <label>Código do Passageiro do Voo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Passageiros do Voo</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PassageiroVoo__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <description>Contato que será usado para criar um passageiro em um trecho</description>
    <inlineHelpText>Contato que será usado para criar um passageiro em um trecho</inlineHelpText>
    <label>Contato</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Passageiro não pode ser do tipo Contato, mas sim do tipo Passageiro ou Cliente - Pessoa Física</errorMessage>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Contato</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Passageiros do Voo</relationshipLabel>
    <relationshipName>PassageirosVoo</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PassageiroVoo__c/fields/Voo__c.field-meta.xml
<CustomField>
    <fullName>Voo__c</fullName>
    <description>Voo ao qual o contato está vinculado e será registrado como passageiro</description>
    <inlineHelpText>Voo ao qual o contato está vinculado e será registrado como passageiro</inlineHelpText>
    <label>Voo</label>
    <referenceTo>Voo__c</referenceTo>
    <relationshipLabel>Passageiros do Voo</relationshipLabel>
    <relationshipName>PassageirosVoo</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Voo__c/Voo__c.object-meta.xml
<CustomObject>
    <description>O Voo de uma aeronave, do ponto de origem até o retorno</description>
    <label>Voo</label>
    <nameField>
        <displayFormat>REVO-{00000000}</displayFormat>
        <label>Número do Voo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Voos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PassageirosVooServiceTest.cls
@IsTest
public class PassageirosVooServiceTest {
    
    @isTest
	public static void getPassageirosVooTest()
    {
        Id standardPricebookId = TestUtil.SetupStandardPricebook();
        TestUtil.insereConfiguracoesPersonalizadas();
        TestUtil.create1Voo2Locais2Trechos2Passageiros();
        List<Contact> contatos = [SELECT Id FROM Contact];
        List<Voo__c> voo = [SELECT Id FROM Voo__c];
        PassageiroVoo__c passageiro = new PassageiroVoo__c(Contato__c = contatos.get(0).Id, Voo__c = voo.get(0).Id);
        insert passageiro;
        
        Test.startTest();
        String serviceResult = PassageirosVooService.getPassageirosVoo(voo.get(0).Id);
        system.assert(serviceResult.length() > 0);
        Test.stopTest();
        //inserir conta
        ////inserir voo
        //inserir contato
        //inserir passageiros voo
    }
}