force-app/main/default/objects/FaixaRegraDesconto__c/FaixaRegraDesconto__c.object-meta.xml
<CustomObject>
    <label>Faixa Regra de Desconto</label>
    <nameField>
        <displayFormat>FRD-{0000}</displayFormat>
        <label>Faixa Regra de Desconto</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Faixas Regras de Desconto</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FaixaRegraDesconto__c/fields/Desconto__c.field-meta.xml
<CustomField>
    <fullName>Desconto__c</fullName>
    <label>% Desconto</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/FaixaRegraDesconto__c/fields/FaixaFinal__c.field-meta.xml
<CustomField>
    <fullName>FaixaFinal__c</fullName>
    <inlineHelpText>Por Quantidade</inlineHelpText>
    <label>Faixa Final</label>
    <precision>15</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FaixaRegraDesconto__c/fields/FaixaInicial__c.field-meta.xml
<CustomField>
    <fullName>FaixaInicial__c</fullName>
    <inlineHelpText>Por Quantidade</inlineHelpText>
    <label>Faixa Inicial</label>
    <precision>15</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FaixaRegraDesconto__c/fields/RegraDesconto__c.field-meta.xml
<CustomField>
    <fullName>RegraDesconto__c</fullName>
    <label>Regra de Desconto</label>
    <referenceTo>RegraDesconto__c</referenceTo>
    <relationshipLabel>Faixas Regras de Desconto</relationshipLabel>
    <relationshipName>Faixas_Regras_de_Desconto</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RegraDesconto__c/RegraDesconto__c.object-meta.xml
<CustomObject>
    <label>Regra de Desconto</label>
    <nameField>
        <displayFormat>RD-{00000000}</displayFormat>
        <label>Regra de Desconto</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Regras de Descontos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RegraDesconto__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Regras de Descontos</relationshipLabel>
    <relationshipName>Regras_de_Descontos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RegraDesconto__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fixo</fullName>
            </value>
            <value>
                <fullName>Faixa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RegraDesconto__c/fields/ValorDesconto__c.field-meta.xml
<CustomField>
    <fullName>ValorDesconto__c</fullName>
    <label>Valor Desconto Unitário</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/RegraDesconto.cls
public class RegraDesconto extends fflib_SObjectDomain {

    public RegraDesconto(List<RegraDesconto__c> sObjectList)
	{
		super(sObjectList);
	}
    
    public class Constructor implements fflib_SObjectDomain.IConstructable
	{
		public fflib_SObjectDomain construct(List<SObject> sObjectList)
		{
			return new RegraDesconto(sObjectList);
		}
	}

    public class RegraDescontoResult {
        public Decimal descontoPercMax {get; set;}
        public Decimal descontoValorMax {get; set;}

        public RegraDescontoResult() {
            this.descontoPercMax = 0;
            this.descontoValorMax = 0;
        }
    }

    public class MelhorDescontoResult {
        public Decimal descontoPerc {get; set;}
        public Decimal descontoValor {get; set;}
        public Decimal melhorValorSimulado {get; set;}

        public MelhorDescontoResult() {
            this.descontoPerc = 0;
            this.descontoValor = 0;
            this.melhorValorSimulado = 0;
        }
    }    

    public static RegraDescontoResult encontraRegraDesconto(List<RegraDesconto__c> regras, DateTime previsaoDecolagem, String quem, Id contaId, Decimal quantidade) {

        RegraDescontoResult selecionado = new RegraDescontoResult();

        Decimal descontoPercMax = 0;
        Decimal descontoValorMax = 0;

        if (regras.isEmpty()) {
            return selecionado;
        } 

        for (RegraDesconto__c regra : regras) {
            if (!regra.Ativo__c) {
                continue;
            }

            if ((regra.DataInicial__c > previsaoDecolagem.date()) 
            || (regra.DataFinal__c < previsaoDecolagem.date())) {
                continue;
            }

            if (regra.Conta__c != null && regra.Conta__c != contaId) {
                continue;
            }

            if (regra.Tipo__c == 'Fixo') {

                if (regra.Desconto__c > 0) {
                    descontoPercMax = descontoPercMax < regra.Desconto__c ? regra.Desconto__c : descontoPercMax;
                } else {
                    descontoValorMax = descontoValorMax < regra.ValorDesconto__c ? regra.ValorDesconto__c : descontoValorMax;
                }

            } else if (regra.Tipo__c == 'Faixa') {
                if (regra.Faixas_Regras_de_Desconto__r == null) continue;

                for (FaixaRegraDesconto__c faixa : regra.Faixas_Regras_de_Desconto__r) {
                    
                    if ((faixa.FaixaInicial__c > quantidade) 
                    || (faixa.FaixaFinal__c < quantidade) ) {
                        continue;
                    }

                    if (faixa.Desconto__c > 0) {
                        descontoPercMax = descontoPercMax < faixa.Desconto__c ? faixa.Desconto__c : descontoPercMax;
                    } else {
                        descontoValorMax = descontoValorMax < faixa.ValorDesconto__c ? faixa.ValorDesconto__c : descontoValorMax;
                    }
                }
            }
        }

        selecionado.descontoPercMax = descontoPercMax;
        selecionado.descontoValorMax = descontoValorMax;

        return selecionado;
    }

    public static MelhorDescontoResult qualMelhorDesconto(RegraDescontoResult base, Decimal quantidade, Decimal precoUnitario) {
        MelhorDescontoResult result = new MelhorDescontoResult();

        result.melhorValorSimulado = precoUnitario * (base.descontoPercMax / 100);

        if (result.melhorValorSimulado >= base.descontoValorMax) {
            result.descontoPerc = base.descontoPercMax;
            result.descontoValor = 0;
        } else {
            result.descontoPerc = 0;
            result.descontoValor = base.descontoValorMax;
            result.melhorValorSimulado = base.descontoValorMax;
        }

        return result;
    }


}