force-app/main/default/objects/FaixaRegraDesconto__c/FaixaRegraDesconto__c.object-meta.xml
<CustomObject>
    <label>Faixa Regra de Desconto</label>
    <nameField>
        <displayFormat>FRD-{0000}</displayFormat>
        <label>Faixa Regra de Desconto</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Faixas Regras de Desconto</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FaixaRegraDesconto__c/fields/RegraDesconto__c.field-meta.xml
<CustomField>
    <fullName>RegraDesconto__c</fullName>
    <label>Regra de Desconto</label>
    <referenceTo>RegraDesconto__c</referenceTo>
    <relationshipLabel>Faixas Regras de Desconto</relationshipLabel>
    <relationshipName>Faixas_Regras_de_Desconto</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RegraDesconto__c/RegraDesconto__c.object-meta.xml
<CustomObject>
    <label>Regra de Desconto</label>
    <nameField>
        <displayFormat>RD-{00000000}</displayFormat>
        <label>Regra de Desconto</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Regras de Descontos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RegraDesconto__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Regras de Descontos</relationshipLabel>
    <relationshipName>Regras_de_Descontos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RegraDescontoSelector.cls
public class RegraDescontoSelector extends fflib_SObjectSelector 
    implements IRegraDescontoSelector {
    
        public static IRegraDescontoSelector newInstance()
        {
            return (IRegraDescontoSelector) Application.Selector.newInstance(RegraDesconto__c.SObjectType);
        }
        
        public RegraDescontoSelector(Boolean includeFieldSetFields)
        {
            super(includeFieldSetFields);
        }
        
        public RegraDescontoSelector()
        {
            super(true);
        }
        
        public override List<Schema.FieldSet> getSObjectFieldSetList()
        {
            List<Schema.FieldSet> fieldSets = new List<Schema.FieldSet>();
            
            fieldSets.add(SobjectType.RegraDesconto__c.FieldSets.ParaCalculoPreco);
            
            return fieldSets;
        }
        
        public List<Schema.SObjectField> getSObjectFieldList()
        {
            return new List<Schema.SObjectField> {
                RegraDesconto__c.Id
            };
        }
        
        public Schema.SObjectType getSObjectType()
        {
            return RegraDesconto__c.sObjectType;
        }    
    
        public Map<Id, List<RegraDesconto__c>> selectByIdProducts(Set<ID> idProducts) 
        {
            fflib_QueryFactory query = newQueryFactory();
    
            query.setCondition('Produto__c IN :idProducts');
            
            fflib_QueryFactory subquery = query.subselectQuery('Faixas_Regras_de_Desconto__r')
            .selectFieldSet(SobjectType.FaixaRegraDesconto__c.FieldSets.SobjectFieldList);

            List<RegraDesconto__c> regras = Database.query( query.toSOQL() );
    
            Map<Id, List<RegraDesconto__c>> result = new Map<Id, List<RegraDesconto__c>>();
    
            for (RegraDesconto__c regra : regras) {
                
                if (!result.containsKey(regra.Produto__c)) {
                    result.put(regra.Produto__c, new List<RegraDesconto__c>());
                }
    
                result.get(regra.Produto__c).add(regra);
            }
    
            return result; 
        }    
    }