force-app/main/default/objects/PassageiroOportunidade__c/PassageiroOportunidade__c.object-meta.xml
<CustomObject>
    <label>Passageiro da Oportunidade</label>
    <nameField>
        <displayFormat>PASS-{0000000}</displayFormat>
        <label>Passageiro da Oportunidade</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Passageiros da Oportunidade</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ProdutoPassageiro__c/ProdutoPassageiro__c.object-meta.xml
<CustomObject>
    <label>Produto do Passageiro</label>
    <nameField>
        <displayFormat>PPO-{0000000}</displayFormat>
        <label>Produto do Passageiro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Produtos do Passageiro</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProdutoPassageiro__c/fields/PassageiroOportunidade__c.field-meta.xml
<CustomField>
    <fullName>PassageiroOportunidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Passageiro da Oportunidade</label>
    <referenceTo>PassageiroOportunidade__c</referenceTo>
    <relationshipLabel>Produtos do Passageiro</relationshipLabel>
    <relationshipName>ProdutosPassageiro</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PassageiroOportunidades.cls
public without sharing class PassageiroOportunidades  extends fflib_SObjectDomain {

    public PassageiroOportunidades(List<PassageiroOportunidade__c> sObjectList)
    {
        super(sObjectList);
    }    

    public class Constructor implements fflib_SObjectDomain.IConstructable
    {
        public fflib_SObjectDomain construct(List<SObject> sObjectList)
        {
            return new PassageiroOportunidades(sObjectList);
        }
    }

    public override void onBeforeDelete()
    {
        fflib_SObjectDomain.getTriggerEvent(ProdutoPassageiros.class).disableAfterDelete();

        System.debug(this.ExistingRecords.keyset());

        List<ProdutoPassageiro__c> outros = [Select Id From ProdutoPassageiro__c Where PassageiroOportunidade__c IN :this.ExistingRecords.keyset()];
        
        System.debug(outros);

        if (!outros.isEmpty()) {
            delete outros;
        }
    }    

}