force-app/main/default/objects/LogVoo__c/LogVoo__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar inforamações oriundas do Skytrac</description>
    <label>Log de Voo</label>
    <nameField>
        <displayFormat>LV-{00000000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs de Voos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LogVoo__c/fields/Local__c.field-meta.xml
<CustomField>
    <fullName>Local__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Local</label>
    <referenceTo>Local__c</referenceTo>
    <relationshipLabel>Logs de Voos</relationshipLabel>
    <relationshipName>LogsVoos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LogVoo__c/fields/Trecho__c.field-meta.xml
<CustomField>
    <fullName>Trecho__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trecho</label>
    <referenceTo>Trecho__c</referenceTo>
    <relationshipLabel>Logs de Voos</relationshipLabel>
    <relationshipName>LogsVoos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LogVoo__c/fields/Voo__c.field-meta.xml
<CustomField>
    <fullName>Voo__c</fullName>
    <label>Voo</label>
    <referenceTo>Voo__c</referenceTo>
    <relationshipLabel>Logs de Voos</relationshipLabel>
    <relationshipName>LogsVoos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Trecho__c/Trecho__c.object-meta.xml
<CustomObject>
    <description>Define um trecho com origem e destino dentro de um Voo</description>
    <label>Trecho</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Código do Trecho</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trechos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trecho__c/fields/AgendarAtraso__c.field-meta.xml
<CustomField>
    <fullName>AgendarAtraso__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo auxiliar para lidar com a alteração de agendamento</description>
    <inlineHelpText>Campo auxiliar para lidar com a alteração de agendamento</inlineHelpText>
    <label>Agendar atraso</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trecho__c/fields/CoordenadasDestinoAlteracao__c.field-meta.xml
<CustomField>
    <fullName>CoordenadasDestinoAlteracao__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo utilizado para controlar quando uma solicitação de alteração de coordenadas for feita</description>
    <inlineHelpText>Campo utilizado para controlar quando uma solicitação de alteração de coordenadas for feita</inlineHelpText>
    <label>Coordenadas Destino - Alteração</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trecho__c/fields/CoordenadasLatitudeDestinoDecimal__c.field-meta.xml
<CustomField>
    <fullName>CoordenadasLatitudeDestinoDecimal__c</fullName>
    <formula>IF(
				CoordenadasDestinoAlteracao__c,
				IF(
								ISPICKVAL(CoordenadasLatitudeDestinoDirecao__c, &apos;S&apos;),
								-1 * (CoordenadasLatitudeDestinoGraus__c + ((CoordenadasLatitudeDestinoMinutos__c / 60) + (CoordenadasLatitudeDestinoSegundos__c / 3600))),
								(CoordenadasLatitudeDestinoGraus__c + ((CoordenadasLatitudeDestinoMinutos__c / 60) + (CoordenadasLatitudeDestinoSegundos__c / 3600)))
				),
				Destino__r.Coordenadas__Latitude__s 
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Coordenadas Latitude Destino - Decimal</label>
    <precision>18</precision>
    <scale>18</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trecho__c/fields/CoordenadasLatitudeOrigemDecimal__c.field-meta.xml
<CustomField>
    <fullName>CoordenadasLatitudeOrigemDecimal__c</fullName>
    <formula>IF(
				CoordenadasOrigemAlteracao__c,
				IF(
								ISPICKVAL(CoordenadasLatitudeOrigemDirecao__c, &apos;S&apos;),
								-1 * (CoordenadasLatitudeOrigemGraus__c + ((CoordenadasLatitudeOrigemMinutos__c / 60) + (CoordenadasLatitudeOrigemSegundos__c / 3600))),
								(CoordenadasLatitudeOrigemGraus__c + ((CoordenadasLatitudeOrigemMinutos__c / 60) + (CoordenadasLatitudeOrigemSegundos__c / 3600)))
				), 
			 Origem__r.Coordenadas__Latitude__s 	
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Coordenadas Latitude Origem - Decimal</label>
    <precision>18</precision>
    <scale>18</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trecho__c/fields/CoordenadasLongitudeDestinoDecimal__c.field-meta.xml
<CustomField>
    <fullName>CoordenadasLongitudeDestinoDecimal__c</fullName>
    <formula>IF(
				CoordenadasDestinoAlteracao__c,
				IF( 
								ISPICKVAL(CoordenadasLongitudeDestinoDirecao__c, &apos;O&apos;),
								-1 * (CoordenadasLongitudeDestinoGraus__c + ((CoordenadasLongitudeDestinoMinutos__c / 60) + (CoordenadasLongitudeDestinoSegundos__c / 3600))),
								(CoordenadasLongitudeDestinoGraus__c + ((CoordenadasLongitudeDestinoMinutos__c / 60) + (CoordenadasLongitudeDestinoSegundos__c / 3600)))
				),
			 Destino__r.Coordenadas__Longitude__s 	
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Coordenadas Longitude Destino - Decimal</label>
    <precision>18</precision>
    <scale>18</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trecho__c/fields/CoordenadasLongitudeOrigemDecimal__c.field-meta.xml
<CustomField>
    <fullName>CoordenadasLongitudeOrigemDecimal__c</fullName>
    <formula>IF(
				CoordenadasOrigemAlteracao__c,
				IF(
								ISPICKVAL(CoordenadasLongitudeOrigemDirecao__c, &apos;O&apos;),
								-1 * (CoordenadasLongitudeOrigemGraus__c + ((CoordenadasLongitudeOrigemMinutos__c / 60) + (CoordenadasLongitudeOrigemSegundos__c / 3600))),
								(CoordenadasLongitudeOrigemGraus__c + ((CoordenadasLongitudeOrigemMinutos__c / 60) + (CoordenadasLongitudeOrigemSegundos__c / 3600)))
				),
				Origem__r.Coordenadas__Longitude__s 
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Coordenadas Longitude Origem - Decimal</label>
    <precision>18</precision>
    <scale>18</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trecho__c/fields/CoordenadasOrigemAlteracao__c.field-meta.xml
<CustomField>
    <fullName>CoordenadasOrigemAlteracao__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo utilizado para controlar quando uma solicitação de alteração de coordenadas for feita</description>
    <inlineHelpText>Campo utilizado para controlar quando uma solicitação de alteração de coordenadas for feita</inlineHelpText>
    <label>Coordenadas Origem - Alteração</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trecho__c/fields/DataAtrasoDecolagem__c.field-meta.xml
<CustomField>
    <fullName>DataAtrasoDecolagem__c</fullName>
    <description>Momento em que o trecho é considerado atrasado.</description>
    <formula>PrevisaoDecolagem__c + ($Setup.ConfiguracaoTempo__c.TempoMaximoAtrasoTrecho__c )/1440</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Momento em que o trecho é considerado atrasado.</inlineHelpText>
    <label>Data de atraso da decolagem</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Trecho__c/fields/DataAtualizacaoAtraso__c.field-meta.xml
<CustomField>
    <fullName>DataAtualizacaoAtraso__c</fullName>
    <description>Data de atualização do campo de atraso.</description>
    <formula>PrevisaoDecolagem__c + (60 + $Setup.ConfiguracaoTempo__c.TempoMaximoAtrasoTrecho__c )/1440</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Data de atualização do campo de atraso.</inlineHelpText>
    <label>Data de atualização atraso</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Trecho__c/fields/Decolagem__c.field-meta.xml
<CustomField>
    <fullName>Decolagem__c</fullName>
    <label>Decolagem</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Trecho__c/fields/Destino__c.field-meta.xml
<CustomField>
    <fullName>Destino__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Local de destino do trecho</description>
    <inlineHelpText>Local de destino do trecho</inlineHelpText>
    <label>Destino</label>
    <referenceTo>Local__c</referenceTo>
    <relationshipLabel>Trechos (Destino)</relationshipLabel>
    <relationshipName>TrechosDestino</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trecho__c/fields/DisponibilidadePeso__c.field-meta.xml
<CustomField>
    <fullName>DisponibilidadePeso__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Disponibilidade de peso calculado pelo Cálculo de Missão Result</description>
    <inlineHelpText>Disponibilidade de peso calculado pelo Cálculo de Missão Result</inlineHelpText>
    <label>Disponibilidade de Peso</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trecho__c/fields/Origem__c.field-meta.xml
<CustomField>
    <fullName>Origem__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Local de origem do trecho</description>
    <inlineHelpText>Local de origem do trecho</inlineHelpText>
    <label>Origem</label>
    <referenceTo>Local__c</referenceTo>
    <relationshipLabel>Trechos (Origem)</relationshipLabel>
    <relationshipName>TrechosOrigem</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trecho__c/fields/PousoTrechoAnterior__c.field-meta.xml
<CustomField>
    <fullName>PousoTrechoAnterior__c</fullName>
    <label>Pouso do trecho anterior</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Trecho__c/fields/PrevisaoDecolagem__c.field-meta.xml
<CustomField>
    <fullName>PrevisaoDecolagem__c</fullName>
    <label>Previsão de Decolagem do Voo</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Trecho__c/fields/PrimeiroTrechoFixo__c.field-meta.xml
<CustomField>
    <fullName>PrimeiroTrechoFixo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primeiro Trecho Fixo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trecho__c/fields/TempoCruzeiro__c.field-meta.xml
<CustomField>
    <fullName>TempoCruzeiro__c</fullName>
    <description>Tempo de cruzeiro para o trecho</description>
    <inlineHelpText>Tempo de cruzeiro para o trecho</inlineHelpText>
    <label>Tempo de cruzeiro</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trecho__c/fields/TempoDecorrido__c.field-meta.xml
<CustomField>
    <fullName>TempoDecorrido__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Tempo decorrido do Voo até esse Trecho</description>
    <inlineHelpText>Tempo decorrido do Voo até esse Trecho</inlineHelpText>
    <label>Tempo Decorrido</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trecho__c/fields/TempoMissao__c.field-meta.xml
<CustomField>
    <fullName>TempoMissao__c</fullName>
    <description>Tempo de missão para o trecho</description>
    <inlineHelpText>Tempo de missão para o trecho</inlineHelpText>
    <label>Tempo de missão</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trecho__c/fields/TempoSolo__c.field-meta.xml
<CustomField>
    <fullName>TempoSolo__c</fullName>
    <description>Tempo de solo para o trecho</description>
    <inlineHelpText>Tempo de solo para o trecho</inlineHelpText>
    <label>Tempo de solo</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trecho__c/fields/TipoHoraFaturamento__c.field-meta.xml
<CustomField>
    <fullName>TipoHoraFaturamento__c</fullName>
    <label>Tipo de hora de Faturamento</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Acionamento-Corte</fullName>
            </value>
            <value>
                <fullName>Decolagem-Pouso Integral</fullName>
            </value>
            <value>
                <fullName>Decolagem-Pouso Navegação</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trecho__c/fields/TrechoAnterior__c.field-meta.xml
<CustomField>
    <fullName>TrechoAnterior__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Referência ao trecho anterior</description>
    <inlineHelpText>Referência ao trecho anterior</inlineHelpText>
    <label>Trecho Anterior</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Voo__c</field>
            <operation>equals</operation>
            <valueField>$Source.Voo__c</valueField>
        </filterItems>
        <infoMessage>Só pode ser Trecho Anterior outro do mesmo voo</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Trecho__c</referenceTo>
    <relationshipLabel>Trechos</relationshipLabel>
    <relationshipName>TrechoAnterior</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trecho__c/fields/Voo__c.field-meta.xml
<CustomField>
    <fullName>Voo__c</fullName>
    <description>Voo ao qual o trecho pertence</description>
    <inlineHelpText>Voo ao qual o trecho pertence</inlineHelpText>
    <label>Voo</label>
    <referenceTo>Voo__c</referenceTo>
    <relationshipLabel>Trechos</relationshipLabel>
    <relationshipName>Trechos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Voo__c/Voo__c.object-meta.xml
<CustomObject>
    <description>O Voo de uma aeronave, do ponto de origem até o retorno</description>
    <label>Voo</label>
    <nameField>
        <displayFormat>REVO-{00000000}</displayFormat>
        <label>Número do Voo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Voos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Voo__c/fields/Decolagem__c.field-meta.xml
<CustomField>
    <fullName>Decolagem__c</fullName>
    <description>Hora de decolagem da aeronave</description>
    <inlineHelpText>Hora de decolagem da aeronave</inlineHelpText>
    <label>Decolagem</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Voo__c/fields/TempoMissao__c.field-meta.xml
<CustomField>
    <fullName>TempoMissao__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Tempo de missão do voo</description>
    <inlineHelpText>Tempo de missão do voo</inlineHelpText>
    <label>Tempo de Missão</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Trechos.cls
public with sharing class Trechos extends fflib_SObjectDomain
implements ITrechos
{
    List<Trecho__c> trechos = new List<Trecho__c>();
    
    public static FINAL String OFFSHORE = 'Offshore';
    public static FINAL String NAOINICIADO = 'Não Iniciado';
    public static FINAL String CHECKINFECHADO = 'Check In Fechado';
    public static FINAL String EMROTA = 'Em Rota';
    public static FINAL String FINALIZADO = 'Finalizado';
    public static FINAL String TRANSLADO = 'Translado';
    Boolean primeiroTrechoRegistered = false;
    
    public static FINAL Set<Schema.SObjectField> FIELDS_IGNORE = new Set<Schema.SObjectField>{
        Trecho__c.AgendarAtraso__c,
        Trecho__c.SystemModstamp,
        Trecho__c.LastModifiedDate,
        Trecho__c.TempoSolo__c,
        Trecho__c.TempoCruzeiro__c,
        Trecho__c.TempoMissao__c,
        Trecho__c.TempoDecorrido__c,
        Trecho__c.PrevisaoDecolagem__c,
        Trecho__c.DisponibilidadePeso__c,
        Trecho__c.DataAtualizacaoAtraso__c,
        Trecho__c.DataAtrasoDecolagem__c,
        Trecho__c.TrechoAnterior__c,
        Trecho__c.PousoTrechoAnterior__c,
        Trecho__c.TipoHoraFaturamento__c,
        Trecho__c.PrimeiroTrechoFixo__c
    };
    
    public Trechos(List<Trecho__c> sObjectList)
    {
        super(sObjectList);

        Configuration.disableTriggerCRUDSecurity();
    }
    
    public static ITrechos newInstance(List<Trecho__c> sObjectList)
    {
        return (ITrechos) Application.Domain.newInstance(sObjectList);
    }
    
    public class Constructor implements fflib_SObjectDomain.IConstructable
    {
        public fflib_SObjectDomain construct(List<SObject> sObjectList)
        {
            return new Trechos(sObjectList);
        }
    }
    
    public List<Local__c> getTrajeto()
    {
        List<Local__c> trajeto = new List<Local__c>();
        List<Trecho__c> trechos = (List<Trecho__c>)records;
        
        if(trechos != null && trechos.size() > 0){
            Integer i = 0;
            Local__c local = new Local__c(Id=trechos.get(i).Origem__c);
            if (trechos.get(i).CoordenadasOrigemAlteracao__c)
            {
                local.Coordenadas__Latitude__s = trechos.get(i).CoordenadasLatitudeOrigemDecimal__c;
                local.Coordenadas__Longitude__s = trechos.get(i).CoordenadasLongitudeOrigemDecimal__c;
            }
            trajeto.add(local);
            do
            { 
                local = new Local__c(Id=trechos.get(i).Destino__c);
                if (trechos.get(i).CoordenadasDestinoAlteracao__c)
                {
                    local.Coordenadas__Latitude__s = trechos.get(i).CoordenadasLatitudeDestinoDecimal__c;
                    local.Coordenadas__Longitude__s = trechos.get(i).CoordenadasLongitudeDestinoDecimal__c;
                }
                trajeto.add(local);            
                i++;
            }
            while (i < trechos.size());
        }
        
        return trajeto;        
    } 
    
    public override void onAfterInsert()
    {       
        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        List<Voo__c> voos = VoosSelector.newInstance().selectWithTrechosById(Utils.getSetIds(records, 'Voo__c'));
        
        Map<Id, Voo__c> voosMap = new Map<Id, Voo__c>(voos);
        Map<Id, Voo__c> voosEditados = new Map<Id, Voo__c>();
        Set<Id> voosId = new Set<Id>();
        
        for (Voo__c voo : voos)
        {
            voosId.add(voo.Id);
        }
        if(!System.isBatch() && !System.isFuture())
        {
            atualizaTempoVoado(voosId);
        }
        //geraRotaEmVoo(uow, new Map<Id,SObject>(), voosMap, voosEditados);
        //uow.registerDirty(voosEditados.values());
        //uow.commitWork();
        //integraStar();
    }
    
    
    public override void onAfterDelete()
    {
        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        List<Voo__c> voos = VoosSelector.newInstance().selectWithTrechosById(Utils.getSetIds(records, 'Voo__c'));
        Map<Id, Voo__c> voosMap = new Map<Id, Voo__c>(voos);
        Map<Id, Voo__c> voosEditados = new Map<Id, Voo__c>();
        Set<Id> voosId = new Set<Id>();

        for (Voo__c voo : voos)
        {
            voosId.add(voo.Id);
        }
        if(!System.isBatch() && !System.isFuture())
        {
            atualizaTempoVoado(voosId);
       }
    }
    
    public Boolean ignorarTriggerUpdate()
    {
        SObjectType accountType = Schema.getGlobalDescribe().get('Trecho__c');
        Map<String,Schema.SObjectField> mfields = accountType.getDescribe().fields.getMap();
        for(Integer i = 0; i < Trigger.new.size(); i++)
        {
            Trecho__c novoTrecho = (Trecho__c)Trigger.new[i];
            Trecho__c oldTrecho = (Trecho__c)Trigger.old[i];
            for(String key : mfields.keyset())
            {
                Schema.SObjectField field = mfields.get(key);
                if(novoTrecho.get(field) != oldTrecho.get(Field) && !FIELDS_IGNORE.contains(field))
                {
                    return false;
                }
            }
        }
        return true;
    }
    @future
    public static void atualizaTempoVoado (Set<Id> voosId){
        Try{    
            Map<Id, Voo__c> vooToUpdate = new Map<Id, Voo__c>();
                                 
            for (AggregateResult result : [SELECT Voo__c, SUM(TempoVoado__c) total 
                                            FROM Trecho__c 
                                            WHERE Voo__c = :voosId 
                                            GROUP BY Voo__c]) {                  
                    Id vooId = (Id)result.get('Voo__c');
                    Decimal totalHorasVoadas = (Decimal)result.get('total');                    
                    if(vooToUpdate.containsKey(vooId)) {
                        vooToUpdate.get(vooId).TotalHorasVoadas__c = totalHorasVoadas; 
                    }else{
                        vooToUpdate.put(vooId, new Voo__c(Id=vooId, TotalHorasVoadas__c=totalHorasVoadas));
                    }
                }                
                if (!vooToUpdate.isEmpty()) {
                    update vooToUpdate.values();
                }            
            }
        Catch (Exception e){
            System.debug('Erro inesperado' + e.getMessage());
            throw new TrechosException('Erro inesperado' + e.getMessage());
        }
    }
    
    public override void onAfterUpdate(Map<Id,SObject> existingRecords)
    {
        integrarSigTripEOOS(existingRecords, records);
        if(!ignorarTriggerUpdate())
        {
            fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();        
            List<Voo__c> voos = VoosSelector.newInstance().selectWithTrechosById(Utils.getSetIds(existingRecords.values(), 'Voo__c'));
            Map<Id, Voo__c> voosMap = new Map<Id, Voo__c>(voos);
            Map<Id, Voo__c> voosEditados = new Map<Id, Voo__c>();
                     
            Set<Id> voosId = Utils.getSetIds(existingRecords.values(), 'Voo__c');
            if(!System.isBatch() && !System.isFuture())
            {
                atualizaTempoVoado(voosId);
            }
            
            //geraRotaEmVoo(uow, existingRecords, voosMap, voosEditados);
            //uow.registerDirty(voosEditados.values());
            //uow.commitWork();
            
        }
    }
    
    private Trecho__c updateTrecho(Trecho__c trecho, LogVoo__c log, Schema.SObjectField field)
    {
        Object value = getValueByField(field, log, trecho);
        //Caso retorne valor, passou nas validações e seta no trecho
        if (value != null)
        {
            trecho.put(field, value);
            return trecho;
        }  
        return null;
    }
    
    @testVisible
    private Boolean existsFieldAndValueIsBlankOrNull(Trecho__c trecho, Schema.SObjectField field)
    {
        //se existe regra para esse tipo de log e o valor nesse campo do trecho está vazio
        return field != null && trecho.get(field) == null;
    }
    

    //TODO: Renato, dá pra criar uma factory aqui e fazer algo do tipo
    //Factory.newInstance(field).checkCoordenadas
    //Sem tempo de fazer isso agora... vai ficar assim mesmo
    @testVisible
    private Object getValueByField(Schema.SObjectField field, LogVoo__c log, Trecho__c trecho)
    {
        Decimal latitude;
        Decimal longitude;
        //Se for decolagem
        if (field == Trecho__c.Decolagem__c 
            || field == Trecho__c.Ligado__c)
        {
            //Utiliza coordenadas de origem pra saber se bate
            latitude = trecho.CoordenadasLatitudeOrigemDecimal__c;
            longitude = trecho.CoordenadasLongitudeOrigemDecimal__c;
        }        
        //Se for pouso
        else if (field == Trecho__c.Pouso__c 
                 || field == Trecho__c.Cut__c)
        {
            //Utiliza coordenadas de destino pra saber se bate
            latitude = trecho.CoordenadasLatitudeDestinoDecimal__c;
            longitude = trecho.CoordenadasLongitudeDestinoDecimal__c;
        }
        
        return 
            checkCoordenadas(log.Latitude__c, log.Longitude__c, latitude, longitude) ?
            log.PosnTimeDatetime__c : null;
    } 
    

    //Função que verifica se o raio entre o local analisado e o ponto do log é próximo o suficiente para ser considerado
    @testVisible
    private Boolean checkCoordenadas(Decimal latitude, Decimal longitude, Decimal latitude2, Decimal longitude2)
    {
        Location loc = Location.newInstance(latitude, longitude);
        Location loc2 = Location.newInstance(latitude2, longitude2);
        
        return raioConsiderado(loc, loc2);
    } 

    @testVisible
    private Boolean raioConsiderado(Location loc, Location loc2)
    {
        if (loc.latitude == null || loc.longitude == null || loc2.latitude == null || loc2.longitude == null)
        {
            return false;
        }
        
        Double raioLogTrecho = Location.getDistance(loc, loc2, 'km') / Locais.DIVISOR;
        return raioLogTrecho <= Locais.RAIOCONSIDERADO;
    }
    
    
    public override void onBeforeInsert()
    {
        Map<Id, Local__c> mapOrigens = new Map<Id, Local__c>(LocaisSelector.newInstance().selectById(Utils.getSetIds(records, 'Origem__c')));
        handleOnBeforeInsert(mapOrigens);
    }
    
    public override void onBeforeUpdate(Map<Id, sObject> existingRecords)
    {
        SObjectType trechoType = Schema.getGlobalDescribe().get('Trecho__c');
        Map<String,Schema.SObjectField> mfields = trechoType.getDescribe().fields.getMap();        
        List<Voo__c> voosList = VoosSelector.newInstance().selectWithTrechosById(Utils.getSetIds(existingRecords.values(), 'Voo__c'));
        for(Voo__c voo: voosList)
        {
            for(Integer i = 0; i < voo.Trechos__r.size(); i++)    
            {
                Trecho__c trechoSelect = voo.Trechos__r[i];
                system.debug('entrou update');
                if(Trigger.newMap.containsKey(trechoSelect.Id))
                {
                    Trecho__c trechoUpdate = (Trecho__c)Trigger.newMap.get(trechoSelect.Id);
                    Trecho__c trechoAntigo = (Trecho__c)Trigger.oldMap.get(trechoSelect.Id);
                    if((trechoUpdate.Cut__c != null && trechoUpdate.Pouso__c == null  && trechoUpdate.Decolagem__c != null) || trechoUpdate.Pouso__c > trechoUpdate.Cut__c)
                    {
                        trechoUpdate.Cut__c = null;
                    }
                    if(i > 0 && trechoUpdate.Ligado__c != null && trechoUpdate.Ligado__c != trechoAntigo.Ligado__c)
                    {
                        Trecho__c trechoAnterior = voo.Trechos__r[i-1];
                        if(Trigger.newMap.containsKey(trechoAnterior.Id))
                        {
                            trechoAnterior = (Trecho__c) Trigger.newMap.get(trechoAnterior.Id);
                        }
                        if(trechoAnterior.Cut__c == null || trechoAnterior.Cut__c > trechoUpdate.Ligado__c)
                        {
                            trechoUpdate.Ligado__c = null;
                        }
                    }
                }                
            }
        }
        
        for(Integer i = 0; i < Trigger.new.size(); i++)
        {
            Trecho__c novoTrecho = (Trecho__c)Trigger.new[i];
            Trecho__c trechoAntigo = (Trecho__c)Trigger.old[i];
            for(String key : mfields.keyset())
            {
                Schema.SObjectField field = mfields.get(key);
                if(field == Trecho__c.PrevisaoDecolagem__c && novoTrecho.get(field) != trechoAntigo.get(Field)){
                    novoTrecho.AgendarAtraso__c = !novoTrecho.AgendarAtraso__c;
                }
                if(field == Trecho__c.Origem__c && novoTrecho.get(field) != trechoAntigo.get(Field))
                {
                    Map<Id, Local__c> mapOrigens = new Map<Id, Local__c>(LocaisSelector.newInstance().selectById(Utils.getSetIds(records, 'Origem__c')));
                    handleOnBeforeUpdate(mapOrigens, existingRecords);
                }
                if(field == Trecho__c.Status__c && novoTrecho.get(field) != trechoAntigo.get(Field) && deveVoltarStatus(novoTrecho, trechoAntigo))
                {
                    novoTrecho.Status__c = trechoAntigo.Status__c;
                }                
            }
            //Solicitação de não gravar segundos em trecho
            novoTrecho.Ligado__c = novoTrecho.Ligado__c != null? novoTrecho.Ligado__c.addSeconds(-1*novoTrecho.Ligado__c.second()) : null;
            novoTrecho.Decolagem__c = novoTrecho.Decolagem__c != null? novoTrecho.Decolagem__c.addSeconds(-1*novoTrecho.Decolagem__c.second()) : null;
            novoTrecho.Pouso__c = novoTrecho.Pouso__c != null? novoTrecho.Pouso__c.addSeconds(-1*novoTrecho.Pouso__c.second()) : null;
            novoTrecho.Cut__c = novoTrecho.Cut__c != null? novoTrecho.Cut__c.addSeconds(-1*novoTrecho.Cut__c.second()) : null;
            
        }
       
    }
    
    
    private Boolean deveVoltarStatus(Trecho__c novoTrecho, Trecho__c trechoAntigo)
    {
        Boolean finalizadoParaEmRota = novoTrecho.Status__c == EMROTA && trechoAntigo.Status__c == FINALIZADO;
        Boolean finalizadoParaCheckIn = novoTrecho.Status__c == CHECKINFECHADO && trechoAntigo.Status__c == FINALIZADO;
        Boolean emRotaParaCheckIn = novoTrecho.Status__c == CHECKINFECHADO && trechoAntigo.Status__c == EMROTA;
        return finalizadoParaEmRota || finalizadoParaCheckIn || emRotaParaCheckIn;
    }
    
    private void handleOnBeforeUpdate(Map<Id, Local__c> mapOrigens, Map<Id, sObject> existingRecords)
    {
        for (Trecho__c trecho : (List<Trecho__c>)records)
        {
            Trecho__c oldTrecho = (Trecho__c)existingRecords.get(trecho.Id);
            if (!trecho.Origem__c.equals(oldTrecho.Origem__c))
            {
                trecho.Offshore__c = isOffshore(mapOrigens.get(trecho.Origem__c));
                if (trecho.Offshore__c == null)
                {
                    //TODO: Renato e Fernando: Setar erro bonitinho
                    trecho.Origem__c.addError('Origem inexistente');
                }                  
            }
        }
    }
    
    @testVisible
    private Boolean isOffshore(Local__c local)
    {
        if (local == null)
        {
            return null;
        }
        
        return local.Tipo__c.equals(OFFSHORE);
    }
    
    private void handleOnBeforeInsert(Map<Id, Local__c> mapOrigens)
    {
        Map<Id,Voo__c> mapVoos = new Map<Id,Voo__c>(VoosSelector.newInstance().selectById(Utils.getSetIds(records, 'Voo__c')));
        for (Trecho__c trecho : (List<Trecho__c>)records)
        {
            trecho.Offshore__c = isOffshore(mapOrigens.get(trecho.Origem__c));
            if (trecho.Offshore__c == null)
            {
                //TODO: Renato e Fernando: Setar erro bonitinho
                trecho.Origem__c.addError('Origem inexistente');
            }
            //Solicitação de não gravar segundos em trecho
            trecho.Ligado__c = trecho.Ligado__c != null? trecho.Ligado__c.addSeconds(-1*trecho.Ligado__c.second()) : null;
            trecho.Decolagem__c = trecho.Decolagem__c != null? trecho.Decolagem__c.addSeconds(-1*trecho.Decolagem__c.second()) : null;
            trecho.Pouso__c = trecho.Pouso__c != null? trecho.Pouso__c.addSeconds(-1*trecho.Pouso__c.second()) : null;
            trecho.Cut__c = trecho.Cut__c != null? trecho.Cut__c.addSeconds(-1*trecho.Cut__c.second()) : null;
            gerenciarTipo(trecho, mapVoos);
        }
    }
    private void integrarSigTripEOOS(Map<Id,SObject> trechosOld, List<Trecho__c> trechos){

        System.debug('>>>>entrou em Trechos.integrarSigTripEOOS');
        Set<Id> voosIds = new Set<Id>();
        Set<Id> voosIdsOOS = new Set<Id>();
        for(Trecho__c trecho:trechos) { 
            Trecho__c trechoOld = (Trecho__c) trechosOld.get(trecho.Id);
            if((!URL.getCurrentRequestUrl().getPath().toLowerCase().contains('/services/data/v')
                || System.Test.isRunningTest())
                    && trecho.IdExternoSigTrip__c <> null
                    && trechoOld.IdExternoSigTrip__c == trecho.IdExternoSigTrip__c
                    && (trechoOld.Ligado__c <> trecho.Ligado__c 
                        || trechoOld.Decolagem__c <> trecho.Decolagem__c
                        || trechoOld.Pouso__c <> trecho.Pouso__c
                        || trechoOld.Cut__c <> trecho.Cut__c                  
                        )
                    ) {                                     
                    if(trecho.processandoSIG__c){
                        Map<String, Object> params = new Map<String, Object>();
                        params.put('vooId', trecho.Voo__c);
                        //Flow.Interview.AguardarSIG myFlow = new Flow.Interview.AguardarSIG(params);
                        //myFlow.start(); TODO, NÃO IMPORTADO O FLOW NA REVO
                        system.debug('AguardarSIG startado');
                    }else{
                        voosIds.add(trecho.Voo__c);
                    }
                }

                if ( trecho.IdExternoOOSVoo__c <> null
                    && trechoOld.IdExternoOOSVoo__c == trecho.IdExternoOOSVoo__c
                    && (
                        trechoOld.Ligado__c <> trecho.Ligado__c 
                        || trechoOld.Decolagem__c <> trecho.Decolagem__c
                        || trechoOld.Pouso__c <> trecho.Pouso__c
                        || trechoOld.Cut__c <> trecho.Cut__c
                        )
                    ) {
                    voosIdsOOS.add(trecho.Voo__c);
              }
        }
        //if(voosIds.size() > 0) System.enqueueJob(new SigtripIntegrarVooOriginSF(voosIds));
        //if(voosIdsOOS.size() > 0) System.enqueueJob(new OOSIntegrarVooOriginSF(voosIdsOOS));  
    }

    private void gerenciarTipo(Trecho__c trecho, Map<Id,Voo__c> mapVoos)
    {
        system.debug('trecho.Tipo__c: ' + trecho.Tipo__c);
        system.debug('mapVoos.get(trecho.Voo__c)?.Tipo__c: ' + mapVoos.get(trecho.Voo__c)?.Tipo__c);
        if(trecho.Tipo__c == null)
        {
            trecho.Tipo__c = mapVoos.get(trecho.Voo__c)?.Tipo__c;
        }
    }
    
    private class TrechosException extends Exception {}
    
    
}