force-app/main/default/objects/ConfiguracaoTempo__c/ConfiguracaoTempo__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Configurações de Tempo</label>
</CustomObject>

force-app/main/default/objects/ConfiguracaoTempo__c/fields/EntreVoosCharterPos__c.field-meta.xml
<CustomField>
    <fullName>EntreVoosCharterPos__c</fullName>
    <inlineHelpText>Número inteiro que representa em minutos o tempo mínimo para que aquela aeronave esteja pronta para efetuar um novo voo</inlineHelpText>
    <label>Entre Voos - Charter (Pós)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConfiguracaoTempo__c/fields/EntreVoosCharterPre__c.field-meta.xml
<CustomField>
    <fullName>EntreVoosCharterPre__c</fullName>
    <inlineHelpText>Número inteiro que representa o tempo em minutos mínimo para que a aeronave esteja pronta para efetuar um voo</inlineHelpText>
    <label>Entre Voos - Charter (Pré)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConfiguracaoTempo__c/fields/EntreVoosFullCabinPos__c.field-meta.xml
<CustomField>
    <fullName>EntreVoosFullCabinPos__c</fullName>
    <inlineHelpText>Número inteiro que representa em minutos o tempo mínimo para que aquela aeronave esteja pronta para efetuar um novo voo</inlineHelpText>
    <label>Entre Voos - FullCabin (Pós)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConfiguracaoTempo__c/fields/EntreVoosFullCabinPre__c.field-meta.xml
<CustomField>
    <fullName>EntreVoosFullCabinPre__c</fullName>
    <inlineHelpText>Número inteiro que representa o tempo em minutos mínimo para que a aeronave esteja pronta para efetuar um voo</inlineHelpText>
    <label>Entre Voos - FullCabin (Pré)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConfiguracaoTempo__c/fields/TempoPlanejamentoPos__c.field-meta.xml
<CustomField>
    <fullName>TempoPlanejamentoPos__c</fullName>
    <inlineHelpText>Número inteiro que representa em minutos o tempo mínimo para que aquela aeronave esteja pronta para efetuar um novo voo</inlineHelpText>
    <label>Entre Voos - ShuttleSeat (Pós)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConfiguracaoTempo__c/fields/TempoPlanejamentoPre__c.field-meta.xml
<CustomField>
    <fullName>TempoPlanejamentoPre__c</fullName>
    <inlineHelpText>Número inteiro que representa o tempo em minutos mínimo para que a aeronave esteja pronta para efetuar um voo</inlineHelpText>
    <label>Entre Voos - ShuttleSeat (Pré)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ConfiguracaoTempoSelector.cls
public with sharing class ConfiguracaoTempoSelector {
  
    public ConfiguracaoTempo getEntrevoosPorTipoVoo(String tipo) {
        ConfiguracaoTempo configuracaoTempo = new ConfiguracaoTempo();

        if(tipo == 'Charter') {
            configuracaoTempo.entreVoosPre = Integer.valueOf(ConfiguracaoTempo__c.getOrgDefaults().EntreVoosCharterPre__c ?? 0);
            configuracaoTempo.entreVoosPos = Integer.valueOf(ConfiguracaoTempo__c.getOrgDefaults().EntreVoosCharterPos__c ?? 0);
        } else if(tipo == 'FullCabin') {
            configuracaoTempo.entreVoosPre = Integer.valueOf(ConfiguracaoTempo__c.getOrgDefaults().EntreVoosFullCabinPre__c ?? 0);
            configuracaoTempo.entreVoosPos = Integer.valueOf(ConfiguracaoTempo__c.getOrgDefaults().EntreVoosFullCabinPos__c ?? 0);
        }else{
            configuracaoTempo.entreVoosPre = Integer.valueOf(ConfiguracaoTempo__c.getOrgDefaults().TempoPlanejamentoPre__c ?? 0);
            configuracaoTempo.entreVoosPos = Integer.valueOf(ConfiguracaoTempo__c.getOrgDefaults().TempoPlanejamentoPos__c ?? 0);
        }

        return configuracaoTempo;
    } 
    
    public ConfiguracaoTempo getEntrevoosByMaxAndMinTime() {
        ConfiguracaoTempo configuracaoTempo = new ConfiguracaoTempo();
        
        // Obter os valores dos campos de configuração
        ConfiguracaoTempo__c config = ConfiguracaoTempo__c.getOrgDefaults();
        
        // Calcular o maior valor para entreVoosPre
        Integer entreVoosCharterPre = Integer.valueOf(config.EntreVoosCharterPre__c ?? 0);
        Integer entreVoosFullCabinPre = Integer.valueOf(config.EntreVoosFullCabinPre__c ?? 0);
        Integer tempoPlanejamentoPre = Integer.valueOf(config.TempoPlanejamentoPre__c ?? 0);
        
        configuracaoTempo.entreVoosPre = Math.max(Math.max(entreVoosCharterPre, entreVoosFullCabinPre), tempoPlanejamentoPre);
        
        // Calcular o maior valor para entreVoosPos
        Integer entreVoosCharterPos = Integer.valueOf(config.EntreVoosCharterPos__c ?? 0);
        Integer entreVoosFullCabinPos = Integer.valueOf(config.EntreVoosFullCabinPos__c ?? 0);
        Integer tempoPlanejamentoPos = Integer.valueOf(config.TempoPlanejamentoPos__c ?? 0);
        
        configuracaoTempo.entreVoosPos = Math.max(Math.max(entreVoosCharterPos, entreVoosFullCabinPos), tempoPlanejamentoPos);

        return configuracaoTempo;
    }
    
    public class ConfiguracaoTempo {
        public Integer entreVoosPre { get; set; }
        public Integer entreVoosPos { get; set; }
    }
}