force-app/main/default/objects/RegraProduto__c/RegraProduto__c.object-meta.xml
<CustomObject>
    <label>Regra de Produto</label>
    <nameField>
        <displayFormat>RP-{0000}</displayFormat>
        <label>Regra de Produto</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Regras de Produtos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RegraProduto__c/fields/Acao__c.field-meta.xml
<CustomField>
    <fullName>Acao__c</fullName>
    <label>Ação</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Permitir</fullName>
            </value>
            <value>
                <fullName>Restringir</fullName>
            </value>
            <value>
                <fullName>RestringirNumeroAssentos</fullName>
                <label>Restringir Número de Assentos</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RegraProduto__c/fields/DisponivelPara__c.field-meta.xml
<CustomField>
    <fullName>DisponivelPara__c</fullName>
    <label>Disponível Para</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cliente</fullName>
            </value>
            <value>
                <fullName>Parceiro</fullName>
            </value>
            <value>
                <fullName>Concierge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RegraProduto__c/fields/LocalDestino__c.field-meta.xml
<CustomField>
    <fullName>LocalDestino__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Local Destino</label>
    <referenceTo>Local__c</referenceTo>
    <relationshipLabel>Regras de Produtos (Local Destino)</relationshipLabel>
    <relationshipName>RegrasProdutos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RegraProduto__c/fields/LocalOrigem__c.field-meta.xml
<CustomField>
    <fullName>LocalOrigem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Local Origem</label>
    <referenceTo>Local__c</referenceTo>
    <relationshipLabel>Regras de Produtos</relationshipLabel>
    <relationshipName>Regras_de_Produtos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RegraProduto__c/fields/NumeroAssentos__c.field-meta.xml
<CustomField>
    <fullName>NumeroAssentos__c</fullName>
    <description>Limita o Número de Assentos que serão disponibilizados para o Voo</description>
    <label>Número de Assentos</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/RegraProduto.cls
public class RegraProduto extends fflib_SObjectDomain {

    public RegraProduto(List<RegraProduto__c> sObjectList)
	{
		super(sObjectList);
	}
    
    public class Constructor implements fflib_SObjectDomain.IConstructable
	{
		public fflib_SObjectDomain construct(List<SObject> sObjectList)
		{
			return new RegraProduto(sObjectList);
		}
	}

    public static RegraProdutoResult trechoValidoParaServico(Id origemId, Id destinoId, DateTime previsaoDecolagem, String quem, List<RegraProduto__c> regras) {
        return trechoValido(true, origemId, destinoId, previsaoDecolagem, quem, regras);
    }

    public static RegraProdutoResult trechoValidoParaVoo(DateTime previsaoDecolagem, String quem, List<RegraProduto__c> regras) {
        return trechoValido(false, null, null, previsaoDecolagem, quem, regras);
    }
    
    public static RegraProdutoResult trechoValido(Boolean servicoValidaLocal, Id origemId, Id destinoId, DateTime previsaoDecolagem, String quem, List<RegraProduto__c> regras) {

        Boolean produtoValido = false;
        Boolean permissaoRestrita = false;

        Long diferencaMinutos = (previsaoDecolagem.getTime() - Datetime.now().getTime()) / (1000 * 60);

        if (regras.isEmpty()) return new RegraProdutoResult(true);

        for (RegraProduto__c regraPositiva : regras) {
            if (!regraPositiva.Ativo__c) continue;
            if (regraPositiva.Acao__c != 'Permitir') continue;

            permissaoRestrita = true;

            if (servicoValidaLocal) { 
                if (RegraProduto.localTrechoInvalido(regraPositiva, origemId, destinoId)) {
                    continue;
                } 
            }

            if (!regraPositiva.DisponivelPara__c.contains(quem)) {
                continue;
            }

            if (RegraProduto.horaTrechoPositiva(regraPositiva, previsaoDecolagem)) {
                continue;
            }
            
            produtoValido = true;
        }
        
        if (!produtoValido && permissaoRestrita) {
            return new RegraProdutoResult(false);
        }

        produtoValido = true;

        for (RegraProduto__c regraNegativa : regras) {
            if (!regraNegativa.Ativo__c) continue;
            if (regraNegativa.Acao__c != 'Restringir') continue;

            if (servicoValidaLocal) {             
                if (RegraProduto.localTrechoInvalido(regraNegativa, origemId, destinoId)) {
                    continue;
                }
            }

            if (!regraNegativa.DisponivelPara__c.contains(quem)) {
                continue;
            }

            if (RegraProduto.horaTrechoNegativa(regraNegativa, previsaoDecolagem)) {
                produtoValido = false;
            }

            if (regraNegativa.MinutosAntecedencia__c > diferencaMinutos) {
                produtoValido = false;
            }
        }
        //SETA REGRAS COM PARAMETROS FIXOS
        RegraProdutoResult regraProdutoResult = new RegraProdutoResult(produtoValido);

        for (RegraProduto__c regraNegativa : regras) {

            if (!regraNegativa.Ativo__c) continue;
            if (regraNegativa.Acao__c != 'RestringirNumeroAssentos') continue;

            if (servicoValidaLocal) {             
                if (RegraProduto.localTrechoInvalido(regraNegativa, origemId, destinoId)) {
                    continue;
                }
            }

            if (!regraNegativa.DisponivelPara__c.contains(quem)) {
                continue;
            }
            
            if (RegraProduto.horaTrechoNegativa(regraNegativa, previsaoDecolagem)) {
                regraProdutoResult.numeroAssentos = regraNegativa.NumeroAssentos__c.intValue();
            }

            if (regraNegativa.MinutosAntecedencia__c > diferencaMinutos) {
                regraProdutoResult.numeroAssentos = regraNegativa.NumeroAssentos__c.intValue();
            }
        }        

        return regraProdutoResult;
    }
    

    private static Boolean horaTrechoPositiva(RegraProduto__c regra, DateTime previsaoDecolagem) {
        return (regra.HorarioInicial__c > previsaoDecolagem.time())
            || (regra.HorarioFinal__c < previsaoDecolagem.time());
    }

    private static Boolean horaTrechoNegativa(RegraProduto__c regra, DateTime previsaoDecolagem) {
        return (regra.HorarioInicial__c <= previsaoDecolagem.time())
            && (regra.HorarioFinal__c >= previsaoDecolagem.time());
    }

    private static Boolean localTrechoInvalido(RegraProduto__c regra, Id origemId, Id destinoId) {
        return (regra.LocalOrigem__c != null && regra.LocalOrigem__c != origemId)
            || (regra.LocalDestino__c != null && regra.LocalDestino__c != destinoId);
    }

    public class RegraProdutoResult {
        public RegraProdutoResult(Boolean valido) {
            this.valido = valido;
        }

        public Boolean valido;
        public Integer numeroAssentos;
    }
}