force-app/main/default/objects/Passageiro__c/Passageiro__c.object-meta.xml
<CustomObject>
    <label>Passageiro</label>
    <nameField>
        <displayFormat>P-{000000000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Passageiros</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Passageiro__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contato</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Passageiro não pode ser do tipo Contato, mas sim do tipo Passageiro ou Cliente - Pessoa Física</errorMessage>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Contato</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Passageiros</relationshipLabel>
    <relationshipName>Passageiros</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Passageiro__c/fields/TipoDocumento__c.field-meta.xml
<CustomField>
    <fullName>TipoDocumento__c</fullName>
    <label>Tipo do documento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TipoDocumento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Passageiro__c/fields/Trecho__c.field-meta.xml
<CustomField>
    <fullName>Trecho__c</fullName>
    <label>Trecho</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Trecho__c.Status__c</field>
            <operation>equals</operation>
            <value>Não Iniciado</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Trecho__c</referenceTo>
    <relationshipLabel>Passageiros</relationshipLabel>
    <relationshipName>Passageiros</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Trecho__c/Trecho__c.object-meta.xml
<CustomObject>
    <description>Define um trecho com origem e destino dentro de um Voo</description>
    <label>Trecho</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Código do Trecho</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trechos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trecho__c/fields/Voo__c.field-meta.xml
<CustomField>
    <fullName>Voo__c</fullName>
    <description>Voo ao qual o trecho pertence</description>
    <inlineHelpText>Voo ao qual o trecho pertence</inlineHelpText>
    <label>Voo</label>
    <referenceTo>Voo__c</referenceTo>
    <relationshipLabel>Trechos</relationshipLabel>
    <relationshipName>Trechos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Voo__c/Voo__c.object-meta.xml
<CustomObject>
    <description>O Voo de uma aeronave, do ponto de origem até o retorno</description>
    <label>Voo</label>
    <nameField>
        <displayFormat>REVO-{00000000}</displayFormat>
        <label>Número do Voo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Voos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Voo__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Conta para o faturamento do(s) voo(s)</description>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Voos</relationshipLabel>
    <relationshipName>Voos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/TipoDocumento.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>RG</fullName>
    </customValue>
    <customValue>
        <fullName>CPF</fullName>
    </customValue>
    <customValue>
        <fullName>CNPJ</fullName>
    </customValue>
    <customValue>
        <fullName>CNH</fullName>
    </customValue>
    <customValue>
        <fullName>RNE</fullName>
    </customValue>
    <customValue>
        <fullName>Passaporte</fullName>
    </customValue>
    <masterLabel>Tipo de Documento</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ContatosSelector.cls
public class ContatosSelector extends fflib_SObjectSelector implements IContatosSelector
{    
    public ContatosSelector(Boolean includeFieldSetFields)
    {
        super(includeFieldSetFields);
    }
    
    public ContatosSelector()
    {
        super(true);
    }
    
    public override List<Schema.FieldSet> getSObjectFieldSetList()
    {
        return new List<Schema.FieldSet>	
        {	SobjectType.Contact.FieldSets.SelectFieldList	};
    }
    
    public static IContatosSelector newInstance()
    {
        return (IContatosSelector) Application.Selector.newInstance(Contact.SObjectType);
    }

    public List<Schema.SObjectField> getSObjectFieldList()
	{
		return new List<Schema.SObjectField> {
				Contact.Id,
				Contact.LastName,
                Contact.Email,
                Contact.Idioma__c,
                Contact.FirstName,
                Contact.Nacionalidade__c,
                Contact.NumeroDocumento__c,
                Contact.Name,
                Contact.PossuiInteresse__c,
                Contact.Account.Name,
                Contact.TakeoffReport__c
		};
	}                  
    
    public Schema.SObjectType getSObjectType()
    {
        return Contact.sObjectType;
    }
    
    public List<Contact> selectById(Set<ID> idSet)
    {
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('Id IN :idSet');
        //query.selectFieldSet(SObjectType.Contact.fieldSets.SelectFieldList);
        return (List<Contact>) Database.query(query.toSOQL());
    }
    
    public List<Contact> selectContatosByVooId(Set<Id> voosId)
    {
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('AccountId in (SELECT Cliente__c FROM Voo__c WHERE Id in :voosId)');
        return (List<Contact>) Database.query(query.toSOQL());
    }
    
    public List<Contact> selectNaoInclusos(
        Set<Id> contatosId,
        String filtro
    ) {

        String passageiroRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Passageiro').getRecordTypeId();
        String clientePFRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('ClientePF').getRecordTypeId();
        
        // Cria a QueryFactory com seu comportamento padrão (fields, ORDER BY padrão, etc.)
        fflib_QueryFactory query = newQueryFactory();

        // Monta o filtro dinâmico com curingas, evitando SOQL Injection
        if (String.isNotBlank(filtro)) {
            String filtroLike = '%' + String.escapeSingleQuotes(filtro) + '%';
            query.setCondition(
                '(RecordTypeId = :passageiroRecordTypeId OR Account.RecordTypeId = :clientePFRecordTypeId) ' +
                'AND Id NOT IN :contatosId ' +
                'AND (NumeroDocumento__c LIKE :filtroLike ' +
                '     OR Name               LIKE :filtroLike)'
            );
        } else {
            query.setCondition('(RecordTypeId = :passageiroRecordTypeId OR Account.RecordTypeId = :clientePFRecordTypeId) AND Id NOT IN :contatosId');
        }

        // Ordena pelo CreatedDate em ordem decrescente
        query.setOrdering('CreatedDate', fflib_QueryFactory.SortOrder.ASCENDING);
        query.setLimit(50);

        // Executa o SOQL dinâmico; os binds :contatosId e :filtroLike são resolvidos
        return (List<Contact>) Database.query(query.toSOQL());
    }

    public List<Contact> selectInteresseDailyReportFromAccounts(Set<Id> accountsId)
    {
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('AccountId IN :accountsId AND DailyOperationsReport__c = true');        
        return (List<Contact>) Database.query(query.toSOQL());
    }
    
    public List<Contact> selectContactsByDocuments(Set<String> tipoDocumentos, Set<String> documentos) {
        fflib_QueryFactory query = newQueryFactory();

        query.setCondition('TipoDocumento__c IN :tipoDocumentos AND NumeroDocumento__c IN :documentos');
        
        return (List<Contact>) Database.query(query.toSOQL());        
    }

    /*
    public List<Contact> selectContatosNaoInclusos(Set<Id> voosId)
    {
        fflib_QueryFactory query = newQueryFactory();
        //query.setCondition('Id NOT IN (SELECT Contato__c FROM Passageiro__c WHERE Trecho__r.Voo__c IN :voosId)');
        query.setLimit(20);
        
        return (List<Contact>) Database.query(query.toSOQL());
    }
*/
    
}