force-app/main/default/objects/Passageiro__c/Passageiro__c.object-meta.xml
<CustomObject>
    <label>Passageiro</label>
    <nameField>
        <displayFormat>P-{000000000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Passageiros</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Passageiro__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contato</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Passageiro não pode ser do tipo Contato, mas sim do tipo Passageiro ou Cliente - Pessoa Física</errorMessage>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Contato</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Passageiros</relationshipLabel>
    <relationshipName>Passageiros</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Passageiro__c/fields/Excluido__c.field-meta.xml
<CustomField>
    <fullName>Excluido__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cancelado?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PassageiroVoo__c/PassageiroVoo__c.object-meta.xml
<CustomObject>
    <description>Armazena os passageiros de um voo</description>
    <label>Passageiro do Voo</label>
    <nameField>
        <displayFormat>PV-{00}</displayFormat>
        <label>Código do Passageiro do Voo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Passageiros do Voo</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PassageiroVoo__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <description>Contato que será usado para criar um passageiro em um trecho</description>
    <inlineHelpText>Contato que será usado para criar um passageiro em um trecho</inlineHelpText>
    <label>Contato</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Passageiro não pode ser do tipo Contato, mas sim do tipo Passageiro ou Cliente - Pessoa Física</errorMessage>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Contato</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Passageiros do Voo</relationshipLabel>
    <relationshipName>PassageirosVoo</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PassageirosVooServiceImpl.cls
public class PassageirosVooServiceImpl implements IPassageirosVooService {

    public String getPassageirosVoo(Id vooId)
    {
        List<PassageiroVoo__c> passageirosVoo = PassageirosVooSelector.newInstance().selectByVooId(new Set<Id>{vooId});
        List<Passageiro__c> ultimosPassageiros = PassageirosSelector.newInstance().selectByVooId(new Set<Id>{vooId});
        
        Set<Id> setContatosRemovidos = new Set<Id>();
        for(Passageiro__c passageiro : ultimosPassageiros){
            System.debug('excluido? ' + passageiro.Excluido__c + ' - ' + passageiro.Contato__c);
            if(passageiro.Excluido__c){
                setContatosRemovidos.add(passageiro.Contato__c);
            }
        }

        Map<Id, Contact> mapContatos = new Map<Id, Contact>();
        for(PassageiroVoo__c passageiro : passageirosVoo)
        {
            System.debug('Contains? ' + passageiro.Contato__r.Id + ' - ' + setContatosRemovidos.contains(passageiro.Contato__r.Id));
            if(!setContatosRemovidos.contains(passageiro.Contato__r.Id)){
                mapContatos.put(passageiro.Contato__r.Id, passageiro.Contato__r);
            }
        }
        return JSON.serialize(mapContatos);
    }
}