force-app/main/default/objects/Passageiro__c/Passageiro__c.object-meta.xml
<CustomObject>
    <label>Passageiro</label>
    <nameField>
        <displayFormat>P-{000000000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Passageiros</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Passageiro__c/fields/Bagagem__c.field-meta.xml
<CustomField>
    <fullName>Bagagem__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Bagagem (Kg)</label>
    <precision>6</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Passageiro__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contato</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Passageiro não pode ser do tipo Contato, mas sim do tipo Passageiro ou Cliente - Pessoa Física</errorMessage>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Contato</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Passageiros</relationshipLabel>
    <relationshipName>Passageiros</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Passageiro__c/fields/IdVoo__c.field-meta.xml
<CustomField>
    <fullName>IdVoo__c</fullName>
    <description>Replica o Id do Voo em que o passageiro estará presente</description>
    <formula>CASESAFEID(Trecho__r.Voo__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Replica o Id do Voo em que o passageiro estará presente</inlineHelpText>
    <label>Id do Voo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Passageiro__c/fields/NomeContato__c.field-meta.xml
<CustomField>
    <fullName>NomeContato__c</fullName>
    <formula>Contato__r.FirstName&amp;&quot; &quot;&amp;Contato__r.LastName</formula>
    <label>Nome</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Passageiro__c/fields/Peso__c.field-meta.xml
<CustomField>
    <fullName>Peso__c</fullName>
    <label>Peso (kg)</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Passageiro__c/fields/StatusVoo__c.field-meta.xml
<CustomField>
    <fullName>StatusVoo__c</fullName>
    <description>Replica o status do voo em passageiro</description>
    <formula>Trecho__r.StatusVoo__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Replica o status do voo em passageiro</inlineHelpText>
    <label>Status do Voo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Passageiro__c/fields/Trecho__c.field-meta.xml
<CustomField>
    <fullName>Trecho__c</fullName>
    <label>Trecho</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Trecho__c.Status__c</field>
            <operation>equals</operation>
            <value>Não Iniciado</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Trecho__c</referenceTo>
    <relationshipLabel>Passageiros</relationshipLabel>
    <relationshipName>Passageiros</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Servico__c/Servico__c.object-meta.xml
<CustomObject>
    <label>Serviço</label>
    <nameField>
        <displayFormat>SERV-{0000000}</displayFormat>
        <label>Serviço</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Serviços</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Servico__c/fields/Passageiro__c.field-meta.xml
<CustomField>
    <fullName>Passageiro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Passageiro</label>
    <referenceTo>Passageiro__c</referenceTo>
    <relationshipLabel>Serviços</relationshipLabel>
    <relationshipName>Servicos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Servico__c/fields/ServicoPromocao__c.field-meta.xml
<CustomField>
    <fullName>ServicoPromocao__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Serviço Promoção</label>
    <referenceTo>Servico__c</referenceTo>
    <relationshipLabel>Serviços</relationshipLabel>
    <relationshipName>Servicos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Servico__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aguardando Execução</fullName>
            </value>
            <value>
                <fullName>PreReservado</fullName>
                <label>Pré-Reservado</label>
            </value>
            <value>
                <fullName>Pago</fullName>
            </value>
            <value>
                <fullName>Executado</fullName>
            </value>
            <value>
                <fullName>No-Show</fullName>
            </value>
            <value>
                <fullName>Faturado</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Servico__c/fields/Trecho__c.field-meta.xml
<CustomField>
    <fullName>Trecho__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trecho</label>
    <referenceTo>Trecho__c</referenceTo>
    <relationshipLabel>Serviços</relationshipLabel>
    <relationshipName>Servicos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Servico__c/fields/Voo__c.field-meta.xml
<CustomField>
    <fullName>Voo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Voo</label>
    <referenceTo>Voo__c</referenceTo>
    <relationshipLabel>Serviços</relationshipLabel>
    <relationshipName>Servicos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trecho__c/Trecho__c.object-meta.xml
<CustomObject>
    <description>Define um trecho com origem e destino dentro de um Voo</description>
    <label>Trecho</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Código do Trecho</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trechos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trecho__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Não Iniciado</fullName>
                <default>true</default>
                <label>Não Iniciado</label>
            </value>
            <value>
                <fullName>Check In Fechado</fullName>
            </value>
            <value>
                <fullName>Em Rota</fullName>
            </value>
            <value>
                <fullName>Finalizado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trecho__c/fields/StatusVoo__c.field-meta.xml
<CustomField>
    <fullName>StatusVoo__c</fullName>
    <description>Replica o Status do Voo no trecho</description>
    <formula>TEXT(Voo__r.Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Replica o Status do Voo no trecho</inlineHelpText>
    <label>Status do Voo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trecho__c/fields/Voo__c.field-meta.xml
<CustomField>
    <fullName>Voo__c</fullName>
    <description>Voo ao qual o trecho pertence</description>
    <inlineHelpText>Voo ao qual o trecho pertence</inlineHelpText>
    <label>Voo</label>
    <referenceTo>Voo__c</referenceTo>
    <relationshipLabel>Trechos</relationshipLabel>
    <relationshipName>Trechos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Voo__c/Voo__c.object-meta.xml
<CustomObject>
    <description>O Voo de uma aeronave, do ponto de origem até o retorno</description>
    <label>Voo</label>
    <nameField>
        <displayFormat>REVO-{00000000}</displayFormat>
        <label>Número do Voo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Voos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Voo__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Define em que momento o voo se encontra</description>
    <inlineHelpText>Define em que momento o voo se encontra</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Rascunho</fullName>
                <default>true</default>
                <label>Rascunho</label>
            </value>
            <value>
                <fullName>Pré-reservado</fullName>
            </value>
            <value>
                <fullName>Reservado</fullName>
            </value>
            <value>
                <fullName>Confirmado</fullName>
            </value>
            <value>
                <fullName>Rota</fullName>
                <label>Em Rota</label>
            </value>
            <value>
                <fullName>LogPendente</fullName>
                <label>Concluindo o Voo</label>
            </value>
            <value>
                <fullName>Executado</fullName>
            </value>
            <value>
                <fullName>Em Faturamento</fullName>
                <isActive>false</isActive>
                <label>Em Faturamento</label>
            </value>
            <value>
                <fullName>Faturado</fullName>
                <isActive>false</isActive>
                <label>Faturado</label>
            </value>
            <value>
                <fullName>Pronto pra Voar</fullName>
                <isActive>false</isActive>
                <label>Pronto pra Voar</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PassageirosSelector.cls
public class PassageirosSelector extends fflib_SObjectSelector
	implements IPassageirosSelector
{
	private FINAL String naoIniciado = 'Não Iniciado';
    
    public static IPassageirosSelector newInstance()
	{
		return (IPassageirosSelector) Application.Selector.newInstance(Passageiro__c.SObjectType);
	}
    
    public PassageirosSelector(Boolean includeFieldSetFields)
    {
        super(includeFieldSetFields);

        this.setDataAccess(fflib_SObjectSelector.DataAccess.SYSTEM_MODE);
    }
    
    public PassageirosSelector()
    {
        super(true);

        this.setDataAccess(fflib_SObjectSelector.DataAccess.SYSTEM_MODE);
    }
    
    public override List<Schema.FieldSet> getSObjectFieldSetList()
    {
        return new List<Schema.FieldSet>	
        {	SobjectType.Passageiro__c.FieldSets.SelectFieldList	};
    }

    public List<Schema.SObjectField> getSObjectFieldList()
	{
		return new List<Schema.SObjectField> {
			Passageiro__c.Id,
            Passageiro__c.Bagagem__c,
            Passageiro__c.Peso__c,
           	Passageiro__c.Contato__c,
            Passageiro__c.Trecho__c,
            Passageiro__c.StatusVoo__c,
            Passageiro__c.NomeContato__c,
            Passageiro__c.Contato__c
            //Passageiro__c.Contato__r.Name
		};
	}
    
    public Schema.SObjectType getSObjectType()
	{
		return Passageiro__c.sObjectType;
	}
    
    public List<Passageiro__c> selectById(Set<ID> idSet)
	{
		return (List<Passageiro__c>) selectSObjectsById(idSet);
	}
    
    public List<Passageiro__c> selectByIdWithTrechosIniciados(Set<ID> idSet)
	{        
        fflib_QueryFactory passageirosQueryFactory = newQueryFactory();
 
      	fflib_SObjectSelector trechosSelector = new TrechosSelector();
      	trechosSelector.configureQueryFactoryFields(passageirosQueryFactory, 'Trecho__r');
        fflib_SObjectSelector ContatosSelector = new ContatosSelector();
      	trechosSelector.configureQueryFactoryFields(passageirosQueryFactory, 'Contato__r');

		return (List<Passageiro__c>) Database.query(
			passageirosQueryFactory
            .setCondition('Id in :idSet AND Trecho__c != null AND Trecho__r.Status__c != :naoIniciado')
            .toSOQL());
	}
    
    public List<Passageiro__c> selectByVooId(Set<Id> vooId)
    {
        fflib_QueryFactory passageirosQueryFactory = newQueryFactory();

        passageirosQueryFactory.subselectQuery('Servicos__r');    

        return (List<Passageiro__c>) Database.query(
            passageirosQueryFactory
            .setCondition('Trecho__r.Voo__c IN :vooId')
            .toSOQL());
    }
    /*public List<Passageiro__c> getPassageirosByContactIdsAndVooIds(Set<Id> idsContato, Set<Id> idsVoo)
    {
        fflib_QueryFactory passageirosQueryFactory = newQueryFactory();
        
        return (List<Passageiro__c>) Database.query(
            passageirosQueryFactory
            .setCondition('Contato__c IN :idsContato AND IdVoo__c IN :idsVoo')
            .toSOQL());
    }*/
    
    /* não utilizado mas fica de exemplo
    public List<PassageiroInfo> selectPassageiroInfo(Set<Id> idSet)
	{
		List<PassageiroInfo> passageiroInfos = new List<PassageiroInfo>();
		for(Passageiro__c passageiro : Database.query(
				newQueryFactory(false).
					selectField(Passageiro__c.Id).
					selectField(Passageiro__c.Bagagem__c).
            		selectField(Passageiro__c.Peso__c).
					selectField('Contato__r.Name').
					selectField('Contato__r.Email').
					selectField('Trecho__r.Status__c').
					setCondition('id in :idSet').
					toSOQL()))
			passageiroInfos.add(new PassageiroInfo(passageiro));
		return passageiroInfos;	
	}
    
    public class PassageiroInfo
	{		 
		private Passageiro__c passageiro;
		public Id Id { get { return passageiro.Id; } }		
        public Double Bagagem { get { return passageiro.Bagagem__c; } }
        public Double Peso { get { return passageiro.Peso__c; } }
		public String ContatoName { get { return passageiro.Contato__r.Name; } }		
		public String ContatoEmail { get { return passageiro.Contato__r.Email; } }		
		public String TrechoStatusDeveloper { get { return passageiro.Trecho__r.Status__c; } }
        public String TrechoStatus { get { return passageiro.Trecho__r.Status__c; } }
		private PassageiroInfo(Passageiro__c passageiro) { this.passageiro = passageiro; }		 
	}
	*/
}