force-app/main/default/objects/Passageiro__c/Passageiro__c.object-meta.xml
<CustomObject>
    <label>Passageiro</label>
    <nameField>
        <displayFormat>P-{000000000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Passageiros</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Passageiro__c/fields/CodigoReserva__c.field-meta.xml
<CustomField>
    <fullName>CodigoReserva__c</fullName>
    <label>Código da Reserva</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Passageiro__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contato</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Passageiro não pode ser do tipo Contato, mas sim do tipo Passageiro ou Cliente - Pessoa Física</errorMessage>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Contato</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Passageiros</relationshipLabel>
    <relationshipName>Passageiros</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Passageiro__c/fields/Excluido__c.field-meta.xml
<CustomField>
    <fullName>Excluido__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cancelado?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Passageiro__c/fields/Trecho__c.field-meta.xml
<CustomField>
    <fullName>Trecho__c</fullName>
    <label>Trecho</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Trecho__c.Status__c</field>
            <operation>equals</operation>
            <value>Não Iniciado</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Trecho__c</referenceTo>
    <relationshipLabel>Passageiros</relationshipLabel>
    <relationshipName>Passageiros</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/PassageiroVoo__c/PassageiroVoo__c.object-meta.xml
<CustomObject>
    <description>Armazena os passageiros de um voo</description>
    <label>Passageiro do Voo</label>
    <nameField>
        <displayFormat>PV-{00}</displayFormat>
        <label>Código do Passageiro do Voo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Passageiros do Voo</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PassageiroVoo__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <description>Contato que será usado para criar um passageiro em um trecho</description>
    <inlineHelpText>Contato que será usado para criar um passageiro em um trecho</inlineHelpText>
    <label>Contato</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Passageiro não pode ser do tipo Contato, mas sim do tipo Passageiro ou Cliente - Pessoa Física</errorMessage>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Contato</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Passageiros do Voo</relationshipLabel>
    <relationshipName>PassageirosVoo</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PassageiroVoo__c/fields/Voo__c.field-meta.xml
<CustomField>
    <fullName>Voo__c</fullName>
    <description>Voo ao qual o contato está vinculado e será registrado como passageiro</description>
    <inlineHelpText>Voo ao qual o contato está vinculado e será registrado como passageiro</inlineHelpText>
    <label>Voo</label>
    <referenceTo>Voo__c</referenceTo>
    <relationshipLabel>Passageiros do Voo</relationshipLabel>
    <relationshipName>PassageirosVoo</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Servico__c/Servico__c.object-meta.xml
<CustomObject>
    <label>Serviço</label>
    <nameField>
        <displayFormat>SERV-{0000000}</displayFormat>
        <label>Serviço</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Serviços</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Servico__c/fields/Oportunidade__c.field-meta.xml
<CustomField>
    <fullName>Oportunidade__c</fullName>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Serviços</relationshipLabel>
    <relationshipName>Servicos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Servico__c/fields/Passageiro__c.field-meta.xml
<CustomField>
    <fullName>Passageiro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Passageiro</label>
    <referenceTo>Passageiro__c</referenceTo>
    <relationshipLabel>Serviços</relationshipLabel>
    <relationshipName>Servicos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Servico__c/fields/ServicoPromocao__c.field-meta.xml
<CustomField>
    <fullName>ServicoPromocao__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Serviço Promoção</label>
    <referenceTo>Servico__c</referenceTo>
    <relationshipLabel>Serviços</relationshipLabel>
    <relationshipName>Servicos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Servico__c/fields/Trecho__c.field-meta.xml
<CustomField>
    <fullName>Trecho__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trecho</label>
    <referenceTo>Trecho__c</referenceTo>
    <relationshipLabel>Serviços</relationshipLabel>
    <relationshipName>Servicos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Servico__c/fields/Voo__c.field-meta.xml
<CustomField>
    <fullName>Voo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Voo</label>
    <referenceTo>Voo__c</referenceTo>
    <relationshipLabel>Serviços</relationshipLabel>
    <relationshipName>Servicos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Servico__c/recordTypes/ShuttleSeat.recordType-meta.xml
<RecordType>
    <fullName>ShuttleSeat</fullName>
    <active>true</active>
    <label>Shuttle Seat</label>
</RecordType>

force-app/main/default/objects/Trecho__c/Trecho__c.object-meta.xml
<CustomObject>
    <description>Define um trecho com origem e destino dentro de um Voo</description>
    <label>Trecho</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Código do Trecho</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trechos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trecho__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <description>Passageiro - Transporte apenas de passageiros no trecho
Carga e passageiro - Transporte de passageiros e carga no trecho
Cargueiro - Transporte apenas de carga no trecho
Translado - Translado da aeronave para reposicionamento
Translado com passageiro - Translado da aeronave para reposicionamento com passageiro a bordo
Comitiva</description>
    <inlineHelpText>Transporte apenas de passageiros no trecho
Transporte de passageiros e carga no trecho
Transporte apenas de carga no trecho
Translado da aeronave para reposicionamento
Translado da aeronave para reposicionamento com passageiro
Comitiva</inlineHelpText>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Passageiros</fullName>
            </value>
            <value>
                <fullName>Cargueiro</fullName>
            </value>
            <value>
                <fullName>Passageiros e Cargas</fullName>
            </value>
            <value>
                <fullName>Translado</fullName>
            </value>
            <value>
                <fullName>Translado com passageiro</fullName>
            </value>
            <value>
                <fullName>Comitiva</fullName>
            </value>
            <value>
                <fullName>Sanitário</fullName>
            </value>
            <value>
                <fullName>Treinamento</fullName>
            </value>
            <value>
                <fullName>SAR</fullName>
            </value>
            <value>
                <fullName>MEDVAC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trecho__c/fields/Voo__c.field-meta.xml
<CustomField>
    <fullName>Voo__c</fullName>
    <description>Voo ao qual o trecho pertence</description>
    <inlineHelpText>Voo ao qual o trecho pertence</inlineHelpText>
    <label>Voo</label>
    <referenceTo>Voo__c</referenceTo>
    <relationshipLabel>Trechos</relationshipLabel>
    <relationshipName>Trechos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Voo__c/Voo__c.object-meta.xml
<CustomObject>
    <description>O Voo de uma aeronave, do ponto de origem até o retorno</description>
    <label>Voo</label>
    <nameField>
        <displayFormat>REVO-{00000000}</displayFormat>
        <label>Número do Voo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Voos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Voo__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <description>Informa o tipo de transporte realizado pelo voo.</description>
    <inlineHelpText>Informs the type of transport performed by the flight.</inlineHelpText>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TipoVoo</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/TipoVoo.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ShuttleSeat</fullName>
        <label>Shuttle Seat</label>
    </customValue>
    <customValue>
        <fullName>Charter</fullName>
    </customValue>
    <customValue>
        <fullName>FullCabin</fullName>
        <label>Full Cabin</label>
    </customValue>
    <customValue>
        <fullName>Sanitário</fullName>
        <isActive>false</isActive>
        <label>Sanitário</label>
    </customValue>
    <customValue>
        <fullName>Treinamento</fullName>
        <isActive>false</isActive>
        <label>Treinamento</label>
    </customValue>
    <customValue>
        <fullName>SAR</fullName>
        <isActive>false</isActive>
        <label>SAR</label>
    </customValue>
    <customValue>
        <fullName>Passageiros</fullName>
        <isActive>false</isActive>
        <label>Passageiros</label>
    </customValue>
    <customValue>
        <fullName>Manutenção</fullName>
        <isActive>false</isActive>
        <label>Manutenção</label>
    </customValue>
    <customValue>
        <fullName>Treinamento NDC</fullName>
        <isActive>false</isActive>
        <label>Treinamento NDC</label>
    </customValue>
    <customValue>
        <fullName>MEDVAC</fullName>
        <isActive>false</isActive>
        <label>MEDVAC</label>
    </customValue>
    <customValue>
        <fullName>Cargueiro</fullName>
        <isActive>false</isActive>
        <label>Cargueiro</label>
    </customValue>
    <customValue>
        <fullName>Passageiros e Cargas</fullName>
        <isActive>false</isActive>
        <label>Passageiros e Cargas</label>
    </customValue>
    <masterLabel>Tipo de voo</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PassageirosServiceImpl.cls
public class PassageirosServiceImpl implements IPassageirosService
{    
    public String salvarListaPassageiros(List<Id> passageirosVoo, Map<Id,List<Id>> passageirosTrechos, Id vooId){
        List<PassageiroVoo__c> ultimosPassageirosVoo = PassageirosVooSelector.newInstance().selectByVooId(new Set<Id>{vooId});
        Map<Id, PassageiroVoo__c> contatosUltimosPassageirosVoo = getMapPassageirosVooPorContato(ultimosPassageirosVoo);
        Set<Id> setPassageirosVoo = Utils.getSetIdsByListIds(passageirosVoo);
        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        
        handlePassageirosVoo(setPassageirosVoo, contatosUltimosPassageirosVoo, vooId, uow);
        
        List<Passageiro__c> ultimosPassageiros = PassageirosSelector.newInstance().selectByVooId(new Set<Id>{vooId});
        Map<Id, List<Passageiro__c>> ultimosPassageirosPorTrecho = (Map<Id, List<Passageiro__c>>)Utils.groupByRelatedTo(ultimosPassageiros, Passageiro__c.Trecho__c, null);
        
        List<Servico__c> servicos = new ServicosSelector().selectByVooId(new Set<Id>{vooId});

        handlePassageirosTrechos(ultimosPassageirosPorTrecho, passageirosTrechos, servicos, uow);
        
        uow.commitWork();
        return 'sucesso';
    }
    
    private void handlePassageirosTrechos(Map<Id, List<Passageiro__c>> ultimosPassageirosPorTrecho, Map<Id,List<Id>> passageirosTrechos, List<Servico__c> servicos, fflib_ISObjectUnitOfWork uow){
        Map<Id, Map<Id, Passageiro__c>> ultimosPassageirosPorTrechoMap = new Map<Id, Map<Id, Passageiro__c>>();
        
        String codigoReserva = '';
        if(servicos.size() > 0){
            codigoReserva = servicos[0].Oportunidade__r.CodigoReserva__c;
        }

        for(Id trechoId : ultimosPassageirosPorTrecho.keySet())
        {
            List<Passageiro__c> passageiros = ultimosPassageirosPorTrecho.get(trechoId);
            ultimosPassageirosPorTrechoMap.put(trechoId, getMapPassageirosPorContato(passageiros));
        }
        
        for(Id trechoId : passageirosTrechos.keySet())
        {
            List<Id> passageiros = passageirosTrechos.get(trechoId);
            Set<Id> setPassageirosTrecho = Utils.getSetIdsByListIds(passageiros);
            Integer passageiroCount = 0;
            Map<Id, Passageiro__c> passageirosDoTrechoPorContato = ultimosPassageirosPorTrechoMap.get(trechoId);
            for(Id passageiroVoo : setPassageirosTrecho)
            {               
                
                if(passageirosDoTrechoPorContato != null)
                {
                    if(passageirosDoTrechoPorContato.containsKey(passageiroVoo))
                    {
                        passageirosDoTrechoPorContato.remove(passageiroVoo);
                    }else
                    {
                        Passageiro__c novoPassageiro = new Passageiro__c(Trecho__c = trechoId, 
                        Contato__c = passageiroVoo,
                        CodigoReserva__c = codigoReserva);
                        uow.registerNew(novoPassageiro);
                    }
                    
                }else{
                    Passageiro__c novoPassageiro = new Passageiro__c(Trecho__c = trechoId, 
                    Contato__c = passageiroVoo,
                    CodigoReserva__c = codigoReserva);
                    uow.registerNew(novoPassageiro);
                }
            }

            if(passageirosDoTrechoPorContato != null){

                for(Passageiro__c passageiro : passageirosDoTrechoPorContato.values()){
                    
                    if(passageiro.Excluido__c){
                        continue;
                    }

                    if(passageiro.Servicos__r.size() > 0){
                        passageiro.Excluido__c = true;
                        uow.registerDirty(passageiro);
                    }else{
                        uow.registerDeleted(passageiro);
                    }
                }
            }
            	
        }
    }
    
    private void handlePassageirosVoo(Set<Id> setPassageirosVoo, Map<Id, PassageiroVoo__c> contatosUltimosPassageirosVoo, Id vooId, fflib_ISObjectUnitOfWork uow)
    {            
        Voo__c voo = new VoosSelector().selectById(new Set<Id>{vooId})[0];

        
        for(Id passageiroVoo : setPassageirosVoo)
        {
            if(contatosUltimosPassageirosVoo.containsKey(passageiroVoo)){
                contatosUltimosPassageirosVoo.remove(passageiroVoo);
            }else{
                if(voo.Tipo__c == 'ShuttleSeat'){
                    throw new AuraHandledException('Não é possível adicionar passageiros à um voo ShuttleSeat');
                }
                
                PassageiroVoo__c novoPassageiro = new PassageiroVoo__c(Voo__c = vooId, Contato__c = passageiroVoo);
                uow.registerNew(novoPassageiro);
            }
        }
        uow.registerDeleted(contatosUltimosPassageirosVoo.values());
    }
    
    private Map<Id, PassageiroVoo__c> getMapPassageirosVooPorContato(List<PassageiroVoo__c> sObjs){
        Map<Id, PassageiroVoo__c> mapRelated = new Map<Id, PassageiroVoo__c>();

        for(PassageiroVoo__c sObj : sObjs)
        {
            mapRelated.put((Id)SObj.get(PassageiroVoo__c.Contato__c), sObj);
        }
        return mapRelated;
    }
    
    private Map<Id, Passageiro__c> getMapPassageirosPorContato(List<Passageiro__c> sObjs){
        Map<Id, Passageiro__c> mapRelated = new Map<Id, Passageiro__c>();

        for(Passageiro__c sObj : sObjs)
        {
            mapRelated.put((Id)SObj.get(Passageiro__c.Contato__c), sObj);
        }
        return mapRelated;
    }
    public static List<Passageiro__c> getPassageirosByVooId(List<Id> vooIds)
    {
        return PassageirosSelector.newInstance().selectByVooId(Utils.getSetIdsByListIds(vooIds));
    }
    
}