force-app/main/default/objects/Servico__c/Servico__c.object-meta.xml
<CustomObject>
    <label>Serviço</label>
    <nameField>
        <displayFormat>SERV-{0000000}</displayFormat>
        <label>Serviço</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Serviços</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Servico__c/fields/Oportunidade__c.field-meta.xml
<CustomField>
    <fullName>Oportunidade__c</fullName>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Serviços</relationshipLabel>
    <relationshipName>Servicos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Servico__c/fields/ProdutoOportunidade__c.field-meta.xml
<CustomField>
    <fullName>ProdutoOportunidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto de oportunidade</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipLabel>Serviços</relationshipLabel>
    <relationshipName>Servicos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Servico__c/fields/Voo__c.field-meta.xml
<CustomField>
    <fullName>Voo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Voo</label>
    <referenceTo>Voo__c</referenceTo>
    <relationshipLabel>Serviços</relationshipLabel>
    <relationshipName>Servicos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Voo__c/Voo__c.object-meta.xml
<CustomObject>
    <description>O Voo de uma aeronave, do ponto de origem até o retorno</description>
    <label>Voo</label>
    <nameField>
        <displayFormat>REVO-{00000000}</displayFormat>
        <label>Número do Voo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Voos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ServicosSelector.cls
public class ServicosSelector extends fflib_SObjectSelector implements IServicosSelector
{

    public ServicosSelector(Boolean includeFieldSetFields)
    {
        super(includeFieldSetFields);
    }
    
    public ServicosSelector()
    {
        super(true);
    }
    
    public override List<Schema.FieldSet> getSObjectFieldSetList()
    {
        return new List<Schema.FieldSet> {
            SobjectType.Servico__c.FieldSets.SelectFieldList
        };
    }
    
    public static IServicosSelector newInstance()
    {
        return (IServicosSelector) Application.Selector.newInstance(Servico__c.SObjectType);
    }

    public List<Schema.SObjectField> getSObjectFieldList()
	{
		return new List<Schema.SObjectField> {
            Servico__c.Id
		};
	}                  
    
    public Schema.SObjectType getSObjectType()
    {
        return Servico__c.sObjectType;
    }    

    public List<Servico__c> selectByOpportunityId(Set<ID> idSet) {
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('Oportunidade__c IN :idSet');
        return (List<Servico__c>) Database.query(query.toSOQL());        
    }

    public List<Servico__c> selectByVooId(Set<ID> idSet) {
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('Voo__c IN :idSet AND ProdutoOportunidade__r.Pacote__c = null');
        query.selectField('Oportunidade__r.CodigoReserva__c');
        return (List<Servico__c>) Database.query(query.toSOQL());        
    }
    

    public List<Servico__c> selectById(Set<ID> idSet) {
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('Id IN :idSet');
        return (List<Servico__c>) Database.query(query.toSOQL());        
    }

}