force-app/main/default/objects/Faturamento__c/Faturamento__c.object-meta.xml
<CustomObject>
    <label>Faturamento</label>
    <nameField>
        <displayFormat>FAT-{000000}</displayFormat>
        <label>Faturamento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Faturamentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Interessado__c/Interessado__c.object-meta.xml
<CustomObject>
    <label>Interessado</label>
    <nameField>
        <displayFormat>I-{000000000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interessados</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Interessado__c/fields/ConclusaoTrecho__c.field-meta.xml
<CustomField>
    <fullName>ConclusaoTrecho__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Conclusão do Trecho</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Interessado__c/fields/ConclusaoVoo__c.field-meta.xml
<CustomField>
    <fullName>ConclusaoVoo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Conclusão do Voo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Interessado__c/fields/EmissaoEmbarque__c.field-meta.xml
<CustomField>
    <fullName>EmissaoEmbarque__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Emissão Embarque</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Interessado__c/fields/Faturamento__c.field-meta.xml
<CustomField>
    <fullName>Faturamento__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Faturamento</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Interessado__c/fields/Reserva__c.field-meta.xml
<CustomField>
    <fullName>Reserva__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reserva</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Interessado__c/fields/TakeOffReport__c.field-meta.xml
<CustomField>
    <fullName>TakeOffReport__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Take Off Report</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Interessado__c/fields/Voo__c.field-meta.xml
<CustomField>
    <fullName>Voo__c</fullName>
    <label>Voo</label>
    <referenceTo>Voo__c</referenceTo>
    <relationshipLabel>Interessados</relationshipLabel>
    <relationshipName>Interessados</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Voo__c/Voo__c.object-meta.xml
<CustomObject>
    <description>O Voo de uma aeronave, do ponto de origem até o retorno</description>
    <label>Voo</label>
    <nameField>
        <displayFormat>REVO-{00000000}</displayFormat>
        <label>Número do Voo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Voos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/InteressadosSelector.cls
public class InteressadosSelector extends fflib_SObjectSelector implements IInteressadosSelector
{
    
    public static IInteressadosSelector newInstance()
    {
        return (IInteressadosSelector) Application.Selector.newInstance(Interessado__c.SObjectType);
    }
    
    public InteressadosSelector()
    {
        super(true);
    }
    
    public override List<Schema.FieldSet> getSObjectFieldSetList()
    {
        List<Schema.FieldSet> fieldSets = new List<Schema.FieldSet>();
        
        fieldSets.add(SObjectType.Interessado__c.FieldSets.SelectFieldList);
        
        return fieldSets;
    }
    
    public List<Schema.SObjectField> getSObjectFieldList()
    {
        List<Schema.SObjectField> fields = new List<Schema.SObjectField>();
        
        return fields;
    }
    
    public Schema.SObjectType getSObjectType()
    {
        return Interessado__c.sObjectType;
    }
    
    public List<Interessado__c> selectById(Set<ID> idSet)
    {
        return (List<Interessado__c>) selectSObjectsById(idSet);
    }    
    
    public List<Interessado__c> selectByVoo(Set<Id> voosIds)
    {
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('Voo__c IN :voosIds');
        
        return (List<Interessado__c>) Database.query(query.toSOQL());
    }
    
    public List<Interessado__c> selectConclusaoVooByVoo(Set<Id> voosIds)
    {
        Boolean condition = true;
        
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('Voo__c IN :voosIds AND ConclusaoVoo__c = :condition');
        
        return (List<Interessado__c>) Database.query(query.toSOQL());
    }
    
    public List<Interessado__c> selectReservaByVoo(Set<Id> voosIds)
    {
        Boolean condition = true;
        
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('Voo__c IN :voosIds AND Reserva__c = :condition');
        
        return (List<Interessado__c>) Database.query(query.toSOQL());
    }
    
    public List<Interessado__c> selectConclusaoTrechoByVoo(Set<Id> voosIds)
    {
        Boolean condition = true;
        
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('Voo__c IN :voosIds AND ConclusaoTrecho__c = :condition');
        
        return (List<Interessado__c>) Database.query(query.toSOQL());
    }
    
    public List<Interessado__c> selectEmissaoEmbarqueByVoo(Set<Id> voosIds)
    {
        Boolean condition = true;
        
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('Voo__c IN :voosIds AND EmissaoEmbarque__c = :condition');
        
        return (List<Interessado__c>) Database.query(query.toSOQL());
    }
    
    public List<Interessado__c> selectFaturamentoByVoo(Set<Id> voosIds)
    {
        Boolean condition = true;
        
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('Voo__c IN :voosIds AND Faturamento__c = :condition');
        
        return (List<Interessado__c>) Database.query(query.toSOQL());
    }
    
    public List<Interessado__c> selectTakeOffReportByVoo(Set<Id> voosIds)
    {
        Boolean condition = true;
        
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('Voo__c IN :voosIds AND TakeOffReport__c = :condition');
        
        return (List<Interessado__c>) Database.query(query.toSOQL());
    }
}