force-app/main/default/objects/ConfiguracoesGerais__c/ConfiguracoesGerais__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Configurações Gerais</label>
</CustomObject>

force-app/main/default/objects/ConfiguracoesGerais__c/fields/IdRemetenteInteressados__c.field-meta.xml
<CustomField>
    <fullName>IdRemetenteInteressados__c</fullName>
    <description>Id do remetente do e-mail que será enviado aos interessados</description>
    <inlineHelpText>Id do remetente do e-mail que será enviado aos interessados</inlineHelpText>
    <label>Id Remetente de Interessados</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Faturamento__c/Faturamento__c.object-meta.xml
<CustomObject>
    <label>Faturamento</label>
    <nameField>
        <displayFormat>FAT-{000000}</displayFormat>
        <label>Faturamento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Faturamentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Interessado__c/Interessado__c.object-meta.xml
<CustomObject>
    <label>Interessado</label>
    <nameField>
        <displayFormat>I-{000000000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interessados</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Interessado__c/fields/ConclusaoTrecho__c.field-meta.xml
<CustomField>
    <fullName>ConclusaoTrecho__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Conclusão do Trecho</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Interessado__c/fields/ConclusaoVoo__c.field-meta.xml
<CustomField>
    <fullName>ConclusaoVoo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Conclusão do Voo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Interessado__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <label>Contato</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Interessados</relationshipLabel>
    <relationshipName>Interessados</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Interessado__c/fields/EmissaoEmbarque__c.field-meta.xml
<CustomField>
    <fullName>EmissaoEmbarque__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Emissão Embarque</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Interessado__c/fields/Faturamento__c.field-meta.xml
<CustomField>
    <fullName>Faturamento__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Faturamento</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Interessado__c/fields/MensagemErro__c.field-meta.xml
<CustomField>
    <fullName>MensagemErro__c</fullName>
    <label>Mensagem de Erro</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Interessado__c/fields/Reserva__c.field-meta.xml
<CustomField>
    <fullName>Reserva__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reserva</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Interessado__c/fields/TakeOffReport__c.field-meta.xml
<CustomField>
    <fullName>TakeOffReport__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Take Off Report</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Interessado__c/fields/Voo__c.field-meta.xml
<CustomField>
    <fullName>Voo__c</fullName>
    <label>Voo</label>
    <referenceTo>Voo__c</referenceTo>
    <relationshipLabel>Interessados</relationshipLabel>
    <relationshipName>Interessados</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Interessado__c/recordTypes/Editavel.recordType-meta.xml
<RecordType>
    <fullName>Editavel</fullName>
    <active>true</active>
    <label>Editável</label>
</RecordType>

force-app/main/default/objects/TemplateEmail__mdt/TemplateEmail__mdt.object-meta.xml
<CustomObject>
    <label>Template de Email</label>
    <pluralLabel>Template de Email</pluralLabel>
</CustomObject>

force-app/main/default/objects/TemplateEmail__mdt/fields/APINameInteresse__c.field-meta.xml
<CustomField>
    <fullName>APINameInteresse__c</fullName>
    <label>API Name do Interesse</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TemplateEmail__mdt/fields/Id__c.field-meta.xml
<CustomField>
    <fullName>Id__c</fullName>
    <label>Id</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trecho__c/Trecho__c.object-meta.xml
<CustomObject>
    <description>Define um trecho com origem e destino dentro de um Voo</description>
    <label>Trecho</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Código do Trecho</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trechos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trecho__c/fields/Voo__c.field-meta.xml
<CustomField>
    <fullName>Voo__c</fullName>
    <description>Voo ao qual o trecho pertence</description>
    <inlineHelpText>Voo ao qual o trecho pertence</inlineHelpText>
    <label>Voo</label>
    <referenceTo>Voo__c</referenceTo>
    <relationshipLabel>Trechos</relationshipLabel>
    <relationshipName>Trechos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Voo__c/Voo__c.object-meta.xml
<CustomObject>
    <description>O Voo de uma aeronave, do ponto de origem até o retorno</description>
    <label>Voo</label>
    <nameField>
        <displayFormat>REVO-{00000000}</displayFormat>
        <label>Número do Voo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Voos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Voo__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Conta para o faturamento do(s) voo(s)</description>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Voos</relationshipLabel>
    <relationshipName>Voos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Interessados.cls
public without sharing class Interessados extends fflib_SObjectDomain implements IInteressados
{   
    public static FINAL String EDITAVEL = 'Editavel'; 
    private List<Trecho__c> trechos;
    private Map<Id, Voo__c> voos;
    private InteresseEnum interesse;
    
    public static FINAL Map<InteresseEnum, Schema.SObjectField> interesseWhatId = 
        new Map<InteresseEnum, Schema.SObjectField> 
    {             
            InteresseEnum.RESERVA => Interessado__c.Voo__c,
            InteresseEnum.CONCLUSAOVOO => Interessado__c.Voo__c,
            InteresseEnum.CONCLUSAOTRECHO => Trecho__c.Id,
            InteresseEnum.EMISSAOEMBARQUE => Interessado__c.Voo__c,
            InteresseEnum.FATURAMENTO => Interessado__c.Voo__c,
            InteresseEnum.TAKEOFFREPORT => Trecho__c.Id                
  	};
    
    public Interessados(List<Interessado__c> sObjectList)
    {
        super(sObjectList);
    }
    
    public static IInteressados newInstance(List<Interessado__c> sObjectList)
    {
        return (IInteressados) Application.Domain.newInstance(sObjectList);
    }
    
    public class Constructor implements fflib_SObjectDomain.IConstructable
    {
        public fflib_SObjectDomain construct(List<SObject> sObjectList)
        {
            return new Interessados(sObjectList);
        }        
    }
    
    public void registerEmails(fflib_ISObjectUnitOfWork uow, TemplateEmail__mdt template)
    {   
        for (Interessado__c interessado : (List<Interessado__c>)records)
        {
            registerInteresses(interessado, uow, template);            
        }        
    }
    
    public void registerEmails(fflib_ISObjectUnitOfWork uow, TemplateEmail__mdt template, InteresseEnum interesse)
    {        
        this.interesse = interesse;
        registerEmails(uow, template);  
    }
    
    public void registerEmails(fflib_ISObjectUnitOfWork uow, TemplateEmail__mdt template, Map<Id, Voo__c> voos, InteresseEnum interesse)
    {        
        this.voos = voos;
        this.interesse = interesse;
        registerEmails(uow, template);  
    }
    
    //Verifica se o Contato (Interessado) possui INTERESSE em receber esse email específico
    public void registerInteresses(Interessado__c interessado, fflib_ISObjectUnitOfWork uow, TemplateEmail__mdt template)
    {
        String mensagemErro = '';
        
        Boolean condition = false;
        try
        {
            condition = (Boolean)interessado.get(template.APINameInteresse__c);                
        }
        catch (SObjectException e) 
        {
            mensagemErro += '[Ocorreu um erro ao enviar o email com template [' + template.MasterLabel + '], pois o campo [' + template.APINameInteresse__c + '] cadastrado como APINameInteresse__c não existe no objeto Interessado__c.] ';
        }
        catch (TypeException e)
        {
            mensagemErro += '[Ocorreu um erro ao enviar o email com template [' + template.MasterLabel + '], pois o campo [' + template.APINameInteresse__c + '] cadastrado como APINameInteresse__c não é do tipo Boolean no objeto Interessado__c.] ';
        }
        catch (Exception e)
        {
            mensagemErro += '[Ocorreu um erro inesperado ao enviar o email com template [' + template.MasterLabel + ']: ' + e.getMessage() +'] ';
        }
        
        if (condition)
        {
            List<EmailMessage> jaEnviado = EmailMessageSelector.newInstance().selectByRelatedToIdEmailTemplateId(getWhatId(interessado), template.Id__c);
        	if(jaEnviado.size() == 0) uow.registerEmail(createEmail(interessado, template.Id__c));
        } 
        
        interessado.MensagemErro__c = String.isNotBlank(mensagemErro) ? mensagemErro : '';
        
        if (String.isNotBlank(mensagemErro)) uow.registerDirty(interessado);
    }
    
    private Messaging.SingleEmailMessage createEmail(Interessado__c interessado, String templateId)
    {
        Id idOrgWideEmailAddres = ConfiguracoesGerais__c.getOrgDefaults().IdRemetenteInteressados__c;
        List<String> destinatarios = new List<String>();
        destinatarios.add(interessado.Contato__r.Email);
        
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
        
        email.setTargetObjectId(interessado.Contato__c);
        email.setSaveAsActivity(true);
        email.setWhatId(getWhatId(interessado));
        email.setTemplateId(templateId);
        email.setOrgWideEmailAddressId(idOrgWideEmailAddres);
        email.toaddresses = destinatarios;
            
        return email;
    }

    private Id getWhatId(Interessado__c interessado)
    {
        Object value;
        SObject sObj = interessado;
        if (this.interesse == InteresseEnum.CONCLUSAOTRECHO || this.interesse == InteresseEnum.TAKEOFFREPORT)
        {
            Voo__c voo = voos.get(interessado.Voo__c);
            Trecho__c trecho = voo.Trechos__r.size() > 0 ? voo.Trechos__r.get(0) : null;
            sObj = trecho;
        }
        
        if (sObj != null)
        {
        	value = sObj.get(interesseWhatId.get(this.interesse));    
        }        
        
        return value != null ? Id.valueOf(String.valueOf(value)) : null;
    }
    
    public void criarInteressados(Set<Voo__c> vooSet, Set<Contact> contactSet, fflib_ISObjectUnitOfWork uow)
    {
        for(Contact contact : contactSet)
        {
            if(String.isNotBlank(contact.AccountId) && contact.PossuiInteresse__c)
            {
                for(Voo__c voo : vooSet)
                {
                    if(String.isNotBlank(voo.Cliente__c) && voo.Cliente__c.equals(contact.AccountId))
                    {
                        Interessado__c interessado = new Interessado__c();
                        interessado.RecordTypeId = Schema.SObjectType.Interessado__c.getRecordTypeInfosByDeveloperName().get(EDITAVEL).getRecordTypeId();
                        interessado.Reserva__c = contact.Reserva__c;
                        interessado.EmissaoEmbarque__c = contact.EmissaoEmbarque__c;
                        interessado.TakeOffReport__c = contact.TakeOffReport__c;
                        interessado.ConclusaoTrecho__c = contact.ConclusaoTrecho__c;
                        interessado.ConclusaoVoo__c = contact.ConclusaoVoo__c;
                        interessado.Faturamento__c = contact.Faturamento__c;
                        uow.registerNew(interessado);
                        uow.registerRelationship(interessado, Interessado__c.Voo__c, voo);
                        uow.registerRelationship(interessado, Interessado__c.Contato__c, contact);
                    }
                }
            }
        }
    }
}