force-app/main/default/objects/ConfiguracoesGerais__c/ConfiguracoesGerais__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Configurações Gerais</label>
</CustomObject>

force-app/main/default/objects/ConfiguracoesGerais__c/fields/IdRemetentePassageiroRemovido__c.field-meta.xml
<CustomField>
    <fullName>IdRemetentePassageiroRemovido__c</fullName>
    <description>Possui o id do remetente que será utilizado no e-mail para informar que o passageiro foi removido do voo</description>
    <inlineHelpText>Possui o id do remetente que será utilizado no e-mail para informar que o passageiro foi removido do voo</inlineHelpText>
    <label>Id Remetente Passageiro Removido</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConfiguracoesGerais__c/fields/IdTemplateEmailPassageiroRemovido__c.field-meta.xml
<CustomField>
    <fullName>IdTemplateEmailPassageiroRemovido__c</fullName>
    <label>Id Template de Email Passageiro Removido</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Passageiro__c/Passageiro__c.object-meta.xml
<CustomObject>
    <label>Passageiro</label>
    <nameField>
        <displayFormat>P-{000000000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Passageiros</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Passageiro__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contato</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Passageiro não pode ser do tipo Contato, mas sim do tipo Passageiro ou Cliente - Pessoa Física</errorMessage>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Contato</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Passageiros</relationshipLabel>
    <relationshipName>Passageiros</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Passageiro__c/fields/EmailEnviado__c.field-meta.xml
<CustomField>
    <fullName>EmailEnviado__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Usado como flag para saber se o passageiro já recebeu o email.</description>
    <label>Email Enviado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Passageiro__c/fields/IdVoo__c.field-meta.xml
<CustomField>
    <fullName>IdVoo__c</fullName>
    <description>Replica o Id do Voo em que o passageiro estará presente</description>
    <formula>CASESAFEID(Trecho__r.Voo__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Replica o Id do Voo em que o passageiro estará presente</inlineHelpText>
    <label>Id do Voo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EmailPassageiroRemovido.cls
public class EmailPassageiroRemovido 
{
    public static void sendEmail()
    {
        Set<Id> idsVoo = new Set<Id>();
        Set<Id> idsContato = new Set<Id>();
        List<id> idsTrechosLista = new List<Id>();
        
        for (Passageiro__c passageiro : (List<Passageiro__c>)Trigger.old)
        {
            if(passageiro.EmailEnviado__c)
            {
                idsVoo.add(passageiro.idVoo__c);
                idsContato.add(passageiro.Contato__c);   
            }
        }
        List<Passageiro__c> passageiros = PassageirosSelector.newInstance().selectByVooId(idsVoo);
        
        Map<Id, Map<Id, List<Passageiro__c>>> vooContatoPassageiro = new Map<Id, Map<Id, List<Passageiro__c>>>();
        
        for(Id idVoo : idsVoo)
        {
            //System.debug(passageiros);
            vooContatoPassageiro.put(idVoo, montarMapContato(idVoo, idsContato, passageiros));
        }
        if (!idsVoo.isEmpty())
        {
            Messaging.sendEmail(montarEmail(vooContatoPassageiro, ConfiguracoesGerais__c.getOrgDefaults().IdTemplateEmailPassageiroRemovido__c));
        }
    }
    public static List<Messaging.SingleEmailMessage> montarEmail(Map<Id, Map<Id, List<Passageiro__c>>> vooContatoPassageiro, Id templateId)
    {
        Id idOrgWideEmailAddres = ConfiguracoesGerais__c.getOrgDefaults().IdRemetentePassageiroRemovido__c;
        Map<Id, Messaging.SingleEmailMessage> mails = new Map<Id, Messaging.SingleEmailMessage>();
        
        for (Passageiro__c passageiro : (List<Passageiro__c>)Trigger.old)
        {
            if(vooContatoPassageiro.get(passageiro.IdVoo__c).get(passageiro.Contato__c).size() == 0 &&
              !mails.containsKey(passageiro.Contato__c))
            {
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                
                mail.setTemplateId(templateId);
                mail.setTargetobjectid(passageiro.Contato__c);
                mail.setWhatid(passageiro.IdVoo__c);
                mail.setOrgWideEmailAddressId(idOrgWideEmailAddres);
                //mail.setSenderDisplayName(Label.RemetenteEmail);
                mails.put(passageiro.Contato__c, mail);
            }
        }
        return mails.values();
    }
    public static Map<Id, List<Passageiro__c>> montarMapContato(Id idVoo, Set<Id> idsContato, List<Passageiro__c> passageiros)
    {
        Map<Id, List<Passageiro__c>> contatoComPassageiros = new Map<Id, List<Passageiro__c>>();
        
        for (Id idContato : idsContato)
        {
            List<Passageiro__c> passageirosPorContato = new List<Passageiro__c>();
            for(Passageiro__c passageiro : passageiros)
            {
                if(passageiro.Contato__c == idContato && passageiro.IdVoo__c == idVoo && 
                   !passageirosPorContato.contains(passageiro))
                {
                    passageirosPorContato.add(passageiro);
                }
            }
            contatoComPassageiros.put(idContato, passageirosPorContato);
        }
        return contatoComPassageiros;
    }
}