force-app/main/default/objects/Aerovia__c/Aerovia__c.object-meta.xml
<CustomObject>
    <label>Aerovia</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Nome</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Aerovias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Aerovia__c/fields/Destino__c.field-meta.xml
<CustomField>
    <fullName>Destino__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Destino</label>
    <referenceTo>Local__c</referenceTo>
    <relationshipLabel>Aerovias (Destino)</relationshipLabel>
    <relationshipName>AeroviasDestino</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Aerovia__c/fields/Origem__c.field-meta.xml
<CustomField>
    <fullName>Origem__c</fullName>
    <label>Origem</label>
    <referenceTo>Local__c</referenceTo>
    <relationshipLabel>Aerovias (Origem)</relationshipLabel>
    <relationshipName>AeroviasOrigem</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AeroviasSelector.cls
public class AeroviasSelector extends fflib_SObjectSelector implements IAeroviasSelector
{

    public static IAeroviasSelector newInstance()
	{
		return (IAeroviasSelector) Application.Selector.newInstance(Aerovia__c.SObjectType);
	}
    
    public AeroviasSelector()
    {
        super(true);
    }
    
    public override List<Schema.FieldSet> getSObjectFieldSetList()
    {
        List<Schema.FieldSet> fieldSets = new List<Schema.FieldSet>();
        
        fieldSets.add(SobjectType.Aerovia__c.FieldSets.SelectFieldList);
     
        return fieldSets;
    }
    
    public List<Schema.SObjectField> getSObjectFieldList()
	{
		return new List<Schema.SObjectField> {
			Aerovia__c.Id
		};
	}
    
    public Schema.SObjectType getSObjectType()
	{
		return Aerovia__c.sObjectType;
	}
    
    public List<Aerovia__c> selectById(Set<ID> idSet)
	{
		return (List<Aerovia__c>) selectSObjectsById(idSet);
	}
    
    public List<Aerovia__c> selectByOrigemDestino(Set<Id> origens, Set<Id> destinos)
    {
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('Origem__c IN :origens AND Destino__c IN :destinos');
        
        return (List<Aerovia__c>) Database.query(query.toSOQL());
    }
    
    public List<Aerovia__c> selectWithRetornoByOrigemDestino(Set<Id> origens, Set<Id> destinos)
    {
        fflib_QueryFactory query = newQueryFactory();
        String condition = ' (Origem__c IN :origens AND Destino__c IN :destinos) ';
        condition += ' OR (Origem__c IN :destinos AND Destino__c IN :origens) ';
            
        query.setCondition(condition);
        
        return (List<Aerovia__c>) Database.query(query.toSOQL());
    }
}