force-app/main/default/objects/Trecho__c/Trecho__c.object-meta.xml
<CustomObject>
    <description>Define um trecho com origem e destino dentro de um Voo</description>
    <label>Trecho</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Código do Trecho</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trechos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trecho__c/fields/Voo__c.field-meta.xml
<CustomField>
    <fullName>Voo__c</fullName>
    <description>Voo ao qual o trecho pertence</description>
    <inlineHelpText>Voo ao qual o trecho pertence</inlineHelpText>
    <label>Voo</label>
    <referenceTo>Voo__c</referenceTo>
    <relationshipLabel>Trechos</relationshipLabel>
    <relationshipName>Trechos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Voo__c/Voo__c.object-meta.xml
<CustomObject>
    <description>O Voo de uma aeronave, do ponto de origem até o retorno</description>
    <label>Voo</label>
    <nameField>
        <displayFormat>REVO-{00000000}</displayFormat>
        <label>Número do Voo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Voos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/VooControllerTest.cls
@isTest
private class VooControllerTest {
    @TestSetup
    static void Setup(){
        TestUtil.SetupStandardPricebook();
        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        TestUtil2.criarVooRascunho(System.now().addMinutes(120), true, uow);
        uow.commitWork();
    }

    @isTest
    static void getVooTest() {
        Voo__c voo = [SELECT Id FROM Voo__c LIMIT 1];

        Test.startTest();
        voo = VooController.getVoo(voo.Id);
        Test.stopTest();
        
        System.assert(voo.Id != null,
            'Algo não correu bem.\nClasse: \'VooController\'' + '\nFunção:\'getVoo\'\n'
            + voo);
    }

    @isTest
    static void getTrechosTest() {
        Voo__c voo = [SELECT Id FROM Voo__c LIMIT 1];

        Test.startTest();
        List<Trecho__c> trechoList = VooController.getTrechos(voo.Id);        
        Test.stopTest();
        
        System.assert(trechoList.size() > 0,
            'Algo não correu bem.\nClasse: \'VooController\'' + '\nFunção:\'getTrechos\'\n'
            + trechoList);
    }

    @isTest
    static void validarVooTest() {
        Voo__c voo = [SELECT Id FROM Voo__c LIMIT 1];

        Test.startTest();
        VooController.validarVoo(voo.Id);        
        Test.stopTest();
    }

    @isTest
    static void checkStatusRascunhoTest() {
        Test.startTest();

        Boolean checkStatusRascunho = VooController.checkStatusRascunho([SELECT Id FROM Voo__c LIMIT 1].Id);
        
        Test.stopTest();
        
        System.assert(checkStatusRascunho);
    }

    @isTest
    static void checkPassageirosCargasTest() {
        Test.startTest();

        Boolean checkPassageirosCargas = VooController.checkPassageirosCargas([SELECT Id FROM Voo__c LIMIT 1].Id);
        System.assert(
            checkPassageirosCargas,
            'Algo não correu bem.\nClasse: \'VooController\''
            + '\nFunção:\'checkPassageirosCargas\'');
        Test.stopTest();
    }
	
    @isTest
    static void checkVooNaoGerenciavelTest() {
        Test.startTest();

        Boolean checkVooNaoGerenciavel = VooController.checkVooNaoGerenciavel([SELECT Id FROM Voo__c LIMIT 1].Id);
        
        Test.stopTest();
        
        System.assert(
            !checkVooNaoGerenciavel,
            'Algo não correu bem.\nClasse: \'VooController\''
            + '\nFunção:\'checkVooNaoGerenciavel\'\n');
    }
    
    @isTest
    static void getVooWrapperTest()
    {
        Test.startTest();
        
        String str = VooController.getVooWrapper([SELECT Id FROM Voo__c LIMIT 1].Id);
        
        Test.stopTest();
    }
}