force-app/main/default/objects/Trecho__c/Trecho__c.object-meta.xml
<CustomObject>
    <description>Define um trecho com origem e destino dentro de um Voo</description>
    <label>Trecho</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Código do Trecho</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trechos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trecho__c/fields/PrimeiroTrecho__c.field-meta.xml
<CustomField>
    <fullName>PrimeiroTrecho__c</fullName>
    <description>Marca de o trecho é o primeiro a ser executado descartando translados</description>
    <formula>OrdemExecucao__c  =  Voo__r.PrimeiroTrecho__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Marca de o trecho é o primeiro a ser executado descartando translados</inlineHelpText>
    <label>Primeiro Trecho</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trecho__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Não Iniciado</fullName>
                <default>true</default>
                <label>Não Iniciado</label>
            </value>
            <value>
                <fullName>Check In Fechado</fullName>
            </value>
            <value>
                <fullName>Em Rota</fullName>
            </value>
            <value>
                <fullName>Finalizado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trecho__c/fields/Voo__c.field-meta.xml
<CustomField>
    <fullName>Voo__c</fullName>
    <description>Voo ao qual o trecho pertence</description>
    <inlineHelpText>Voo ao qual o trecho pertence</inlineHelpText>
    <label>Voo</label>
    <referenceTo>Voo__c</referenceTo>
    <relationshipLabel>Trechos</relationshipLabel>
    <relationshipName>Trechos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Voo__c/Voo__c.object-meta.xml
<CustomObject>
    <description>O Voo de uma aeronave, do ponto de origem até o retorno</description>
    <label>Voo</label>
    <nameField>
        <displayFormat>REVO-{00000000}</displayFormat>
        <label>Número do Voo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Voos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Voo__c/fields/DataVoo__c.field-meta.xml
<CustomField>
    <fullName>DataVoo__c</fullName>
    <description>Dia e hora solicitada para a realização do voo</description>
    <inlineHelpText>Dia e hora solicitada para a realização do voo</inlineHelpText>
    <label>Data</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Voo__c/fields/FaturamentoInformado__c.field-meta.xml
<CustomField>
    <fullName>FaturamentoInformado__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo marca se o voo já teve Interessados em seu faturamento informados</description>
    <label>Faturamento Informado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Voo__c/fields/Prefixo__c.field-meta.xml
<CustomField>
    <fullName>Prefixo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Prefixo da aeronave que realizará o voo</description>
    <inlineHelpText>Prefixo da aeronave que realizará o voo</inlineHelpText>
    <label>Prefixo</label>
    <referenceTo>Aeronave__c</referenceTo>
    <relationshipLabel>Voos</relationshipLabel>
    <relationshipName>Voos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Voo__c/fields/PrimeiroTrecho__c.field-meta.xml
<CustomField>
    <fullName>PrimeiroTrecho__c</fullName>
    <description>Resumo de totalização com o número da ordem de execução do primeiro trecho do voo</description>
    <inlineHelpText>Resumo de totalização com o número da ordem de execução do primeiro trecho do voo</inlineHelpText>
    <label>Primeiro Trecho</label>
    <summarizedField>Trecho__c.OrdemExecucao__c</summarizedField>
    <summaryFilterItems>
        <field>Trecho__c.Tipo__c</field>
        <operation>notEqual</operation>
        <value>Translado</value>
    </summaryFilterItems>
    <summaryForeignKey>Trecho__c.Voo__c</summaryForeignKey>
    <summaryOperation>min</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Voo__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Define em que momento o voo se encontra</description>
    <inlineHelpText>Define em que momento o voo se encontra</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Rascunho</fullName>
                <default>true</default>
                <label>Rascunho</label>
            </value>
            <value>
                <fullName>Pré-reservado</fullName>
            </value>
            <value>
                <fullName>Reservado</fullName>
            </value>
            <value>
                <fullName>Confirmado</fullName>
            </value>
            <value>
                <fullName>Rota</fullName>
                <label>Em Rota</label>
            </value>
            <value>
                <fullName>LogPendente</fullName>
                <label>Concluindo o Voo</label>
            </value>
            <value>
                <fullName>Executado</fullName>
            </value>
            <value>
                <fullName>Em Faturamento</fullName>
                <isActive>false</isActive>
                <label>Em Faturamento</label>
            </value>
            <value>
                <fullName>Faturado</fullName>
                <isActive>false</isActive>
                <label>Faturado</label>
            </value>
            <value>
                <fullName>Pronto pra Voar</fullName>
                <isActive>false</isActive>
                <label>Pronto pra Voar</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VoosSelectorTest.cls
@isTest
private class VoosSelectorTest {

    @TestSetup
    static void setup()
    {
        TestUtil.SetupStandardPricebook();
    }
    
    @isTest
    public static void selectRastreaveisBetweenDatesTest()
    {
        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        Date data = System.today().addDays(50);
        Datetime dataVoo = Datetime.newInstance(data, Time.newInstance(12, 0, 0, 0));
        Voo__c voo = TestUtil2.criarVooRascunho(dataVoo, true, uow);
        uow.commitWork();
        Test.startTest();
        List<Voo__c> voosRastreaveis = VoosSelector.newInstance().selectRastreaveisBetweenDates(data, data);
        System.assertEquals(0, voosRastreaveis.size());
        voo.Status__c = 'Confirmado';
        update voo;
        voosRastreaveis = VoosSelector.newInstance().selectRastreaveisBetweenDates(Datetime.newInstance(data, Time.newInstance(0, 0, 0, 0)), Datetime.newInstance(data.addDays(1), Time.newInstance(0, 0, 0, 0)));
        System.assertEquals(1, voosRastreaveis.size());
        Test.stopTest();
        
    }
    
  
    @isTest
    private static void selectWithLeadByIdTest()
    {
        Test.startTest();
        List<Voo__c> voosSelecionados = VoosSelector.newInstance().selectByIdWithLead(new Set<Id>());
        Test.stopTest();
        System.assertEquals(0, voosSelecionados.size());
    }
    
    @IsTest
    public static void selectRecentsWithTrechosTest()
    {
        
        Test.startTest();
        List<Voo__c> voosRecentes = VoosSelector.newInstance().selectRecentsWithTrechos();
        Test.stopTest();
        
        System.assertEquals(0, voosRecentes.size());
    }
    
    @isTest
    public static void selectDeletedByIdTest()
    {
        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        Datetime dataVoo = Datetime.newInstance(System.today()+10, Time.newInstance(12, 00, 00, 00));
        Voo__c voo = TestUtil2.criarVooRascunho(dataVoo, true, uow);
        uow.commitWork();
        delete voo;
        Test.startTest();
        List<Voo__c> voosDeletados = VoosSelector.newInstance().selectDeletedById(new Set<Id>{voo.Id});
        System.assertEquals(1, voosDeletados.size());
        Test.stopTest();
    }
    
    @isTest
    public static void getVoosHojeByStatusTest()
    {
        Test.startTest();
        List<Voo__c> voosList = VoosSelector.newInstance().getVoosAmanhaByStatus(Voos.RASCUNHO);
        Test.stopTest();
        System.assertEquals(0, voosList.size());
    }
    
    @isTest
    public static void selectByIdWithCombinedAttachmentsTest()
    {
        Test.startTest();
        VoosSelector.newInstance().selectByIdWithCombinedAttachments(new Set<Id>());
        Test.stopTest();
    }
    
    @isTest
    public static void selectByIdToInteressadosFaturamentoTest()
    {
        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        Datetime diavoo = Datetime.newInstance((Date.today()).addDays(1) , time.newInstance(13, 0, 0, 0));
        Voo__c voo = TestUtil2.criarVooRascunho(diavoo, true, uow);
        //voo.FaturamentoInformado__c = true;
        uow.commitWork();
        Test.startTest();
        List<Voo__c> selecteds = VoosSelector.newInstance().selectByIdToInteressadosFaturamento(new Set<Id>{voo.Id});
        Test.stopTest();
        System.assertEquals(1, selecteds.size());
    }
    
    @isTest
    public static void selectWithPrefixosAndBetweenDatesTest()
    {
        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        Datetime diavoo = Datetime.newInstance((Date.today()).addDays(1) , time.newInstance(13, 0, 0, 0));
        Voo__c voo = TestUtil2.criarVooRascunho(diavoo, true, uow);
        uow.commitWork();
        Test.startTest();
        Date menorData = voo.DataVoo__c.date().addDays(-1);
        Date maiorData = voo.DataVoo__c.date().addDays(1);
        List<Voo__c> voosNoIntervalo = VoosSelector.newInstance().selectWithPrefixosAndBetweenDates(new Set<Id>{voo.Prefixo__c}, menorData, maiorData);
        system.assert(voosNoIntervalo.size() == 1);
        Test.stopTest();
    }
    
    
    @isTest
    public static void selectWithPrimeiroTrechoByIdTest()
    {
        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        Datetime diavoo = Datetime.newInstance(Date.today() , time.newInstance(13, 0, 0, 0));
        Voo__c voo = TestUtil2.criarVooRascunho(diavoo, true, uow);
        uow.commitWork();

        Test.startTest();
        List<Voo__c> voos = VoosSelector.newInstance().selectWithPrimeiroTrechoById(new Set<Id>{voo.id});
        system.assert(voos.size() == 1);
        system.assertEquals(1, voos[0].trechos__r.size());
        system.assertEquals(true, voos[0].trechos__r[0].primeiroTrecho__c);
        Test.stopTest();
    }
    

}