force-app/main/default/objects/Protocolo__c/Protocolo__c.object-meta.xml
<CustomObject>
    <label>Protocolo</label>
    <nameField>
        <displayFormat>{MM}{YY}{0000}{DD}</displayFormat>
        <label>Número Protocolo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Protocolos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Protocolo__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Protocolos</relationshipLabel>
    <relationshipName>Protocolos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Protocolo__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contato</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Protocolos</relationshipLabel>
    <relationshipName>Protocolos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tabulacao__c/Tabulacao__c.object-meta.xml
<CustomObject>
    <label>Tabulação</label>
    <nameField>
        <label>Nome da Tabulação</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tabulações</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tabulacao__c/fields/CodigoAtribuicao__c.field-meta.xml
<CustomField>
    <fullName>CodigoAtribuicao__c</fullName>
    <label>Código de Atribuição</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tabulacao__c/fields/PermiteAtendimento__c.field-meta.xml
<CustomField>
    <fullName>PermiteAtendimento__c</fullName>
    <label>Permite Atendimento</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cliente - Pessoa Física</fullName>
            </value>
            <value>
                <fullName>Cliente - Pessoa Jurídica</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tabulacao__c/fields/TabulacaoInterna__c.field-meta.xml
<CustomField>
    <fullName>TabulacaoInterna__c</fullName>
    <defaultValue>false</defaultValue>
    <description>As tabulações internas não ficam visíveis para o componente de criação de casos de atendimento, mas somente para casos internos.</description>
    <inlineHelpText>As tabulações internas não ficam visíveis para o componente de criação de casos de atendimento, mas somente para casos internos.</inlineHelpText>
    <label>Tabulação Interna</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Tabulacao__c/fields/TabulacaoOculta__c.field-meta.xml
<CustomField>
    <fullName>TabulacaoOculta__c</fullName>
    <defaultValue>false</defaultValue>
    <description>As tabulações ocultas não ficam visíveis para os componentes de criação de casos.</description>
    <inlineHelpText>As tabulações ocultas não ficam visíveis para os componentes de criação de casos.</inlineHelpText>
    <label>Tabulação Oculta</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Tabulacao__c/recordTypes/FluxoTrabalho.recordType-meta.xml
<RecordType>
    <fullName>FluxoTrabalho</fullName>
    <active>true</active>
    <label>FluxoTrabalho</label>
</RecordType>

force-app/main/default/classes/TestFactory.cls
@IsTest
public class TestFactory {
  public static Account createBusinessAccount(String name) {
    Account acc = new Account();

    acc.Name = name;
    acc.RecordTypeId = Schema.getGlobalDescribe()
      .get('Account')
      .getDescribe()
      .getRecordTypeInfosByDeveloperName()
      .get('ClientePJ')
      .getRecordTypeId();
    acc.CNPJCPF__c = '11.444.777/0001-61';
    acc.BillingCity = 'São Paulo';
    acc.BillingState = 'SP';
    acc.BillingPostalCode = '12345-678';
    acc.BillingCountry = 'Brasil';
    acc.Phone = '1133334444';
    acc.Industry = 'Outros';
    acc.Type = 'Cliente';
    acc.BillingStreet = 'Rua Teste, 123';
    acc.Email__c = 'teste@email.com';
    return acc;
  }

  public static Account createPersonAccount(String firstName, String lastName) {
    Account acc = new Account();
    String cpf = GeraCpfCnpj.cpf(true);
    acc.put('FirstName', firstName);
    acc.put('LastName', lastName);
    acc.RecordTypeId = Schema.getGlobalDescribe()
      .get('Account')
      .getDescribe()
      .getRecordTypeInfosByDeveloperName()
      .get('ClientePF')
      .getRecordTypeId();
    acc.BillingCity = 'São Paulo';
    acc.BillingState = 'SP';
    acc.BillingPostalCode = '12345-678';
    acc.BillingCountry = 'Brasil';
    acc.BillingStreet = 'Rua Teste, 123';
    acc.CNPJCPF__c = cpf;
    acc.PersonEmail = firstName + '.' + lastName + '@email.com';
    acc.Phone = '1133334444';
    acc.PersonHomePhone = '1133334444';
    acc.put('TipoDocumento__pc', 'CPF');
    acc.put('NumeroDocumento__pc', cpf);
    acc.put('Email__c', firstName + '.' + lastName + '@email.com');

    return acc;
  }

  public static Case createCaseWorkflow() {
    Case cs = new Case();

    cs.RecordTypeId = Schema.getGlobalDescribe()
      .get('Case')
      .getDescribe()
      .getRecordTypeInfosByDeveloperName()
      .get('FluxoTrabalho')
      .getRecordTypeId();

    return cs;
  }

  public static Contact createContact(Id accountId, String lastName) {
    Contact ct = new Contact();

    ct.AccountId = accountId;
    ct.LastName = lastName;

    return ct;
  }

  public static Tabulacao__c createTabulacao(
    String name,
    String accountType,
    String recTypeDevName,
    Boolean isTabulacaoOculta,
    Boolean isTabulacaoInterna
  ) {
    Tabulacao__c tabulacao = new Tabulacao__c();

    tabulacao.Name = name;
    tabulacao.CodigoAtribuicao__c = 'Atendimento';
    tabulacao.PermiteAtendimento__c = accountType;
    tabulacao.TabulacaoInterna__c = isTabulacaoInterna;
    tabulacao.TabulacaoOculta__c = isTabulacaoOculta;
    tabulacao.RecordTypeId = Schema.getGlobalDescribe()
      .get('Tabulacao__c')
      .getDescribe()
      .getRecordTypeInfosByDeveloperName()
      .get(recTypeDevName)
      .getRecordTypeId();

    return tabulacao;
  }

  public static Protocolo__c createProtocolo(
    String accountId,
    String contactId
  ) {
    Protocolo__c protocolo = new Protocolo__c();

    protocolo.Conta__c = accountId;
    protocolo.Contato__c = contactId;

    return protocolo;
  }
}