force-app/main/default/objects/Protocolo__c/Protocolo__c.object-meta.xml
<CustomObject>
    <label>Protocolo</label>
    <nameField>
        <displayFormat>{MM}{YY}{0000}{DD}</displayFormat>
        <label>Número Protocolo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Protocolos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tabulacao__c/Tabulacao__c.object-meta.xml
<CustomObject>
    <label>Tabulação</label>
    <nameField>
        <label>Nome da Tabulação</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tabulações</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tabulacao__c/fields/SLAConclusao__c.field-meta.xml
<CustomField>
    <fullName>SLAConclusao__c</fullName>
    <inlineHelpText>Horas para finalização do Marco</inlineHelpText>
    <label>SLA de Conclusão</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tabulacao__c/recordTypes/FluxoTrabalho.recordType-meta.xml
<RecordType>
    <fullName>FluxoTrabalho</fullName>
    <active>true</active>
    <label>FluxoTrabalho</label>
</RecordType>

force-app/main/default/classes/CaseTabulationMilestoneAssignmentTest.cls
@IsTest
public class CaseTabulationMilestoneAssignmentTest {
  @IsTest
  static void test() {
    Tabulacao__c tabulacao = TestFactory.createTabulacao(
      'Suporte > Troca',
      'Cliente - Pessoa Jurídica',
      'FluxoTrabalho',
      false,
      false
    );
    tabulacao.SLAConclusao__c = 12;
    insert tabulacao;

    Protocolo__c protocolo = TestFactory.createProtocolo(null, null);
    insert protocolo;

    Case newCase = InsereCasoTabulacaoController.insereCasoTabulacao(
      tabulacao.Id,
      protocolo.Id
    );

    Test.startTest();

    new CaseTabulationMilestoneAssignment()
      .calculateMilestoneTriggerTime(newCase.Id, null);

    Test.stopTest();
  }
}