force-app/main/default/objects/Horarioextradamalha__c/Horarioextradamalha__c.object-meta.xml
<CustomObject>
    <label>Horário extra da malha</label>
    <nameField>
        <displayFormat>HEM - {000}</displayFormat>
        <label>HEM</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Horários extras da malha</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Horarioextradamalha__c/fields/DataHoraExtra__c.field-meta.xml
<CustomField>
    <fullName>DataHoraExtra__c</fullName>
    <label>Data/Hora Extra</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Horarioextradamalha__c/fields/MalhadeVoo__c.field-meta.xml
<CustomField>
    <fullName>MalhadeVoo__c</fullName>
    <label>Malha de Voo</label>
    <referenceTo>MalhaVoo__c</referenceTo>
    <relationshipLabel>Horários extras da malha</relationshipLabel>
    <relationshipName>HorariosExtraMalha</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MalhaVoo__c/MalhaVoo__c.object-meta.xml
<CustomObject>
    <label>Malha de Voo</label>
    <nameField>
        <displayFormat>MV-{000000}</displayFormat>
        <label>Malha de Voo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Malhas de Voos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MalhaVoo__c/fields/Ativa__c.field-meta.xml
<CustomField>
    <fullName>Ativa__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ativa</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MalhaVoo__c/fields/DataFim__c.field-meta.xml
<CustomField>
    <fullName>DataFim__c</fullName>
    <label>Data Fim</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MalhaVoo__c/fields/DataInicio__c.field-meta.xml
<CustomField>
    <fullName>DataInicio__c</fullName>
    <label>Data Início</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MalhaVoo__c/fields/Destino__c.field-meta.xml
<CustomField>
    <fullName>Destino__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Destino</label>
    <referenceTo>Local__c</referenceTo>
    <relationshipLabel>Malhas de Voos (Destino)</relationshipLabel>
    <relationshipName>MalhasVoosDestino</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MalhaVoo__c/fields/Origem__c.field-meta.xml
<CustomField>
    <fullName>Origem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Origem</label>
    <referenceTo>Local__c</referenceTo>
    <relationshipLabel>Malhas de Voos</relationshipLabel>
    <relationshipName>MalhasVoosOrigem</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MalhaVoo__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>ShuttleSeat</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Malhas de Voos</relationshipLabel>
    <relationshipName>Malhas_de_Voos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MalhaVooSelector.cls
public class MalhaVooSelector  extends fflib_SObjectSelector 
implements IMalhaVooSelector {
    
    public static IMalhaVooSelector newInstance()
    {
        return (IMalhaVooSelector) Application.Selector.newInstance(MalhaVoo__c.SObjectType);
    }
    
    public MalhaVooSelector(Boolean includeFieldSetFields)
    {
        super(includeFieldSetFields);
    }
    
    public MalhaVooSelector()
    {
        super(true);
    }
    
    public override List<Schema.FieldSet> getSObjectFieldSetList()
    {
        List<Schema.FieldSet> fieldSets = new List<Schema.FieldSet>();
        
        fieldSets.add(SobjectType.MalhaVoo__c.FieldSets.SelectFieldList);
        
        return fieldSets;
    }
    
    public List<Schema.SObjectField> getSObjectFieldList()
    {
        return new List<Schema.SObjectField> {
            MalhaVoo__c.Id
        };
    }
    
    public Schema.SObjectType getSObjectType()
    {
        return MalhaVoo__c.sObjectType;
    }

    public List<MalhaVoo__c> selectById(Set<ID> idSet)
    {
        return (List<MalhaVoo__c>) selectSObjectsById(idSet);
    }   

    public List<MalhaVoo__c> selectByProduct(Id productId) {
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('Produto__c = :productId');
        query.setOrdering('Name', fflib_QueryFactory.SortOrder.ASCENDING);
        return Database.query(query.toSOQL());
    }

    public MalhaVoo__c malhaDeVooDoProdutoNaData(Id idProduct, Date data, Id origem, Id destino, Datetime menorData, Datetime maiorData) {
        fflib_QueryFactory query = newQueryFactory();

        query.setCondition('Ativa__c = True And Produto__c = :idProduct And ' + 
        'Origem__c = :origem And Destino__c = :destino And ' + 
        'DataInicio__c <= :data And DataFim__c >= :data');

        fflib_QueryFactory subquery = query.subselectQuery('HorariosExtraMalha__r')
        .setCondition('DataHoraExtra__c >= :menorData And DataHoraExtra__c <= :maiorData')
        .selectFieldSet(SobjectType.HorarioExtraDaMalha__c.FieldSets.SobjectFieldList);
        
        System.debug('MalhaVoo: ' + query.toSOQL());
        
        List<MalhaVoo__c> malhas = Database.query( query.toSOQL() );

        return malhas.size() > 0 ? malhas[0] : null; 
    }    
    
}