force-app/main/default/objects/Horarioextradamalha__c/Horarioextradamalha__c.object-meta.xml
<CustomObject>
    <label>Horário extra da malha</label>
    <nameField>
        <displayFormat>HEM - {000}</displayFormat>
        <label>HEM</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Horários extras da malha</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Horarioextradamalha__c/fields/DataHoraExtra__c.field-meta.xml
<CustomField>
    <fullName>DataHoraExtra__c</fullName>
    <label>Data/Hora Extra</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Horarioextradamalha__c/fields/MalhadeVoo__c.field-meta.xml
<CustomField>
    <fullName>MalhadeVoo__c</fullName>
    <label>Malha de Voo</label>
    <referenceTo>MalhaVoo__c</referenceTo>
    <relationshipLabel>Horários extras da malha</relationshipLabel>
    <relationshipName>HorariosExtraMalha</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MalhaVoo__c/MalhaVoo__c.object-meta.xml
<CustomObject>
    <label>Malha de Voo</label>
    <nameField>
        <displayFormat>MV-{000000}</displayFormat>
        <label>Malha de Voo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Malhas de Voos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/MalhaVooService.cls
public class MalhaVooService {
    
    public static List<AddHorarioMalhaController.OptionDTO> getActiveProducts() {
        List<Product2> products = Product2Selector.newInstance().selectActiveShuttleSeatProducts();
        return OptionDTOMapper.mapProducts(products);
    }
    
    public static List<AddHorarioMalhaController.OptionDTO> getMalhasByProduct(Id productId) {
        if (productId == null) {
            return new List<AddHorarioMalhaController.OptionDTO>();
        }
        
        List<MalhaVoo__c> malhas = MalhaVooSelector.newInstance().selectByProduct(productId);
        return OptionDTOMapper.mapMalhas(malhas);
    }
    
    public static Id createHorarioExtra(Id malhaId, DateTime dataHora) {
        MalhaVooService.validateHorarioExtraInput(malhaId, dataHora);
        
        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        
        Horarioextradamalha__c horarioExtra = new Horarioextradamalha__c(
            MalhadeVoo__c = malhaId,
            DataHoraExtra__c = dataHora
        );
        
        uow.registerNew(horarioExtra);
        uow.commitWork();
        
        return horarioExtra.Id;
    }
    
    private static void validateHorarioExtraInput(Id malhaId, DateTime dataHora) {
        if (malhaId == null) {
            throw new MalhaVooServiceExceptions.MalhaNaoInformadaException();
        }
        if (dataHora == null) {
            throw new MalhaVooServiceExceptions.DataHoraNaoInformadaException();
        }
    }
}