force-app/main/default/objects/IntervaloSol__c/IntervaloSol__c.object-meta.xml
<CustomObject>
    <label>Intervalo do Sol</label>
    <nameField>
        <displayFormat>PS-{00000000}</displayFormat>
        <label>Código de Por do Sol</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intervalos de Sol</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IntervaloSol__c/fields/Aero__c.field-meta.xml
<CustomField>
    <fullName>Aero__c</fullName>
    <description>Local de referência do nascer e por do sol</description>
    <inlineHelpText>Local de referência do nascer e por do sol</inlineHelpText>
    <label>Aero</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IntervaloSol__c/fields/CodigoICAO__c.field-meta.xml
<CustomField>
    <fullName>CodigoICAO__c</fullName>
    <description>Código ICAO</description>
    <inlineHelpText>Código ICAO</inlineHelpText>
    <label>Código ICAO</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IntervaloSol__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Data de referência do por do sol</description>
    <label>Data</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/IntervaloSol__c/fields/Sunrise__c.field-meta.xml
<CustomField>
    <fullName>Sunrise__c</fullName>
    <description>Hora do nascer do sol</description>
    <inlineHelpText>Hora do nascer do sol</inlineHelpText>
    <label>Nascer do Sol</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/IntervaloSol__c/fields/Sunset__c.field-meta.xml
<CustomField>
    <fullName>Sunset__c</fullName>
    <description>Hora do por do sol</description>
    <inlineHelpText>Hora do por do sol</inlineHelpText>
    <label>Por do Sol</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/IntervaloSol__c/fields/WeekDay__c.field-meta.xml
<CustomField>
    <fullName>WeekDay__c</fullName>
    <description>Número do dia da semana</description>
    <inlineHelpText>Número do dia da semana</inlineHelpText>
    <label>Dia da Semana</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/IntervalosSolSelector.cls
public without sharing class IntervalosSolSelector extends fflib_SObjectSelector implements IIntervalosSolSelector
{
    public static IIntervalosSolSelector newInstance()
	{
		return (IIntervalosSolSelector) Application.Selector.newInstance(IntervaloSol__c.SObjectType);
	}
    
    public IntervalosSolSelector(Boolean includeFieldSetFields)
    {
        super(includeFieldSetFields);
    }
    
    public IntervalosSolSelector()
    {
        super(true);
    }
    
    public List<Schema.SObjectField> getSObjectFieldList()
	{
		return new List<Schema.SObjectField> {
            IntervaloSol__c.Date__c,
            IntervaloSol__c.Sunrise__c,
            IntervaloSol__c.Sunset__c,
            IntervaloSol__c.WeekDay__c,
            IntervaloSol__c.Aero__c,
            IntervaloSol__c.CodigoICAO__c
		};
	}
    
    public override List<Schema.FieldSet> getSObjectFieldSetList()
    {
        return new List<Schema.FieldSet>	
        {	SobjectType.IntervaloSol__c.FieldSets.Intervalo	};
    }
    
    public Schema.SObjectType getSObjectType()
	{
		return IntervaloSol__c.sObjectType;
	}

    public List<IntervaloSol__c> selectById(Set<ID> idSet)
	{
		return (List<IntervaloSol__c>) selectSObjectsById(idSet);
	}
    
    public List<IntervaloSol__c> selectByCodigoICAOAndDate(Set<String> codigoICAOSet, Date data)
    {
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('CodigoICAO__c in :codigoICAOSet AND Date__c = :data');
        return (List<IntervaloSol__c>) Database.query(query.toSOQL());
    }
    
    public List<IntervaloSol__c> selectAllFuture()
    {
        fflib_QueryFactory query = newQueryFactory();
        Date data = Date.today();
        query.setCondition('Date__c >= :data');
        return (List<IntervaloSol__c>) Database.query(query.toSOQL());
    }
}