force-app/main/default/objects/Interessado__c/Interessado__c.object-meta.xml
<CustomObject>
    <label>Interessado</label>
    <nameField>
        <displayFormat>I-{000000000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interessados</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Interessado__c/fields/Voo__c.field-meta.xml
<CustomField>
    <fullName>Voo__c</fullName>
    <label>Voo</label>
    <referenceTo>Voo__c</referenceTo>
    <relationshipLabel>Interessados</relationshipLabel>
    <relationshipName>Interessados</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Voo__c/Voo__c.object-meta.xml
<CustomObject>
    <description>O Voo de uma aeronave, do ponto de origem até o retorno</description>
    <label>Voo</label>
    <nameField>
        <displayFormat>REVO-{00000000}</displayFormat>
        <label>Número do Voo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Voos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/InteressadosSelectorTest.cls
@isTest
public class InteressadosSelectorTest {
    @testSetup
    public static void setup()
    {
        //fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        //TestUtil2.criarVooRascunho(System.today()+1, true, uow);
        //uow.commitWork();
        TestUtil.insereConfiguracoesPersonalizadas();
        TestUtil.SetupAccountContactVooComTrechoEPassageiro('nome', 'email@email.com', 'Rascunho', 'Não Iniciado');
        // Assegure que TestUtil.createAccount preenche BillingCountry, BillingCity, BillingPostalCode e CNPJCPF__c
    }
    
    @isTest
    static void selectorTest()
    {
        Test.startTest();
        Set<Id> idSet = Utils.getSetIds((List<SObject>) [SELECT Id FROM Interessado__c], 'Id');
        Set<Id> voosIds = Utils.getSetIds((List<SObject>) [SELECT Id FROM Voo__c], 'Id');
        System.assert(InteressadosSelector.newInstance().selectById(idSet).size() > 0);
        System.assert(InteressadosSelector.newInstance().selectByVoo(voosIds).size() > 0);
        System.assert(InteressadosSelector.newInstance().selectConclusaoTrechoByVoo(voosIds).size() > 0);
        System.assert(InteressadosSelector.newInstance().selectConclusaoVooByVoo(voosIds).size() > 0);
        System.assert(InteressadosSelector.newInstance().selectEmissaoEmbarqueByVoo(voosIds).size() > 0);
        System.assert(InteressadosSelector.newInstance().selectFaturamentoByVoo(voosIds).size() > 0);
        System.assert(InteressadosSelector.newInstance().selectReservaByVoo(voosIds).size() > 0);
        System.assert(InteressadosSelector.newInstance().selectTakeOffReportByVoo(voosIds).size() > 0);
        Test.stopTest();
    }
}