force-app/main/default/objects/Interessado__c/Interessado__c.object-meta.xml
<CustomObject>
    <label>Interessado</label>
    <nameField>
        <displayFormat>I-{000000000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interessados</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Interessado__c/fields/Voo__c.field-meta.xml
<CustomField>
    <fullName>Voo__c</fullName>
    <label>Voo</label>
    <referenceTo>Voo__c</referenceTo>
    <relationshipLabel>Interessados</relationshipLabel>
    <relationshipName>Interessados</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Voo__c/Voo__c.object-meta.xml
<CustomObject>
    <description>O Voo de uma aeronave, do ponto de origem até o retorno</description>
    <label>Voo</label>
    <nameField>
        <displayFormat>REVO-{00000000}</displayFormat>
        <label>Número do Voo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Voos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/InteressadosServiceImpl.cls
public without sharing class InteressadosServiceImpl implements IInteressadosService {
    public void criarInteressados(Set<Id> voosSetId)
    {
        Set<Contact> contactSet = new Set<Contact> (ContatosSelector.newInstance().selectContatosByVooId(voosSetId));
        Set<Voo__c> vooSet = new Set<Voo__c> (VoosSelector.newInstance().selectById(voosSetId));
        
        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        Interessados.newInstance(new List<Interessado__c>()).criarInteressados(vooSet, contactSet, uow);
        uow.commitWork();
    }
}