force-app/main/default/objects/TemplateEmail__mdt/TemplateEmail__mdt.object-meta.xml
<CustomObject>
    <label>Template de Email</label>
    <pluralLabel>Template de Email</pluralLabel>
</CustomObject>

force-app/main/default/objects/TemplateEmail__mdt/fields/APINameInteresse__c.field-meta.xml
<CustomField>
    <fullName>APINameInteresse__c</fullName>
    <label>API Name do Interesse</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TemplateEmail__mdt/fields/Id__c.field-meta.xml
<CustomField>
    <fullName>Id__c</fullName>
    <label>Id</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TemplateEmailSelector.cls
public class TemplateEmailSelector extends fflib_SObjectSelector implements ITemplateEmailSelector
{
    
    public static ITemplateEmailSelector newInstance()
    {
        return (ITemplateEmailSelector) Application.Selector.newInstance(TemplateEmail__mdt.SObjectType);
    }
    
    public TemplateEmailSelector()
    {
        super(true);
    }
    
    public List<Schema.SObjectField> getSObjectFieldList() 
    {
        List<Schema.SObjectField> fields = new List<Schema.SObjectField>();
        
        fields.add(TemplateEmail__mdt.Id__c);
        fields.add(TemplateEmail__mdt.APINameInteresse__c);
        fields.add(TemplateEmail__mdt.DeveloperName);
        fields.add(TemplateEmail__mdt.MasterLabel);
        
        return fields;
    }
    
    public Schema.SObjectType getSObjectType() 
    {
        return TemplateEmail__mdt.sObjectType;
    }
    
    public List<TemplateEmail__mdt> selectAll()
    {
        fflib_QueryFactory query = newQueryFactory();
        
        return (List<TemplateEmail__mdt>) Database.query(query.toSOQL());
    }
    
    public List<TemplateEmail__mdt> selectByDeveloperName(String developerName)
    {
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('DeveloperName = :developerName');
        
        return  (List<TemplateEmail__mdt>) Database.query(query.toSOQL());       
    }
}