force-app/main/default/objects/ConfiguracoesIntegracaoSkyTrac__c/ConfiguracoesIntegracaoSkyTrac__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Configurações Integração SkyTrac</label>
</CustomObject>

force-app/main/default/objects/ConfiguracoesIntegracaoSkyTrac__c/fields/RaioConsiderado__c.field-meta.xml
<CustomField>
    <fullName>RaioConsiderado__c</fullName>
    <description>Qualquer ponto que venha do log que esteja localizado, no máximo, nesse raio de distância de um local, será considerado que o log é referente a aquele local.</description>
    <inlineHelpText>Qualquer ponto que venha do log que esteja localizado, no máximo, nesse raio de distância de um local, será considerado que o log é referente a aquele local.</inlineHelpText>
    <label>Raio considerado (Milhas náuticas)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Local__c/Local__c.object-meta.xml
<CustomObject>
    <label>Local</label>
    <nameField>
        <label>Local</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Local__c/fields/CoordenadasLatitudeDirecao__c.field-meta.xml
<CustomField>
    <fullName>CoordenadasLatitudeDirecao__c</fullName>
    <label>Coordenadas Latitude - Direção</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DirecaoLatitude</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Local__c/fields/CoordenadasLatitudeGraus__c.field-meta.xml
<CustomField>
    <fullName>CoordenadasLatitudeGraus__c</fullName>
    <label>Coordenadas Latitude - Graus</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Local__c/fields/CoordenadasLatitudeMinutos__c.field-meta.xml
<CustomField>
    <fullName>CoordenadasLatitudeMinutos__c</fullName>
    <label>Coordenadas Latitude - Minutos</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Local__c/fields/CoordenadasLatitudeSegundos__c.field-meta.xml
<CustomField>
    <fullName>CoordenadasLatitudeSegundos__c</fullName>
    <label>Coordenadas Latitude - Segundos</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Local__c/fields/CoordenadasLongitudeDirecao__c.field-meta.xml
<CustomField>
    <fullName>CoordenadasLongitudeDirecao__c</fullName>
    <label>Coordenadas Longitude - Direção</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DirecaoLongitude</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Local__c/fields/CoordenadasLongitudeGraus__c.field-meta.xml
<CustomField>
    <fullName>CoordenadasLongitudeGraus__c</fullName>
    <label>Coordenadas Longitude - Graus</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Local__c/fields/CoordenadasLongitudeMinutos__c.field-meta.xml
<CustomField>
    <fullName>CoordenadasLongitudeMinutos__c</fullName>
    <label>Coordenadas Longitude - Minutos</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Local__c/fields/CoordenadasLongitudeSegundos__c.field-meta.xml
<CustomField>
    <fullName>CoordenadasLongitudeSegundos__c</fullName>
    <label>Coordenadas Longitude - Segundos</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/DirecaoLatitude.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>N</fullName>
        <label>Norte</label>
    </customValue>
    <customValue>
        <fullName>S</fullName>
        <label>Sul</label>
    </customValue>
    <masterLabel>Direção Latitude</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/DirecaoLongitude.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>L</fullName>
        <label>Leste</label>
    </customValue>
    <customValue>
        <fullName>O</fullName>
        <label>Oeste</label>
    </customValue>
    <masterLabel>Direção Longitude</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Locais.cls
public without sharing class Locais extends fflib_SObjectDomain implements ILocais
{    
    private static FINAL String VALIDADO = 'Validado';
    public static FINAL Double DIVISOR = 1.852; //Converte para Milhas Náuticas
    public static FINAL Double RAIOCONSIDERADO = ConfiguracoesIntegracaoSkyTrac__c.getOrgDefaults().RaioConsiderado__c; //EM MILHAS NÁUTICAS
    
    public Locais(List<Local__c> sObjectList)
    {
        super(sObjectList);
    }

    public class Constructor implements fflib_SObjectDomain.IConstructable
    {
        public fflib_SObjectDomain construct(List<SObject> sObjectList)
        {
            return new Locais(sObjectList);
        }
    }
    
    public override void onAfterUpdate(Map<Id,SObject> existingRecords)
    {
        Set<Id> locaisIds = Trigger.newMap.keySet();          
    }
    
    public override void onBeforeUpdate(Map<Id,SObject> existingRecords)
    {
        for(Local__c local : (List<Local__c>)records)
        {
            Local__c localAnt = (Local__c)existingRecords.get(local.Id);
            if (local.Coordenadas__Latitude__s  != localAnt.Coordenadas__Latitude__s ||
                local.Coordenadas__Longitude__s != localAnt.Coordenadas__Longitude__s )
            {
                ConversorGeolocation.LocalGraus localGrau = new ConversorGeolocation.LocalGraus();
                localGrau = ConversorGeolocation.convertLocalDecimalParaGrau(local.Coordenadas__Latitude__s, local.Coordenadas__Longitude__s);
                if (localGrau.latitude != null && localGrau.longitude != null)
                {
                    local.CoordenadasLatitudeDirecao__c = localGrau.latitude.direcao;
                    local.CoordenadasLatitudeGraus__c = localGrau.latitude.grau;
                    local.CoordenadasLatitudeMinutos__c = localGrau.latitude.minuto;
                    local.CoordenadasLatitudeSegundos__c = localGrau.latitude.segundo;
                    local.CoordenadasLongitudeDirecao__c = localGrau.longitude.direcao;
                    local.CoordenadasLongitudeGraus__c = localGrau.longitude.grau;
                    local.CoordenadasLongitudeMinutos__c = localGrau.longitude.minuto;
                    local.CoordenadasLongitudeSegundos__c = localGrau.longitude.segundo;
                }
            }
            else
            {
                ConversorGeolocation.LocalDecimais localdec = new ConversorGeolocation.LocalDecimais();
                localdec = ConversorGeolocation.convertLocalGrauParaDecimal(
                    new ConversorGeolocation.CoordenadaGraus( 
                    	(Integer)local.CoordenadasLatitudeGraus__c,
                    	(Integer)local.CoordenadasLatitudeMinutos__c,
                    	local.CoordenadasLatitudeSegundos__c,
                    	local.CoordenadasLatitudeDirecao__c), 
                    new ConversorGeolocation.CoordenadaGraus(
                    	(Integer)local.CoordenadasLongitudeGraus__c,
                    	(Integer)local.CoordenadasLongitudeMinutos__c,
                    	local.CoordenadasLongitudeSegundos__c,
                    	local.CoordenadasLongitudeDirecao__c));
                if(localdec.latitude != null && localdec.longitude != null)
                {
                    local.Coordenadas__Latitude__s = localdec.latitude;
                    local.Coordenadas__Longitude__s = localdec.longitude;
                }
            }
        }
    }
    
    public override void onBeforeInsert()
    {
        for(Local__c local : (List<Local__c>)records)
        {
            addError(inserindoCoordenadasDeAmbosTipos(local), local, System.Label.AmbosTiposCoordenada);          
            
            //Atualizando as coordenadas em branco com as preenchidas
            if (local.Coordenadas__Latitude__s  != null &&
                local.Coordenadas__Longitude__s != null)
            {
                ConversorGeolocation.LocalGraus localGrau = new ConversorGeolocation.LocalGraus();
                localGrau = ConversorGeolocation.convertLocalDecimalParaGrau(local.Coordenadas__Latitude__s, local.Coordenadas__Longitude__s);
                local.CoordenadasLatitudeDirecao__c = localGrau.latitude.direcao;
                local.CoordenadasLatitudeGraus__c = localGrau.latitude.grau;
                local.CoordenadasLatitudeMinutos__c = localGrau.latitude.minuto;
                local.CoordenadasLatitudeSegundos__c = localGrau.latitude.segundo;
                local.CoordenadasLongitudeDirecao__c = localGrau.longitude.direcao;
                local.CoordenadasLongitudeGraus__c = localGrau.longitude.grau;
                local.CoordenadasLongitudeMinutos__c = localGrau.longitude.minuto;
                local.CoordenadasLongitudeSegundos__c = localGrau.longitude.segundo;
            }
            else
            {
                ConversorGeolocation.LocalDecimais localdec = new ConversorGeolocation.LocalDecimais();
                localdec = ConversorGeolocation.convertLocalGrauParaDecimal(
                    new ConversorGeolocation.CoordenadaGraus( 
                        (Integer)local.CoordenadasLatitudeGraus__c,
                        (Integer)local.CoordenadasLatitudeMinutos__c,
                        local.CoordenadasLatitudeSegundos__c,
                        local.CoordenadasLatitudeDirecao__c), 
                    new ConversorGeolocation.CoordenadaGraus(
                        (Integer)local.CoordenadasLongitudeGraus__c,
                        (Integer)local.CoordenadasLongitudeMinutos__c,
                        local.CoordenadasLongitudeSegundos__c,
                        local.CoordenadasLongitudeDirecao__c));
                if(localdec.latitude != null && localdec.longitude != null)
                {
                    local.Coordenadas__Latitude__s = localdec.latitude;
                    local.Coordenadas__Longitude__s = localdec.longitude;
                }
        	}
        }
    }
    
    private Boolean inserindoCoordenadasDeAmbosTipos(Local__c local)
    {
        if ((local.Coordenadas__Latitude__s != null || local.Coordenadas__Longitude__s != null) &&
            (local.CoordenadasLatitudeDirecao__c != null ||
            local.CoordenadasLatitudeGraus__c != null ||
            local.CoordenadasLatitudeMinutos__c != null ||
            local.CoordenadasLatitudeSegundos__c != null ||
            local.CoordenadasLongitudeDirecao__c != null ||
            local.CoordenadasLongitudeGraus__c != null ||
            local.CoordenadasLongitudeMinutos__c != null ||
            local.CoordenadasLongitudeSegundos__c != null))
        {
            return true;
        }
        return false;
    }
    
    private void addError(Boolean errorCondition, Local__c local, String msgErro)
    {
        if (errorCondition) local.addError(msgErro);
    }
}